### ISSUE TITLE
snip

### ISSUE THREAD

**Issue by ErikHumphrey** [TranslucentTB/TranslucentTB#100]
nevermind

**Comment by ScruffyRules** [comment]
Please don't wipe the issue clean, just close it.

**Comment by denosawr** [comment]
For the reference, there is an option to do so, and it should be documented in other issues. Also, @ErikHumphrey please leave an issue alone after you close it - it may be just you didn't see the option, but still document how you solved it and don't rename it in the future. Thanks!
