### ISSUE TITLE
A few options/features request

### ISSUE THREAD

**Issue by 03302024** [TranslucentTB/TranslucentTB#1001]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

- Please make the Start menu transparent, similar to the taskbar.
- Please provide an option to hide the taskbar icon (no overflow).
- Please provide setup exe files for the new releases, as well. Download from store doesn't work for me.
- The portable download requires extra dependancies on Windows 11. Please include them in the download zip file.

### Expected results

No response

### Actual results

No response

### Windows version

Windows 11 RTM (build 22000)

**Comment by sylveon** [comment]
> Please make the Start menu transparent, similar to the taskbar.

TranslucentTB focuses on altering the taskbar for now. There are alternative projects for the start menu, for example https://github.com/rounk-ctrl/TranslucentSM

> Please provide an option to hide the taskbar icon (no overflow).

This already exists, in the config file set `hide_tray` to `true`.

> Please provide setup exe files for the new releases, as well. Download from store doesn't work for me.

We rely on MSIX package identity for features now. Which means an exe installer would just install the MSIX - so, we can just distribute the MSIX because Windows has a built-in installer for MSIX. In the releases, there is an appinstaller file that will install the MSIX and its dependencies. Are you experiencing problems with the appinstaller file?

> The portable download requires extra dependancies on Windows 11. Please include them in the download zip file.

I can look into bundling the dependencies inside the zip, but they will need to be installed on the system either way, they cannot be used without being installed, due to limitations in WinUI 2.

**Comment by 03302024** [comment]
> There are alternative projects for the start menu, for example https://github.com/rounk-ctrl/TranslucentSM

Thank you for the link. 

> in the config file set `hide_tray` to `true`.

Thank you for the information.

> Are you experiencing problems with the appinstaller file?

Yes, I tried a few things with no success and I gave up. I guess, my only chance is to use a complete installer or a complete portable app, that includes all the dependacies.

> I can look into bundling the dependencies inside the zip

That would be great.

> but they will need to be installed on the system either way

That is just fine with me, as long as I don't have to go through Microsoft store/powershell scripts/extra downloads, etc.

**Comment by sylveon** [comment]
Just to unblock you, these are the current dependencies:
https://github.com/TranslucentTB/TranslucentTB/releases/download/2024.1/winui-x64.appx
https://github.com/TranslucentTB/TranslucentTB/releases/download/2022.1/vclibs-uwp-x64.appx
https://github.com/TranslucentTB/TranslucentTB/releases/download/2022.1/vclibs-desktop-x64.appx

Install the VCLibs before WinUI.

**Comment by 03302024** [comment]
> Install the VCLibs before WinUI.

Thanks for the links, but I have trouble installing .appx files.

**Comment by 03302024** [comment]
> I can look into bundling the dependencies inside the zip

I was wondering if there is any new update on this. The issue is the portable download requires extra dependancies on Windows 11. Please include them in the download zip file.

**Comment by sylveon** [comment]
I suppose you didn't mean to close this. Unfortunately, it's not really doable because WinUI 2 does not support SxS deployment scenarios.

**Comment by 03302024** [comment]
Well, this was sitting there for a while and I thought it has past its time.

**Comment by sylveon** [comment]
See [this document](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/xaml-islands/xaml-islands#supported-only-with-workarounds)

> If your desktop app is not packaged using MSIX, you can host WinUI controls only if you install a prerelease version of the [Microsoft.UI.Xaml](https://www.nuget.org/packages/Microsoft.UI.Xaml) NuGet package, or if you use the [Dynamic Dependencies API](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/framework-packages/framework-packages-overview).

The latest prerelease version is over a year older than the latest stable, so it's not really an option. The current solution uses Dynamic Dependencies, which does require the dependency to be installed on the system.
![image](https://github.com/user-attachments/assets/8bd6782b-9eae-4e6f-92e2-17289c6e83e1)

**Comment by 03302024** [comment]
Thanks for the info. I will look into that.
