### ISSUE TITLE
[Source Code Support]: I'm just looking for source codes that won't make the taskbar transparent

### ISSUE THREAD

**Issue by mcyenikoylu** [TranslucentTB/TranslucentTB#1006]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

I'm just looking for source codes that won't make the taskbar transparent. I'm examining the TaskbarAttributeWorker.cpp file. Rather than installing all the software and any errors it may have. I want to create a new VS project and just add transparency to the taskbar. Could you please show me the code line number and the names of the relevant functions?

### Expected results

-

### Actual results

-

### Windows version

Windows 11 RTM (build 22000)

### Other details

Edition	Windows 11 Pro
Version	23H2
Installed on	‎11/‎07/‎2022
OS build	22631.3296
Experience	Windows Feature Experience Pack 1000.22687.1000.0

**Comment by sylveon** [comment]
Look at ExplorerTAP
