### ISSUE TITLE
[Bug]: Stopped working today after a Windows 11 update

### ISSUE THREAD

**Issue by thealjey** [TranslucentTB/TranslucentTB#1007]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Use on the latest Windows 11 and all of the updates.

I'm fairly certain it's this update specifically - "Windows Configuration Update (KB5035942)".

### Expected results

App launches.

### Actual results

![image](https://github.com/TranslucentTB/TranslucentTB/assets/2216553/66be0fed-f74a-4a36-a2ea-af7b8afc08f3)

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

Version 23H2 (OS Build 22631.3447)

**Comment by liushui985** [comment]
did you work out this bug?

**Comment by Aleks-Levet** [comment]
me too it stopped working

**Comment by sakana1110** [comment]
Same issues,but when I open in Microsoft Store it work,not sure why

**Comment by sgf520** [comment]
This bug has been reported before. You can see this issue (https://github.com/TranslucentTB/TranslucentTB/issues/920) to solve it. And don't forget to close your issue.

**Comment by thealjey** [comment]
@sgf520 I can't verify that it works anymore, because I have stopped using the app since

but, I'm ok closing the issue now :)
