### ISSUE TITLE
REQ: 32px taskbar icons

### ISSUE THREAD

**Issue by Andreasvb** [TranslucentTB/TranslucentTB#101]
If possible, an option to show taskbar icons in 32px, like WIndows 7.
It works with [7+ Taskbar Tweaker](http://rammichael.com/7-taskbar-tweaker) but only on stable (not Insider builds).

![image](https://user-images.githubusercontent.com/3948747/30221518-dc02cd76-94c3-11e7-96ec-c7d4b5e67205.png)

http://winaero.com/blog/how-to-make-taskbar-icons-bigger-in-windows-10/

**Comment by sylveon** [comment]
Unfortunately this is out of the scope of this project. And it would probably require changes for each update, same as 7+TT.

**Comment by ethanhs** [comment]
I actually conversed with the developer of 7+TT and he does DLL injection. We try to avoid that. Also I expect he will release a fix at some point.
