### ISSUE TITLE
[Bug]: Maximised window mode doesn't activate when using PowerTOys

### ISSUE THREAD

**Issue by pedro-de-rycker** [TranslucentTB/TranslucentTB#1020]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Use poser toys to occupy the whole screen with two window.

### Expected results

Expected Maximed window to kick in and change my bar to acrylic as set up by configuration.

### Actual results

Still is transparent because I guess it is detecting floating window mode

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

Not insider build, version is 22631.3593

**Comment by sylveon** [comment]
Windows resized by FancyZones are not maximized windows, but just normal windows. There is plan to detect snapping via Windows's builtin snapping support, but unless FancyZones offers a way to detect snapping, it remains out of scope to try and guess if windows are snapped.
