### ISSUE TITLE
[Bug]: application shutdown after adding rules into the settings.json

### ISSUE THREAD

**Issue by starfish233e** [TranslucentTB/TranslucentTB#1023]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

open the task bar and click the TB application icon, choose "advanced settings" --> "edit setting" , than edit the "rules" into :
"rules": {
      "window_class": {},
      "window_title": {},
      "process_name": ["Code.exe"]
here is the [settings.json](https://github.com/user-attachments/files/15546004/settings.json)

### Expected results

When I save the setting, it will not provide warning. And then when I open the Microsoft Visual Studio Code, the task bar should be opaque, and it will stay transparent when I make it full-screen.

### Actual results

The application shutdown, and it reports the wrong log.

![屏幕截图 2024-06-04 173658](https://github.com/TranslucentTB/TranslucentTB/assets/145137214/1db067ac-ca18-4a2d-8b1c-9a9de39114db)

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment]
The error code is correct - rules aren't an array but a keyed object. You want something like this:
```json
"rules": {
  "process_name": {
    "Code.exe": {
      "accent": "opaque"
    }
  }
}
```


Because the config file is not in a valid format, TTB rejects it and returns to default settings.
