### ISSUE TITLE
How to reset custom accent color?

### ISSUE THREAD

**Issue by Cris--** [TranslucentTB/TranslucentTB#1024]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Set the taskbar mod anything the Normal.
Set a custom accent color.
The custom accent color is now sticked so if i change the wallpaper with Auto Color taskbar color didn't got changed anymore.

### Expected results

Didn't get changed to Windows dynamic accent color.

### Actual results

Doesn't matter if i change the TTB back to normal where the new color is correct and then maybe to Acrylic (then i got my custom accent color back again).

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

Windows version 24H2 Build 26100.712 but also on many previous versions!

**Comment by Cris--** [comment]
Don't know if it is a bug so tag label "bug" is useless. It is more a question.

**Comment by sylveon** [comment]
At the moment, you can't combine a normal accent color with a custom effect. It's either normal color and effect, or custom color and effect.

**Comment by Cris--** [comment]
You mean dynamic accent color from Windows wallpaper only with Normal effect and all other effects only with TTB custom static color right?

Is something in the pipeline to change that behavior?

**Comment by sylveon** [comment]
> You mean dynamic accent color from Windows wallpaper only with Normal effect and all other effects only with TTB custom static color right?

Yes

> Is something in the pipeline to change that behavior?

Not at the moment.
