### ISSUE TITLE
[Bug]: Open on startup is grayed out, TTB doesn't launch on startup.

### ISSUE THREAD

**Issue by AsuToki360** [TranslucentTB/TranslucentTB#1026]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

- Right click on the TTB icon
- Try to check the "Open on startup" option (I'm on Spanish, so no idea how is it called in English.)

### Expected results

TranslucentTB launches when turning on the PC.

### Actual results

TranslucentTB doesn't open, forced to open it manually.

Checking the settings of the program itself, the option is grayed out.
![image](https://github.com/TranslucentTB/TranslucentTB/assets/40326499/0d15ae4f-cbda-4901-aba8-4f947df04e91)

### Windows version

Windows 10 2004-22H2 (builds 19041-19045)

**Comment by sylveon** [comment]
Try saving this as "StartupTasks.reg", merging it into the registry by double-clicking and accepting the prompt, then rebooting
```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System]
"EnableFullTrustStartupTasks"=dword:00000002
"EnableUwpStartupTasks"=dword:00000002
"SupportFullTrustStartupTasks"=dword:00000001
"SupportUwpStartupTasks"=dword:00000001
```

**Comment by AsuToki360** [comment]
Thanks, it's now working, I will save this just in case it happens again.
