### ISSUE TITLE
[Bug]: TranslucentTB fails on start on Windows 11 23H2 22631.3737

### ISSUE THREAD

**Issue by SirLionfire** [TranslucentTB/TranslucentTB#1032]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

After updating to Windows 11 23H2 build 22631.3737 (June updates) TranslucentTB fails on start:

![image](https://github.com/TranslucentTB/TranslucentTB/assets/19512638/7b932541-077f-4ac3-b46d-61ffee72f244)

This issue is not resolved by restarting the PC, or by ending the TranslucentTB.exe process and trying again.  It was not an issue until this Windows update, which I suspect made some changes to the taskbar.

### Expected results

Starting without error.

### Actual results

Shows error.

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Relevant log output

```shell
Log:

[2024-06-20 07:37:36.707] [critical] [taskbarattributeworker.cpp:1271] Failed to initialize XAML Diagnostics. (0x80070490: Element not found.)

Event error:

Faulting application name: TranslucentTB.exe, version: 2024.1.0.0, time stamp: 0xaf1d7492
Faulting module name: ProgramLog.dll, version: 0.0.0.0, time stamp: 0xa35bc982
Exception code: 0xc0000409
Fault offset: 0x000000000002616e
Faulting process ID: 0x0x1F164
Faulting application start time: 0x0x1DAC2E4A66986BC
Faulting application path: C:\Program Files\WindowsApps\28017CharlesMilette.TranslucentTB_2024.1.0.0_x64__v826wp6bftszj\TranslucentTB.exe
Faulting module path: C:\Program Files\WindowsApps\28017CharlesMilette.TranslucentTB_2024.1.0.0_x64__v826wp6bftszj\ProgramLog.dll
Report ID: 3bf864bb-e6e4-4220-ade6-27084927c296
Faulting package full name: 28017CharlesMilette.TranslucentTB_2024.1.0.0_x64__v826wp6bftszj
Faulting package-relative application ID: TranslucentTB
```

**Comment by Pawel-Parma** [comment]
Hi. I had the same issue, the update probably broke something. In version 23H2 Build 22631.3807 it works again. Just to let anyone who has the same issue how to solve it:
- Turn on Windows Insider Program
- Update to Version 23H2 and Build 22631.3807

**Comment by SirLionfire** [comment]
Yeah, it appears so.  I upgraded to 22631.3810 and the issue has resolved itself (thanks Microsoft).
