### ISSUE TITLE
[Bug]: Failed to set hook. 0x80070005: Access is denied.

### ISSUE THREAD

**Issue by luaotix** [TranslucentTB/TranslucentTB#1036]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

My system is Windows 11, version 23H2. Previously, I was able to use TranslucentTB without any issues. However, after upgrading (KB5039302) yesterday, I can no longer open it, and an error message pops up.
![2](https://github.com/TranslucentTB/TranslucentTB/assets/94216417/189fa1f2-e813-4b8e-ac28-2f42ada84f06)

I found a similar report (https://github.com/TranslucentTB/TranslucentTB/issues/1021), but it has already been closed. The person mentioned using CCleaner to clean the registry, which I also tried, but it didn’t help.

I have also tried other methods: running TranslucentTB as an administrator, downloading and reinstalling the latest version, and attempting both TranslucentTB.appinstaller and TranslucentTB-portable-x64.zip.

### Expected results

TranslucentTB is running normally.

### Actual results

TranslucentTB has encountered a fatal error and cannot continue
executing.
Failed to set hook.
0x80070005: Access is denied

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

**Comment by WindDrift** [comment]
I'm so sorry to hear that you found my issue #1021 and you didn't get any help.

Before I close that issue, I just use CCleaner to clean the registry without paying attention. It seems worked just at that time, so I closed that issue. But the next day, the same problem happened again, I'm so sorry that I didn't reopen that issue in a timely manner.

**Comment by Legend3894** [comment]
I also encountered this problem yesterday, you can refer to this post to solve the problem. The source of the problem is that the resource manager is protected by the Huorong security software, and the protection can be turned off to run TB.
https://tieba.baidu.com/p/9069691007?pid=150608439054&cid=0#150608439054

**Comment by luaotix** [comment]
> I also encountered this problem yesterday, you can refer to this post to solve the problem. The source of the problem is that the resource manager is protected by the Huorong security software, and the protection can be turned off to run TB.我昨天也遇到这个问题了，可以参考这个帖子解决问题。问题根源在于资源管理器受到了火绒安全软件的保护，关闭保护即可运行TB。 https://tieba.baidu.com/p/9069691007?pid=150608439054&cid=0#150608439054

Thanks, the problem is solved.
