### ISSUE TITLE
[Bug]: 无法自启动，自启动选项是灰色的无法选中

### ISSUE THREAD

**Issue by lbyisme** [TranslucentTB/TranslucentTB#1039]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

无法自启动，自启动选项是灰色的无法选中

### Expected results

能够选中自启动

### Actual results

无法自启动

### Windows version

Windows 10 2004-22H2 (builds 19041-19045)

### Relevant log output

```shell
[2024-07-10 01:30:29.623] [warning] [taskbarattributeworker.cpp:867] Failed to query for ICortanaExperienceManager (0x80004002: 不支持此接口)
```

**Comment by sylveon** [comment]
Try saving this as "StartupTasks.reg", merging it into the registry by double-clicking and accepting the prompt, then rebooting
```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System]
"EnableFullTrustStartupTasks"=dword:00000002
"EnableUwpStartupTasks"=dword:00000002
"SupportFullTrustStartupTasks"=dword:00000001
"SupportUwpStartupTasks"=dword:00000001
```

**Comment by lbyisme** [comment]
> 尝试将其另存为“StartupTasks.reg”，通过双击并接受提示将其合并到注册表中，然后重新启动
> 
> ```reg
> Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System]
> "EnableFullTrustStartupTasks"=dword:00000002
> "EnableUwpStartupTasks"=dword:00000002
> "SupportFullTrustStartupTasks"=dword:00000001
> "SupportUwpStartupTasks"=dword:00000001
> ```

谢谢老哥，可以了
