### ISSUE TITLE
Feature Request: Adapt colors of windows specific task-bar items

### ISSUE THREAD

**Issue by polaroidkidd** [TranslucentTB/TranslucentTB#104]
Hi

First: Love it.

Second: Is there any way to change the color of the taskbar items? With white background they become somewhat hard to out:

Exhibit A:

![image](https://user-images.githubusercontent.com/11783457/30561448-602d26ec-9cbb-11e7-9aee-0d2cdbb86e87.png)

Any help would be appreciated.

**Comment by ethanhs** [comment]
Glad you like it! Sadly, not currently. Also, this is a duplicate of #41.
