### ISSUE TITLE
[Bug]: TranslucentTB exiting on its own & causing issues with Windows

### ISSUE THREAD

**Issue by voidZiAD** [TranslucentTB/TranslucentTB#1044]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Run TaskbarTB, make it Clear.

### Expected results

Clear Taskbar, no issues.

### Actual results

Clear Taskbar, but sometimes when I close an app, especially File Explorer, my windows blacks out for a sec and then reloads the taskbar, and two to three times later TranslucentTB says that file explorer refreshed twice in the last 30 secs and exited on its own.

![image](https://github.com/user-attachments/assets/74557a20-c612-45eb-8ebc-078675887aef)

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

10.0.22635 Build 22635. It also applies for every other app that has its main purpose as customization for Windows. I was customizing my File Explorer opacity through an app, and the same thing happened.

### Relevant log output

```shell
Idk where the logs are tbh
```

**Comment by voidZiAD** [comment]
I also noticed that I was on an Insider Program version of windows. I left it, and restarted my computer which got windows to install a public release, and the issue is still there. Less frequent, but still there.

**Comment by dAvidcA** [comment]
Same problem here.

![Captura de pantalla 2024-07-16 082346](https://github.com/user-attachments/assets/7eb76696-0371-46d0-9a23-257576e23f24)

![image](https://github.com/user-attachments/assets/ea2d8334-dcdc-4bc3-ab69-cb670bdc67db)

**Comment by dAvidcA** [comment]
**Update:**
Windows was updated an hour ago to version **24H2** (26100.1150) and the problem disappeared.
Thanks Microsoft.

**Comment by voidZiAD** [comment]
Yeah, it stopped happening after the new update. GGs

**Comment by RubinDublone593** [comment]
Im not in insider and this just started happening with my pc (about two weeks ago) and my laptop (today) weirdly it started about when windows stole the year number of the date in the bottom right corner. Any tips on how to fix it? I uninstalled translucent on both machines and explorer is restarting constantly. Pls help!!
