### ISSUE TITLE
[Bug]: TranslucentTB breaks on the latest Windows Insider Build 26120.1252 ge_release (last update released on 2024/07/20)

### ISSUE THREAD

**Issue by martinotecco** [TranslucentTB/TranslucentTB#1048]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

 1. Start TranslucentTB and note that it applies your changes;
 2. Click on any taskbar element like the little arrow for tray icons or on any pinned/opened taskbar apps you have;
 3. You see that TranslucentTB breaks and there isn't the translucent taskbar anymore.

### Expected results

It's expected to work properly, but it's not.
Please, review the code and find what is causing that bug with the latest Windows Insider Build.

### Actual results

TranslucentTB starts fine, it applies the modifications correctly but then it breaks right after clicking any taskbar elements or apps.

### Windows version

Microsoft Windows 11 - Version 24H2 (OS Insider Build 26120.1252 ge_release)
last os update: 2024/07/20

**Comment by sylveon** [comment]
Seems to work for me
![image](https://github.com/user-attachments/assets/9172454b-494a-4fa9-915f-038d2d2e95c0)

**Comment by martinotecco** [comment]
@sylveon Are you running an Insider Build? There was an update yesterday for the Insider Build that changed the taskbar a bit, StartAllBack also is broken now... I see that probably you've modded your taskbar since the group of three, internet, volume and battery is not there

**Comment by sylveon** [comment]
You can see in the about windows dialog that this is 26120.1252.

There is no battery button because this is a desktop PC. This is a brand new unmodified install of the OS, running only TranslucentTB.

**Comment by martinotecco** [comment]
The problem is solved now, apparently there was a bug affecting the shell32.dll of Explorer after the update.
I uninstalled StartAllBack v3.11.7 (the latest release) and I re-installed the program using the ALPHA version provided by the creator on X (https://x.com/StartIsBack/status/1810318642011378160). TranslucentTB is working fine now.

**Comment by sylveon** [comment]
I should really edit the issue template so that people declare if they run other taskbar customization software 😅
