### ISSUE TITLE
Multiple Monitors. vertical setup

### ISSUE THREAD

**Issue by fenrisswolf** [TranslucentTB/TranslucentTB#105]
On My setup, I have two monitors, one stacked above the other.  
Now windows 10 has a few issues dealing with this, like overdrawing full screen programs from the bottom monitor a few pixels into the monitor on top.

My issue is this:
Translucent TB has an issue where I have my taskbars set to autohide, and the transparency from the top monitor slides down into the top of the bottom monitor, obscuring the top of whatever app I Have running full screen on the bottom monitor.  It doesn't seem to affect the functionality of the app on the bottom screen, although it is visually distracting...

**Comment by ethanhs** [comment]
We cannot control the drawing area of the taskbar. This seems to be an issue with the settings of your monitor. Sorry.
