### ISSUE TITLE
[Bug]: Cannot change anything inTTB

### ISSUE THREAD

**Issue by Alf-from-Mannheim** [TranslucentTB/TranslucentTB#1051]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

TTB makes – after installation – my taskbar translucent. That's fine.
But where can I change the settings? So my taskbar isn't 100 % transparent, but 50 or 60 %?
I have no icon whatsoever on my desktop and when I click on Start -> All programs -> Apps -> TranslucentTB **NOTHING** happens ... The program itself is in a folder to which I have no access: c:\programs\windowsapps.
Is there anywhere a comprehensible manual on the net?
Thanks in advance for any help
Alf

### Expected results

To be able to change my settings.

### Actual results

nuffin'

### Windows version

Windows 10 2004-22H2 (builds 19041-19045)

**Comment by sylveon** [comment]
The app is in the system tray on the taskbar (where your volume icon and etc. are)
