### ISSUE TITLE
[Bug]: After i update my windows into latest version my taskbar shrinks every time i open an application

### ISSUE THREAD

**Issue by yopijay** [TranslucentTB/TranslucentTB#1055]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Just open multiple application and you will notice that the taskbar shrinks horizontally

### Expected results

Taskbar width should adjust depends on how many apps i will open
![image](https://github.com/user-attachments/assets/da21694d-62aa-4268-b36c-535d1080cbf8)

### Actual results

![image](https://github.com/user-attachments/assets/aad09592-d314-418c-9f04-fe786d7a6f42)

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

**Comment by sylveon** [comment]
Uninstall RoundedTB
