### ISSUE TITLE
[close this please] Cortana & applications

### ISSUE THREAD

**Issue by Announcement** [TranslucentTB/TranslucentTB#106]
# edit
sorry I didn't do my due diligence and look through the comments and realized this is the same old issue you guys have seen a million times, my bad! *great* product though!

instantly fell in love. Especially on desktop view it's absolutely gorgeous. I found it on some "awesome" list where they show a bunch of cool applciations and it looked intruiging, I didn't even realize I needed it until I got it and it's amazing.

I have a few suggestions though, ~but these might be possible with autohotkey or something but I really don't know how to use that so if you could provide me with some scripts or an update that would be~ *amazing*

- better application support
- cortana

## cortana
cortana is not colored it's just the nasty theme colored

## application support
if you could make it stretch applications past the taskbar that would be amazing and show through them or something, or even just theme it to the color of the bottom of the application that would be perfectly fine too!

btw all of the strikeouts are because midway through typing this I discovered the "Dynamic Windows" feature.

**Comment by ethanhs** [comment]
You can close your own issues by the way. But I'm glad you like it so much!
