### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by fahad826** [TranslucentTB/TranslucentTB#1062]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

d

### Expected results

d

### Actual results

d

### Windows version

Windows 10 May/November 2019 Update (builds 18362 and 18363)

### Other details

d

### Relevant log output

```shell
d
```

**Comment by sylveon** [comment]
Can you explain the problem instead of spamming d?
