### ISSUE TITLE
[Bug]: Notification about update though my version is actual

### ISSUE THREAD

**Issue by apeofiron** [TranslucentTB/TranslucentTB#1064]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

After every system reboot I see a notification about an updated program and a request for system reboot in notification and the TB isn't translucent until I open the program by myself. The reinstalation doesn't help. 
![Снимок экрана 2024-09-06 003940](https://github.com/user-attachments/assets/5ba4dec8-82fc-46ee-ac04-9a15f722963f)

### Expected results

After reboot I don't see this notification and the TB is translucent without my additional actions

### Actual results

After every system reboot I see a notification about an updated program and the TB isn't translucent.

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

Build 22631.4112

**Comment by sylveon** [comment]
Do you have any software that could conflict running?

**Comment by apeofiron** [comment]
I'm not sure. Is there any way to check for conflicts?

**Comment by sylveon** [comment]
Well, anything else that could be modifying the taskbar? Two copies of TTB running at once?
There are apps which repackage TTB on the Store, and they could be causing issues with the legitimate TranslucentTB.

**Comment by apeofiron** [comment]
I found the reason of conflict. It is iTop Easy Desktop, an app for creating groups of files on Desktop. Looks like they somehow intersect but I'm not sure how

**Comment by apeofiron** [comment]
I found the reason of conflict. It is iTop Easy Desktop, an app for creating groups of files on Desktop. Looks like they somehow intersect but I'm not sure how

**Comment by sylveon** [comment]
It appears it's their fancy taskbar module. It is using stolen TranslucentTB code:
![image](https://github.com/user-attachments/assets/30ad8196-836d-4539-8a43-5de6b3b36bb2)

https://github.com/TranslucentTB/TranslucentTB/blob/6320ce5b0834f853d0c9466e0a3e694b7c0c2910/ExplorerTAP/api.cpp#L13
