### ISSUE TITLE
no blur option in windows 11 latest build

### ISSUE THREAD

**Issue by lgkahn** [TranslucentTB/TranslucentTB#1065]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

installed latewst build still no blur option

### Expected results

how do i get blur back.. or give me link to earlier build

### Actual results

no blur optoin

### Windows version

Windows 10 May/November 2019 Update (builds 18362 and 18363)

**Comment by sylveon** [comment]
The code to support blur is no longer present in the OS, therefore it has been removed from TranslucentTB at the moment. It will be back in a future update of the app.
