### ISSUE TITLE
[Bug]: Element Not Found

### ISSUE THREAD

**Issue by NightDust981989** [TranslucentTB/TranslucentTB#1069]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Can not run TranslucentTB on newest version of windows 11 (23H2 OS 22631.4169)

### Expected results

i wish no error!

### Actual results

Fatal error,microsoft update explorer ig,so TranslucentTB encounter error"Element not found".

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

plz update this program to suit newest windows.

**Comment by NightDust981989** [comment]
TranslucentTB -Error
TranslucentTB has encountered a fatal error and cannot continue
executing.
Failed to initialize XAML Diagnostics.
0x80070490: Element not found

**Comment by zalfrost** [comment]
same error here

_Windows Version_
![image](https://github.com/user-attachments/assets/95090d88-9a8d-4eec-89d7-9cebc7d85f1c)

_Error_
![Screenshot 2024-09-14 221623](https://github.com/user-attachments/assets/4a5d8ccb-9ff8-4f93-9233-67954ed5b84f)

**Comment by NightDust981989** [comment]
重启explorer即可解决此问题
