### ISSUE TITLE
Feature Request: Slight colored tint option

### ISSUE THREAD

**Issue by JBoxman7** [TranslucentTB/TranslucentTB#107]
I love having a translucent taskbar, but many applications use a very light-colored background. The light background (and as a result, the translucent color) makes the white text of the clock, internet connectivity, and other icons on the right of the taskbar difficult to read. This could be solved by adding the option for the translucent mode to be tinted by an accent color (e.g. light blue) to provide color contrast for the white text. Alternatively, a feature could be added that changes the color of the aforementioned taskbar elements between black and white depending on the value (HSV) of the current taskbar color. For example, if the taskbar is used over a dark application, the text would remain white. However, if the taskbar is used over a light application, the text would become black, providing better contrast/readability.

**Comment by sylveon** [comment]
This already exists but is not exposed with the tray icon: https://github.com/TranslucentTB/TranslucentTB/blob/master/usage.md

You'll need to launch it via command line.
