### ISSUE TITLE
[Bug]: YouTube Music is not available in your area on a VPN

### ISSUE THREAD

**Issue by bossotron13** [TranslucentTB/TranslucentTB#1080]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

![image](https://github.com/user-attachments/assets/03d9ae8b-b669-47cf-88e3-10b02a77b174)
Connect to a vpn? I'm unsure which areas are not available, I was able to watch YouTube videos normally so i'd assume the ip is not banned.

### Expected results

I expected the app to work and be able to listen to music

### Actual results

![image](https://github.com/user-attachments/assets/08b7089a-47ad-4e77-acea-0ea5effe81c5)
I get this error.

### Windows version

Windows 10 May/November 2019 Update (builds 18362 and 18363)

**Comment by sylveon** [comment]
Not a TranslucentTB bug

**Comment by Lamparter** [comment]
How is it even possible to mistake TranslucentTB for a VPN...

**Comment by bossotron13** [comment]
I posted this in the wrong repository lol
