### ISSUE TITLE
Config file located in weird folder

### ISSUE THREAD

**Issue by michidk** [TranslucentTB/TranslucentTB#1088]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

- Install TranslucentTB
- Open the config from the dialogue provided

Will the current config path always be the same?

I use a dotfile manager (https://github.com/Shemnei/punktf/) and I want to be able to automatically deploy the config file. Therefore I must be sure it's always (every version, every install on every other device) going to the same location.

Additionally, a nicer path would be great, so I could find the `settings.json` naturally.

### Expected results

Config path: `C:\Users\<username>\Local\translucenttb\settings.json`.

### Actual results

Config path: `C:\Users\<username>\AppData\Local\Packages\28017CharlesMilette.TranslucentTB_v826wp6bftszj\RoamingState\settings.json`

### Windows version

Windows 11 RTM (build 22000)

**Comment by sylveon** [comment]
The file will always be in that folder, but it can't be moved to a "nicer" path because of [MSIX file virtualization](https://learn.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-behind-the-scenes#appdata-operations-on-windows-10-version-1903-and-later)
