### ISSUE TITLE
[Feature Request]: Auto Shutdown Feature

### ISSUE THREAD

**Issue by kobiek225** [TranslucentTB/TranslucentTB#1092]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

N/A

### Expected results

N/A

### Actual results

N/A

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

Very niche feature but I use StartAllBack which is a taskbar/start menu/system tray overhaul program. However it conflicts with TranslucentTB when it is active. It does however work flawlessly when I start TTB and close TTB manually. Unfortunately making a Batch file to start TTB then kill the TTB task does not work. If TTB had a auto shutdown feature I could set it to like 10 seconds after startup so that it will start and then close itself and would work perfectly with StartAllBack.

**Comment by sylveon** [comment]
This feels like an XY problem. Why not ask to solve the StartAllBack issues instead of asking for a niche feature that most people would never use just to make your workaround more convenient?

**Comment by kobiek225** [comment]
Hence the reason for a feature *request*.  A simple "No, would take too long and would not be used by many" would have sufficed. You didn't have to be a defensive little brony f@ggot. Unalive yourself. Your twitter should be banned btw you furry twink.

**Comment by sylveon** [comment]
I'm suggesting to solve the underlying issue with StartAllBack. Sorry if this may not have initially come across this way.

I have seen the deleted comment, and it violates this repository's [Code of Conduct](https://github.com/TranslucentTB/TranslucentTB/blob/release/CODE_OF_CONDUCT.md). Further violations may result in actions as detailed in the COC. Please keep discussion civil.
