### ISSUE TITLE
[Bug]: error "0x80073D05" when trying to install

### ISSUE THREAD

**Issue by ridler24** [TranslucentTB/TranslucentTB#1094]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

When starting my computer i noticed the microsoft logo in the taskbar was half white. I uninstalled the app and when trying to install from the microsoft store, i get an error. Also get an error with the github installer, the error is "0x80073D05".

### Expected results

Install the app.

### Actual results

The installation failed.

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment]
Reboot before attempting to reinstall the app if you've just uninstalled it.
