### ISSUE TITLE
How do I set it up so that at startup it's dynamic ws?

### ISSUE THREAD

**Issue by McBaws** [TranslucentTB/TranslucentTB#110]
I've tried setting it up in config, but it's not working. 
Sidenote: Also, I have it set to accent = transparent, but when it's on at startup, it opens with blur on. Any way to fix this?

**Comment by sylveon** [comment]
Duplicate of #79

**Comment by ethanhs** [comment]
See https://github.com/TranslucentTB/TranslucentTB/issues/79#issuecomment-316569713
(Closing as a duplicate)
