### ISSUE TITLE
[Bug]: Failed to initialize XAML Diagnostics.  0x800401E3: Operation unavailable

### ISSUE THREAD

**Issue by JustJace1** [TranslucentTB/TranslucentTB#1109]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

launching translucenttb on windows(23H2) gives me this error

### Expected results

launch translucenttb normally

### Actual results

i ran it and i get this error
TranslucentTB has encountered a fatal error and cannot
continue executing.

Failed to initialize XAML Diagnostics.

0x800401E3: Operation unavailable

### Windows version

Windows 10 2004-22H2 (builds 19041-19045)

**Comment by JustAiden9** [comment]
same issue here

**Comment by Kennytops** [comment]
Same issue after updating to the latest windows 11 Ver 24H2

**Comment by BigYous** [comment]
Same issue here tried to run as administrator too but same error came up

**Comment by WkField** [comment]
same error after updating latest windows version

**Comment by Pigeon0v0** [comment]
Try the workaround from #1063

**Edit:** This will disable User Account Control (UAC) on your system and it is not recommended. A restart is required to fully apply the change after you edit the registry.
