### ISSUE TITLE
[Bug]: cannot verify the digital signature of this file

### ISSUE THREAD

**Issue by rellea6** [TranslucentTB/TranslucentTB#1114]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

After unzipping portable-x64.zip, when opening translucenttb.exe, a warning is displayed: Windows cannot verify the digital signature of this file. A file with an incorrect signature or a damaged file may have been installed...

### Expected results

translucenttb.exe **can open** 

### Actual results

a warning is displayed...

### Windows version

Windows 10 May/November 2019 Update (builds 18362 and 18363)

### Other details

My Windows version is **Windows 10 1511**

**Comment by sylveon** [comment]
Your Windows version is too old to run TranslucentTB.
