### ISSUE TITLE
Windows Defending Automatically Flagging This as a Trojan

### ISSUE THREAD

**Issue by finalised** [TranslucentTB/TranslucentTB#112]
As of today, MS's Window Defender automatically removed this claiming it was a trojan. Just thought I would let the developer know.

**Comment by sylveon** [comment]
My defender isn't flagging it, despite having the latest definition updates. Could you retry?

**Comment by denosawr** [comment]
My Defender's also completely chill. Weird.

**Comment by ethanhs** [comment]
Closing, as it is a false positive.
