### ISSUE TITLE
Multiple Monitors Support

### ISSUE THREAD

**Issue by gerbil124** [TranslucentTB/TranslucentTB#113]
Can you add it ? Because right now it seems like it will make the second one transparent no matter what settings you choose ?
Thank You

**Comment by ethanhs** [comment]
We do support multiple monitors. Can you try restarting and see if the issue persists?

**Comment by gerbil124** [comment]
I added this parametr into the shortcut --tint 60606060 and it does some weird things with the second monitor. It works fine with the first one.
In First picture u can see it works fine on 1. monitor than in 2. picture u can see is transparent.(ignore the orange things that is a part of wallpaper).
1. Picture https://ctrlv.cz/ytqX
2. Picture https://ctrlv.cz/KeOd

**Comment by gerbil124** [comment]
I Used this in shortcut to get the color  --tint 60606060

**Comment by matze19999** [comment]
sometimes it doesnt work anymore for the 2. monitor. then a restart of the program helps. Can I provide you any log files?

**Comment by sylveon** [comment]
Due to the lack of activity, I will be closing this issue. If you still experience any issue, feel free to reopen. (btw i think i fixed this in the store branch)

**Comment by ducktested** [comment]
> Can you add it ? Because right now it seems like it will make the second one transparent no matter what settings you choose ? Thank You

Hi, have you solved this problem? I also met this
