### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by Creazawolf** [TranslucentTB/TranslucentTB#115]
Hey guys. How do I uninstall Translucent? By simply deleting the folder in the C: drive?

**Comment by ethanhs** [comment]
That is correct. There is no installation,  hence simply removing it will "uninstall" it

**Comment by bentoBAUX** [comment]
How do you delete the TranslucentTB.2017 one. It wouldn't delete though, an error message pops up saying it is currently being used.

**Comment by ethanhs** [comment]
@bemtoBAUX you can stop the program in task manager then it should be deletable. If that doesn't work, restart, kill TTB and then try again.

**Comment by F-Luggo17** [comment]
You can type Windows key and after that search for TranslucentTB. You will see the application with a dropdown. You can see uninstall button and click it like the photo. (Example with Whatsapp Desktop)


![image](https://user-images.githubusercontent.com/42460315/122087102-fce63d00-cdc9-11eb-89eb-450d92ff931e.png)

**Comment by Justice4emall** [comment]
Gang stalkers are using/ abusing GitHub to cyberattck and Lisa is using GitHub translucent tb to commit serious crime as well as making people missing if not murdering them. LISA WORKED AT STEPHEN SHELTER. POSSIBLY WORKING AT SIMPSONS SHELTER, 1ST COVENT SHELTER, OR SOME OUT REACH PROGRAM IF SHES STILL WORKING WITH SHELTERS IN MINNEAPOLIS, MINNESOTA.

**Comment by Justice4emall** [comment]
I've been approached by a translucent tb person and is still making contact and it been bought to my attention that Lisa have recruiting and abusing those who are in translucent tb. They need help getting the app uninstall for their appearance but she is refusing to do so.
