### ISSUE TITLE
The dynamic window mode doesn't work 

### ISSUE THREAD

**Issue by celeste95** [TranslucentTB/TranslucentTB#119]
The dynamic window mode doesn't work......
![image](https://user-images.githubusercontent.com/33062636/33112393-f90311b0-cf8d-11e7-9675-cfd789ed8d9f.png)

**Comment by ethanhs** [comment]
This is likely the result of the second issue listed here: https://github.com/TranslucentTB/TranslucentTB#known-issues

The line you want to uncomment is https://github.com/TranslucentTB/TranslucentTB/blob/master/TranslucentTB/dynamic-ws-exclude.csv#L18

**Comment by celeste95** [comment]
@ethanhs I restarted my computer and then it works normally. Thank u so much!

**Comment by ethanhs** [comment]
Glad that worked!

**Comment by ethanhs** [comment]
We apparently don't have an issue tracking this known issue, so I'll leave this open.

**Comment by celeste95** [comment]
this problem appeared again and I kill the "ApplicationFrameHost.exe" process then it works normally.
