### ISSUE TITLE
Trigger repaint of taskbar on exit

### ISSUE THREAD

**Issue by ethanhs** [TranslucentTB/TranslucentTB#12]
Right now the user needs to open start to trigger a repaint of the taskbar after exiting. We should do this for them. RedrawWindow did not work for me, but more experimentation is needed.

**Comment by charlesmilette** [comment]
Just send WM_PAINT to the taskbar

**Comment by ethanhs** [comment]
I was thinking of that. The docs for WM_PAINT do start with "The WM_PAINT message is generated by the system __and should not be sent by an application.__" (emphasis mine), but then again, I see no reason why not.

**Comment by charlesmilette** [comment]
SetWindowCompositionAttribute is an undocumented API and should not be
used. Yet we are using it ;)

**Comment by ethanhs** [comment]
Yes, that is true. I will look at this.

**Comment by ethanhs** [comment]
Easiest solution was to just
```
opt.taskbar_appearance = ACCENT_ENABLE_GRADIENT;
SetTaskbarBlur();
```
No chance of further issues.
