### ISSUE TITLE
Taskbar changes color back to stock for a moment while opening start menu

### ISSUE THREAD

**Issue by matze19999** [TranslucentTB/TranslucentTB#121]
You can see here the issue:

https://youtu.be/Xi7oz_-Dc5Q

The taskbar is changing the color while opening the start menu.

**Comment by denosawr** [comment]
This has got to do with the way Windows works and how we apply the effects; unfortunately, we cannot fix this without increasing the poll refresh rate, which will result in dramatically higher CPU usage.
