### ISSUE TITLE
Win10 17063 issue

### ISSUE THREAD

**Issue by Chenastron** [TranslucentTB/TranslucentTB#123]
In Win10 17063, the 'Blur' option makes the taskbar look strange.
Maybe the Win10 APIs have changed and we need to update the code.

**Comment by sylveon** [comment]
No, it's a graphical glitch in the insider build.

Other system areas have this bug too (the language and wifi flyout, tray area, window previews to name a few)

This is a bug in the system renderer so we can't do anything but hope they fix it next insider build. In the meantime you can download the appveyor development snapshots, they have support for fluent. (There is a link in the readme)
