### ISSUE TITLE
extended display & top align issue

### ISSUE THREAD

**Issue by orchaosis** [TranslucentTB/TranslucentTB#124]
this awesome thing works perfectly but ,  when i add my second display (with extend option) and set task bar aligns to top, there is some glitchy unblurred regions occurs at the very top of the screen .

here is an example http://imgim.com/8618incic3201908.png

my main screen 1920x1080 and second 1600x900
also i noticed that when i revert my theme to default windows 10 themes , bug disappears at current session  after rebooting it comes back , hope you understand my language :)

**Comment by sylveon** [comment]
Unfortunately this is a bug in the system compositor. It's not possible to fix on our end,

**Comment by orchaosis** [comment]
hey , maybe not solve issue but i found a way to get rid of that bug ,by  just using slideshows and issue not persist  anymore . then you can set wallpaper etc all works ;D
