### ISSUE TITLE
Not starting Transparent

### ISSUE THREAD

**Issue by wytniga** [TranslucentTB/TranslucentTB#127]
Saving with options Clear and Open at boot selected, but when Windows finishes booting, program opens, but Blur is active choice.

Running Windows 10, Ryzen 5 1600, RX 480 18.1.1

**Comment by jaad34** [comment]
It happens the same to me too. When I restart the PC, it returns to the blur mode. The transparent mode is not fixed at the restart.

Running Windows 10, Versión 1709, SO compilation 16299.192

**Comment by sylveon** [comment]
Open the Windows registry editor, go to
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run. You
should see an entry named TranslucentTB. Double-click on it to edit it
and add " --config
C:\Path\to\where\TranslucentTB\is\stored\config.cfg". Press OK, and
reboot.

Your future changes should now correctly get saved.

2018-01-20 9:08 UTC−05:00, José Antonio <notifications@github.com>:
> It happens the same to me too. When I restart the PC, it returns to the blur
> mode. The transparent mode is not fixed at the restart.
>
> Running Windows 10, Versión 1709, SO compilation 16299.192
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/TranslucentTB/TranslucentTB/issues/127#issuecomment-359174120


-- 
Envoyé de mon Gmail

**Comment by jaad34** [comment]
Thank you, sylveon!!!!
Now, it's ok.
Thanks again.

**Comment by wytniga** [comment]
Awesome! Works now! Thanks so much!
