### ISSUE TITLE
Can I change the default state into clear at boot?

### ISSUE THREAD

**Issue by wyfoffice** [TranslucentTB/TranslucentTB#130]
The default state is blurred, however, I wish to stay in the clear state, is there any way to keep clear without any operation after my computer boots?

**Comment by sylveon** [comment]
Open the Windows registry editor, go to `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`. You should see an entry named `TranslucentTB`. Double-click on it to edit it and add ` --config C:\Path\to\where\TranslucentTB\is\stored\config.cfg`. Press OK, and reboot.

Now all the changes you do via the tray should be kept over reboots

**Comment by wyfoffice** [comment]
@sylveon 
in this way?
"E:\隐藏任务栏\TranslucentTB.2017.3\TranslucentTB.exe" --config.cfg
should I change some parameters in config.cfg?

**Comment by wyfoffice** [comment]
@sylveon 
it didn't work...

**Comment by sylveon** [comment]
Nope, like this:
```
"E:\隐藏任务栏\TranslucentTB.2017.3\TranslucentTB.exe" --config "E:\隐藏任务栏\TranslucentTB.2017.3\config.cfg"
```

**Comment by wyfoffice** [comment]
@sylveon 
after setting this         "E:\隐藏任务栏\TranslucentTB.2017.3\TranslucentTB.exe" --config 
what should I do to keep clear?

**Comment by ethanhs** [comment]
@wyfoffice open the config.cfg file and change `accent=blur` to `accent=clear` (should be the second line).

**Comment by wyfoffice** [comment]
@ethanhs it works! thanks a lot!
