### ISSUE TITLE
when use the blur mod,the taskbar will become weird  

### ISSUE THREAD

**Issue by Anonymous233** [TranslucentTB/TranslucentTB#131]
![4](https://user-images.githubusercontent.com/36198738/35865873-9792a672-0b90-11e8-8e25-a2275c263f39.png)

**Comment by sylveon** [comment]
You're running an Insider Preview according to the desktop watermark. There was a bug with the blur effect in the 17063 and 17074 builds. Upgrade to 17083, this one is fixed.
