### ISSUE TITLE
Discussion and drafting of a TranslucentTB Issue Policy

### ISSUE THREAD

**Issue by denosawr** [TranslucentTB/TranslucentTB#133]
There have been a plethora of issues which ask for support or basic help. If we plan using the issue tracker properly we will need a strict and firm issue policy. Here, let's discuss such an issue policy.
* Questions asking "How do I...", "Can TranslucentTB do..." or "Can you help me with..."  won't be handled here. Such questions should be directed at a support forum; TTB in particular has its own support forums, such as the Discord, and there are a plethora of tech-savvy people and forums out there who can provide help (however you are not guaranteed free, working support). These questions will be closed with a reference to this issue.
* Similarly, questions which are a result of user error, syntax errors or the result of lack of experience with TTB, C++ and similar will be closed with a reference to this issue. (Example: a build error due to MSVC not being installed).
* Issues which have an accompanying investigation which shows the root or cause of the issue should be given priority.
* Feature requests which have an accompanying PR will go into peer review and be passed by the core developers.
* Feature requests and pull requests should be within the scope of TTB (which is to modify or change the colour/appearance of the Windows taskbar). If they are not, these requests should be closed with a reference to this issue. Likewise, the core devs have no obligation to implement pull requests, even if they are within the scope of TTB.
* Please don't submit untested pull requests. We (the core devs) have no obligation to fix issues in PR code. Also, an explanation as to how the PR works would be appreciated.
* Highest priority is testing and ensuring that PR's work as intended. Next comes bugfixing, and finally feature requests.

Here is a template for issues (credit to @sylveon):
```
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: <!-- The current version of TranslucentTB you're using. Open the properties of the TranslucentTB.exe file and look at the details tab to find this out. -->
 - Windows build number: <!-- You can find this by opening winver.exe and checking the number to the right of "OS Build" -->
 - Steps to reproduce: <!-- What you do that triggers the problem -->
 - Expected results: <!-- What should happen -->
 - Actual results: <!-- What happens instead -->
 - Other: <!-- Other things that you feel could help in diagnosing the problem -->
```

**Comment by denosawr** [comment]
Oh, and if this were to be implemented the "Question" label would need to be deleted :D

**Comment by denosawr** [comment]
@ethanhs @sylveon opinions?

**Comment by denosawr** [comment]
Here is a draft Issue Template which we could enforce.

**Issue Template**
Commit/Version: The commit which this error occurs after, or your current commit, or your current version)
Steps to Repro: How you reproduce this bug. Please be as accurate and precise as possible!
Expected: What should happen.
Actual: What happens instead.
Other things to note: Other things which should be said, such as your current operating environment and factors which could be influencing the expected result.

**Comment by sylveon** [comment]
My 2 cents on it:
```markdown
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: <!-- The current version of TranslucentTB you're using. Open the properties of the TranslucentTB.exe file and look at the details tab to find this out. -->
 - Windows build number: <!-- You can find this by opening winver.exe and checking the number to the right of "OS Build" -->
 - Steps to reproduce: <!-- What you do that triggers the problem -->
 - Expected results: <!-- What should happen -->
 - Actual results: <!-- What happens instead -->
 - Other: <!-- Other things that you feel could help in diagnosing the problem -->
```

**Comment by denosawr** [comment]
Yeah, good call for the build number.

**Comment by ethanhs** [comment]
I propose we use @sylveon's template and move this forward.

**Comment by denosawr** [comment]
Seconded.

(Thirded? Is Sylveon in agreement with his own proposal? XD)

**Comment by sylveon** [comment]
Added in `store`
