### ISSUE TITLE
Open at boot not working

### ISSUE THREAD

**Issue by alexander-turner** [TranslucentTB/TranslucentTB#139]
Has anyone else run into this problem?

**Comment by sylveon** [comment]
Can you see TranslucentTB in the task manager's Startup tab?
![](https://charles.getsharex.com/PerfectPleasedRainbowfish)

**Comment by alexander-turner** [comment]
Yeah - two of them, in fact!

**Comment by sylveon** [comment]
Weird, can we see a screenshot of the Startup tab?

**Comment by sylveon** [comment]
Closing as stale. Please reopen if you still have issues.
