### ISSUE TITLE
Cortana Search not recognised as Start Menu Open

### ISSUE THREAD

**Issue by denosawr** [TranslucentTB/TranslucentTB#140]
(This is concerning the `store` branch)
The new start menu hooks don't actually hook Cortana Search; therefore, when you open Cortana Search _or_ when you start searching for something while the Start Menu is open TTB will not activate Dynamic Start.

For reference (both screenshots were taken with Dynamic Start enabled):
https://i.imgur.com/tfJO8C3.png - Start Menu open
https://i.imgur.com/5pQALQv.png - Cortana Search open

**Comment by denosawr** [comment]
(Reason as to why this occurs for anybody interested: the Windows Event Constants which we are using do not actually trigger on Cortana's launch, instead they only trigger on the _Start Menu_ being opened or closed.)
I think the best approach is to, alas, try to look to see if the Start Menu window is in the foreground. I've been playing around with `EVENT_SYSTEM_FOREGROUND` (documented [here](https://msdn.microsoft.com/en-us/library/windows/desktop/dd318066(v=vs.85).aspx)) which is supposed to fire when the foreground window changes, but I have had no success actually getting it to fire. Perhaps, though, that could be a valid approach which doesn't require polling.
@sylveon

**Comment by denosawr** [comment]
The foreground window has changed. The system sends this event even if the foreground window has changed to another window in the same thread. Server applications never send this event.
For this event, the WinEventProc callback function's hwnd parameter is the handle to the window that is in the foreground, the idObject parameter is OBJID_WINDOW, and the idChild parameter is CHILDID_SELF.

`EVENT_SYSTEM_FOREGROUND` according to the linked MSDN page.

**Comment by sylveon** [comment]
The old method, even if it was polling, was also based on the foreground window. Pretty sure this will make #51 resurface.

**Comment by denosawr** [comment]
The current approach, which uses `IAppVisibility -> IsLauncherVisible`, doesn't return true for Cortana, only the start menu. It seems that unless there is also a similar API call for Cortana we'll have to revert back to looking at the foreground window.

**Comment by denosawr** [comment]
Right, so `
bool win32::IsStartVisible()
{
	static bool failed = false;

	TCHAR lp_class_name[MAX_PATH], lp_window_text[MAX_PATH];

	// HWND Start = FindWindow(L"Windows.UI.Core.CoreWindow", L"Cortana");
	static HWND fg_window = GetForegroundWindow();
	
	if (!GetClassName(fg_window, lp_class_name, _countof(lp_class_name))) failed = true;
	if (!GetWindowText(fg_window, lp_window_text, _countof(lp_window_text))) failed = true;
	OutputDebugString(lp_class_name);
	OutputDebugString(lp_window_text);
	
	if (failed)
	{
		LastErrorHandle(Error::Level::Log, L"Retrieval of foreground window failed.");
		return false;
	}
	return (!_tcscmp(L"Windows.UI.Core.CoreWindow", lp_class_name) &&
			!_tcscmp(L"Cortana", lp_window_text));

	/* To-do:
	 * Test on all Windows versions
	 * Test on different locales and languages
	 * Test for if Cortana is disabled
	 */

}
`
seems to work on my machine, however there are a few caveats (look at the to-do comment). I'm not going to push the commit yet, because I'm honestly not very sure if it's a good solution.

**Comment by sylveon** [comment]
Why don't you just do

```cpp
return GetForegroundWindow() == FindWindow(L"Windows.UI.Core.CoreWindow", L"Cortana");
```

Also, prefer the Window class, as it does error handling for you.

```cpp
Window foreground = Window::ForegroundWindow();

return foreground.classname() == L"Windows.UI.Core.CoreWindow" && foreground.title() == L"Cortana"
```

Instead of dropping `IAppVisibility`, we could add another possible taskbar state (Cortana open) and keep `IAppVisibility` for start menu open.

**Comment by denosawr** [comment]
I didn't use the first code example as it would (probably) use more resources finding the window than getting the foreground window and retrieving the class name and window title. That being said, you could probably get away with just finding the window at application launch, but that opens up problems of its own (especially if explorer is restarted or similar). Cheers for the Window class call, by the way - I've been out of the loop for a while :)

Also, Cortana is still the foreground window if Start is open (the normal Start page), so if we can get that to work well then I see no reason to continue using IAppVisibility.

**Comment by sylveon** [comment]
IAppVisibility has the advantage of being an interface, meaning that in the future, as long as this interface is not deprecated, it will always work. Assuming Cortana open == Start open might not.

**Comment by sylveon** [comment]
Added new state for Cortana.

Assuming cortana is foreground window == start opened showed unreliable:
![image](https://user-images.githubusercontent.com/6440374/41374468-38d3b19a-6f21-11e8-808f-a41bd857f099.png)
