### ISSUE TITLE
Taskbar flashing repeatedly after changing opacity

### ISSUE THREAD

**Issue by ShadsHD** [TranslucentTB/TranslucentTB#141]
After I changed the opacity from 0 to 100, my taskbar began flashing back and forth from translucent to the solid color it was set to before running TranslucentTB.exe. Is this a known issue/how can I fix it?

**Comment by sylveon** [comment]
What is the complete content of the config file?

What Windows version are you on?

What TranslucentTB version are you on?

**Comment by ShadsHD** [comment]
Solved it. It turns out for some reason it was running 3 instances of TranslucentTB, so they were switching back and forth between configs. I just killed the extras in Task Manager and it was fixed.

**Comment by sylveon** [comment]
Glad that you figured it out. However that shouldn't happen unless you're using an old version, as we have checks for multiple instances in the latest version.
