### ISSUE TITLE
Multi Screen Support

### ISSUE THREAD

**Issue by George199** [TranslucentTB/TranslucentTB#142]
When used on a docking type laptop with multi screen plugged in it works fine until the laptop is undocked and then docked again. The application will then only run on the display selected as the main display.

The application then needs to be exited and restarted for it to work on both displays.

**Comment by sylveon** [comment]
I've already added this as TODO in version 4. It seems like the display change notification is so fast that we are already done checking for new taskbars when the explorer actually creates it.

**Comment by sylveon** [comment]
Now fixed in V4
