### ISSUE TITLE
Strange behaviour on multi monitor setup in blur mode

### ISSUE THREAD

**Issue by ferceg** [TranslucentTB/TranslucentTB#143]
If I arrange my monitors in a vertically shifted setup (see picture, sorry for hungarian UI) a few lines of pixels in the bottom of Monitor 2 stay unblurred. (Windows 10).
You may have to zoom in to see the unblurred pixels.
After moving back the monitors side by side, the artifacts disappear.

![taskbar](https://user-images.githubusercontent.com/3636937/38975673-0409c032-43af-11e8-979e-790ff4acd2d3.png)

**Comment by sylveon** [comment]
This is a bug in the Desktop Window Manager's rendering code and we can't do anything about it :/

The `store` branch supports Fluent design taskbars on build 17063 and up, which doesn't presents this issue.
