### ISSUE TITLE
Fluent not working

### ISSUE THREAD

**Issue by ConnorB123** [TranslucentTB/TranslucentTB#144]
I'm trying to set the accent to fluent. It's disabled in the selection menu, and when I try to edit the settings file to fluent, the log says `Unknown value found in configuration file: fluent (for key: accent)`. I'm on the latest Windows 10 version, and I'm using the latest version from appveyor.

**Comment by sylveon** [comment]
You need to be on the Insider Builds for this to work right now. When the new major Windows update drops (planned this month), you should be able to use it there.

**Comment by sylveon** [comment]
Also added https://github.com/TranslucentTB/TranslucentTB/commit/328e0ace49b36ef58f1551a599a680060bafa747 which hides them completely when they aren't available.
