### ISSUE TITLE
An error message should be presented when attempting to open a second instance

### ISSUE THREAD

**Issue by c16u** [TranslucentTB/TranslucentTB#145]
If TransluscentTB is already open and a user attempts to open a second instance of it, an error message should be presented.
![image](https://user-images.githubusercontent.com/35878502/39104821-58bf0458-466f-11e8-8cbd-b390cd941486.png)

**Comment by sylveon** [comment]
Actually, what happens right now is that the new instance replaces the other.

Makes it more friendly, since opening a second instance with different
parameters feels like if the second instance actually passed the new
parameters to the first.

-- 
Envoyé de mon Gmail
