### ISSUE TITLE
Does not apply "dynamic" states on windows startup

### ISSUE THREAD

**Issue by Netherspark** [TranslucentTB/TranslucentTB#148]
I run the program from the Command Prompt with **TranslucentTB.exe --dynamic-ws opaque --startup --save-all**, and for the moment it works fine.   But when I restart the PC it loads with the taskbar set to clear, and manually setting it to dynamic in-program does nothing at all.

The only way to make work on dynamic is to do it via the command line, every single time.

I've cheked the Config file but everything looks right.  It shows enabled but it doesn't seem to do anything.

> ; Taskbar appearance: opaque, transparent, or blur (default).
> accent=transparent
> ; Dynamic states: Window States and (WIP) Start Menu
> dynamic-ws=enable
> dynamic-start=enable
> 
> ; Color and opacity of the taskbar.
> color=181818    ; A color in hexadecimal notation. Described in usage.md.
> opacity=0    ; A value in the range 0 to 255.

**Comment by sylveon** [comment]
Open the Windows registry editor, go to `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`. You should see an entry named TranslucentTB. Double-click on it to edit it and add `--config C:\Path\to\where\TranslucentTB\is\stored\config.cfg`. Press OK, and reboot.

**Comment by Netherspark** [comment]
Anything I change in it causes the program to not load at all.  Should I add that to the end of what's already there, or replace the line entirely?  

If this is what was originally there, what should it look like?

> "E:\INSTALLATION FILES\TranslucentTB.2017.3\TranslucentTB.exe"

**Comment by sylveon** [comment]
```
"E:\INSTALLATION FILES\TranslucentTB.2017.3\TranslucentTB.exe" --config "E:\INSTALLATION FILES\TranslucentTB.2017.3\config.cfg"
```

(assuming the config file is located at E:\INSTALLATION FILES\TranslucentTB.2017.3\config.cfg, change it if it's somewhere else)

**Comment by Netherspark** [comment]
Yeah, still the same problem.   The only difference now is that if I click the system tray icon it says it's on "Dynamic" but the taskbar itself is still clear all the time.

It just won't apply the opaque taskbar unless manually started from the command line

**Comment by Netherspark** [comment]
The new one works great.  Thanks alot.
