### ISSUE TITLE
Not saving settings across reboots

### ISSUE THREAD

**Issue by theailer** [TranslucentTB/TranslucentTB#149]
Im starting ttb with this syntax in powershell:
\TranslucentTB.exe --dynamic-ws opaque --save-all --startup
and it works as it's supposed to. But when rebooting it defaults to standard settings, ie blur with no dynamic-ws.

**Comment by StbCG** [comment]
I don't believe this is a bug, have you edited the config.cfg file in the extracted archive?
Also, if this doesn't work, you can always make a .bat or .ps script and run it at startup or add a startup event via the windows task scheduler (I do the latter)

**Comment by sylveon** [comment]
It actually is, the current directory passed at startup is System32 and TranslucentTB assumed that settings are in the current directory. The solution is to manually pass a config parameter.

Open the Windows registry editor, go to `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`. You should see an entry named TranslucentTB. Double-click on it to edit it and add `--config C:\Path\to\where\TranslucentTB\is\stored\config.cfg`. Press OK, and reboot.

**Comment by allan37825** [comment]
I have attempted to edit the registry but I am unsure how to edit the entry to fix the issue.

I tried 

- "C:\Users\NAME\Desktop\TranslucentTB.2017.3\TranslucentTB.exe" \config.cfg

- "C:\Users\NAME\Desktop\TranslucentTB.2017.3\TranslucentTB.exe" --config.cfg

Unfortunately neither work. Could you perhaps specify the path, especially the ending?
Sorry, I am very new to this sort of stuff :)

**Comment by sylveon** [comment]
"C:\Users\NAME\Desktop\TranslucentTB.2017.3\TranslucentTB.exe" --config "C:\Users\NAME\Desktop\TranslucentTB.2017.3\config.cfg

**Comment by insanezz** [comment]
I'm having the same issue as @allan37825. Altough i have my TB folder located in my program files folder. I gues that shouldn't matter tough? 

I've tried these path's as specified by @sylveon 

"C:\Program Files (x86)\TranslucentTB.2017.3\TranslucentTB.exe" --config

"C:\Program Files (x86)\TranslucentTB.2017.3\config.cfg"  <- this one only opens the config file and not the program at least for me. 

Is there something i'm doing wrong? I'm also new to this stuff but i really like the program :).

**Comment by sylveon** [comment]
It does matter because the program doesn't haves write permission to the config file.

**Comment by insanezz** [comment]
@sylveon ah, well just because i wanted to try it out. I put the folder inside of my documents folder instead of program files. But it had the same result, it didn't open the config file for me when i rebooted. My documents folder is on the D drive tough. Not sure if that also matters. 

But it works just fine when using the preview build, also when the folder is in my program files. Just thought i'd let you know.

**Comment by theailer** [comment]
Thanks for the info, it works like a charm.

**Comment by iolqc** [comment]
Hi, there is no entry named TranslucentTB for me in HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run

TranslucentTB automatically start at boot time but does not remember my settings (accent color)

What should i do? 

Thanks

**Comment by sylveon** [comment]
This issue is old and guidance provided isn't up to date. Can you open a new issue?
