### ISSUE TITLE
Option to change opacity of taskbar to match that of startmenu fullscreen in dynamic start

### ISSUE THREAD

**Issue by NeeharVijay** [TranslucentTB/TranslucentTB#150]
Full screen start menu has a "transparent overlay", match the same overlay in taskbar when stat menu is activated in dynamic start

activate start full screen and put dynamic start and you will see what i mean

**Comment by NeeharVijay** [comment]
![capture 1](https://user-images.githubusercontent.com/37122724/40052897-8f9eea7e-583f-11e8-8217-4cf4bf52d51a.PNG)

**Comment by NeeharVijay** [comment]
![capture 1](https://user-images.githubusercontent.com/37122724/40053050-1829f1b8-5840-11e8-9a16-e75a330cf106.PNG)

**Comment by sylveon** [comment]
Fixed in V4. Dynamic start now has its own color and accent options.

**Comment by nhrvi** [comment]
@sylveon can you delete this issue?
This comes up when I google my name. I've since changed my username.
