### ISSUE TITLE
Config does not load on auto startup with windows

### ISSUE THREAD

**Issue by zekroTJA** [TranslucentTB/TranslucentTB#152]
I've set some settings in the config file like color and opacity, which are not getting loaded if the tool starts with windows boot.
If I start the tool manually, the config is loaded correctly.

This is how my `config.cfg` looks like:
```cfg
; Taskbar appearance: opaque, transparent, or blur (default).
accent=transparent

; Color and opacity of the taskbar.
color=0x1e1e1e    ; A color in hexadecimal notation. Described in usage.md.
opacity=75    ; A value in the range 0 to 255. 255 = opaque 0 = transparent

; dynamic windows: opaque, transparent, or blur (default).
; dynamic-ws=blur
; dynamic windows can be used in conjunction with a custom color and non-zero opacity!

; dynamic start
dynamic-start=false
```

After boot, the tool is set to `blur` mode also, which is not enabled in the config.<br>
![](http://zekro.de/ss/2018-05-23_20-05-32.png)

Maybe, I will look for it in the code later and send a pull request if I found a solution.

Version is latest `2017.3`.

**Comment by zekroTJA** [comment]
Okay, I got what the problem is:

The config file is read relatively where the current work directory is.

So, for example, the .exe is in the following path:
> C:/Programs/TTB/TranslucentTB.exe
Then it will read the config file correctly:
> C:/Programs/TTB/config.cfg
Now, if you start the tool from another path (what happens if windows starts it on startup), the script will be read from the current work directorie, which is for example:
> C:/Windows/Windows32

Maybe there should be a way to se the path of the config in the registry or change the current work directory to the executables location.

**Comment by sylveon** [comment]
Yes, add `--config C:/Programs/TTB/config.cfg` to the TTB startup entry in the registry. (under `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`)


V4 fixes this issue by hardcoding the file to be read from the current user's appdata folder.

**Comment by zekroTJA** [comment]
Okay, nice. I've tried setting the working directory manually to the current executables path, but this was not successful ^^
Thanks for the answer :)
