### ISSUE TITLE
Doesn't go clear after a restart

### ISSUE THREAD

**Issue by sassanix** [TranslucentTB/TranslucentTB#153]
I have to manually select clear every time my windows starts, is there a fix?

**Comment by sylveon** [comment]
Yes, there is.

Open the Windows registry editor, go to `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`. You should see an entry named TranslucentTB. Double-click on it to edit it and add ` --config "C:\Path\to\where\TranslucentTB\is\stored\config.cfg"`.

The final entry should look like this:

    "C:\blabla\TranslucentTB.exe" --config "C:\blabla\config.cfg"

Reboot.

Now your settings should be preserved when Windows restarts in the future.
