### ISSUE TITLE
Dynamic Windows does not work after not using the computer for some time

### ISSUE THREAD

**Issue by maxloh** [TranslucentTB/TranslucentTB#154]
Here is my shortcut launching TranslucentTB
`TranslucentTB.exe --tint FF101010 --transparent --dynamic-ws tint --no-tray`

After leaving the computer for an hour or longer, the Dynamic Windows function does not work as it supposed to be. The task bar should be transparent when no windows are maximised but instead, it is FF101010 all the time. 

Killing the app in task manager and open TranslucentTB again does not fix it. Only log out and log in again can fix the problem. The appveyor builds have the same problem.

I am using Surface Pro 4 i5 256GB with Windows 10 Pro 17134.48 installed.

**Comment by sylveon** [comment]
This is a known issue caused by UWP apps. Adding `ApplicationFrameHost.exe` to the dynamic blacklist fixes this issue, at the cost of dynamic windows not working with UWP apps. Another solution is to get the latest development build, which fixed this issue correctly.
