### ISSUE TITLE
Google Chrome border extends too high

### ISSUE THREAD

**Issue by SeinopSys** [TranslucentTB/TranslucentTB#156]
I keep my taskbar at the top of the screen, and as of Chrome 67 (Stable) through Chrome 69 (Canary) the window has a strange top border when the "Clear" option is selected. This is not visible when using any other display setting.

>![out](https://user-images.githubusercontent.com/3200580/40795644-ff09855c-6502-11e8-99bd-29de18a55fe1.gif)

I'm not sure I could report this to the Chromium bug tracker, so I figured I'd ask here if this is something that can be sorted out. Until then I'll stick with the "Dynamic Windows" option which does not seem to have this issue.

Using Windows 10 version 1803, build 17134.81

**Comment by sylveon** [comment]
This is most probably part of the bug that Chrome and Electron apps in general have in 1803 when there's a custom frame. It has been fixed in the recent Insider builds.

**Comment by denosawr** [comment]
I can second that this is probably the Chromium bug which results in a weird frame. [This Reddit link](https://www.reddit.com/r/Windows10/comments/8h3eqo/windows_1803_white_bar_across_top_of_maximized/) documents some possible remedies, including changing the shortcut to launch the application in Windows 8-compatible mode (which shouldn't really affect Chrome at all). Some people have recommended just restoring and maximising the window.

Also, please could you do some more testing to see if it _just_ occurs when the Clear option is selected? According to the linked thread, it's more or less random and concerns _maximising_ the window, which TTB doesn't really affect at all.

**Comment by SeinopSys** [comment]
I've modified my shortcut to start TranslucentTB in Dynamic Windows mode and it looks like when started via the shortcut the window's top side sometimes is visible through blur even with that option, but I can't reproduce this reliably. When changing options during run time all options except for Clear hide the extra border properly.

Without TranslucentTB running the border is completely invisible (thanks to the taskbar not being see-through), so I'm hesitant to submit this as a bug anywhere else because it's technically an issue made apparent by a 3rd party program. If it's been fixed i na later build of windows as you say then I guess there isn't much point in keeping this issue open.

**Comment by denosawr** [comment]
Have you tried changing the compatibility settings to run in Windows 8 mode? Some people have gotten success out of that.

But, I honestly don't think this is due to TranslucentTB. It's a clear bug in Chromium and, like I said, nothing which we are doing to the taskbar would likely be a culprit to the issue.

**Comment by SeinopSys** [comment]
Fair enough, I'll have a look at the possible solutions. Thank you for your suggestions.

**Comment by sylveon** [comment]
I think it's also possible to disable "Custom-drawn Windows 10 Titlebar" in chrome://flags @SeinopSys

**Comment by Licheng-Xu** [comment]
Thanks.

**Comment by Rubture** [comment]
Thank you very much sylveon, been trying to fix this for a while now!!! Only solution that works!!!

**Comment by axe-murderer** [comment]
this problem is back because chrome has removed the "Custom-drawn Windows 10 Titlebar" flag.

however, you can add "--disable-features=Windows10CustomTitlebar" to the end of your chrome shortcut instead and it will have the same effect as disabling the flag through chrome://flags.

**Comment by Rubture** [comment]
> however, you can add "--disable-features=Windows10CustomTitlebar" to the end of your chrome shortcut instead and it will have the same effect as disabling the flag through chrome://flags.

I've been looking for a new solution since last week, awesome that you found one already!!!
For people who don't know how this works:

Go to your shortcut location, right click and go to properties.
In properties go to the end of the "target" line (keep all the text that is there) and paste:" --disable-features=Windows10CustomTitlebar" without the " and with one space before the -- otherwise it won't work. 

Awesome work axe-murderer (wow complementing a murderer feels weird)

**Comment by Rubture** [comment]
AAAAAND it's back, again... Solution anyone?

**Comment by sylveon** [comment]
Except "not using Chrome" I don't think there's much of a solution. Might be possible to create a bug on their bug tracker: https://bugs.chromium.org/p/chromium/issues/list

**Comment by axe-murderer** [comment]
I used the patch found here.

https://www.reddit.com/r/chrome/comments/bgtkzd/chromeflagswindows10customtitlebar_removed/elqjj9o/

scroll down for the reupload. it worked for me.

**Comment by Rubture** [comment]
Yes worked, don't really know what it did thought, since part of the text in the messagebox was in Russian. Hopefully it will keep a little longer this time, Thanks again!

**Comment by axe-murderer** [comment]
hey so my previously linked solution still works but it breaks netflix for me. just in case anyone else is dealing with this issue
