### ISSUE TITLE
Dynamic-ws isn't being saved in config file.

### ISSUE THREAD

**Issue by NickVandenberghe** [TranslucentTB/TranslucentTB#158]
When using the cmd and giving the tint , the dynamic-ws works.
But when starting the program, it reads the config.cfg file. 
However this file saves options, but it doesn't save the settings for dynamic-ws.
(I think the dynamic-ws tint is overwritten by the normal color).

Even when assigning a color to the tint and assiging the tint to dynamic-ws in cmd. It still doesn't save this configuration option in the config.cfg file.
I know a bit of code, but sadly enough i can't program with cpp files. Otherwise i would've fixed it myself :)

**Comment by denosawr** [comment]
Apologies for the issue, but it's been fixed in later releases (look at the `store` branch). If you want to give them a test drive, feel free to download the AppVeyor builds or compile the branch yourself!

I'm closing for now, but if the issue persists on `store` feel free to reopen it.
