### ISSUE TITLE
"I can't get clear to open on startup" - an address of this issue and possible solutions

### ISSUE THREAD

**Issue by denosawr** [TranslucentTB/TranslucentTB#159]
There seem to be a plethora of questions concerning how TTB cannot seem to get a certain window state to open up automatically on startup. This issue has been addressed in the latest version on the `store` branch (feel free to either build it yourself or to download the AppVeyor builds to test it out), but in the meantime, here are a temporary solution which may be able to help.

**Fix**
Open the Windows registry editor, go to `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`. You should see an entry named TranslucentTB (provided you've enabled autostart). Double-click on it to edit it and add --config `C:\<path to where TTB is stored>\config.cfg`.
The final entry should look like this:
`C:\<path>\TranslucentTB.exe" --config "C:\<path>\config.cfg`
Now reboot, and profit!

**Semi-automated fix for the lazy ones among us**
[Download this file](https://gist.githubusercontent.com/denosawr/2640316a3ad2c1bb209a2cc810c94dd4/raw/e3de804aa37000fe3298f70b5b42aafbb37df817/FixTTB.bat), run it, and follow its commands. Does the same thing as the above fix: allows you to drag-and-drop two files into the command prompt window and gives you a command you can run as Administrator to update the registry.

**Things to Note**
TTB reads the config.cfg file from the path you specify above, or from the local folder. It also tries to write there. However, some folders require write permissions under Windows. For instance, you cannot write to `C:\Program Files` or `C:\Windows` without administrator permissions, which TTB may not be running with. To fix this, you can put the `config.cfg` file somewhere you _do_ have write permissions (like your Documents folder) and change the above registry command to be follow that. Alternatively, use the "semi-automated fix for the lazy ones among us".

**Comment by sylveon** [comment]
Fixed in version 4

**Comment by Joeyet** [comment]
i tried everthing but it didn't work, and i turned to microsoft soft to download one,it is okay to open at boot now~~~

**Comment by maxlm128** [comment]
I also tried everything above, the download link doesnt exist anymore, the command doesnt work (is says --config is a unexpected token when trying that command in terminal" installing it from every possible source didnt get it to work either. Putting the exe in the startup folder (C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup) works, but it throws errors and in addition it shows the "Welcome to TranslucentTB". Regarding the "Fixed" comment, in my experience, nothing seems fixed, everything is broke and doesnt work.
