### ISSUE TITLE
Handle explorer restart in Tray

### ISSUE THREAD

**Issue by ethanhs** [TranslucentTB/TranslucentTB#16]

**Comment by olliethepikachu** [comment]
Sorta different but you could recreate all your HWNDs every few seconds. That would be more CPU-intensive but it would remove the need for a button.

**Comment by ethanhs** [comment]
Actually there is a global message when the taskbar gets recreated, so I just need to implement it.

**Comment by charlesmilette** [comment]
The tray also allows for configuration of the effect, to close the tool and perhaps a future about and color picker dialog. The message queue could also be useful when auto-detecting system colors.

**Comment by charlesmilette** [comment]
Hiding the icon on user demand is not hard. Simply not initializing the tray stuff but still calling CreateWindow and ShowWindow would allow the program to operate normally without any tray icon

**Comment by charlesmilette** [comment]
And also what I think he meant is to correctly recreate the tray icon when explorer restarts.

**Comment by ethanhs** [comment]
@charlesmilette there was another request for a command line switch to disable the tray icon. I don't really understand that, as how are you supposed to exit, but...

**Comment by charlesmilette** [comment]
People probably want to have the thing always running and never think about it again

**Comment by PFCKrutonium** [comment]
Yah, make a shortcut to it in your startup folder, set option --no-taskbar-icon and boom, you never think about it ever again.

**Comment by charlesmilette** [comment]
If we do this, we need to handle configuration parsing way earlier. Nothing real hard, just move a function call.

**Comment by ethanhs** [comment]
Noted, if you have your config work nearly done please open it up and I will merge, then I can start working on refactor.

**Comment by charlesmilette** [comment]
Almost done! Only a couple of things here and there, some testing and then it's ready.

**Comment by ethanhs** [comment]
Can I ask where you are on this? I understand being very busy haha.

**Comment by charlesmilette** [comment]
The config I was referring earlier is the one I failed, it got superseded by @olliethepikachu's implementation. You can go on with the refactor and I will implement this after you are done.

**Comment by olliethepikachu** [comment]
@charlesmilette My implementation? I don't have an implementation of a config file... Perhaps you mean @MrAksel 's implementation?

**Comment by ethanhs** [comment]
Regardless, I am on spring break in just over a week, I should be able to finish the refactoring then and maybe work on a feature or two. TBH, I have another program idea that I really want to work on (it inserts emoji in Windows based on the Github :emoji:  style). But I will certainly commit some of my break to this.

**Comment by olliethepikachu** [comment]
Hey, the emoji idea is pretty cool. I might just steal that idea from you :D

Get Outlook for iOS




On Fri, Mar 17, 2017 at 2:51 PM +0800, "Ethan" <notifications@github.com> wrote:












Regardless, I am on spring break in just over a week, I should be able to finish the refactoring then and maybe work on a feature or two. TBH, I have another program idea that I really want to work on (it inserts emoji in Windows based on the Github :emoji:  style). But I will certainly commit some of my break to this.

**Comment by ethanhs** [comment]
Itll be open source and Ill be releasing it in a couple weeks. Also please dont steal it. Hahaha

**Comment by olliethepikachu** [comment]
I'm joking, haha. I might use the idea of :command: though, but I certainly won't steal the idea.

Get Outlook for iOS




On Fri, Mar 17, 2017 at 4:00 PM +0800, "Ethan" <notifications@github.com> wrote:












Itll be open source and Ill be releasing it in a couple weeks. Also please dont steal it. Hahaha

**Comment by denosawr** [comment]
Isn't this already implemented in `develop`?

**Comment by ethanhs** [comment]
At least on my machine, the taskbar transparency stays, but the tray icon does not.

**Comment by charlesmilette** [comment]
We implemented transparency staying but not the tray icon. Should be easy enough.
