### ISSUE TITLE
EXE file missing?

### ISSUE THREAD

**Issue by ModDM** [TranslucentTB/TranslucentTB#160]
Dear Sir / Madam,

I thought this program could be opened in Microsoft Windows? Where is the EXE file? It seems to be missing. Your documentation speaks about TranslucentTB.exe, but it is not present.
Can you help? I have no idea how to open this program on my computer.

With thanks and regards,

ModDM

**Comment by sylveon** [comment]
You downloaded the source code. Binary (.exe) releases are available at https://github.com/TranslucentTB/TranslucentTB/releases

**Comment by ModDM** [comment]
Thank you, simple solution. I have it running and working now.
