### ISSUE TITLE
Feature suggestion: hide the border from "show desktop" button

### ISSUE THREAD

**Issue by pedrocab** [TranslucentTB/TranslucentTB#162]
Love the new transparent taskbar on my computer, but the border from "show desktop" button on windows break the magic a little.

![capture](https://user-images.githubusercontent.com/5692711/41552147-4a8a05ec-7304-11e8-8588-5b0636223c78.PNG)

Can you do something about it in a new version? =)

**Comment by sylveon** [comment]
It's already implemented for the next version:

![](https://yiff.forsale/PersonalBlankGrayling)
