### ISSUE TITLE
Dynamic Windows doesn't reset after locking PC

### ISSUE THREAD

**Issue by DiNitride** [TranslucentTB/TranslucentTB#163]
Hi, I run TTB in Dynamic Windows mode. There seems to be be a bug where upon locking and then unlocking my PC, on my main monitor the task bar stays blurred (As if there was a maximised window). Restarting TTB does not fix.

Is this a known issue/reproducible, or is it just my PC being my PC and breaking for the sake of it. 

Edition: Windows 10 Home
Version: 1803
OS Build: 17134.112

**Comment by ethanhs** [comment]
See https://github.com/TranslucentTB/TranslucentTB#known-issues.Feel free to leave a comment if none of those work arounds work.
