### ISSUE TITLE
--dynamic-start don't work on build 17134

### ISSUE THREAD

**Issue by Vixb1122** [TranslucentTB/TranslucentTB#166]
Command:` .\TranslucentTB.exe --tint e64577d3 --dynamic-ws tint --dynamic-start --save-all`

The taskbar is still transparent when the start menu is opened.
![snipaste_2018-06-27_11-48-48](https://user-images.githubusercontent.com/17810492/41951966-32020dfa-7a00-11e8-82ef-28b9aa5d9b8f.jpg)
![snipaste_2018-06-27_11-49-17](https://user-images.githubusercontent.com/17810492/41951957-298fb5b4-7a00-11e8-9791-bc4b196666e5.jpg)

**Comment by sylveon** [comment]
Could you try the latest AppVeyor build? Version 4 has a lot of improvements related to detection of start menu, your issue might already be fixed.

**Comment by denosawr** [comment]
Please elaborate on what you mean, ‘it took too long to open the task manager’? I’m not understanding at all, haha.

**Comment by Vixb1122** [comment]
@denosawr In the Task Manager, if I don't open this app, it only takes half a second to load the list of processes. Otherwise, it takes a few seconds to load the list of processes.

**Comment by denosawr** [comment]
I don’t think that this is an issue with TTB. Could you try to reproduce it on another machine (preferably a clean one)?

All the core contributors cannot seem to reproduce this issue.

On another note, is the title issue resolved (`--dynamic-start`)?
