### ISSUE TITLE
How do I make it start in "Dinamic Windows" by default?

### ISSUE THREAD

**Issue by psydex** [TranslucentTB/TranslucentTB#169]
![screenshot_1](https://user-images.githubusercontent.com/5594251/42413421-42e74d08-8228-11e8-86a0-482afc7ee522.jpg)

**Comment by denosawr** [comment]
Check #159. Feel free to reopen if the issue persists after.

**Comment by psydex** [comment]
I don't have issues, i just need to know how to edit the config so program starts in Dynamic Windows mode

**Comment by denosawr** [comment]
Try opening the config.cfg file found in the folder TTB.exe is located.

**Comment by psydex** [comment]
Yes , I know where config is located but what do i comment out to make it run in this mode every time?
