### ISSUE TITLE
TranslucentTB.exe

### ISSUE THREAD

**Issue by DreadnoughtZx** [TranslucentTB/TranslucentTB#170]
Clearly, there is no such thing as TranslucentTB.exe anywhere in the files. It was said that it has only three files while one of them are the TranslucentTB.exe but now it's a lot and full of non-openable files, however, there is no such thing as close to TranslucentTB.exe.

**Comment by denosawr** [comment]
You must have downloaded the source code behind the application. You can find the precompiled releases [here](https://github.com/TranslucentTB/TranslucentTB/releases).

**Comment by DreadnoughtZx** [comment]
it finally worked, thank you very much :)))))
