### ISSUE TITLE
[BUG] lose opacity value in config.cfg

### ISSUE THREAD

**Issue by Cologler** [TranslucentTB/TranslucentTB#171]
step:

1. set `opacity=50` in config.cfg
2. run TranslucentTB.exe
3. change mode (for example, `clear` to `blur`)
4. exit TranslucentTB.exe
5. **opacity is lost**

Is any better way to edit opacity value ? (since `opacity=0` make system time become unreadable).

**Comment by sylveon** [comment]
Could you please try the development builds, to see if it's fixed there?

**Comment by Cologler** [comment]
fixed in dev build
