### ISSUE TITLE
Doesnt start on boot even the option for start on boot was enabled 

### ISSUE THREAD

**Issue by jvrang** [TranslucentTB/TranslucentTB#174]
I looked into my startup programs on task manager and enabled on startup. But every time I reboot it wont open automatically unless I manually open the exe file

**Comment by denosawr** [comment]
This is addressed in #159. If the issue still persists, feel free to bring it up there.

**Comment by mcbarker69** [comment]
This program no longer runs on startup. I've tried all of the solutions suggested here, and several other fixes, including uninstall, and reinstall and config; and manually creating a shortcut, and placing it in the startup folder. "Open at boot" is checked, it's showing in CCleaner's startup menu, and also in Task Manager's startup list. I'm wondering if this has anything to do with MS latest W10 update (which broke at least one of its own apps). Your #159 solution changed the entry in the StartupApproved\Run folder in the registry, but nothing in the StartupApproved\StartuoFolder. I would imagine that there's supposed to be an entry there.
