### ISSUE TITLE
TranslucentTB no longer loads on startup

### ISSUE THREAD

**Issue by mcbarker69** [TranslucentTB/TranslucentTB#177]
This program no longer runs on startup (It doesn't load on reboot). I've tried all of the solutions suggested here, and several other fixes, including uninstall, and reinstall and config. Also, manually creating a shortcut, and placing it in the startup folder. "Open at boot" is checked, it's checked to load on startup in CCleaner's startup menu, and also in Task Manager's startup list. I'm wondering if this has anything to do with MS latest W10 update (which broke at least one of its own apps). Your #159 solution changed the entry in the StartupApproved\Run folder in the registry, but nothing in the StartupApproved\StartupFolder. I would imagine that there's supposed to be an entry there. My Windows 10 build is 1803  OS Build 17134.167. If you need more detailed information, let me know specifically what you need.

**Comment by sylveon** [comment]
Is there anything in the reliability monitor about a crash of the application?

**Comment by mcbarker69** [comment]
No. Since the latest W10 update, devicecensus.exe has been crashing regularly, but no mention of TranslucentTB. Chkdsk and sfc didn't find any errors either. Normally, if your program was trying to load, and failed, there would be some indication in the Computer Management Event Logs, but TTB doesn't show up. It seems that it just isn't attempting to load on startup - Possible conflict between W10 and your Load at boot routine?

**Comment by ABBZ120** [comment]
I am having the same problem, the program won't run on startup

**Comment by Alexusson** [comment]
Hello,

I have a similar but little different situation then users above! I already tried to implement the registry suggestion from #159 but without success.

I am doing my own build (19H1 1903) and throughout the SetupComplete.cmd I preinstalled TranslucentTB v5.0. Translucent is installed successfully but I could not succeed to get Translucent startup at the first login even I do a registry tweaks as you suggested above!

Registry tweaks I have tried to implement are on these two locations
[**HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run**]
"TranslucentTB"="\"C:\\Program Files (x86)\\TranslucentTB\\TranslucentTB.exe\"

[**HKEY_USERS\S-1-5-21-831427557-4018788969-239127199-1002\Software\Microsoft\Windows\CurrentVersion\Run**]
"TranslucentTB"="\"C:\\Program Files (x86)\\TranslucentTB\\TranslucentTB.exe\"

I know the second entry is not the real one but try even there. I also try with the path to the my config file 
--config \"C:\\Program Files (x86)\\TranslucentTB\\TranslucentTB\\config.cfg\"" but with the same result. I even manually check "Open at boot" option from the icon tray and then export from the registry. Same result.

Also, I put .csv file to %AppData%\Roaming\TranslucentTB to bypass GLP license which is also OK and works as it should!

Can you help to solve my situation and get Translucent at first login? 
Thanks in advance

**Comment by sylveon** [comment]
Have you tried the latest version available on GitHub and made sure that the Visual C++ 2017/2019 redistributable is installed? https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by mcbarker69** [comment]
I'm using v5.0.0.0, and it works perfectly. I had the same problems that your having with older versions of the utility. Just make sure you've checked the "**Open at boot**" and chosen "**Clear**" on the other options.

**Comment by CitizenDroid** [comment]
If your TranslucentTB won't enable at start up create a short cut to TranslucentTB then paste it in the startup folder here. C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup 

if you have an issue finding TTB uninstall your version and go download portable version and unpack it to your c drive in its own TTB folder then make short cut in that folder and drag it over to the startup folder above.
would have been handy that an entry was added to the settings cfg ! werird whay it isn't listed there!!

**Comment by maxlm128** [comment]
> If your TranslucentTB won't enable at start up create a short cut to TranslucentTB then paste it in the startup folder here. C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup
> 
> if you have an issue finding TTB uninstall your version and go download portable version and unpack it to your c drive in its own TTB folder then make short cut in that folder and drag it over to the startup folder above. would have been handy that an entry was added to the settings cfg ! werird whay it isn't listed there!!

It works, but its not a very good solution, since the "Welcome to TranslucentTB" windows pops up when the exe is executed.

**Comment by CitizenDroid** [comment]
Translucent got fixed ages ago so the normal install from Microsoft store should work ok have you tried that if your running latest windows just make sure to remove every trace of the portable version. including the shortcut before installing the app though I prefer the portable version also I placed my portable version in its own folder on C drive then made a short to it and pasted that in C:\ProgramData\Microsoft\Windows\StartMenu\Programs\ Startup folder not the actual program itself in case that's what you did though not sure if that would make any difference to your pop up! do you mean it pops up when windows loads which is just its splash screen which is normal and is only present for a second or two my other app Glass2K does the same though |I think you can edit the cfg to stop that if you want not sure how though.

you can check my  translucent cfg file in case yours differs in some way.

// See https://TranslucentTB.github.io/config for more information
{
  "$schema": "https://TranslucentTB.github.io/settings.schema.json",
  "desktop_appearance": {
    "accent": "clear",
    "color": "#00000000",
    "show_peek": false,
    "show_line": false
  },
  "visible_window_appearance": {
    "enabled": false,
    "accent": "clear",
    "color": "#00000000",
    "show_peek": true,
    "show_line": false,
    "rules": {
      "window_class": {},
      "window_title": {},
      "process_name": {}
    }
  },
  "maximized_window_appearance": {
    "enabled": false,
    "accent": "acrylic",
    "color": "#00000000",
    "show_peek": true,
    "show_line": true,
    "rules": {
      "window_class": {},
      "window_title": {},
      "process_name": {}
    }
  },
  "start_opened_appearance": {
    "enabled": false,
    "accent": "normal",
    "color": "#00000000",
    "show_peek": true,
    "show_line": true
  },
  "search_opened_appearance": {
    "enabled": false,
    "accent": "normal",
    "color": "#00000000",
    "show_peek": true,
    "show_line": true
  },
  "task_view_opened_appearance": {
    "enabled": true,
    "accent": "normal",
    "color": "#00000000",
    "show_peek": false,
    "show_line": true
  },
  "battery_saver_appearance": {
    "enabled": false,
    "accent": "opaque",
    "color": "#00000000",
    "show_peek": true,
    "show_line": false
  },
  "ignored_windows": {
    "window_class": [],
    "window_title": [],
    "process_name": []
  },
  "hide_tray": true,
  "disable_saving": false,
  "verbosity": "warn"
}

**Comment by hahaha9510-design** [comment]
> > If your TranslucentTB won't enable at start up create a short cut to TranslucentTB then paste it in the startup folder here. C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup
> > if you have an issue finding TTB uninstall your version and go download portable version and unpack it to your c drive in its own TTB folder then make short cut in that folder and drag it over to the startup folder above. would have been handy that an entry was added to the settings cfg ! werird whay it isn't listed there!!
> 
> It works, but its not a very good solution, since the "Welcome to TranslucentTB" windows pops up when the exe is executed.

> On the startup menu, right-click TranslucentTB > property > select RUN menu > Minimize > Apply

**Comment by Xeedius** [comment]
I found a workaround

- Press [Windows] + [R]

- Type `Shell:AppsFolder` then press "OK".

- Create a shortcut of the TranslucentTB app anywhere you like and name it something simple. I named it TTB.

- Create a BAT file at the same path and put this inside then modify it accordingly =>   `start "" "C:\PathToWhereTheShortcutIs\TTB.lnk"`    where TTB is the name of your shortcut. (This BAT file is gonna be used to start the TranslucentTB shortcut)

- Create a VBS file at the same path and put this inside without modification =>   `CreateObject("Wscript.Shell").Run """" & WScript.Arguments(0) & """", 0, False` (This VBS file is gonna be used to run the BAT file silently)

- Open Task Scheduler and from the toolbar choose Action > Create Basic Task.

- Type any name and press next.

- Choose "When I log on" then choose "Start a program".

- Type `wscript.exe` in the Program/script field.

- In the Add arguments field, add `C:\PathToWhereTheShortcutIs\TTB.vbs" "C:\PathToWhereTheShortcutIs\TTB.bat` and modify the paths accordingly.

- Hit Save, sign out of your PC then sign back in to test. Voila!
