### ISSUE TITLE
When the taskbar on the top the screen and on the "clear" mode, a gray strip will appear.

### ISSUE THREAD

**Issue by Licheng-Xu** [TranslucentTB/TranslucentTB#179]
![Imgur](https://i.imgur.com/bTI1nCH.png)
OS: win10 1803;
TranslucentTB: 2017.3

**Comment by denosawr** [comment]
Duplicate of #156. Closing, as possible fixes have been addressed there, and the fix depends on the folks making Chromium, not us.
