### ISSUE TITLE
Blur also uses a bit of the second monitor.

### ISSUE THREAD

**Issue by pasi123567** [TranslucentTB/TranslucentTB#183]
If you use blur and you have another monitor, some colors of that monitor are also seen on the taskbar. Havin totaly different colors this is kind of bothering me.
Also the bottom of the taskbar is not fully blured.
https://i.imgur.com/KrlzsbX.png

**Comment by denosawr** [comment]
Alas, this isn't something which we can solve. TTB actually gets Windows to draw the taskbar as blurred (through a Windows method call), and unfortunately Windows' rendering is the cause of this bug.

TL;DR: nothing we can do, sorry :(
