### ISSUE TITLE
Effect resets sometimes

### ISSUE THREAD

**Issue by ChuckxxNorris** [TranslucentTB/TranslucentTB#185]
I use the Program without start-parameters just with context menu settings and auto startup.

Sometimes, I don't exactly know when, but I think its happening after I play a game in fullscreen the effect resets to blur instead of clear.

I am running Windows 10 Version 1803 Build 17134.191

**Comment by denosawr** [comment]
Assuming you have Dynamic Windows open, and you're not running the development branch (`store`), this is a duplicate of #184. If not, feel free to reopen.

**Comment by ChuckxxNorris** [comment]
Actually, this also happens using the clear mode and not the Dynamic Windows mode.
Same Problem?

**Comment by denosawr** [comment]
So you mean that even if TTB is set to Clear mode with Dynamic Windows off, after playing a game in fullscreen the effect will be blurred but not clear? Could you send a video to show this effect happening (to make it easier to pinpoint)?

**Comment by ChuckxxNorris** [comment]
I tested it out a little and I can say for sure that the effect resets when I reboot my PC. 
I am also pretty sure it does reset sometimes randomly but so far I was not able to determine the source.

**Comment by sylveon** [comment]
I think this is happening because of UWP apps, which has been fixed in the latest version. If it still occurs, feel free to reopen this issue.
