### ISSUE TITLE
More intense Blurr

### ISSUE THREAD

**Issue by pasi123567** [TranslucentTB/TranslucentTB#186]
There is an option in the older taskbartool program to make the taskbar even more blurry. The thing is I need that as it would fit togetehr way better with my dektop background. Sadly taskbartools has too many bugs and is unreliable most of the time.

I really hope you could add that effect to this programm :)

**Comment by sylveon** [comment]
The development builds have support for a Fluent-style blur. I'm expecting to release this before the end of the month (I hope)
