### ISSUE TITLE
Improve DPI awareness

### ISSUE THREAD

**Issue by ethanhs** [TranslucentTB/TranslucentTB#19]
Low priority, but things are blurry on HiDPI displays, I think we want to use [`SetProcessDPIAwareness`](https://msdn.microsoft.com/en-us/library/windows/desktop/dn302122(v=vs.85).aspx).

**Comment by olliethepikachu** [comment]
Just for clarification: the tray icon, right?

**Comment by ethanhs** [comment]
The context menu actually. The icon just needs to have a large enough bitmap (I think the one I put in has 256px to at least 32px, so that shouldn't be a problem. The context menu however is blurry on HiDPI displays.

**Comment by ethanhs** [comment]
I pushed an initial attempt in ab29b34aa5f73b2a807dee343809d30625dabf6a . We may want to make it per-monitor at some point, but Im not sure how that works. Awaiting further testing before closing.
