### ISSUE TITLE
Dynamic Windows is opaque when maximized, blurred otherwise

### ISSUE THREAD

**Issue by Anti-Antidote** [TranslucentTB/TranslucentTB#190]
From the description of Dynamic Window's function, it should be that it is always transparent unless there is a maximized window on the monitor. Is this something I can fix in the config?

**Comment by sylveon** [comment]
Most probably something in your config. Can you try with the latest version?

**Comment by validatedev** [comment]
I've encountered the same problem atm. Blur option doesn't work when maximized.

**Comment by validatedev** [comment]
> From the description of Dynamic Window's function, it should be that it is always transparent unless there is a maximized window on the monitor. Is this something I can fix in the config?

Advanced > Edit Settings and change dynamic-ws-opacity=170 to 0, under the Dynamic Windows section. Save the config file and Advanced > Save Settings.
