### ISSUE TITLE
the microsoft store link in the develop branch readme seems to be broken.

### ISSUE THREAD

**Issue by exo66** [TranslucentTB/TranslucentTB#191]
this link https://www.microsoft.com/store/apps/9PF4KZ2VN4W9 takes me to an error page, and i couldn't find ttb on the microsoft store by searching.

**Comment by sylveon** [comment]
The app is currently in certification, that link will become valid once it passes certification.

**Comment by exo66** [comment]
Is the version that will be availabe there built from the master or develop branch?

**Comment by sylveon** [comment]
Develop, which will get merged to master once released.

**Comment by exo66** [comment]
Ok, thanks. And sorry for my apparently superflous
