### ISSUE TITLE
Start Menu opened sometimes behaves like Cortana opened

### ISSUE THREAD

**Issue by YueLengM** [TranslucentTB/TranslucentTB#192]
![4](https://user-images.githubusercontent.com/11801894/44395139-85d1c100-a56b-11e8-9363-6fe9c83aa997.gif)

Here is my settings (partly):
![snipaste_180821_180008](https://user-images.githubusercontent.com/11801894/44395266-f2e55680-a56b-11e8-8da4-39e764c071ec.png)

All other Dynamic feature works fine, except Dynamic Start.
But I noticed that if I opened a full screen application like a browser, then the Dynamic Start will works with some flicker.

**Comment by YueLengM** [comment]
After a bit of test, I also found that when it works wrongly, open start menu behaves like open Cortana. Hope this will help.

**Comment by sylveon** [comment]
I've had a couple other users experience that (behaves like open Cortana).

**Comment by sylveon** [comment]
I had a repro on my machine and suddenly now for no reason it started working as intended :/

**Comment by YueLengM** [comment]
Maybe it's related to Windows version?

**Comment by sylveon** [comment]
Probably not, considering I haven't even restarted my PC when I had my repro vs when I haven't.

**Comment by sylveon** [comment]
Fixed in 0c3a63b

**Comment by sylveon** [comment]
Fix available in latest version
