### ISSUE TITLE
Error after fresh installing

### ISSUE THREAD

**Issue by RodrigoCM14** [TranslucentTB/TranslucentTB#193]
So there is a error message I get everytime I try to start TranslucentTB:

![sin titulo](https://user-images.githubusercontent.com/42663484/44562855-130a4680-a721-11e8-9f25-e897bfbccba9.png)

**Comment by sylveon** [comment]
This function is only available in windows 10 version 1607 or above. Try upgrading windows to the latest RTM version (1803)
