### ISSUE TITLE
Task manager lags if TransulucentTB is open

### ISSUE THREAD

**Issue by farhantahir3** [TranslucentTB/TranslucentTB#197]
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 
 - Windows build number: 
 - Steps to reproduce: 
 - Expected results: 
 - Actual results: 
 - Other:

**Comment by farhantahir3** [comment]
I have windows and windows apps both installed on a ssd and whenever I try to open task manager it lags a lot. If I close this app it doesn't lags anymore. And my pc is pretty good so I don't think that's in anyway related with my pc hardware as even if I keep my taskmanager open it will lag only if this app is running. Closing the app stops the lag and opening it again makes it really hard to even switch tabs in task manager.

**Comment by FlorianLeChat** [comment]
#173
