### ISSUE TITLE
Request: auto reload config on file changes

### ISSUE THREAD

**Issue by spikespaz** [TranslucentTB/TranslucentTB#200]
Could you add an **option** to enable a file watcher that reloads the config automatically on file changes?

It should be able to be disabled so the file watcher isn't running when we don't need it. This would save a lot of time that right now is spent clicking on the taskbar icon.

**Comment by sylveon** [comment]
If you're not already aware of it, when the editor is closed after selecting Edit settings, they are reloaded. I'll see what I can tho.

**Comment by spikespaz** [comment]
I was aware but I open the file in VS Code for INI syntax highlighting. It won't detect file changes after my editor autosaves.

**Comment by sylveon** [comment]
Done in https://github.com/TranslucentTB/TranslucentTB/commit/5638fe3cabcd10c9ee41cee12fa9938ed331c877

**Comment by spikespaz** [comment]
Thanks!
