### ISSUE TITLE
TranslucentTB Color Picker Crash

### ISSUE THREAD

**Issue by cca310** [TranslucentTB/TranslucentTB#201]
[✓] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version:  4.0.0.0 
 - Windows build number: 17134.228 
 - Steps to reproduce: Open color picker https://gfycat.com/BlushingCandidCowbird
 - Expected results: Color picker should open 
 - Actual results: Program crashes 
 - Other: I installed from Windows Store. It worked correctly on first installation. After a restart, it did not save any of my settings. When I opened it and tried to change the color, it crashed. I have tried to reset the settings and reinstall it, and nothing has fixed it.

**Comment by sylveon** [comment]
Could you try installing the latest AppVeyor build and see if the crash still occurs?

**Comment by cca310** [comment]
@sylveon 

I uninstalled the Windows Store one. I'm not exactly sure what AppVeyor is, but I installed the .exe in the latest release. Unfortunately, I am experiencing the same issue.

**Comment by sylveon** [comment]
The latest github release is the same than what is running on the store. AppVeyor is our CI server, providing fresh build for each change we make to the program's source. The latest build as of now is this one: https://ci.appveyor.com/api/buildjobs/irse38p913r0c6vl/artifacts/TranslucentTB-setup.exe

**Comment by cca310** [comment]
@sylveon Thanks for the clarification.
I installed the appveryor build and it works fine for me. No crashes when opening color picker.

Thank you for your help.

**Comment by sylveon** [comment]
Nice! I have a pull request opened with the fix, and if everything goes well it should be available in a couple of days on the Microsoft Store. https://github.com/TranslucentTB/TranslucentTB/pull/198
