### ISSUE TITLE
Request: Dynamic Start Menu/Cortana Options

### ISSUE THREAD

**Issue by Blaze5565** [TranslucentTB/TranslucentTB#203]
Perhaps adding a "Dynamic" option to the Start Menu and Cortana/Search opened would make the program look a bit smoother, so that the taskbar in either of those situations simply goes to the Maximised or Regular setting, whichever currently applies.

**Comment by sylveon** [comment]
Unless I'm misunderstanding, there already is a dynamic option for start menu and Cortana opened.

**Comment by Blaze5565** [comment]
Hm, sorry, seems like you're right. I just checked again, and having it disabled for both has the same effect as a "Dynamic" option would. Before I posted this, disabling would instead revert the taskbar to the Windows default with the Start Menu or Cortana open. so I guess there's something odd going on there.

**Comment by sylveon** [comment]
Oh I see what you're asking. Yes disabling dynamic modes should just make it apply the current setting instead of reverting to windows default (which is intentional with the default settings)

**Comment by sylveon** [comment]
Oh I see what you're asking. Yes disabling dynamic modes should just make it apply the current setting instead of reverting to windows default (which is intentional with the default settings)
