### ISSUE TITLE
When power menu is opened from start menu, TranslucentTB do not recognize that start menu is opened

### ISSUE THREAD

**Issue by maxloh** [TranslucentTB/TranslucentTB#204]
- TranslucentTB version: Latest Windows store version
 - Windows build number: 17713.1002
 - Steps to reproduce: 
1. Open Start Menu
2. Open Power Menu
![screenshot 5337](https://user-images.githubusercontent.com/35831069/44844239-e902d800-ac7c-11e8-984b-c584c934a6ce.png)

 - Expected results: Taskbar is opaque (according to `dynamic-start-accent` settings)
 - Actual results: Taskbar is clear (general Taskbar `accent` settings)

**Comment by sylveon** [comment]
This seems to be a bug with your Windows Insider build, everything works fine here on stable Windows. Can't do anything as we just piggyback IAppVisibilityEvents, and the bug is present in bad reporting of the state of the start menu to the application (so it's up to Microsoft to fix it).
