### ISSUE TITLE
`portable` file does not work as expected, Still save settings to %APPDATA% directory

### ISSUE THREAD

**Issue by gitterliu** [TranslucentTB/TranslucentTB#206]
1. Portable file does not work as expected, Still save settings to %APPDATA% directory when you click save menu
2. There should be a ZIP archive release

**Comment by sylveon** [comment]
You need to use the latest build from AppVeyor for this to work, it's not released yet.

Next release will have a portable zip.

**Comment by gitterliu** [comment]
🤣  I thought #202 was closed 4 days ago, but acturally that's the opened time.
