### ISSUE TITLE
Feature Request: Ability to hide/fade-out taskbar on hotkey press

### ISSUE THREAD

**Issue by Darthagnon** [TranslucentTB/TranslucentTB#208]
I was wondering if it would be possible to add a "hide taskbar" toggle with a customisable keyboard shortcut? (e.g. similar to the RocketDock utility program called "Total Taskbar Controller" - since the website has died, link: https://drive.google.com/open?id=1nMLAy9m4feoUAui79DW1gbUvzaWEYvTw )

**Comment by Darthagnon** [comment]
Maybe this is more of a 7+ Taskbar Tweaker thing... I just posted about it there.

**Comment by denosawr** [comment]
Yeah, I think this may be just outside of the scope of TTB - closing. Sorry!
