### ISSUE TITLE
Only in 1 of the multiple display works

### ISSUE THREAD

**Issue by SRobiZ** [TranslucentTB/TranslucentTB#209]
Hi!

I installed this cool app to my laptop. My problem is that I use 3 extended display (Not using laptop's own).

When I start the app the settings apply only in 1 display. And it is interesting, that not in the main display.

Is it possible to work in 3 displays?

Thanks in advance!

**Comment by sylveon** [comment]
Are you using any multi monitor tool such as DisplayFusion?

**Comment by SRobiZ** [comment]
No, I’m not using any tool. It is a HP Z book 15 G4. I use the 3 monitors with DP in chain mode.

**Comment by sylveon** [comment]
Multiple displays should work. This is weird.

**Comment by SequoiaDu** [comment]
Same here. Running Win10 64-bit 1809, the effect only works on taskbar on the main display, but two other ones are still in black color...

**Comment by BenjaminChoou** [comment]
Similar here XPS 13 with Samsung monitor extended. The built-in monitor is of 4K and the other is of 2K. When I switch on the setting 'Automatically hide the Taskbar', I got this problem: even though I set all to be 'fluent', sometimes the taskbar in the extended monitor would be 'clear', which is wired.

**Comment by X0LR** [comment]
I have the same problem when i extend the desktop of my Hp Pavilion to a second monitor.
I have the October Update of Windows 10, it could be this the problem...!

**Comment by sollswl** [comment]
Same problem. Running Windows 10 1803.

**Comment by LER0ever** [comment]
Same problem here (occurs after maximizing a window for the first time), Windows 10 1809

**Comment by LibertQuinten** [comment]
Same problem with _**Windows 10 18267 Insider preview**_. I am using _Dual Monitor Tools_ though, but I had this issue **before** I started to use that program.

**Comment by Dealtz** [comment]
Sometimes it happened on 17134.
It only works well on my second display. 
Restart the program and it randomly start working again.

**Comment by sollswl** [comment]
>           Same problem. Running Windows 10 1803.

It can be fixed by restarting the program after connecting to another monitor.

**Comment by AndreasFurster** [comment]
Just a friendly reminder... I just installed and thought I had the same problem, but I just had maximized windows on my second (and third) screen. Then it just keeps using the default settings. You can change or turn off this behavior under 'Maximized window'.

Maybe an idea to turn it off by default. I find it's a bit too confusing for first use.

**Comment by gh102003** [comment]
For me, it seems its based on what displays are plugged in when TTB loads.
When I start the program with my external display, it works on both. However, when I unplug it, it stops working on both screens until I restart the program.

**Comment by hypercube33** [comment]
Started with 3 monitors connected and it only works on one.

**Comment by ianm32** [comment]
It does seem to be related to which monitors are turned on (or connected) when the program starts.

Starting my machine with only my primary display on applies it correctly.  When I switch on my secondary display, the effect is applied to that monitor and no longer works on the primary.  The only way to fix that seems to be to quit and restart TTB.  Even when the secondary display is turned back off, TTB doesn't refresh the primary display's taskbar to be transparent.

**Comment by sylveon** [comment]
The latest version has a button to manually refresh the taskbar handles, this can be used as a temporary workaround until the next major version.

**Comment by mikesafari** [comment]
> The latest version has a button to manually refresh the taskbar handles, this can be used as a temporary workaround until the next major version.

Where? I just installed TTB from the Store yesterday (first time) and I don't see that button. I'm also using a desktop so my monitors are always connected.

**Comment by sylveon** [comment]
Advanced > Refresh taskbar handles

**Comment by mikesafari** [comment]
> 
> 
> Advanced > Refresh taskbar handles

That doesn't seem to work reliably. For me it often doesn't work at all :(

**Comment by sylveon** [comment]
Do you use multi-monitor software like DisplayFusion? TranslucentTB was only programmed with the native windows taskbar in mind so this might be breaking things if you have it.

**Comment by mikesafari** [comment]
> 
> 
> Do you use multi-monitor software like DisplayFusion? TranslucentTB was only programmed with the native windows taskbar in mind so this might be breaking things if you have it.

I do not. Funny thing is it worked a little earlier today (when I thumbs-upped your comment), but then I noticed it stopped working a few hours ago.

**Comment by sylveon** [comment]
What exactly is "not working"?
- Are the taskbars that are correctly recognized by TranslucentTB still working after?
- Are the ones that aren't recognized still aren't after?
- Does it works after restarting TranslucentTB?

**Comment by mikesafari** [comment]
> 
> 
> What exactly is "not working"?
> 
>     * Are the taskbars that are correctly recognized by TranslucentTB still working after doing "Refresh taskbar handles"?
> 
>     * Are the ones that aren't recognized still not after?
> 
>     * Does it works after restarting TranslucentTB?

My left (main) monitor works as expected: it's clear when none of the other settings apply (all others are set to Fluent). My right-hand monitor, the taskbar simply shows up clear, no matter what's on screen (including if I hit the Start button, open Cortana/Search, timeline, etc.). This behaviour is the same when I click "Refresh taskbar handles" and when I restart the application itself.

**Comment by sylveon** [comment]
It also doesn't works if a window is maximised?

**Comment by mikesafari** [comment]
> 
> 
> It also doesn't works if a window is maximised?

Correct. It kinda seems to come and go as it pleases.

**Comment by 7HE-W0R1D** [comment]
I'm using the duet software to turn my iPad into a second screen, and this cool app only works on the iPad's screen, not the main one even when I disconnect it and exit duet. Weirdly the wallpaper engine only works for my main monitor, they are kind of complement to each other lol, are there any solutions to this :)

**Comment by theseanl** [comment]
Why is this issue closed even if there are many complaints here that it is not resolved? I am having the same issue. My taskbar is displayed only in "clear" mode, or sometimes even half-clear, half-blur mode -- it must be a bug. "Refresh taskbar handles" has no effect.

**Comment by TheFireMage** [comment]
If you want to apply TranslucentTB to all monitors. Click on TranslucentTB icon in the taskbar or in Show hidden icons. Go to Show Aero Peek->Consider main monitor only, uncheck it.

**Comment by krYsti** [comment]
TranslucentTB works only on second monitor for me. Main monitor has normal taskbar, only the second is clear. 
Refresh taskbar handles option works only until I start my computer again. Then I have to press it again.

**Comment by TheFireMage** [comment]
Have you tried the method I mentioned?

**Comment by frenchee1607** [comment]
I found a fix (that worked for me). If you go to Maximized Window > Accent Color and u pull the transparency bar down to the lowest it should work. (Refer to image below to know what im talking about).

![TranslucentTB_vqHtFiqPIH](https://user-images.githubusercontent.com/67718541/125183085-7a427900-e1e1-11eb-98e4-7b79d5da1854.png)

**Comment by tute123456** [comment]
Avanced - Reset Dinamic State

**Comment by Xytheur** [comment]
I found a fix, at least for me. For anyone still struggling with this, turn on "Show taskbar border" in Desktop

**Comment by HoodBlah** [comment]
still broken, Win11
