### ISSUE TITLE
Crashes on startup for UWP version

### ISSUE THREAD

**Issue by Thesharing** [TranslucentTB/TranslucentTB#210]
[*] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: the newest UWP version
 - Windows build number: 17134.285
 - Steps to reproduce: Every time when I start Windows
 - Expected results: Work properly
 - Actual results: Crash and exit
 - Other: After the start of Windows, the task bar becomes transparent and then the TranslucentTB just crashes. I checked #159 but I cannot find TranslucentTB in `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`

**Comment by sylveon** [comment]
Does this occurs if you manually start TranslucentTB?

**Comment by Thesharing** [comment]
Yes. The app crashes when I manually start it. It doesn’t work even if I reset it in the Settings of Windows.

**Comment by sylveon** [comment]
Is there any info in the reliability monitor?

**Comment by Thesharing** [comment]
The language of my Windows is Simplified Chinese, so I try to translate it into English.

### Source
TranslucentTB

### Abstract
Stopped working

### Date
‎2018/‎9/‎16 0:00

### Status
Report sent

### Description
Faulting Application Path: C:\Program Files\WindowsApps\28017CharlesMilette.TranslucentTB_5.0.0.0_x86__v826wp6bftszj\TranslucentTB\TranslucentTB.exe

### Problem signature
Problem Event Name:MoAppCrash
Application Name: 28017CharlesMilette.TranslucentTB_5.0.0.0_x86__v826wp6bftszj
Application Version: praid:App
Application Version: 5.0.0.0
Application Timestamp: 5b83fcf0
Fault Module Name: StackHash_e17e
Fault Module Version: 10.0.17134.254
Fault Module Timestamp: bf2f8c99
Exception Code: c0000374
Exception Offset: PCH_62_FROM_ntdll+0x0006A81C
OS Version: 10.0.17134.2.0.0.256.48
Locale ID: 2052
Additional Information 1: e17e
Additional Information 2: e17e7c7778340ad76444129e4c59ed8e
Additional Information 3: 9db0
Additional Information 4: 9db05015f066392fae6e292a1ecd65ad

Extra information about the problem
Bucket ID: fae910c711772e25eb74a04310c0d7c8 (1978382346226816968)

**Comment by sylveon** [comment]
![image](https://user-images.githubusercontent.com/6440374/45599767-8c632500-b9bf-11e8-892e-061443ebe11b.png)
Is there any internal metadata file in the report?

**Comment by Thesharing** [comment]
> ![image](https://user-images.githubusercontent.com/6440374/45599767-8c632500-b9bf-11e8-892e-061443ebe11b.png)
> Is there any internal metadata file in the report?

Sorry, I can't find anything like internal metadata file in the report.

**Comment by Thesharing** [comment]
I install the executable version and it crashed, too. But this time I get internal data and another report.

### Source
TranslucentTB

### Abstract
Stopped working

### Date
‎2018/‎9/‎17 18:28

### Status
Report Unsent

### Description
Faulting Application Path:	C:\Program Files (x86)\TranslucentTB\TranslucentTB.exe

### Problem signature
Problem Event Name:	APPCRASH
Application Name:	TranslucentTB.exe
Application Version:	5.0.0.0
Application Timestamp:	5b83f99f
Fault Module Name:	StackHash_0c7c
Fault Module Version:	10.0.17134.254
Fault Module Timestamp:	bf2f8c99
Exception Code:	c0000374
Exception Offset:	PCH_62_FROM_ntdll+0x0006A81C
OS Version:	10.0.17134.2.0.0.256.48
Locale ID:	2052
Additional Information 1:	0c7c
Additional Information 2:	0c7c14be87727e52a5f30e4b8d46ea58
Additional Information 3:	27bc
Additional Information 4:	27bc90d23f2c4e05e280831dea795fb4

### Files that helps describe the problem
minidump.mdmp
WERInternalMetadata.xml
WERInternalRequest.xml
memory.csv
sysinfo.txt
AppCompat.txt
memory.hdmp

I just upload the file above here.

[WER4629.tmp.zip](https://github.com/TranslucentTB/TranslucentTB/files/2388632/WER4629.tmp.zip)

And thank you for developing such a good application!

**Comment by sylveon** [comment]
That's awesome, I've been able to identify the issue with that internal metadata.

![image](https://user-images.githubusercontent.com/6440374/45642451-373e1680-ba86-11e8-9e44-cf6c8822fa6b.png)

By inspecting the stack trace, it seems to be caused by MacType. Try adding `TranslucentTB.exe` to `[UnloadDll]` and see if it works after restarting your PC. If it does works, maybe it should be something to add to https://github.com/snowie2000/mactype/issues/426 (you'd have to ask @sammilucia for that)

**Comment by Thesharing** [comment]
> That's awesome, I've been able to identify the issue with that internal metadata.
> 
> ![image](https://user-images.githubusercontent.com/6440374/45642451-373e1680-ba86-11e8-9e44-cf6c8822fa6b.png)
> 
> By inspecting the stack trace, it seems to be caused by MacType. Try adding `TranslucentTB.exe` to `[UnloadDll]` and see if it works after restarting your PC. If it does works, maybe it should be something to add to [snowie2000/mactype#426](https://github.com/snowie2000/mactype/issues/426) (you'd have to ask @sammilucia for that)

Thank you for your analysis, after adding `TranslucentTB.exe` to `[UnloadDll]` and it works!

**Comment by sylveon** [comment]
This should be fixed by [the latest preview of MacType](https://github.com/snowie2000/mactype/releases/tag/1.2018.917.0-beta2)
