### ISSUE TITLE
no-tray flag doesn't work

### ISSUE THREAD

**Issue by jordi-7** [TranslucentTB/TranslucentTB#212]
[x] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 5.0.0.0
 - Windows build number: 18237.1000
 - Steps to reproduce: Open config.cfg and change no-tray to enable.
 - Expected results: When starting the program, the tray icon should not be visible.
 - Actual results: The tray icon persists.

**Comment by sylveon** [comment]
Have you restarted TranslucentTB after changing this setting?

**Comment by jordi-7** [comment]
Yes. I even restarted the system. No effect.

**Comment by sylveon** [comment]
Probably stupid question, but are you sure that you're not confusing the configuration file from the desktop version with the one from the store version. They don't use the same file.

**Comment by jordi-7** [comment]
I never installed the store version. I'm running the desktop version.

**Comment by jordi-7** [comment]
Solved. I was changing the file inside "Program Files (x86)" instead of Appdata

**Comment by sylveon** [comment]
Ah, that does it. The config.cfg file in program files is the template for what gets put in AppData; perhaps there's a way to be more clear about this. (all the stuff integrated in the application for editing config files opens the appdata file already)
