### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by CommanderSmash** [TranslucentTB/TranslucentTB#213]
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 5.0.0.0
 - Windows build number: 10.0.17134 Build 17134
 - Steps to reproduce: Every Time I Launch the application
 - Actual results: Everytime I launch TranslucentTB taskmanager shows that it is using 25% of my cpu (i5 7500) and I don't know why.
 - Other: I don't use antivirus and am very good at keeping my system clean. Also it could be caused by wallpaper engine.

**Comment by sylveon** [comment]
Can you still interact with the context menu when this happens?

**Comment by CommanderSmash** [comment]
Yeah, I had full functionallity just with high cpu.

**Comment by CommanderSmash** [comment]
And I also since then reset my computer, reinstalled translucentTB. And it fixed it.

**Comment by sylveon** [comment]
I seriously have no idea how that could occur. You fixed it so I'll close this.
