### ISSUE TITLE
"Minimize all?"

### ISSUE THREAD

**Issue by SimplisticGH** [TranslucentTB/TranslucentTB#215]
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: Version 4 hotfix
 - Windows build number: 17134.285
 Easier to show than explain https://streamable.com/ih1j2

**Comment by denosawr** [comment]
Check the TTB context menu (right click the icon), under "Show Aero Peek" there is an option to disable.

**Comment by SimplisticGH** [comment]
Oh my bad
