### ISSUE TITLE
Color-Picker error

### ISSUE THREAD

**Issue by cafuu** [TranslucentTB/TranslucentTB#216]
Windows 10 x64 1809 Build 17763.55
TranslucentTB version 5.0.0.0

The accent-color option doesn't work for me. There's always an error-popup, when trying to activate it. The error-message is: "An error occured in the color-picker! Exception from HRESULT: [failed to get error-message for HRESULT] (0x887a0031)"

**Comment by sylveon** [comment]
I have an attempted fix for this in the latest commit of `develop`. The CI is missing something required for building so if you aren't comfortable with building from source you can download [this build](https://cdn.discordapp.com/attachments/312341949078306818/500097436396814336/ttb-warp.zip). Just extract it somewhere, run it, and see if the color picker works.

**Comment by sylveon** [comment]
Confirmed by someone else: it works.
