### ISSUE TITLE
I hope to support custom colors and transparency

### ISSUE THREAD

**Issue by caliban511** [TranslucentTB/TranslucentTB#218]
I hope to support custom colors and transparency

**Comment by denosawr** [comment]
Please elaborate?

**Comment by caliban511** [comment]
@denosawr 
Sorry, I don't know English. I am using Google Translate to talk to you. I mean I want to let users define the color and transparency of the taskbar themselves.

**Comment by caliban511** [comment]
> error :
![snipaste_20181030_192113](https://user-images.githubusercontent.com/13557387/47714884-179b3000-dc79-11e8-972f-48dec5a34150.jpg)

**Comment by sylveon** [comment]
The following build fixes this error: https://cdn.discordapp.com/attachments/312341949078306818/500097436396814336/ttb-warp.zip

**Comment by caliban511** [comment]
> 
> 
> The following build fixes this error: https://cdn.discordapp.com/attachments/312341949078306818/500097436396814336/ttb-warp.zip

Thanks for the help, the problem is solved.
But what I don't understand is, why not fix the installation files? But to solve the problem in this way?

**Comment by sylveon** [comment]
The bug only affects a small portion of users using old hardware, so it is not an emergency and will come in the next update

**Comment by denosawr** [comment]
It should be mentioned that this fix was only recently created; in fact, we only found out about the error after the release came out. It'll definitely be in the next release.
