### ISSUE TITLE
Taskbar blinking on focus change when fluent is set.

### ISSUE THREAD

**Issue by oomek** [TranslucentTB/TranslucentTB#220]
[x] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 5.0.0.0
 - Windows build number: Windows 10 1809 build: 17763.165
 - Steps to reproduce: Watch the video
 - Expected results:  Not blinking
 - Actual results: Taskbar is blinking
 - Other: https://youtu.be/eG5L4K0eeaI

**Comment by sylveon** [comment]
Unfortunately this is a bug in DWM (the part of Windows that is responsible for rendering the final screen image as well as various transparency and blur effects) that we cannot work around.
