### ISSUE TITLE
BUG: What happen to enable button of "Enable" in Maximised window?

### ISSUE THREAD

**Issue by Williams-Ren** [TranslucentTB/TranslucentTB#222]
Sorry, I don't know much about this but I still want to ask a question
Version: released on Aug 29, 2018
Win 10 newest on Dec 6, 2018
![image](https://user-images.githubusercontent.com/45218090/49559643-6a3bcc00-f94a-11e8-9209-e13bccbdb3e9.png)
![image](https://user-images.githubusercontent.com/45218090/49559674-82135000-f94a-11e8-8458-b7e3757b4562.png)
Why it seems enable means unable??
When I enable the Maximized window the app didn't work, but when I disenabled it, it works.

**Comment by sylveon** [comment]
When there is a checkmark to the left of `Enabled`, it means it is enabled. When there isn't, it means it is disabled.

**Comment by Williams-Ren** [comment]
Yeah, I knew it. But I have already set it in every mode to be blur. But when I enable it under the Maximized window, the taskbar becomes opaque. When I disable it, it becomes blur. It confused me

**Comment by Williams-Ren** [comment]
@Darthagnon I think it definitely a bug if you have the same problem. It took me 20 mins to figure out what happened.

**Comment by Virtuoz-Ier** [comment]
Fix: go to the config file in %appdata%, replace dynamic-ws-opacity=170 by dynamic-ws-opacity=0
Enjoy your translucent tb as it should be.

**Comment by jessefjxm** [comment]
Came up with same bug in latest release. Hope it can be fixed.

**Comment by N3pp** [comment]
> Yeah, I knew it. But I have already set it in every mode to be blur. But when I enable it under the Maximized window, the taskbar becomes opaque. When I disable it, it becomes blur. It confused me

Late but this is likely because you have different A (alpha/transparency) values for accent colors of "Regular" and "Maximized Window". Notice how it's not actually opaque but just less transparent (higher alpha). When you disable the settings for "Maximized Window", it uses "Regular"s accent color values.

@Williams-Ren @Darthagnon

**Comment by Williams-Ren** [comment]
Thanks N3pp, it is fixed.
