### ISSUE TITLE
Taskbar starts to blink with transparency right after this tool runs

### ISSUE THREAD

**Issue by bvn13** [TranslucentTB/TranslucentTB#223]
[x] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 
Version 4 hotfix
@sylveon sylveon released this on 29 Aug

 - Windows build number: 
Version 1803 Build 17134.407

 - Steps to reproduce: 
Right after program runs

 - Expected results: 
I can tweak taskbar

 - Actual results: 
Taskbar starts to blink with transparency like a demon

**Comment by sylveon** [comment]
Do you have another tool that changes the appearance of the taskbar or an older version of TranslucentTB running?

**Comment by bvn13** [comment]
@sylveon, no.

**Comment by bvn13** [comment]
No. Standart task bar only.

**Comment by sylveon** [comment]
Weird, I never had this happen during testing. I assume a restart doesn't fixes it?

**Comment by bvn13** [comment]
Nor this tool restart neither my computer restart - nothing helps.

**Comment by fingerwarrior** [comment]
Having same issue, taskbar would flicker and transition between transparent and normal windows frosted when something changes the taskbar (say, opening a new window). Does not happen always, but enough to get noticed.

**Comment by waterprism** [comment]
I have this too, this flicker when the computer starts. It's like the default taskbar settings try to come through before TranslucentTB takes over. This happens when you open the start menu or programs for the first little while after starting the computer. Seems, from this thread, that it's been happening for a while now.

**Comment by QuentinQuantique** [comment]
Same! This is blinking whenever I click on a window or else

**Comment by sylveon** [comment]
Fixed by the injected DLL
