### ISSUE TITLE
Icon is no longer transparent when the window is focused

### ISSUE THREAD

**Issue by l1ving** [TranslucentTB/TranslucentTB#226]
[x] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 5.0.0.0

> I downloaded v4 hotfix, but this is what the details tab says

 - Windows build number: 1809 (18237.1000)
 - Steps to reproduce:
    1) Not sure if it's related, but I have autohide taskbar *ON*
    2) Open a window, don't maximize it (again, not sure if it's related but that's what I did)
    3) Look at the icon when the window is focused
    4) Look at the icon when the window is not focused
 - Expected results: Icon is still transparent when the window is focused
 - Actual results: Icon is not transparent
 - Other: It doesn't seem to happen when the window is maximized.
 - Example: [Screenshots](https://imgur.com/a/oGESD7f)

**Comment by sylveon** [comment]
Disable "Show accent color on taskbar"

![](https://camo.githubusercontent.com/0da5e1159418c088294fa02c278da5f0ce4150b4/68747470733a2f2f66696c65732e636861726c65736d696c657474652e6e65742f4665775472697669616c48796c61656f736175727573)

**Comment by ChristoferMinestar** [comment]
I already did. I disabled it on both Taskbar and Title Bar before I made the issue, as per the Tips and Tricks said

**Comment by ZeroSiks** [comment]
Enable "Transparency effects" under more options. Fixed the issue for me
