### ISSUE TITLE
Dragging down and to the side of color sliders switches slider

### ISSUE THREAD

**Issue by l1ving** [TranslucentTB/TranslucentTB#227]
[x] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

  - TranslucentTB version: 5.0.0.0

> I downloaded v4 hotfix, but this is what the details tab says

 - Windows build number: 1809 (18237.1000)
  - Steps to reproduce:
    1) Open the accent color menu
    2) Try dragging a transparency slider
    3) Drag it to the left
    4) Observe the other slider being moved
 - Expected results: Keeps changing the first slider
 - Actual results: The second slider changes

**Comment by sylveon** [comment]
Dev builds use an XAML-based color picker, which does not expose this issue.
