### ISSUE TITLE
Stops responding after clicking the icon

### ISSUE THREAD

**Issue by tooruu** [TranslucentTB/TranslucentTB#228]
TranslucentTB version: 2018.2.0.833ae80fe3040177c933b2a7ef362c421b10f7ed.master-Store (downloaded from Microsoft Store)
Windows build number: 17763.195
After I right-click the icon in taskbar, everything is OK but if I right-click it again, the menu stops responding and I can't change settings for ~15 seconds. However, if I **left**-click it again, it shows _Querying startup state..._ instead of **Open at boot** option. Windows doesn't throw any errors, I just can't click anything in the menu.

**Comment by tooruu** [comment]
Now it stopped at all.

**Comment by pzhg** [comment]
Confirm

**Comment by quantum5** [comment]
Keyboard navigation of the menu still works when mouse doesn't.

**Comment by kkkst** [comment]
> Keyboard navigation of the menu still works when mouse doesn't.

quantum5, you are so smart.  it is working.

**Comment by giggio** [comment]
Confirmed. But is still here. I just installed it from the Store.

**Comment by ArchonFine** [comment]
Confirmed, waiting for a fix

**Comment by sylveon** [comment]
Fix available in latest version
