### ISSUE TITLE
Timeline: Unexpected Shadow in bar when windows are snapped to side of screen

### ISSUE THREAD

**Issue by e-luo** [TranslucentTB/TranslucentTB#232]
Newest version of TranslucentTB on newest Windows 10 build.

Steps to replicate:
1. snap two windows to each side of the screen
2. open timeline view
3. see a shadow across taskbar
4. exit timeline
5. close one of the windows
6. open timeline view
7. see a shadow across half the taskbar

Current settings I'm using for Timeline Opened:
Clear
Accent Color: 0x00000065

With no windows snapped to sides, or when window maximized:
![image](https://user-images.githubusercontent.com/12617612/51002529-8f030080-1501-11e9-93f2-fe0936bafbc7.png)

With a single window snapped to left side of screen:
![image](https://user-images.githubusercontent.com/12617612/51002446-45b2b100-1501-11e9-9123-d47bc59d5727.png)

**Comment by sylveon** [comment]
This is not really a bug and more a result of how Timeline was designed. If
you completely close TranslucentTB, drag a window under the taskbar in such
a way that it's easy to notice it's under it, and then open Timeline,
you'll see that the window is still under the taskbar.

Windows themselves don't move at all during Timeline. It's just an overlay
that animates images of the windows.

**Comment by e-luo** [comment]
@sylveon thanks for replying. Oh I see what you mean, I tried putting a window under the taskbar and yes I could still see the window there when the timeline was open. 
But when I make a window full screen, the shadow isn't there anymore. Why is it that when it's snapped the shadow's there? I guess that's by Window's design, but it'd be great if there was some way to hide the shadows, at least when timeline is open.

**Comment by denosawr** [comment]
I don't think there is; like you said, it's very much a part of Windows' design, and completely out of our control :(

**Comment by sylveon** [comment]
Maximised windows don't have shadows. I believe that removing shadows when
timeline opens would be a possibility, but would end up being super sketchy.
