### ISSUE TITLE
Failure to apply effect if auto-hide is enabled

### ISSUE THREAD

**Issue by 0x5c** [TranslucentTB/TranslucentTB#233]
[x] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 5.0.0.0
 - Windows build number: 17763 (1809)
 - Steps to reproduce:
Just use the app for a couple of minutes, on a setup with 2 external monitors, taskbar auto-hide enabled.
 - Expected results:
The selected effect should be applied to the whole taskbar.
 - Actual results:
The effect is applied to only the pixels that stay visible on the screen, the rest becoming completely transparent, regardless of the effect (except normal), and until TTB is closed or the auto-hide cycled..
 - Other:
  - The monitor that gets a partial taskbar is random, sometimes all monitors will have no/full effect.
  - I use no dynamic features.

**Comment by Heinzip** [comment]
Same on my machine with the same OS and same version of TranslucentTB.
My -non satisfying- solution so far: Toggle in taskbar options the auto-hide off and on again. Nevertheless, it need to be fixed.

**Comment by 0x5c** [comment]
Looking at the current (TTB) startup behaviour, it would seems that it _tries_ to mitigate that issue by having all the bars show up for a second, but seemingly fails due to a timing issue.

**Comment by benrodarte** [comment]
i have same problem,unless auto-hide off

**Comment by sylveon** [comment]
This is fixed in 2024.1 and up.
