### ISSUE TITLE
How to make titlebar transparent

### ISSUE THREAD

**Issue by Solid-Block** [TranslucentTB/TranslucentTB#234]
[√] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 4
 - Windows build number: 1803 os 17134.523
 - Steps to reproduce: 
 - Expected results: Transparent titlebar
 - Actual results: The title bar is not transparent as default

How to make titlebar transparent?

**Comment by sylveon** [comment]
This is out of the scope of this program, you are looking for something like [glass8](http://glass8.eu/)

**Comment by LeeBinder** [comment]
Hi @sylveon It's been a while so I dare to revive this request. Indeed, transparent title bars would be a different app. With glass8 having been completely abandoned in the meantime, and considering Stardock's WindowBlinds (which is capable of making title bars translucent) overkill for this limited requested task: do you at least see the possibility of looking into an additional app separate from TranslucentTB to enable title bar translucency? (you could label it TranslucentTBs because there is more than just one taskbar, LOL :) )

**Comment by sylveon** [comment]
Altering the appearance of the titlebar requires injecting into DWM, a protected system process, which is much more complex and risky than Explorer. It's not something I have particular knowledge doing. Modifying the taskbar is miles easier compared to titlebars.

**Comment by LeeBinder** [comment]
Gotcha Charles - thanks for explaining the difference.

So I did some research: some other folks managed to restore title bar transparency/ glass/ blur effect, even for the latest Windows 11 👍 . Quoted from [Looking for Aero Glass replacements? Check Here - Aero Glass For Windows 8+ - MSFN](https://msfn.org/board/topic/186093-looking-for-aero-glass-replacements-check-here/):

---------------
[DWMBlurGlass](https://github.com/Maplespe/DWMBlurGlass) - An Open Source utility that adds support for the Acrylic effect to the Windows 10 and Windows 11 title bar, and Explorer UI. Would be considered the community replacement of Aero Glass, supports custom Aero textures and custom blur amounts. Lightweight, customized with a configuration file.

[MicaForEveryone](https://github.com/MicaForEveryone/MicaForEveryone) - An Open Source utility that does the same as DWMBlurGlass, but with more customization options and configuration. Runs as a tray application, and is only compatible with Windows 11. Allows you to use any type of Windows 11 built-in blur, such as Mica, Acrylic, and Opaque. It supports blurring any Win32 application background, and supports whitelisting and blacklisting applications that may not play nicely.

Some applications have built in support for acrylic title bars, even on Windows 10. The new Windows Terminal supports Acrylic title bars as a setting built in, and an acrylic background to the terminal. I just felt like making a post like this to organize the replacements, and keep them all in one place. I will update this document with more if I find any.

---------------
Additional infos re. **MicaForEveryone**, in case someone opts to use it:
- It requires the [.NET Core v3.1.32 Desktop Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/3.1#runtime-desktop-3.1.32) ([x64](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-3.1.32-windows-x64-installer) | [x86](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-3.1.32-windows-x86-installer))
- Currently, the latest release is quite old from 2023-07-15, therefore consider using the latest from their [GitHub Actions sections](https://github.com/MicaForEveryone/MicaForEveryone/actions?query=is%3Asuccess). Latest build Artifacts are from [2024-03-08](https://github.com/MicaForEveryone/MicaForEveryone/actions/runs/8205765429#artifacts)
- To add background blur or Acrylic (Mica for Win11) effect to Win10 and Win11 File Explorer, also install the [ExplorerBlurMica](https://github.com/Maplespe/ExplorerBlurMica) add-on
