### ISSUE TITLE
Make Aero Peek work even with the button hidden

### ISSUE THREAD

**Issue by quantum5** [TranslucentTB/TranslucentTB#235]
I like the aesthetic appeal of hiding the Aero Peek button, however, the feature, as well as showing the desktop, is still useful at times. It would be nice to let the location where the button is act as Aero Peek even though the button itself is hidden.

While using the dynamic mode for "Show Aero Peek" mitigates some of the issues, show desktop and Aero Peek is still desirable when having a lot of non-maximized windows visible.

 - TranslucentTB version: 5.0.0.0 (Windows Store)
 - Windows build number: 1809 (17763.292)
 - Steps to reproduce: Set "Show Aero Peek" to "Never" (or "Dynamic" and show desktop).
 - Expected results: Clicking the bottom right corner of the screen shows desktop, hovering the bottom right corner lets you peek the desktop.
 - Actual results: Nothing happens.

**Comment by brandynn** [comment]
+1

**Comment by sylveon** [comment]
Fixed in dev builds
