### ISSUE TITLE
Feature Request: hide window focused shading

### ISSUE THREAD

**Issue by pressRtowin** [TranslucentTB/TranslucentTB#237]
When a window is focused, its icon is shaded in the taskbar, and that shading doesn't respect the rest of the taskbar's transparency settings. Is there a way to hide it completely? I use auto-hide and that means when the taskbar hides, there's a small line left over on the bottom of my screen whenever a window is focused. Would love to get rid of it entirely.

**Comment by tusing** [comment]
Would also really appreciate a setting like this!

**Comment by sylveon** [comment]
Disable showing color on the taskbar. Alternatively, fixed in 11.
