### ISSUE TITLE
[Feature Request" Having colors even when win tabs opens

### ISSUE THREAD

**Issue by barrychen0507** [TranslucentTB/TranslucentTB#238]
1. If you may have colors options even w/ win tab opens (Basically changes the theme)
2. Design an U.I. which may let people to select colors (So basically one is Lite which is task bar and one is standard for many options :)
3. make a whole theme options, so I do not have to select color for each one (IDK if there is that feature or not but currently IDK.

**Comment by sylveon** [comment]
If by Win-Tab open you mean the Timeline view, it's already present in the latest version.

The configuration file format is easy to parse, feel free to write something. I've personally explored making an UWP configuration frontend but it's not currently in the goals for the next version.

I don't feel like this is a problem big enough to complexify the existing GUI in weird ways, as it's not extremely long to change them one by one. This would fit better in a proper configuration app but as mentioned it's not in our goals for now.

**Comment by barrychen0507** [comment]
No, I have set all the colors to blue, yet when I open the win tab is still Black. But other things still works, so I think that might be an issue.
Mine is the latest version, just downloaded
winver: 1803:17134648

**Comment by sylveon** [comment]
Change it to something else than normal
![image](https://user-images.githubusercontent.com/6440374/55251545-3cdf9a80-5227-11e9-8940-003cf4de3684.png)

**Comment by barrychen0507** [comment]
Yes, I have changed it to Blur before u said it.
What I meant is that when u press the "Win" button, while the screen pops out, and it is usually GREY.
That's what I am requesting. like ur task menu, it is grey, same for the Win button even w/ every option set to Blur and color Blue.

**Comment by sylveon** [comment]
So if I understand well, you want it to be have the same tint than the timeline background when timeline is opened? Or you want everything to be blue but it doesn't works?

**Comment by denosawr** [comment]
我们不会改变开始菜单的颜色-只会改变任务栏的颜色.

(We don't change the Start Menu colour, only the colour of the Taskbar)

**Comment by barrychen0507** [comment]
@sylveon 
The everything change is for a feature request.
I am asking that while you open the windows tab "Like when you click the WIN button"
Inside, there is many apps, and its always black. And I am requesting that we can add a feature to change colour for that.

And, we can also add an option which we can change the colour for ALL of these, so that it'll always be the same colour.

**Comment by barrychen0507** [comment]
@denosawr 
hmm... Ok I understood.
but just requesting for changing color TOGETHER if I am not misunderstood that there is not that option.

喔...我懂了
如果我沒有錯的話，那裏應該沒有 全部一起改 的選項

**Comment by denosawr** [comment]
全部一起？你意思吧开始和任务栏的颜色两个都换掉吗？

现在，不可以改变开始的颜色 - 我们用`SetWindowCompositionAttribute`换任务栏颜色，但是这不可以用在开始上面。

(Change the colour together? Do you mean to change both the colour of the start menu and the taskbar?

Currently, we can't change the colour of the start menu - we use SWCA, to set the colour, which doesn't really work on the Start Menu.)

对不起！(Sorry!)

Oh, 我的中文没有特别强（现在只说英语了），对不起如果你不能了解我 :D

**Comment by sylveon** [comment]
Yes, as said there is no method to change the color of the Start Menu or the Timeline interface.

As for the ability to change the color of all the dynamic states at once, I'm going to quote my original message:

> I don't feel like this is a problem big enough to complexify the existing GUI in weird ways, as it's not extremely long to change them one by one. This would fit better in a proper configuration app but as mentioned it's not in our goals for now.
