### ISSUE TITLE
Please test with Windows Version 1903 - No transparency except for Taskbar

### ISSUE THREAD

**Issue by mkanet** [TranslucentTB/TranslucentTB#239]
Tested with Windows Version 1903.  
Tested with the latest version of TranslucentTB from Windows Store.

There were some big changes to transparency in this Version of Windows 10; causing almost all features of TranslucentTB to not have any effect on Windows components.

**Comment by sylveon** [comment]
TranslucentTB from the Windows Store works fine on build 18362.53 for me. Where you expecting it to do more than change the appearance of the taskbar?

**Comment by mkanet** [comment]
Yes, I expected to be able to use all the other options to change transparency for other Windows components (offered in TranslucentTB's context menu); such as Transparency for Start Menu, Cortana Search, Timeline, etc.  I'm using the version from the Microsoft Store, not beta.  See below:

![Screenshot](https://user-images.githubusercontent.com/811008/56059545-294d2d00-5d19-11e9-91b1-5a95191fa825.png)

**Comment by sylveon** [comment]
This is intended. These options are there to make the taskbar look different when Timeline, Start Menu or Cortana is opened. It does not changes the appearance of those components themselves - and it's outside the scope of this project.
