### ISSUE TITLE
Multi monitors

### ISSUE THREAD

**Issue by naderhandal** [TranslucentTB/TranslucentTB#240]
Hello guys, am not a programmer, and i don't understand anything about coding.
 so i've looked up my problem before i post this and it was from 2017 

i just connected my Ipad as a second monitor and its only effecting the task bar on the Ipad so please help 
thanks in advance.

**Comment by sylveon** [comment]
Does it works if you close and reopen TranslucentTB?

**Comment by naderhandal** [comment]
I’ve tried to restart my computer but same result

**Comment by naderhandal** [comment]
> Does it works if you close and reopen TranslucentTB?

so ive tried to close the app and reopen it and it worked just fine.

**Comment by sylveon** [comment]
Then that's a duplicate of #209
