### ISSUE TITLE
Feature Request: Battery Save Mode

### ISSUE THREAD

**Issue by liyafe1997** [TranslucentTB/TranslucentTB#244]
[✔] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 5.0.0.0
 - Windows build number: 17763.437

When battery save mode turned on, the blur effect will gone as windows 10 default.
![批注 2019-04-25 104744](https://user-images.githubusercontent.com/18359157/56706714-906ed680-6748-11e9-93c8-00c86a8a80c4.jpg)
But after TranslucentTB enabled, this feature will gone, whatever whether on battery save mode or not, it always follow the TranslucentTB settings.
So can you add a status option (like On Battery Save Mode), make it can change status on battery save mode.
Thank you.

**Comment by rbreaves** [comment]
Not sure that is worded very well, but I will concur that a change needs to happen during battery saver mode - in my case the background went completely transparent during battery saver mode when I would have preferred a solid black instead until it is back out of battery saver mode.

**Comment by sylveon** [comment]
For future reference:
https://docs.microsoft.com/en-ca/windows/win32/api/winuser/nf-winuser-registerpowersettingnotification
https://docs.microsoft.com/en-ca/windows/win32/api/winbase/ns-winbase-system_power_status

**Comment by sylveon** [comment]
I finally implemented this, and noticed that in Windows 20H2, the taskbar stays acrylic when battery saver is on... however when TranslucentTB is running and the normal style is used, instead of being acrylic in power saver as it should, it turns completely transparent! Odd...

**Comment by sylveon** [comment]
Implemented in c94804e. The current implementation uses a hardcoded black (or white, when you're using light theme) for power saver mode, since I don't think there's much demand to customize a mode where power usage is minimized. Let me know if you actually want to customize it.

**Comment by rbreaves** [comment]
I'm good with plain black in power saver mode!
