### ISSUE TITLE
Startup has been disabled in group policy

### ISSUE THREAD

**Issue by ghost** [TranslucentTB/TranslucentTB#247]
after updating windows version 1903
this app no longer supports this function
![2019-05-25](https://user-images.githubusercontent.com/23550195/58361701-49990b80-7ec3-11e9-98a4-2d4574ed8ab9.png)

**Comment by sylveon** [comment]
This usually means that the company controlling your device disallowed the startup of TranslucentTB. I assume this is not the case?

**Comment by Mercerry** [comment]
> This usually means that the company controlling your device disallowed the startup of TranslucentTB. I assume this is not the case?

This is my personal computer
maybe windows updated group policy control?

**Comment by sylveon** [comment]
Honestly I have no idea. As a temporary workaround, using the desktop version will also work (it's functionally equivalent to the store version)

**Comment by Mercerry** [comment]
> Honestly I have no idea. As a temporary workaround, using the desktop version will also work (it's functionally equivalent to the store version)

I've switched to the desktop version, and it worked.
This is some of the situations provided as a reference. I‘ve enabled in Task Manager manually
It will be disabled next boot
