### ISSUE TITLE
Edit this program error D8021 无效的数值参数“/Wno-missing-field-initializers”

### ISSUE THREAD

**Issue by H-olxx** [TranslucentTB/TranslucentTB#252]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	D8021	无效的数值参数“/Wno-missing-field-initializers”	CPicker	E:\SourceFile\Repos\TranslucentTB\CPicker\cl	1

**Comment by sylveon** [comment]
The master branch requires [Clang](http://releases.llvm.org/download.html) to be installed.
