### ISSUE TITLE
How to accept GPLv3 via registry?

### ISSUE THREAD

**Issue by Alexusson** [TranslucentTB/TranslucentTB#253]
I integrate/preinstalled TranslucentTB in "install.wim" so it will be a part of Windows 10 19H1 1903.
I figure out how to set the app to be run automatically at first startup via registry but how to accept GPLv3 via registry to avoid confirmation pop up window at the first login?

Thank in advance

**Comment by sylveon** [comment]
Just creating a configuration file for the program will make it skip the first use experience

**Comment by Alexusson** [comment]
So if I copy config file before to install folder before I run the app the first time it will not pop up the window??? Is that your statement
I will try and come to report. Thanks for suggestion!

**Comment by sylveon** [comment]
The config file is in `%AppData%\TranslucentTB`, but yes

**Comment by Alexusson** [comment]
OK, I will try that, sounds promising, and come back to report later!

**Comment by Alexusson** [comment]
Thank you very much sylveon! Everything went smooth! No 
For others with similar requests just copy the config file to

%AppData%\TranslucentTB 
OR
C:\Users\YOUR USER NAME\AppData\Roaming

... and it will skip the first use experience window!
