### ISSUE TITLE
When the computer wakes up and wakes up the desktop, the transparency of the software settings will be invalid.

### ISSUE THREAD

**Issue by liby** [TranslucentTB/TranslucentTB#254]
[x] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 5.0.0.0
 - Windows build number: 17763.504
 - Steps to reproduce: 
    1. Screen standby until extinguished
    2. Wake up the screen and enter the desktop
    3. Found that the software settings have failed
    4. The taskbar is no longer transparent
    5. Need to restart the software to make the software take effect again
 - Expected results: Like the 2017 version, my settings are valid no matter what the circumstances, not an unexpected situation.
 - Actual results: After restarting the screen again, the taskbar transparency effect of the software setting is invalid. It is useless to change the settings. The software must be restarted.

**Comment by sylveon** [comment]
This should be fixed in the latest update, available in the Store.
