### ISSUE TITLE
Chinese Translation of Menu Items (BY Picture Form)

### ISSUE THREAD

**Issue by MasterOfStar** [TranslucentTB/TranslucentTB#255]
I try to translation some menu items to Chinese.Maybe you can put it to the [WIKI](https://github.com/TranslucentTB/TranslucentTB/wiki/Tips-and-tricks-for-a-better-looking-taskbar)？
_______________________________________________________________________________________________________
# **菜单项目中英文对照**
## **↓主菜单↓**
![主菜单-Main Menu](https://user-images.githubusercontent.com/21274896/60389361-9e4b2a00-9af2-11e9-9642-6bd1f8a619a9.png)
## **↓全局设置↓**
![全局设置-Regular](https://user-images.githubusercontent.com/21274896/60389368-b15dfa00-9af2-11e9-93cb-9d25a1c7f4f1.png)
## **↓最大化窗口时↓**
![最大化窗口时-Maximised Windows](https://user-images.githubusercontent.com/21274896/60389375-b91d9e80-9af2-11e9-9adc-8e92af36df1c.png)
## **↓打开开始菜单时↓**
![打开开始菜单时-Start Menu Opened](https://user-images.githubusercontent.com/21274896/60389378-c5096080-9af2-11e9-8b3a-5c15e3f2a1a3.png)
## **↓打开小娜或搜索时↓**
![打开小娜或搜索时-Cortana Search Opened](https://user-images.githubusercontent.com/21274896/60389381-d3577c80-9af2-11e9-9439-642e1b0f5364.png)
## **↓打开时间线时↓**
![打开时间线时-Timeline Opened](https://user-images.githubusercontent.com/21274896/60389385-dd797b00-9af2-11e9-9b73-99ddf3e832e0.png)
## **↓显示桌面速览按钮↓**
![显示桌面速览按钮-Show Aero Peek](https://user-images.githubusercontent.com/21274896/60389390-e5391f80-9af2-11e9-8230-48a0f40ff2fe.png)
## **↓高级设置↓**
![高级设置-Advanced](https://user-images.githubusercontent.com/21274896/60389395-f3873b80-9af2-11e9-8ab0-5fe53e588d8f.png)
_______________________________________________________________________________________________________________
And here are some of my questions:
1.Will the software support start menu transparent in the future?
2.Maybe "Tips and tracks" could be renamed "Help"?

**Comment by xyhmnb** [comment]
wow，thanks.I hope this software can have translation，its  a little hard for chinese

**Comment by taylorsfan** [comment]
> wow，thanks.I hope this software can have translation，its a little hard for chinese

i think english is more hard.

**Comment by taylorsfan** [comment]
老哥 稳

**Comment by xyhmnb** [comment]
> 老哥 稳

哈哈哈，英语我太南了

**Comment by denosawr** [comment]
Thank you! I know that @sylveon has had some success with localisation into French so I'm sure this will come into handy for when he does implement it (soon, hopefully)!

**Comment by limbia** [comment]
厉害，顺便求支持设置显示桌面，开了这个原来的显示桌面就点不了了。
wish to have a option of display desktop.

**Comment by MasterOfStar** [comment]
@limbia 有这个设置选项来着，你可以仔细看下上面的对照图片进行设置

**Comment by boyliuxiaopeng** [comment]
感谢，软件为什么不编译中文呢

**Comment by sylveon** [comment]
Because the software doesn't supports translations as of yet and no developer in the team is Chinese,

**Comment by Geeyun-JY3** [comment]
现在可以翻译了：

https://github.com/TranslucentTB/TranslucentTB/issues/419#issuecomment-962548616

> Pull request has been merged. You can now follow the contributing guide to translate TranslucentTB.

**Comment by MasterOfStar** [comment]
> 现在可以翻译了：
> 
> [#419 (comment)](https://github.com/TranslucentTB/TranslucentTB/issues/419#issuecomment-962548616)
> 
> > Pull request has been merged. You can now follow the contributing guide to translate TranslucentTB.

bravo!

**Comment by sylveon** [comment]
Seeing as I merged both traditional and simplified chinese translations, I will close this issue
