### ISSUE TITLE
Error with MSVCP140.dll

### ISSUE THREAD

**Issue by leifniem** [TranslucentTB/TranslucentTB#256]
[x] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 2018.2 (can't run program)
 - Windows build number: 1903 (18362.207)
 - Steps to reproduce: 1. Run.
 - Expected results: Program would start as usual
 - Actual results: Getting the error message attached
 - Other: Updated VCredist to no avail.

![image](https://user-images.githubusercontent.com/5417518/60421128-7e4a6200-9be9-11e9-9a23-a606418d944f.png)

**Comment by sylveon** [comment]
TranslucentTB depends on the x86 visual C++ 2017 redistributable and this message tells me that it is corrupted. Try uninstalling and reinstalling it.

**Comment by leifniem** [comment]
Seems to work. Thank you very much for your help! 😊
