### ISSUE TITLE
Latest version crashes out after a few minutes on the latest Windows build.

### ISSUE THREAD

**Issue by JohnRWMarchant** [TranslucentTB/TranslucentTB#258]
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 
 - Windows build number: 
 - Steps to reproduce: 
 - Expected results: 
 - Actual results: 
 - Other:

**Comment by sylveon** [comment]
The form is here to be filled, not ignored. Anyways, does it happens if you use the version on GitHub?

**Comment by JohnRWMarchant** [comment]
Hi,

Sorry missed the form but i left a message up on the MS Store. The latest
version from a few days ago on the MS Store suddenly stops working after a
few minutes.

I have not tried the one from github, is this a more up to date version
then.

**Comment by sylveon** [comment]
It is the same version, but it's easier for me to give you a version to test derived from the GitHub version than it is to with the Microsoft Store.

**Comment by JohnRWMarchant** [comment]
Hi,

Ive uninstalled the MS Store one and installed the github one. Seems ok at
the moment. Will let you know if it crashes out later.

Regards, John

**Comment by JohnRWMarchant** [comment]
Hi,

Just to let you know it crashed again. I'm wondering if it has something to
do with my screen switching off after 5 mins with no use.

Regards, John

**Comment by sylveon** [comment]
Possibly, I've also had reports it happens when a game leaves/exits fullscreen, both situations involve a monitor being disconnected from the program's perspective. I'll do some testing myself and come back with a version that you could test.

**Comment by JohnRWMarchant** [comment]
Hi,

Thanks for that.

**Comment by sylveon** [comment]
Could you check if the reliability monitor has a memory dump?

Search and open "Reliability monitor" in Cortana, you should see something like this:
![](https://cdn.discordapp.com/attachments/312341949078306818/598772581612388374/unknown.png)

Click on "View technical details" for one of the events pertaining to TranslucentTB, you should see this:
![](https://cdn.discordapp.com/attachments/312341949078306818/598773206505226241/unknown.png)

Find one that has a file ending with ".mdmp", ".hdmp" or ".dmp" in this category (if the event you're currently viewing doesn't, try another one and so on):
![](https://cdn.discordapp.com/attachments/312341949078306818/598773632331808779/unknown.png)

Once you find an event with that, click on "View a temporary copy of these files", compress them all in a .zip file, and upload it here on GitHub or send it to my email (charles.milette@gmail.com)

That would be very helpful for me to diagnose the problem!

**Comment by sylveon** [comment]
Could you try this version?

[TranslucentTB-setup.zip](https://github.com/TranslucentTB/TranslucentTB/files/3388202/TranslucentTB-setup.zip)

**Comment by JohnRWMarchant** [comment]
Hi Charles,

So far so good, the screen has gone to standby a couple of times and no
issues so far.

Regards, John.

**Comment by sylveon** [comment]
I've published this as an staged rollout to the Microsoft Store, about 50% of users are getting this updated build automatically (people who manually check will always get the latest build) and I'm monitoring telemetry data to see if the issue is resolved for everyone.

**Comment by JohnRWMarchant** [comment]
Hi Charles,

Good to hear and i hope it all goes well with no other issue.

MInd you next Win 10 update who knows.

Regards, John

**Comment by sylveon** [comment]
Rollout finalized, this new version is available to everyone and a GitHub release was published

**Comment by JohnRWMarchant** [comment]
Hi Charles,

Thanks very much.

Regards, John
