### ISSUE TITLE
Tray icon gone, forever; unable to access preference

### ISSUE THREAD

**Issue by normalranger** [TranslucentTB/TranslucentTB#259]
- TranslucentTB version: 7.0 (Store version)
 - Windows build number: 1903 Insider Build (Slow); 18362.10000
 - Steps to reproduce: Untick "Show tray icon"
 - Expected results: Another way to bring back the settings/preference UI
 - Actual results: Besides starting and closing the app, I can no longer find any other way to customize the settings.
 - Other: I've tried resetting the app from the Microsoft Store, doesn't do anything. Also tried forcing my way into the config.cfg but the the string is already "no-tray=disable"

**Comment by sylveon** [comment]
The `config.cfg` for the Microsoft Store version is in `%LocalAppData%\Packages\28017CharlesMilette.TranslucentTB_v826wp6bftszj\RoamingState\TranslucentTB`, not %AppData%\Roaming\TranslucentTB`

**Comment by normalranger** [comment]
> 
> 
> The `config.cfg` for the Microsoft Store version is in `%LocalAppData%\Packages\28017CharlesMilette.TranslucentTB_v826wp6bftszj\RoamingState\TranslucentTB`, not `%AppData%\Roaming\TranslucentTB`

Got it, should have went with the simple question instead of a ticket. Thank you for the clarification!

**Comment by Nagidrop** [comment]
I came across this while finding a solution on Google. But as the time of my comment (Dec 8th 2021), the path to configuration file (settings.json) is changed into `%LocalAppData%\Packages\28017CharlesMilette.TranslucentTB_v826wp6bftszj\RoamingState`.

EDIT: Still works in July 15, 2023

**Comment by Squall2103** [comment]
"ignored_windows": {
    "window_class": [],
    "window_title": [],
    "process_name": []
  },
  **"hide_tray": true,**
  "disable_saving": false,
  "verbosity": "warn"
}

just add that line before disable saving, and that makes the trick, save the changes and u gucci, this is only for tray icon / notification icon
