### ISSUE TITLE
The "show desktop" button on taskbar doesn't work

### ISSUE THREAD

**Issue by zhufengning** [TranslucentTB/TranslucentTB#260]
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 2019.1.0.9a3e1907fc08190a2d46350aa1a8ba...
 - Windows build number: 18362.239
 - Steps to reproduce: open TranslucentTB.exe
 - Expected results: The "show desktop" button works well
 - Actual results: it doesn't work at all, seems disappeared

**Comment by sylveon** [comment]
Change "Show Aero Peek" to "always", by default it will get hidden if there is no window maximised.
![image](https://user-images.githubusercontent.com/6440374/61485649-a10da200-a96f-11e9-8280-4acf9a33796c.png)
