### ISSUE TITLE
TranslucentTB doesn't work when I maximise a windows

### ISSUE THREAD

**Issue by LukieVie** [TranslucentTB/TranslucentTB#261]
- TranslucentTB version is 6.0.0.0
 - Windows Version is Build 17763.615

TranslucentTB doesn't work when I'm in other window, 
![image](https://user-images.githubusercontent.com/53366791/61992288-d8c2cb00-b08e-11e9-8181-0535f0b484a9.png) --> This is when I'm on my desktop.
![image](https://user-images.githubusercontent.com/53366791/61992307-014ac500-b08f-11e9-87db-0ed2345a7049.png) --> This is when I'm in a window.

You can see the taskbar is fully black in a window, and transparent on my desktop.

Is this normal?

**Comment by sylveon** [comment]
That's the default configuration of TranslucentTB, you can change it or disable it altogether by opening the context menu, and selecting the submenu "Maximized window"
