### ISSUE TITLE
TranslucentTB as an exe file.

### ISSUE THREAD

**Issue by MarchWorks** [TranslucentTB/TranslucentTB#262]
I would like to use TranslucentTB in an app in this way `execFile(TranslucentTB.exe, opacity)` where opacity is a value between 0 and 100.

So `TranslucentTB.exe` need to accept args like if you are executing it from `cmd` like so `path-To_TranslucentTB>TranslucentTB.exe 50`

**Comment by sylveon** [comment]
TranslucentTB used to have command line arguments - you might be interested in them: https://github.com/TranslucentTB/TranslucentTB/releases/tag/2017.3.

Those where removed for the latest version, and I've planified to add them to the next version (they actually used to be present in the code for the next version, but I've removed them while redoing the code for app configuration.

**Comment by MarchWorks** [comment]
Looking forward for the next version. I will use 2017.3 for now

**Comment by MarchWorks** [comment]
@sylveon One question please. How to return the taskbar to its default state?

**Comment by sylveon** [comment]
2017.3 does not supports that.
