### ISSUE TITLE
Translucent Taskbar crashes after a short while [Windows 10]

### ISSUE THREAD

**Issue by brandyyn** [TranslucentTB/TranslucentTB#263]
I have installed the latest update from the windows store AND off of google, I'm not sure exactly what causes it but after a short while of it working it will just crash, stop working and I have no clue how to fix it or what is causing it.

**Comment by du33169** [comment]
The same thing happened to me. Especially when I press "Accent Color".

**Comment by sylveon** [comment]
This should be fixed in the latest update, available in the Store.
