### ISSUE TITLE
Main monitor not affected by TranslucentTB after lock and/or sleep

### ISSUE THREAD

**Issue by BoneheadFraggle** [TranslucentTB/TranslucentTB#270]
[X] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 7.0.0.0 2019-0728 Version 4 hotfix 3 
 - Windows build number: 18362.418 
 - Steps to reproduce: Probably related to computer wake up from sleep and/or display changes from one internal laptop display to two external displays and/or going from locked stae to unlocked. For me these states are tightly connected so I have a hard time reproducing the issue separately 
 - Expected results: Translucent is set to be Clear in all options. It should continue to be clear after a display change 
 - Actual results: Sometimes, it becomes "not active at all" on the main display, but it remains Clear on the secondary display
 - Other: Manually "Refresh taskbar handles" solves the problem. I could live with a work around like "at Windows Security event 4648 (logon), refresh taskbar handles. But that would require a scriptable access to TTB.

**Comment by sylveon** [comment]
Next version has more accurate monitor removal/connection detection

**Comment by DerRockWolf** [comment]
@sylveon can you give us a date?

**Comment by sylveon** [comment]
Unfortunately, no. There's quite a lot of work missing and I have barely any free time to work on TranslucentTB.

**Comment by DerRockWolf** [comment]
@sylveon No problem, thanks for the info :D

**Comment by aravindpanil** [comment]
Hi. Is there an update? I too am facing this problem. On PC restart it works fine but after sleep, the main monitor doesn't work well with Translucent TB. @sylveon

**Comment by sylveon** [comment]
This issue is fixed on the dev version. There are instructions to acquire it in the readme, but some features are missing.
