### ISSUE TITLE
Flashing taskbar

### ISSUE THREAD

**Issue by cyborgium** [TranslucentTB/TranslucentTB#274]
[ x] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: version 4 hotfix 3
 - Windows build number: 18363.418 but I also had it on version 1903
 - Steps to reproduce: press the windows startbutton
 - Expected results: taskbar should remain whatever option I have selected, in my case "opaque".
 - Actual results: taskbar flashes whatever accent colour is set in windows
 - Other: When holding mouse on taskbar, it only happens the first time I press the windows bar

**Comment by sylveon** [comment]
Duplicate of #196
