### ISSUE TITLE
 How to change the startup default to "clear" please

### ISSUE THREAD

**Issue by LeeZhuoHeng** [TranslucentTB/TranslucentTB#276]
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 
 - Windows build number: 
 - Steps to reproduce: 
 - Expected results: 
 - Actual results: 
 - Other:

**Comment by sylveon** [comment]
What do you mean?

**Comment by soybn** [comment]
me ayudas esque me dice transculent tb error es q no se inicia al inciar windows )=
