### ISSUE TITLE
Remove Shadow when the Application is maximized

### ISSUE THREAD

**Issue by cricrazy** [TranslucentTB/TranslucentTB#277]
[x ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: Version 4 hotfix 3
 - Windows build number: Windows 10  - Version 1809  (OS Build 17763.864)
 - Steps to reproduce: When any application is maximized (like Google Chrome or Notepad++), the shadow darkens the task bar. (See screenshots)
 - Expected results: The Taskbar should stay clear (Translucent). 
 - Actual results: There is a darker shadow that make it less clear. 

![image](https://user-images.githubusercontent.com/4622816/70081178-aa6d7300-15cd-11ea-8765-7dba3f609e67.png)

![image](https://user-images.githubusercontent.com/4622816/70081297-de489880-15cd-11ea-8db3-39ceb49a83e7.png)

![image](https://user-images.githubusercontent.com/4622816/70081469-3b444e80-15ce-11ea-84e9-7a4429fb5662.png)

**Comment by sylveon** [comment]
This is the default configuration, to change it disable maximised windows in the tray context menu:

![image](https://user-images.githubusercontent.com/6440374/70458225-ad5ddd00-1a7f-11ea-9b23-86af0f6a1aec.png)

**Comment by cricrazy** [comment]
@sylveon Sorry, but I don't think it is fixed yet. I have changed the settings as you mentioned.

Here are two screenshots, 

1. First one is not maximized, you can see the transparent taskbar very clearly without any shadow. 
2. Second one is maximized, the taskbar is transparent, but it does have some shadow. Taskbar is much darker than previous screenshot. 

**No Shadow**
![t1](https://user-images.githubusercontent.com/4622816/70461085-77b7f480-1a7d-11ea-9dec-f80dcc4fd376.jpg)

**With Shadow**
![t2](https://user-images.githubusercontent.com/4622816/70461095-7d153f00-1a7d-11ea-914a-7e659c5f2afc.jpg)

**Comment by sylveon** [comment]
That's weird, it should and works for me.

**Comment by cricrazy** [comment]
What version are you using?

**Comment by sylveon** [comment]
The latest from the windows store (which is also equivalent to the latest from GitHub)

I just reset the settings of the app, disabled "Maximised windows" (Maximised windows > Enabled is unchecked) and it does the behavior you expect.

**Comment by cricrazy** [comment]
I installed one from Windows store. Still same issue. 

Can you please attach two screenshot, one without maximized and one with the maximized? Appreciate it.

**Comment by zeyonaut** [comment]
For future reference, you should change the accent color to 0x00000000 to achieve transparency. If you have this issue, that means that your accent is merely translucent. The accent color is not shared between the menu options, so this can cause some confusion when all of them are transparent but one.
