### ISSUE TITLE
Windows on ARM64 version

### ISSUE THREAD

**Issue by james856** [TranslucentTB/TranslucentTB#278]
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: latest from the Microsoft Store
 - Windows build number: 18363.535

TranslucentTB currently runs as emulated x86 on Windows 10 on ARM64. Can you port the app to native ARM64 for better performance?

[Windows 10 ARM-based PCs FAQ](https://support.microsoft.com/en-us/help/4521606/windows-10-arm-based-pc)
[Surface Pro X app compatibility](https://docs.microsoft.com/en-us/surface/surface-pro-arm-app-performance)

**Comment by sylveon** [comment]
This is already planned (and prior to the last couple commits, it actually builded in ARM64) because of the way the next version works.

**Comment by sylveon** [comment]
An official ARM64 build is now available (almost 2 years later, oops)
