### ISSUE TITLE
Black Taskbar after upgrading to Windows 10 1909

### ISSUE THREAD

**Issue by pro4tlzz** [TranslucentTB/TranslucentTB#279]
- TranslucentTB version: 7.0.0.0
 - Windows build number: 18363.535
 - Steps to reproduce: After I updated to Windows 10 1909 from 1903 my taskbar does not show the desktop image colour even though I have full clear set everywhere, I can see the clear when on my desktop but not when in a maximised window or start menu opened. Timeline and desktop are fine. I have the dark Windows theme but not the apply accent to the taskbar enabled. This worked completely fine in 1903
 - Expected results: Clear blue taskbar everywhere
 - Actual results: Clear taskbar desktop and timeline
 - Other: Changing to Windows light mode makes my taskbar fully black and hides the Windows Icons along with some other taskbar icons, toggling transparency has no effects

**Comment by pro4tlzz** [comment]
![image](https://user-images.githubusercontent.com/22709115/71534613-edceaf00-28f7-11ea-9cd5-d54773b28bb9.png)
![image](https://user-images.githubusercontent.com/22709115/71534618-f4f5bd00-28f7-11ea-90ad-989324de6d47.png)
![image](https://user-images.githubusercontent.com/22709115/71534628-02ab4280-28f8-11ea-849c-315c7cee8dd1.png)

**Comment by sylveon** [comment]
Not sure why this could be happening, my desktop PC with 1909 runs TranslucentTB fine :/

**Comment by pro4tlzz** [comment]
> Not sure why this could be happening, my desktop PC with 1909 runs TranslucentTB fine :/

odd i reinstalled and still the same

**Comment by thepcwiz101** [comment]
i think you have to enable transparency effects in windows settings.

**Comment by pro4tlzz** [comment]
I figured out falconx was set to use transparency, so basically I used two programs for the same thing 🤦‍♂️

**Comment by sylveon** [comment]
Haha that would absolutely do it.
