### ISSUE TITLE
Crash after updating the latest update of windows kb4528760 kb4532938

### ISSUE THREAD

**Issue by AmrBinBashir** [TranslucentTB/TranslucentTB#280]
[Yes ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: Latest, store version
 - Windows build number: 1909 os build 18363.592
 
This is a weird problem, microsoft pushed a cumulative update last night and i updated but TranslucentTB(store version) doesn't work and just crashes 2 sec after starting the app.
When i use TranslucentTB(github version) it works fine without crash but when all of my settings are lost and when i try to open the color picker to choose an accent the app crashes.
I had a system restore point before the update and i reverted back and everything works just fine. today, i wanted to check if the problem still exists so i updated and my doubts were right, the same problem happens again.
update version: kb4528760 kb4532938
uninstalling these updates doesn't seem to fix the problem only restore point works

2nd Update: system restore doesn't work anymore

**Comment by sylveon** [comment]
Can you reproduce the crash, find it in reliability monitor, press view technical details and then upload a zipped copy of the files that help describe the problem?
![](https://camo.githubusercontent.com/a4636f43e08ba6003949de5ff8fe7abf628e06af/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3331323334313934393037383330363831382f3539383737323538313631323338383337342f756e6b6e6f776e2e706e67)

![image](https://user-images.githubusercontent.com/6440374/72564569-0e967e80-387e-11ea-8418-3038128e85b1.png)
The file I'm interested in is the .hdmp file, if you don't find it on one of the crashes try looking at the others if they have it.

**Comment by AmrBinBashir** [comment]
Unfortunately there is no files attached to the crash here is the  creash report 
`Source
TranslucentTB

Summary
Stopped working

Date
‎1/‎16/‎2020 11:42 PM

Status
Report sent

Description
Faulting Application Path:	C:\Program Files\WindowsApps\28017CharlesMilette.TranslucentTB_7.0.0.0_x86__v826wp6bftszj\TranslucentTB\TranslucentTB.exe

Problem signature
Problem Event Name:	MoAppCrash
Package Full Name:	28017CharlesMilette.TranslucentTB_7.0.0.0_x86__v826wp6bftszj
Application Name:	praid:APP
Application Version:	7.0.0.0
Application Timestamp:	5d2a394a
Fault Module Name:	StackHash_0000
Fault Module Version:	10.0.18362.387
Fault Module Timestamp:	a4208572
Exception Code:	c0000374
Exception Offset:	PCH_03
OS Version:	10.0.18363.2.0.0.256.48
Locale ID:	1033
Additional Information 1:	0000
Additional Information 2:	00000000000000000000000000000000
Additional Information 3:	0000
Additional Information 4:	00000000000000000000000000000000

Extra information about the problem
Bucket ID:	c899cdbfa78d58aef675963fe05fe03a (1618364842201047098)
`

**Comment by amrbashir** [comment]
I reinstalled windows and the app is working fine now, i think the crash was because of some corrupted files on my machine.
