### ISSUE TITLE
TranslucentTB inverting detection of Primary and Secondary monitor

### ISSUE THREAD

**Issue by iamthekings5** [TranslucentTB/TranslucentTB#282]
[/] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 7.0.0.0

 - Windows build number: 19546.1000

 - Steps to reproduce:
1) Boot my laptop disconnected from my external monitor.
2) Connect to monitor (main monitor: laptop screen)
2) Use a 3rd party application (DisplayFusion) to change main monitor. (main monitor: External monitor).

 - Expected results:
TranslucentTB should see external monitor as primary monitor now that it has been set.

 - Actual results:
However, it seems Translucent still sees the now primary monitor as secondary, and the now secondary monitor as primary. This issue will not be resolved until a reboot happens with the profile that is being intended for further use is active while rebooting.

 - Other:
I have tried the option only center primary taskbar but that would just center the taskbar on the secondary monitor which it sees is primary. The visual effects of Translucent should look as if it has been switched for both primary and secondary. E.g. if you are full screen on secondary monitor, then primary taskbar will activate maximised effect.

**Comment by sylveon** [comment]
TranslucentTB relies on the Windows API to match a monitor to a window, there's not much we can do if DisplayFusion makes the API return wrong results.

**Comment by iamthekings5** [comment]
> 
> 
> TranslucentTB relies on the Windows API to match a monitor to a window, there's not much we can do if DisplayFusion makes the API return wrong results.

Completely understandable, had no idea DisplayFusion could be the one causing the issue. Thanks!
