### ISSUE TITLE
Solved - Maximised Window styling is dark; not working properly?

### ISSUE THREAD

**Issue by Darthagnon** [TranslucentTB/TranslucentTB#286]
Yes, I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 4 hotfix 4 (latest)
 - Windows build number: v1709 Home (build 16299.967)
 - Steps to reproduce: Set Maximised Window styling of taskbar to "Clear" or "Blur" (Normal and Opaque seem to work). 
 - Expected results: The taskbar should be clear or blurred, exactly as when set to Clear or Blur for Regular or Star Menu, or any of the other modes.
 - Actual results: "Clear" is a slightly darker version of Normal, "Blur" ignores tinting, and is a dark blur.
 - Other: I'll swear I had it working fine before, when on v4 hotfix 1, but since then I've tried using it in combination with FalconX, and updating to v4h4, and now, it doesn't work.

**Comment by sylveon** [comment]
Change the accent color for maximised. By default it has a darkish tint.

**Comment by Darthagnon** [comment]
Solved! Thank you! I had assumed accent colours were universal.

**Comment by Darthagnon** [comment]
Sorry about the bad issue title; thought I'd typed it out in full before submitting.
