### ISSUE TITLE
Why not use TaskbarAcrylicOpacity value to adjust?

### ISSUE THREAD

**Issue by vhanla** [TranslucentTB/TranslucentTB#287]
I don't know if you are aware of using `TaskbarAcrylicOpacity` DWORD (0-225) value in `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced` key
in order to adjust the Acrylic opacity of the taskbar.

I'm trying to use `SendNotifyMessage(HWND_BROADCAST, WM_SETTINGCHANGE, 0, LongInt(PChar('TraySettings')));` and `SHChangeNotify(SHCNE_ASSOCCHANGED, SHCNF_IDLIST, NULL, NULL)` without success, it doesn't refresh.

However, after restarting of Explorer.exe the opacity level updates.

**Comment by sylveon** [comment]
Because it only controls the opacity, which is not the full feature set of TranslucentTB. Since we need to use SetWindowCompositionAttribute for our full feature set, and that can also control the opacity, we're using that.

**Comment by vhanla** [comment]
I see, one thing I noticed though, is that if another process calls SetWindowCompositionAttribute without a hook to the explorer taskbar periodically (using a timer), TranslucentTB fails i.e. slowsdown or hangs the system. Is there any way to detect that call coming from another process to modify explorer's so it can be ignored?
