### ISSUE TITLE
Feature Request:The preview desktop button on the far right of the taskbar is unavailable

### ISSUE THREAD

**Issue by cyan-river** [TranslucentTB/TranslucentTB#288]
The preview desktop button on the far right of the taskbar is unavailable and I need him very much.

**Comment by sylveon** [comment]
Set "Show Aero Peek" to "Always"
![image](https://user-images.githubusercontent.com/6440374/76312368-4aabf580-62a9-11ea-958c-fdf664af2b6e.png)

**Comment by cyan-river** [comment]
Think you very much！
