### ISSUE TITLE
better support for windows' new system-wide light mode

### ISSUE THREAD

**Issue by eNV25** [TranslucentTB/TranslucentTB#289]
- TranslucentTB version: 8.0.0.0 (windows store)
 - Windows build number: 1909 (OS Build 18363.693)
 - Steps to reproduce: 
   enable light mode
   windows settings > personalization > colors > choose your default windows color mode [light]
                                                          OR            > choose your default windows color mode [custom] > choose your default app mode [light]

Problem:

In opaque setting:
   - no visibility
   - icons black
   - taskbar black

All other settings: 
-  icons are black but most backgrounds are usually dark, so poor visibility.

Suggested solution:
Program should automatically detect if windows is on dark mode or light mode, and 
- change [opaque] taskbar color to white 
- control color of icons according to background for better visibility (can be global too)

**Comment by sylveon** [comment]
> change [opaque] taskbar color to white

Use the color picker ("Accent Color") to set the color to white.

> control color of icons according to background for better visibility (can be global too)

TranslucentTB cannot control the icon color.

**Comment by eNV25** [comment]
not that i like the light theme, just pointed it out

**Comment by KeshiSmith** [comment]
I am using a tool named "Auto Dark Mode" for changing my computer theme and wallpaper automatically. So, use the color picker "Accent Color" can not solve my problem. I hope TranlucentTB can Improve support for system themes. Best wishes!
