### ISSUE TITLE
Reenable Tray Icon

### ISSUE THREAD

**Issue by Hexality** [TranslucentTB/TranslucentTB#293]
Hi, I hided the tray icon and I can't find the file to reenable it. where it is located?

**Comment by Hexality** [comment]
TTB downloaded from MS Store

**Comment by sylveon** [comment]
`C:\Users\<you>\AppData\Local\Packages\28017CharlesMilette.TranslucentTB_v826wp6bftszj\RoamingState\TranslucentTB\config.cfg`

**Comment by sylveon** [comment]
Has this been resolved?

**Comment by sylveon** [comment]
Going to take this as a yes, let me know if you still have problems.
