### ISSUE TITLE
Taskbar clear issue

### ISSUE THREAD

**Issue by CyberL1** [TranslucentTB/TranslucentTB#294]
[x] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue here.
 - TranslucentTB version: 8.0.0.0
 - Windows build number: 18363.720
 - Steps to reproduce: Change any taskbar opion to Clear
 - Expected results: Taskbar sould be transparent
 - Actual results: Taskbar isn't transparent
 - Other:

**Comment by sylveon** [comment]
Are you sure that's not just caused by the maximised option's default accent color being set to a non-0 opacity?

**Comment by CyberL1** [comment]
> Are you sure that's not just caused by the maximised option's default accent color being set to a non-0 opacity?

I have maximalised window option disabled
