### ISSUE TITLE
FLASH when I switch from maximised window to desktop

### ISSUE THREAD

**Issue by vickychinghk** [TranslucentTB/TranslucentTB#297]
**FLASH** when I switch from maximised window to desktop

a very short time (about 0.05 second ) flash of the theme color at the  taskbar

right after I get to the desktop (from window) (by using "windows+D" or aero peek)

sometime twice (0.05 second x 2) or more

**Comment by misaeldry** [comment]
Hello!

I have the same problem. In my case, the taskbar flashes whenever I open the Start menu. It also happens after opening the start menu and clicking somewhere else.

**Comment by sylveon** [comment]
This flash is caused by a transition between normal (or acrylic) and another style. The dev builds use another technique that makes this flash invisible or much less noticeable, but they're not in a pretty poor state otherwise.

**Comment by x10102** [comment]
@sylveon Any idea when will this get fixed? I love the program otherwise but this is annoying the hell out of me.

**Comment by linpxzz** [comment]
me too

**Comment by thvozdovic** [comment]
Same here

**Comment by sylveon** [comment]
Wish I had a timeframe. I'm hoping by the end of the year it will be ready.

**Comment by sylveon** [comment]
This should be fixed in the latest update, available in the Store.
