### ISSUE TITLE
Where is executable in latest (2020) version of TranslucentTB-master?

### ISSUE THREAD

**Issue by chaloots** [TranslucentTB/TranslucentTB#298]
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 
 - Windows build number: 
 - Steps to reproduce: 
 - Expected results: 
 - Actual results: 
 - Other:

**Comment by sylveon** [comment]
You can download the setup from https://github.com/TranslucentTB/TranslucentTB/releases/tag/2020.1

**Comment by chaloots** [comment]
Thanks for this, Charles. Ever since coming across TB a couple of years ago
(on reddit, I believe) I've been a contented, satisfied user. The *only *issue
I've encountered was that I had to repeatedly re-open it after the monitor
had shut down from the settings in Windows. No big deal, but it got old.
This was all in the github version I should add, as opposed to the Windows
store flavor. Every now and then I'd check in on github to see if a new
version was available. With the latest, the one I originally referenced
with the "-master" suffix, I couldn't find an .exe file, and not knowing
diddly about coding, I didn't know what my options were, panicked and
installed the Windows store version. Come to find out I had difficulty
verifying it to start up with Windows. Maybe I overlooked something, but I
soon deleted it. Call me stubborn, but given the choice between a vendor
version and one on the Windows Store, well, IMO there really is no
comparison. So I went back to github and found the Version 4 Hotfix, which
I downloaded/installed. Maybe I won't have to re-invoke it to come back to
life after a period of inactivity. Who knows? I'll keep my fingers crossed
in the meantime.

Again, molto grazie for the prompt, pertinent reply. It's much appreciated.
Would really like to express my gratitude for what I consider to be a
gotta-have program. How can I show this in the way of a donation to the
cause?

Charlie

**Comment by sylveon** [comment]
Thank you for the words! It really means a lot to me when people show their appreciation. I see you've found the way to the Liberapay account yourself, but I'll link it for future reference: https://liberapay.com/TranslucentTB/
