### ISSUE TITLE
Windows taskbar icons hardly visible in transparent mode

### ISSUE THREAD

**Issue by oxk4r01** [TranslucentTB/TranslucentTB#299]
Is it possible to make the icons black when the the clear mode is selected? 
Having the taskbar transparent and the icons white makes very difficult to see them.
![image](https://user-images.githubusercontent.com/1032224/79867667-fd11c500-83de-11ea-8277-716e47a5c7e7.png)

**Comment by sylveon** [comment]
See #273. Use the system white taskbar theme to turn the icons black.

**Comment by oxk4r01** [comment]
Ok, solved it. Thank you very much @sylveon
