### ISSUE TITLE
Log file

### ISSUE THREAD

**Issue by MrAksel** [TranslucentTB/TranslucentTB#30]
Now that the program has grown a little it might be fitting to include a log file to make it easier to debug in case someone experiences problems. I'm mostly thinking logging details related to config file IO and parsing, but there may be other areas that benefit too.

**Comment by charlesmilette** [comment]
In case it crashes, it could dump the memory so then I’d be easy to debug some cases (of course we’d need some PDB files for the public release builds), along with the log file.

De : Aksel Lunde Aase
Envoyé le :13 janvier 2017 17:34
À : ethanhs/TranslucentTB
Cc : Subscribed
Objet :[ethanhs/TranslucentTB] Log file (#30)

Now that the program has grown a little it might be fitting to include a log file to make it easier to debug in case someone experiences problems. I'm mostly thinking logging details related to config file IO and parsing, but there may be other areas that benefit too.
