### ISSUE TITLE
Still effective after uninstall.

### ISSUE THREAD

**Issue by itsenti** [TranslucentTB/TranslucentTB#300]
TranslucentTB: Latest version from the Microsoft Store, couldn't figure out the exact version (have uninstalled)
After I uninstalled TranslucentTB, the taskbar doesn't get back to normal but it is still completely transparent as if the program is still running. 
-Restart doesn't help. 
-Reinstall TranslucentTB, reset to default settings, then uninstall again doesn't help.
-Big Windows feature update (2004 May Update) doesn't get it back to normal.
-When I turn off the transparent setting of windows, the taskbar goes opaque as normal; but as I turn on transparent setting, it goes completely clear again.

All I want now is to get the taskbar to its default transparency. 
Thanks in advance.
![image](https://user-images.githubusercontent.com/56781493/80526365-d21a0900-89bc-11ea-8740-15f71f3551e2.png)

**Comment by sylveon** [comment]
TranslucentTB does no permanent modification to the system so this is most likely unrelated.

**Comment by itsenti** [comment]
I'm pretty sure it's a bug. TranslucentTB starts acting weird after I turn off and on the Transparency setting of Windows while TranslucentTB is still active (this is why I have to uninstall it in the first place). I made no modifications to Windows except for TranslucentTB. Hope this makes my problem clearer.

**Comment by itsenti** [comment]
Fixed it. I reinstalled the app with .exe file instead of the version from the windows store like it did before, then uninstalled it. The taskbar now behaves normally with the transparency setting of windows. Thanks for you help though. I think the problem is of TranslucentTB version on the store.
