### ISSUE TITLE
Other:Is it possible to add a translucent mask, just like start menu, between icons and the bar?

### ISSUE THREAD

**Issue by Thy3634** [TranslucentTB/TranslucentTB#301]
When I open the start menu, I realized that the taskbar should have the same texture as it.

**Comment by sylveon** [comment]
What do you mean?

**Comment by Thy3634** [comment]
Darken the background.

**Comment by sylveon** [comment]
You can get that by changing the accent color:
![image](https://user-images.githubusercontent.com/6440374/80851248-851d7900-8bee-11ea-8db4-a733327d008d.png)

**Comment by Thy3634** [comment]
Thanks. I have set "dynamic-start-opacity=148" ,it's great!

**Comment by sylveon** [comment]
Glad you got it resolved!
