### ISSUE TITLE
Feature Suggestion | Add screen splitting settings and start menu settings as appropriate

### ISSUE THREAD

**Issue by Wzyyyu** [TranslucentTB/TranslucentTB#302]
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 -TranslucentTB version: Latest Store Version
 -Windows build number: 18363.778
 -Suggestion:  It can't adjust the split screen. I want to add options (depending on whether the desktop is full or other ways). Opening the start menu will be out of place. For example, when I set the non window maximization to transparent, the window maximization is the original system mode, but when I perform the split screen task, even though my screen is full, its display is still transparent. In addition , when I open the start menu, its color and status bar will be out of place. If possible, I want to add the function that the transparency of the start menu changes according to the status bar.

**Comment by sylveon** [comment]
I understand the idea, but detecting windows being snapped or otherwise covering the work area (work area being the area of the monitor where there isn't any taskbar) is tricky business.

I'm not sure what you mean about the start menu, could you explain in more details and/or add screenshots?

**Comment by WHLUXI** [comment]
Thank you for your reply. I'll give you a screenshot, which is the interface that appears after pressing the windows button. These are the two situations, when I open the start menu on the desktop, it will seem inappropriate. So I hope you can add the function that the start menu can change according to the change of the status bar. I don't know if it will be very troublesome.
![QT2T B{S}P)O(XVJ)LH0}SE](https://user-images.githubusercontent.com/57252036/80992709-80fe8f00-8e6c-11ea-8ad1-2d5c6af5bdc6.png)
![5O3VO}M4SPA5KYSW@%EO_GM](https://user-images.githubusercontent.com/57252036/80992717-84921600-8e6c-11ea-9ca5-628c96458d2f.png)

**Comment by WHLUXI** [comment]
Thank you for your reply. I'll give you a screenshot, which is the interface that appears after pressing the windows button. These are the two situations, when I open the start menu on the desktop, it will seem inappropriate. So I hope you can add the function that the start menu can change according to the change of the status bar. I don't know if it will be very troublesome.
![KAAN5R8K_B0JZ22}G0F%HAS](https://user-images.githubusercontent.com/57252036/80993055-01bd8b00-8e6d-11ea-806a-d1da6d62c9e5.png)
![~H~B7YLZW HJKB TR~4K~HE](https://user-images.githubusercontent.com/57252036/80993062-041fe500-8e6d-11ea-88f6-d6e8d2375c04.png)

**Comment by Wzyyyu** [comment]
Thank you for your reply. I'll give you a screenshot, which is the interface that appears after pressing the windows button. These are the two situations, when I open the start menu on the desktop, it will seem inappropriate. So I hope you can add the function that the start menu can change according to the change of the status bar. I don't know if it will be very troublesome.
![1H~H6%YX8{ZDB0KRA5CU5~Q](https://user-images.githubusercontent.com/57252036/80993258-5fea6e00-8e6d-11ea-8637-eb4011f56f27.png)
![AHZ1 4WOTP1}}ZJ9)L2P)0F](https://user-images.githubusercontent.com/57252036/80993268-61b43180-8e6d-11ea-9763-bc2a8acf74b5.png)

**Comment by sylveon** [comment]
Ah. TranslucentTB can't (and most likely never will) change the appearance of the start menu. As an alternative, you can configure the appearance of the taskbar when the start menu is open:
![image](https://user-images.githubusercontent.com/6440374/80992886-321f0e00-8e08-11ea-8916-4c1d2dec817f.png)

This way, the taskbar can be using a different appearance when the start menu is open, even while on the desktop.

**Comment by Wzyyyu** [comment]
OK, I see. Thank you for your reply. This is really a very good software. I am very happy to meet it. I hope you can keep working hard. I believe more and more people will like it.

**Comment by sylveon** [comment]
Duplicate of #116
