### ISSUE TITLE
Taskbar blinking !!!

### ISSUE THREAD

**Issue by massouu** [TranslucentTB/TranslucentTB#303]
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 2020.1
 - Windows build number: 1909.18363.628
 - Steps to reproduce: Click on the desktop or any other window and then click on the Start menu
 - Expected results: Taskbar blinking like this(https://gfycat.com/shallowtangiblefeline)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/64867020/81196752-ae664c80-8fd4-11ea-8c66-99845f543f85.gif)
 - Actual results: 
 - Other:

**Comment by massouu** [comment]
It's weird that you didn't solve this problem in various updates. This is a very annoying problem
I used another program and there was no problem, but I like your program more than that and I want to use this program but not with these problems.
Please solve the problem
we are waiting

**Comment by sylveon** [comment]
This issue is caused by Windows Explorer trying to restore the default appearance while opening the start menu. You can go in the settings file and reduce the sleep time to minimize the flicker, a definitive solution should land in the next major update.

**Comment by massouu** [comment]
Thanks for your reply
I changed the sleep time but the problem was not solved
I will wait for the update
