### ISSUE TITLE
Set Taskbar states for Cortana/Search opened, and open the Search, but Taskbar states not change.

### ISSUE THREAD

**Issue by rsp4jack** [TranslucentTB/TranslucentTB#306]
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 8.0.0.0 (UWP Edition)
 - Windows build number: 19041.207
 - Steps to reproduce: Set Taskbar states for Cortana/Search opened, and open the Search
 - Expected results: Taskbar states is change.
 - Actual results: Taskbar states isn't change.
 - Other: None

**Comment by sylveon** [comment]
This should be fixed in the latest update, available in the Store.
