### ISSUE TITLE
Recurring TB crash issues from log 

### ISSUE THREAD

**Issue by chaloots** [TranslucentTB/TranslucentTB#310]
From TB log:
(Thu May 21 08:55:42 2020) Getting class name of a window failed. Exception from HRESULT: Invalid window handle. (0x80070578) (T:\Projects\TranslucentTB\TranslucentTB\window.cpp:70 at function class std::shared_ptr<class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const > __thiscall Window::classname(void) const)

(Wed Nov  6 09:24:48 2019) Getting class name of a window failed. Exception from HRESULT: Invalid window handle. (0x80070578) (C:\Users\Sylveon\Desktop\TranslucentTB\TranslucentTB\window.cpp:70 at function class std::shared_ptr<class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const > __thiscall Window::classname(void) const)

TranslucentTB version 8, HotFix 4, on Windows 10, 1903, 18362.720.

**Comment by sylveon** [comment]
Those are not crashes, just noise. They will be at a lower log level in a future version, making them silent unless you lower the log level to info or debug.

**Comment by chaloots** [comment]
OK. Thanks for the prompt, pertinent reply. I appreciate it.
