### ISSUE TITLE
Reopening

### ISSUE THREAD

**Issue by Lightcaster5** [TranslucentTB/TranslucentTB#312]
After spending two minutes messing with it, I clicked the "hide" button and can't access any settings anymore. Whenever it starts, it just hides. Is there any way I can toggle this so I can change some settings?

**Comment by sylveon** [comment]
If you got it from the store, open the config file at `C:\Users\<you>\AppData\Local\Packages\28017CharlesMilette.TranslucentTB_v826wp6bftszj\RoamingState\TranslucentTB\config.cfg` and set `no-tray` to `disable`

**Comment by Lightcaster5** [comment]
Thanks for the help!
