### ISSUE TITLE
Taskbar stays transparent when Windows 10 Energy Saver Mode is active after TranslucentTB uninstallation.

### ISSUE THREAD

**Issue by ebespali** [TranslucentTB/TranslucentTB#315]
Hello!

In default Windows 10 installation. when Energy Saver mode is active, Start Menu, Action Center and Taskbar go to fully opaque mode, without transparency. But, after TranslucentTB installation and using it for some time, i decided to uninstall it and noticed that taskbar remains transparent with Energy Saver mode active. Start and Action Center however follow Energy Saver settings correctly. After TranslucentTB uninstallation, with Energy Saver active, when turning "Transparency Effects" switch off, taskbar go to fully opaque mode but when i manually set Transparency Effects switch to on - taskbar became fully transparent.
My question is, how to debug this issue, maybe some settings or hooks to DWM remains active even after TranslucentTB uninstallation?

This issue is present on my 2 Windows 10 installations on 2 separate machines, with 1903 and 2004 versions with latest TranslucentTB available from Microsoft Store.

Thanks for any feedback in advance!

**Comment by sylveon** [comment]
TranslucentTB does no hooking or system setting alteration... Have you tried rebooting after uninstalling it?

**Comment by ebespali** [comment]
Yes, of course.
Taskbar remains transparent with Energy Saver mode active even after reboot.
In fact, i checked this on another Win 10 1903 system, and it has the same issue after TranslucentTB uninstallation.
Could someone check, if this is the case for them too?
Maybe there is some debug information i could check, to resolve this issue without reinstalling entire OS.
Thanks!

Update: I check closed issues and find the same problem:
https://github.com/TranslucentTB/TranslucentTB/issues/300

I will try proposed solution there, but please, check taskbar state after uninstallation Store version of TranslucentTB with Energy Saver active on your laptops. Probably you will get the same result.

Thanks in advance!

**Comment by ebespali** [comment]
I tried the solution from: https://github.com/TranslucentTB/TranslucentTB/issues/300, but it didn't work for me. Transparency on taskbar in Energy Saver mode is still active, which is not the case in vanilla Windows 10.

Please check this behaviour on you machines with Store Version and Energy Saver Active.
Thanks.

**Comment by ebespali** [comment]
No answer since almost 2 weeks after bug report.
No mean to be rude but is it too difficult to check this case or at least give some feedback?

**Comment by sylveon** [comment]
I think this is actually normal behavior... A quick Google and I can see multiple images where the taskbar is also transparent in Energy Saver, for example: https://www.digitalcitizen.life/windows-10-power-slider-save-battery-increase-performance and https://superuser.com/questions/1052865/windows-10-has-both-battery-saver-option-and-power-saver-plan-what-is-the-diffe

As far as I recall, my laptop also does this too even without TTB.

Are you sure that it wasn't just your background giving you the impression that it was pure black? I know the default Windows 10 dark background can give you that impression.

**Comment by ebespali** [comment]
Thank you very much for time and answer.
I have checked this behaviour on my friend laptop without TTB and it also have transparent taskbar with Energy Saver.
Maybe this is now by default in recent Windows 10 versions, or i don't now why i was sure this is a bug.
Anyway, thanks for your feedback and i will close this issue.

**Comment by sylveon** [comment]
After looking into it more, it is indeed a Windows bug. What happens is that when power saver is active, explorer skips applying the composition attribute that the taskbar normally uses, which means the taskbar renders as if there wasn't any (so fully transparent). And when initially going into power saver, the composition attribute from pre-power saver mode is conserved.
