### ISSUE TITLE
Cant restore default settings

### ISSUE THREAD

**Issue by nisalk96** [TranslucentTB/TranslucentTB#316]
I installed the App and its working fine, but sometime middle Taskbar icons jumps to the right corner and hide, So I decided to uninstall the TranslucentTB app.
But trancelucent effect still remain and cant restore default system theme even after reboot.
Q:How to restore default system theme

**Comment by Danita** [comment]
Something similar is happening to me. I had some strange issues, so I uninstalled it and now sometimes some of my tray icons appear sporadically with a black background. I suspect some registry change may fix it, but I don't know where to look.

**Comment by CRAMOX43** [comment]
have yall already fixed it? Because i have the same problem and dont know how to fix it.

**Comment by nisalk96** [comment]
I couldn't fix it 
I had to reset my pc 😣
I think they don't reverse registry changes completely

**Comment by sylveon** [comment]
TranslucentTB does not change the registry at all. I don't even know how this can be happening.

**Comment by jaigak** [comment]
> TranslucentTB does not change the registry at all. I don't even know how this can be happening.

Windows may sync app settings so you can reset the app if you want to restore default settings

**Comment by CRAMOX43** [comment]
and where can i do that??

**Comment by jaigak** [comment]
@CRAMOX43 Right click TranslucentTB in the Start menu, click on more, select App Settings and hit reset.
