### ISSUE TITLE
Maximizing Window Introduces Darkness to Taskbar

### ISSUE THREAD

**Issue by coledeb** [TranslucentTB/TranslucentTB#317]
Hello. I believe this behavior started after a recent Windows update, but I cannot say for sure. When I attempt to maximize any windows on my desktop, TranslucentTB now makes the taskbar have a dark filter of some sorts over it. My settings for the program are to have the taskbar clear by default, then blurred for every other setting. I have attached screenshots of what is happening now.

My version of TranslucentTB is v8.0.0.0, and my build of Windows is v1909 (Build 18363.900)

![RegularWindow](https://user-images.githubusercontent.com/27379200/84870478-fef5ae80-b044-11ea-8efb-ddbb0ca9f739.png)

![DarkBlurred](https://user-images.githubusercontent.com/27379200/84870510-061cbc80-b045-11ea-86f0-55443df7ecc0.png)

**Comment by LubosMertak** [comment]
Change in settings ->Maximised window -> uncheck Enabled value ;-)

The same setting is too for start menu and other scenarios.

**Comment by coledeb** [comment]
@LubosMertak I think you are misunderstanding what I am saying. I *want* the blurred effect to happen on all of those. However, recently it has begun darkening the bar when applying the blurred effect. Before, it would be blurred and the same brightness as the wallpaper.

**Comment by LubosMertak** [comment]
Yeah... its my fail. I have the same problem like you.

**Comment by sylveon** [comment]
This is the default configuration. Change the color by using Maximised windows > Accent Color

**Comment by coledeb** [comment]
@sylveon is it? I have used TranslucentTB for several months now and this is recent behavior that it goes darker than the wallpaper. I'll change the value though 😄

**Comment by sylveon** [comment]
This has always been the default... your settings probably got reset.

**Comment by Alexx4SysteM** [comment]
> Change in settings ->Maximised window -> uncheck Enabled value ;-)
> 
> The same setting is too for start menu and other scenarios.

Thanks a lot, I had the same issue.
