### ISSUE TITLE
Possible to not run constantly?

### ISSUE THREAD

**Issue by wolf99** [TranslucentTB/TranslucentTB#322]
- TranslucentTB version: 8.0.0.0
 - Windows build number: 1909

Is it possible to set TTB to not need to run constantly?
When my system is low on resources it would be nice to not need to have anything running that is not actively doing something. As far as I can tell TTB sets some stuff for the taskbar, when I change the settings only but otherwise does not need to do anything further. Is that correct?
Thanks.

**Comment by sylveon** [comment]
That's incorrect, TranslucentTB needs to run constantly for the effect to apply. If TranslucentTB does not run, Windows Explorer will automatically reapply its normal style.

However, TranslucentTB is very light on resources (around 2-5mb of ram used for me) that I doubt it will make much of a difference closed or open.

**Comment by wolf99** [comment]
@sylveon  Thanks for the info
Suggestion to add similar info to, or near, the following README section: https://github.com/TranslucentTB/TranslucentTB#add-to-startup
