### ISSUE TITLE
Taskbar remains clear when battery saver mode in enabled

### ISSUE THREAD

**Issue by lucaptlr** [TranslucentTB/TranslucentTB#323]
Even though the taskbar is set to be normal when a program, timeline or start menu is open, when battery saver mode is enabled it remains clear as set in "regular" view. 

 - TranslucentTB version: 9.0.0.0 from windows store

**Comment by sylveon** [comment]
This is expected. The "normal" mode uses what explorer would normally use. When battery saver is on, explorer uses a non acrylic version to save battery.

**Comment by lucaptlr** [comment]
Thank you for the response. Cheers
