### ISSUE TITLE
Bug of Maximised windows in Win10 2004

### ISSUE THREAD

**Issue by F-Unction** [TranslucentTB/TranslucentTB#326]
[√] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: `9.0.0.0`
 - Windows build number: `19041.450`
 - Steps to reproduce: 

>Open the new style of start menu for Win10 2004
>
>> Create a file `open.reg` with
>>
>> ```
>> Windows Registry Editor Version 5.00
>> [HKEY_LOCAL_MACHINESYSTEMCurrentControlSetControlFeatureManagementOverrides2093230218]
>> "EnabledState"=dword:00000002
>> "EnabledStateOptions"=dword:00000000
>> ```
>>
>> and run it.
>>
>> Reboot.
>
>Select `Maximised windows -> Enable` and `Clear`
>
>Open a window, maximize it.
>
>

 - Expected results: The taskbar should be turn to clear
 - Actual results: It is still black but not clear.
![Snipaste_2020-08-22_15-03-58](https://user-images.githubusercontent.com/51352133/90950963-17d97080-e489-11ea-8dd6-119ec58912bf.png)
 - Other: Other features are ok.

**Comment by sylveon** [comment]
Are you sure that's not just a result of the default color for the maximized state being a darkish tint? You can change that using Maximised windows > Accent Color

**Comment by F-Unction** [comment]
thank you!
