### ISSUE TITLE
Enabled when disabled

### ISSUE THREAD

**Issue by garrychrstn** [TranslucentTB/TranslucentTB#327]
[ ] first, sorry, i am not native in english, so my report maybe will be difficult to understand
[ ] My TranslucentTB configured as follows :
    - Regular : clear
    - Star Menu opened : Enabled; clear
    - Timeline opened : Enabled; clear
    - Show aeropeek : Always
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 9.0.0.0
![disabled](https://user-images.githubusercontent.com/70214107/91187350-44f08200-e71a-11ea-8007-6f60d1098022.png)
![enabled](https://user-images.githubusercontent.com/70214107/91187370-4b7ef980-e71a-11ea-954e-95eca73f2b0a.png)

TB you're using. Open the properties of the TranslucentTB.exe file and look at the details tab to find this out. -->
 - Windows build number: Windows 10 Version 1903, OS Build 18362.1016
 - Steps to reproduce: I just wanna have some blur when in maximized windows, so i went to Maximized Windows -> *Check Enabled* and choose blur settings
 - Expected results: The taskbar will go blur, and the brightness should be same as when it's set as *clear*
 - Actual results: The taskbar went blur, but darker than clear state with unmaximized windows
 - Other: Also, when i *check* the enabled and select clear state in maximized windows settings, the taskbar went darker than normal, i think it should be in the same brightness as unmaximized windows.

If I am have some mistakes about what the features should do, please do tell me, Thank you

**Comment by sylveon** [comment]
The default Accent Color for maximized is a dark tint. You can use Maximized windows > Accent Color to change that.

**Comment by garrychrstn** [comment]
Thanks!
It works
