### ISSUE TITLE
Color bleed over between monitors using blur

### ISSUE THREAD

**Issue by Erithax** [TranslucentTB/TranslucentTB#329]
- TranslucentTB version: 2020.2 (version 4 hotfix 5)
 - Windows build number: 19041.450 (10 Home)
 - Steps to reproduce: Enable blur effect on a dual monitor setup with a repeated wallpaper on both monitors.
 - Expected results: The colours should not bleed over to the other screen.
 - Actual results: If the colours at the bottom-left and bottom-right of the wallpaper differ significantly you will get noticable bleedover from one monitor to the other.

 - Other: I attached screenshots of wallpaper in which the problem is very obvious, I originally noticed it in a picture, however. 
![prtsc-0](https://user-images.githubusercontent.com/64774344/91640189-ec6ffc00-ea1b-11ea-92b2-4a5e93014308.png)
![prtsc-1](https://user-images.githubusercontent.com/64774344/91640190-ed089280-ea1b-11ea-817d-73139429ef50.png)
![prtsc-1-zoom](https://user-images.githubusercontent.com/64774344/91640191-eda12900-ea1b-11ea-9420-5dade0ce4054.png)

**Comment by sylveon** [comment]
This is a DWM rendering artifact that we cannot resolve.
