### ISSUE TITLE
Timeline flickers when opened - Win 10 2004

### ISSUE THREAD

**Issue by bitkbs** [TranslucentTB/TranslucentTB#330]
Timeline flickers/flashes when opened with multiple windows open on the desktop. Continues with TranslucentTB closed so aren't sure if it's the cause. 

 - TranslucentTB version: 
 - Windows build number: 19041.450
 - Steps to reproduce: Open Timeline
 - Expected results: Smooth animation
 - Actual results: Flickers
 - Other:

**Comment by sylveon** [comment]
Can you get a recording of this?

**Comment by miladmaz12** [comment]
I get this whenever I have multiple windows open and the wallpaper of my dual-monitored PC changes every 10 minutes. I'm on Win 10 2004 as well.

**Comment by bitkbs** [comment]
> Can you get a recording of this?

Yes here we go: https://www.youtube.com/watch?v=h_vEz2SWJj4

**Comment by Pyker** [comment]
I have this happen as well, but it happens even with TranslucentTB closed entirely. I think it's just the way Windows loads the window titles which causes it to flicker.

**Comment by sylveon** [comment]
That's my conclusion as well

**Comment by bitkbs** [comment]
Which windows versions do you guys experience this on?

**Comment by Pyker** [comment]
I am also on Windows 10 2004 (build 19041.050)
