### ISSUE TITLE
New Fluent tray icon

### ISSUE THREAD

**Issue by prakharb5** [TranslucentTB/TranslucentTB#337]
With arrival of fluent design in Windows, I would like to request a new fluent design icon for the system tray. It will look good also. Also, please keep the tray icon in monochrome color.

**Comment by sylveon** [comment]
How can you be fluent while still being monochrome?

Also, the point of the current flat tray icon is to fit in with the rest of OS tray icons, so fluent design would defeat that point.

**Comment by prakharb5** [comment]
Ah, I see your point. Thanks for telling. Them there is no need for fluent icon.

**Comment by prakharb5** [comment]
I am closing this issue, since it does not make sense.
