### ISSUE TITLE
How to enlarge icon when mouse over?

### ISSUE THREAD

**Issue by englianhu** [TranslucentTB/TranslucentTB#339]
How to enlarge icon when mouse over? Especially icon on taskbar...

Below links talk about it

- [How to increase size of icon on hover?](https://www.reddit.com/r/Rainmeter/comments/70k48d/how_to_increase_size_of_icon_on_hover/)
- [How to import and export tweaks you did with Winaero Tweaker](https://winaero.com/import-export-winaero-tweaker/?unapproved=42792&moderation-hash=230e7679c9618effa336c22fe1024de8#comment-42792)

![20200928_010638.gif](https://user-images.githubusercontent.com/7227582/94369818-f2deba00-0126-11eb-9a66-0b1b49d9ef00.gif)

**Comment by sylveon** [comment]
I'm confused, is this a feature request?

**Comment by englianhu** [comment]
that's right

**Comment by englianhu** [comment]
I founded it...
https://www.hellotech.com/blog/the-best-dock-app-for-windows-10-to-download

**Comment by englianhu** [comment]
原来用苹果就行了，呵呵... RocketDock~@dashencaicai
https://github.com/englianhu/report/issues/2#issue-710304252

**Comment by englianhu** [comment]
using Stardock facebook (@official.stardock) + WinCustomize facebook (@wincustomize) will get it...
https://englianhu.wordpress.com/2020/09/29/discover-good-software-for-windows-users/
