### ISSUE TITLE
New Fluent Design Icon

### ISSUE THREAD

**Issue by akhilesh-balaji** [TranslucentTB/TranslucentTB#342]
This is a really cool app. However, the current icon looks really bad on the new start menu in Windows. I would suggest one that adhered to the Fluent Design guidelines more, like this one I designed:

![BeforeAfter](https://user-images.githubusercontent.com/69246693/98899363-7127cd80-24d5-11eb-833f-ab06c80198e2.png)

**Comment by sylveon** [comment]
We already have a new icon, however it is coming in a future update

**Comment by akhilesh-balaji** [comment]
@sylveon How does this icon look? Could you please share an image? Just curious to know.

**Comment by SinkKathir** [comment]
I like the colored icons a long time ago.😄

**Comment by sylveon** [comment]
You can see it here now: https://github.com/TranslucentTB/TranslucentTB/blob/develop/AppPackage/Assets/SmallTile.scale-400.png
