### ISSUE TITLE
i want to change language in it

### ISSUE THREAD

**Issue by AadilFarhan29** [TranslucentTB/TranslucentTB#343]
![image](https://user-images.githubusercontent.com/74016678/99893292-894ada00-2c97-11eb-80d5-3b7688644c36.png)
i cant find on how to change language or i cant change any extra settings because its not in English i don't  know Chinese any help??

**Comment by sylveon** [comment]
You installed a Chinese-translated fork. You want to install this version: https://www.microsoft.com/store/productId/9PF4KZ2VN4W9

**Comment by AadilFarhan29** [comment]
> You installed a Chinese-translated fork. You want to install this version: https://www.microsoft.com/store/productId/9PF4KZ2VN4W9

Thanks a lot man finally i understood
