### ISSUE TITLE
Accidentally launching twice freezes PC

### ISSUE THREAD

**Issue by mcoolidge** [TranslucentTB/TranslucentTB#344]
[X ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: Windows Store latest (can't find specific)
 - Windows build number: 19042.630
 - Steps to reproduce: 

1. Install the app from the store. 
2. Click launch twice. The GPL dialog will appear but might be behind other windows. 
3. Click accept on first dialog. 
4. Click accept on second dialog

 - Expected results: Only one instance starts
 - Actual results: Both instances start and lock computer. Even CTRL+ALT+DEL does not work.

**Comment by sylveon** [comment]
Fixed in dev build.
