### ISSUE TITLE
The software disables show-desktop button on the taskbar.

### ISSUE THREAD

**Issue by zacharyhuo** [TranslucentTB/TranslucentTB#345]
The software is quite amazing. But I want to know why the button on the right side of the taskbar that can show the desktop disappears when the software is on?
![image](https://user-images.githubusercontent.com/60465723/102002301-17196280-3d36-11eb-8563-2706ce01d8ea.png)

**Comment by sylveon** [comment]
It's an option. Right click on the tray icon, and under "show aero peek" click "always" to restore it.

**Comment by zacharyhuo** [comment]
Sorry that I did not find this option. Thanks for your great work!

**Comment by sylveon** [comment]
You're welcome!
