### ISSUE TITLE
What's your compile option?

### ISSUE THREAD

**Issue by SainoNamkho** [TranslucentTB/TranslucentTB#347]
I built the latest release to Release x86 with clang /o2, but the program starts very slowly, compared with your exe. It takes about 10 seconds before the program is initialized. Can anyone tell me how to speedup the executive?

**Comment by sylveon** [comment]
All the options used are in the solution/project files that are commited in this repo. I built the latest release from them. Does this same slowness reproduce when you use the LLVM toolset within VS?

**Comment by SainoNamkho** [comment]
The problem comes with ANSI locale. When I changed the default codepage to 437 and recompile it, the program starts faster.
