### ISSUE TITLE
reset when using displayport

### ISSUE THREAD

**Issue by hadeslmao** [TranslucentTB/TranslucentTB#349]
when using displayport, when you close the monitor (by turning it off, no unplug) because of displayport the computer thinks you unpluffed the monitor until you turn it back on. since translucentTB resets when a monitor is unplugged, every time I turn off the monitor and turn it back on translucentTB stops running and I need to run it again. not that big of a problem but since almost every new monitors are using displayport this might be something to fix.

**Comment by sylveon** [comment]
If you click advanced > refresh taskbar handles it should work as a workaround for now. This is going to be fixed in the next version.

**Comment by hadeslmao** [comment]
> If you click advanced > refresh taskbar handles it should work as a workaround for now. This is going to be fixed in the next version.

what do you mean advanced options? when I open the app nothing pops up it justs makes tb translucent

**Comment by sylveon** [comment]
There's a tray icon. If you right click it, a menu should show up

**Comment by hadeslmao** [comment]
thank you this should fix the problem
