### ISSUE TITLE
I would like to report a person ruining the softwares reputation 

### ISSUE THREAD

**Issue by aboody29** [TranslucentTB/TranslucentTB#351]
Theres a guy on tik tok ruining your reputation and i think you must see it.. heres the link to his video https://vm.tiktok.com/ZSWvQmkR/

**Comment by sylveon** [comment]
Thanks! I've reached out privately to that user and pointed them to #350

**Comment by aboody29** [comment]
Glad i could help, I couldnt stand an idiot ruining a softwares reputation
THATS ON MS STORE and gets that many views

**Comment by Calinou** [comment]
This issue can be probably be closed now :slightly_smiling_face:

**Comment by UntrustedInstaller** [comment]
> 
> 
> Thanks! I've reached out privately to that user and pointed them to #350

![image](https://user-images.githubusercontent.com/80781818/134251910-2d835b10-3bf5-43bd-9013-9924f18fbba4.png)
LOL

**Comment by aboody29** [comment]
Wait it got taken down
