### ISSUE TITLE
Center apps in Taskbar

### ISSUE THREAD

**Issue by ghost** [TranslucentTB/TranslucentTB#352]
It's nice to have this app, but It would be awesome if there is an option to center apps in the taskbar.
Like below, I am using another app for that currenlty.
![image](https://user-images.githubusercontent.com/63898013/103284890-84014d80-4a02-11eb-8211-0548e9addfa4.png)

**Comment by junesties** [comment]
FalconX or TaskbarX? I don't like it cause whenever i restart the explorer (or causing crash) i have to restart TX too. 

But absolutley! Center apps would be awesome for TB.

**Comment by ghost** [comment]
@junesties It's taskbarX

**Comment by TechyAditya** [comment]
Well, first of all, you don't need an app for this in windows 10. Follow this in win 10:
1.  Remove taskbar lock
2.  Add links toolbar
3. Drag links way too right till it reaches the left side
4. Adjust icons by dragging and centring
5. Hide links toolbar text or labels
Free hacks

Another way: update to windows 11.

**Comment by sylveon** [comment]
Yeah, closing because Windows 11 supports this natively.
