### ISSUE TITLE
Taskbar Glitching

### ISSUE THREAD

**Issue by Hudinec** [TranslucentTB/TranslucentTB#353]
https://user-images.githubusercontent.com/64325662/103779672-60f32100-5034-11eb-8131-c6f064779fbb.mp4

I really don't know why this is happening, any suggestions?

**Comment by sylveon** [comment]
TranslucentTB is most likely conflicting with TaskbarX. You'll have to disable the options to change the taskbar appearance/effect within TaskbarX's settings.

**Comment by Hudinec** [comment]
Fixed it! Yep, That was the problem. Thank you so much! :D
