### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by harribo2712** [TranslucentTB/TranslucentTB#355]
To whom this may concern, 

This is a formal request to delete all information you have relevant to my account. I have deleted your programme from your computer and expect you to delete all information which you may hold from me - considering you had access to all files on my computer - and all files. 

Kind regards, 
Harrison,

**Comment by sylveon** [comment]
We don't have an account system and don't upload any information to any server according to our [privacy policy](https://translucenttb.github.io/privacy-policy).
