### ISSUE TITLE
[Development] Can't seem to build develop branch

### ISSUE THREAD

**Issue by amrbashir** [TranslucentTB/TranslucentTB#359]
A while back I proposed [this](https://github.com/TranslucentTB/TranslucentTB/issues/242#issuecomment-574756953) feature and I've got some time now soI might be able to contribute (my c++ skills is so shit) but I think I might be able to do it.

Anyhow, I am able to build the app on `release` branch but can't on 'develop', So I thought you could maybe give me some guidance.

At first it didn't wan to build because I didn't have Windows 10 SDK (10.0.19041.0)
Then it needed MSVC v141 - VS2017 C++ x64/x86 spectre-mitigated libs (v14.16)
and now I can't seem to know what is the problem

![image](https://user-images.githubusercontent.com/48618675/105908675-2f67e700-602f-11eb-81b9-6fb2fa763d5d.png)

I rarely use visual studio and .net in general, so I am kinda clueless here

## Clang
```
Clang version 11.0.1
Target: x86_64-pc-windows-msvc
Thread model: posix
```

## Inno setup
```
version 6.1.2
```

## Visual studio 2019 with the following installed:
```
Desktop development with C++ workload
Universal Windows Platfrom development workload
.NET desktop development workload
.NET Framework 4.6.2 SDK
.NET Framework 4.6.2 targeting pack
Windows 10 SDK (10.0.19041.0)
Windows 10 SDK (10.0.18362.0)
MSVC v141 - VS2017 C++ x64/x86 build tools (v14.16)
MSVC v141 - VS2017 C++ x64/x86 spectre-mitigated libs (v14.16)
```

**Comment by sylveon** [comment]
You need to install [vcpkg](https://github.com/microsoft/vcpkg) and then run the following commands:
```
vcpkg install --triplet x64-windows fmt spdlog discord-game-sdk
vcpkg install --triplet x64-windows --overlay-ports=D:\Development\Projects\TranslucentTB\ports --head detours gtest member-thunk rapidjson wil
```

**Comment by amrbashir** [comment]
Unfortunately, gtest fails to install 

```
CMake Error at ports/gtest/portfile.cmake:79 (file):
  file INSTALL cannot find
  "D:/Development/Projects/vcpkg/buildtrees/gtest/src/head/master-12015919a3.clean/googletest/LICENSE":
  No such file or directory.
Call Stack (most recent call first):
  scripts/ports.cmake:128 (include)


Error: Building package gtest:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gtest:x64-windows
  Vcpkg version: 2021-01-13-unknownhash

Additionally, attach any relevant sections from the log files above.
```
and even though other packages installed correctly, I still see their errors

**Comment by sylveon** [comment]
You can skip installing gtest if you don't intend to run the unit tests

**Comment by amrbashir** [comment]
The build still fails 
![image](https://user-images.githubusercontent.com/48618675/105916427-8ecaf480-6039-11eb-8293-0afd40ce87d6.png)

**Comment by sylveon** [comment]
Did you integrate vcpkg with VS using `vcpkg integrate install`?

Sorry if the docs are out of date, I wanted to get them up to date before release.

**Comment by amrbashir** [comment]
> Did you integrate vcpkg with VS using `vcpkg integrate install`?

Thanks, it is working now, sorry for the hassle.

> Sorry if the docs are out of date, I wanted to get them up to date before release.

It is fine, I know you have a lot to worry about. I can submit a PR to update the contribution guide with these instructions .

**Comment by sylveon** [comment]
That would be appreciated! Please target the develop branch if you do :)

**Comment by sylveon** [comment]
I fixed the issue with google test since it started affecting azure pipelines as well: https://github.com/microsoft/vcpkg/pull/16071

**Comment by amrbashir** [comment]
yeah it can be installed now, it builds fine but the app won't run
```
Unhandled exception at 0x00007FFA9AB3224F (ProgramLog.dll) in TranslucentTB.exe: Fatal program exit requested.
```
this error existed a weak ago but I go busy and forgot about it. 
it has something to do with this

```cpp
if (errInfo)
	{
		  if (const HRESULT hr = SetRestrictedErrorInfo(errInfo); SUCCEEDED(hr))
		{
			// This gives much better error reporting if the error came from a WinRT module:
			// the stack trace in the dump, debugger and telemetry is unaffected by our error handling,
			// giving us better insight into what went wrong.
			RoFailFastWithErrorContext(err);
		}
		else if (initialized)
		{
			HresultHandle(hr, spdlog::level::warn, L"Failed to set restricted error info");
		}
	}
```

**Comment by sylveon** [comment]
You need to go check up the stack trace, the frame right before `Error::Handle`, to find the real culprit. The code you're seeing is error reporting code

**Comment by amrbashir** [comment]
It had something to do with kernel.dll but I got kinda busy, I will try to look more into it.

**Comment by amrbashir** [comment]
These are the exceptions ordered as they appear after starting the debugger

![image](https://user-images.githubusercontent.com/48618675/107404657-2c7cf400-6b0f-11eb-950a-8749c31cd1e2.png)

![image](https://user-images.githubusercontent.com/48618675/107404683-330b6b80-6b0f-11eb-9399-e37112337610.png)

![image](https://user-images.githubusercontent.com/48618675/107404709-3999e300-6b0f-11eb-92fe-cb0907da81f2.png)

![image](https://user-images.githubusercontent.com/48618675/107404921-69e18180-6b0f-11eb-9e56-cdcd7c2e2f7b.png)

**Comment by sylveon** [comment]
When the first exception happens, go check the call stack:
![image](https://user-images.githubusercontent.com/6440374/107407328-8792f480-6ad7-11eb-84d8-eeb36d4c98f2.png)

What I'm suspecting is happening is that you're launching the `TranslucentTB` project when `AppPackage` should be used as launch target (otherwise XAML resources aren't properly built)

**Comment by amrbashir** [comment]
Indeed, I had TranslucentTB as the startup project. Now it builds fine I guess but after the app is launched I get fmtd.dll is missing. So I cleaned the solution, removed `vcpkg` reinstalled all the deps and integrated it into vs but still can't find `fmtd.dll`. 

At this point, I kinda give up on trying to build the project. My windows and Visual Studio installation is heavily tempered and plan to reinstall windows soon, maybe I will try again then

**Comment by sylveon** [comment]
This is an issue introduced by https://github.com/microsoft/vcpkg/commit/401b26c9866a071f645ae57831caa419b2c48be1, I've yet to fully diagnose and report it. As a temporary workaround, you can copy discord_game_sdk.dll and fmtd.dll from `<vcpkg>\installed\x64-windows\debug\bin` to `<ttb>\AppPackage\bin\x64\Debug\AppX`

**Comment by amrbashir** [comment]
It worked at last. I Love the new On Boarding screen and the color picker.

**Comment by sylveon** [comment]
Thanks ^_^
Filled a bug for the DLL issue: https://github.com/microsoft/vcpkg/issues/16184
