### ISSUE TITLE
Virtual-desktop support for Dynamic Windows

### ISSUE THREAD

**Issue by denosawr** [TranslucentTB/TranslucentTB#36]
[This](https://msdn.microsoft.com/en-us/library/windows/desktop/mt186440%28v=vs.85%29.aspx) is the COM interface which interacts with virtual desktops.

**Comment by ethanhs** [comment]
I'm putting this and #37 on V4 because V3 is already taking longer than I'd want, and I think it'd be good to ship a new version with the new fixes.

**Comment by denosawr** [comment]
Modified to V3. I hope it can be completed bythen, as this is pretty important.

**Comment by denosawr** [comment]
Commit https://github.com/TranslucentTB/TranslucentTB/commit/e10a2403afc3e027ccfcc631ae3cfc6fde34e948 should fix this. It is yet to be properly tested and merged into `develop` though.

**Comment by charlesmilette** [comment]
I have a IVirtualDesktopManager implementation working. However it's taking
huge amounts of processing power. (Maybe because I'm opening and closing
two interfaces each 5ms lol)

**Comment by denosawr** [comment]
Hmm... Does that implementation have any benefits over the current one?

**Comment by charlesmilette** [comment]
Except using the regular API and not an outdated one, I don't think so...

Do you see a significant increase in CPU usage on your machine? Might just be me.
