### ISSUE TITLE
Taskbar windows is in alt tab

### ISSUE THREAD

**Issue by m1hne4** [TranslucentTB/TranslucentTB#361]
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: <9.0.0.0>
 - Windows build number: <18363.1198>
 - Steps to reproduce: <!press alt + tab and you'll see a taskbar window>
 - Expected results: <no expected results>
 - Actual results: 
 - Other: <This kinda bugs me. It would be nice if you could make it stop appearing in alt tab>

**Comment by sylveon** [comment]
I can't reproduce this with 9.0.0.0 and 19042. Do you have any other system modification tool installed?

**Comment by m1hne4** [comment]
Yes I fo have taskbarX for centering the taskbar. I'll try and close it to
see if that is causing the issue and email you back.

**Comment by m1hne4** [comment]
I have found out that the problem was indeed from taskbarX. Even if it is
stopped.I saw the issue already on the developers page and see if there
will be an update. Love your work xoxo.
Also as a new future would be centering the taskbar if possible:)

În dum., 31 ian. 2021 la 22:03, Mihnea <mihnearazvanghe@gmail.com> a scris:

**Comment by sylveon** [comment]
There's an issue opened in #352 for that, it's under consideration.
