### ISSUE TITLE
Taskbar blinking

### ISSUE THREAD

**Issue by FluffyDiscord** [TranslucentTB/TranslucentTB#362]
#303 

 - TranslucentTB version: 9.0.0.0
 - Windows build number: 20H2 19042.746
 - Steps to reproduce: nothing special, happens anytime everytime
 - Expected results: won't flicker
 - Actual results: flickers
 - Other: example https://www.youtube.com/watch?v=YVC7GrMH6kU

**Comment by sylveon** [comment]
The flickering you're seeing when closing/opening start is fixed in development builds already ;)

**Comment by FluffyDiscord** [comment]
Where would I get these builds, please ? Github release or do I need to compile master branch myself

**Comment by sylveon** [comment]
The latest dev build, as of today, is available here: https://dev.azure.com/sylve0n/TranslucentTB/_build/results?buildId=86&view=artifacts&pathAsName=false&type=publishedArtifacts

You want the `Portable x64 Release` download. Note that these builds have some partly implemented features, and may crash.

**Comment by FluffyDiscord** [comment]
Ooooh, I didn't notice the small "published" button. Thank you, will try them out.
