### ISSUE TITLE
Only works on extra monitor, not on main screen

### ISSUE THREAD

**Issue by eatprawns77** [TranslucentTB/TranslucentTB#365]
- TranslucentTB version: Version 4 hotfix 5
 - Windows build number: Build 19042.844
 - Steps to reproduce: Set all five options to "clear"
 - Expected results: Taskbar should become clear 
 - Actual results: Taskbar area on spare monitor becomes clear, but main one does not. Main one also does not become clear even without monitor. 
 - Other: Tried saving settings and restarting computer. Tried downloading both from MS store and from Github (neither work)

**Comment by sylveon** [comment]
This should be fixed in the latest update, available in the Store.
