### ISSUE TITLE
Translucent causing memory leakage in latest dev Windows 10 version

### ISSUE THREAD

**Issue by 7HE-W0R1D** [TranslucentTB/TranslucentTB#366]
[ yes ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: Latest UWP
 - Windows build number: Build 21327
 - Steps to reproduce: Nothing, it just appear automatically
 - Expected results: No excessive memory usage of the dwm
 - Actual results: DWM is gradually gaining memory until manually restart
 - Other: I've updated to the latest windows build 21327 few days ago, now if I start translucentTB, it will cause the "desktop window manager" to gradually eat up all memory in my PC, it will also cause significant lagging when dragging a window with another window behind in fullscreen mode. If you keeps on dragging the window the ram usage of dwm will quickly exceed 1000MB, even if you don't drag or do anything, the dwm would still gradually gaining its ram usage. The only way to temporarily relieve is to restart dwm from task manager, but it will start to grow right away. Already checked that it appears on intel graphics driver 7985 9316 9168 & 6577, so probably not a driver led leakage (though the symptoms is really identical)

**Comment by sylveon** [comment]
This isn't really something we can resolve on our side - it affects all apps using SetWindowCompositionAttribute as well (for example the AMD driver control panel reproduces the issue). Better chances to report it DWM leaking in the Feedback Hub and wait for Microsoft to fix it.

**Comment by 7HE-W0R1D** [comment]
oh then I see why there are so many people complain about that, I'd better wait for MS to fix that.

**Comment by hello-smile6** [comment]
Could TranslucentTB optionally restart DWM to fix that?

**Comment by sylveon** [comment]
No, user-mode processes don't have the permissions required to do anything to the DWM process.

**Comment by hello-smile6** [comment]
Huh. Could TranslucentTB inject code into DWM to fix it using Win32 APIs, as a temporary solution?

**Comment by sylveon** [comment]
Not having the permissions to do anything includes not being able to inject code. It's an Insider bug so I don't see the benefit in spending much time trying to fix this when it'll be (hopefully) fixed before the stable release.

**Comment by sylveon** [comment]
Seems fixed in Windows 11
