### ISSUE TITLE
Taskbar bleeds onto bottom screen with auto hide taskbar option in windows

### ISSUE THREAD

**Issue by Nerxxy** [TranslucentTB/TranslucentTB#367]
[ ✔️ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: Latest Windows Store Version 9.0.0.0.
 - Windows build number: 19042 
 - Steps to reproduce: have 2 screens, one above the other, then Task bar settings -> Automatically Hide in desktop mode
 and now have blur on any of the options in TranslucentTB 
 - Expected results: no task bar bleed onto the bottom screen
 - Actual results: taskbar that should be "hidden" bleeds to second screen 
 - Other: 
![image](https://user-images.githubusercontent.com/37718547/111093127-0db7b600-8530-11eb-9df9-b29ba4aad5ff.png)

**Comment by Nerxxy** [comment]
@sylveon i hate to beg or ping, but this issue and many others are very annoying, would be nice to have some closure if its fixable or if its just a windows problem, since atm im having to use the "clear" option and sometimes it makes it hard to see the time/date etc if the thing that im looking at is bright, or if there is a lot a text underneath it makes it difficult to see

**Comment by sylveon** [comment]
This is something I might be looking at fixing in the future. I should have dropped a comment about it however, my bad.

**Comment by Nerxxy** [comment]
thank you for letting me know :)
