### ISSUE TITLE
"show desktop" button disappearing

### ISSUE THREAD

**Issue by danielecll** [TranslucentTB/TranslucentTB#368]
- TranslucentTB version: 9.0.0
 - Windows build number: 19041.867
 - Steps to reproduce: activate "clear" in normal mode
 - Expected results: the button show desktop remains on-screen
 - Actual results: it disappears and isn't clickable anymore
 - Other: if i have multiple windows not maximized and i want to press "show desktop" to return to it the if translucentTB's clear mode is enabled the button doesn't show up and isn't clickable

**Comment by sylveon** [comment]
Right-click the tray icon, and under Show Aero Peek enable "Always"
