### ISSUE TITLE
Blur start menu, notification center and hidden icon menu

### ISSUE THREAD

**Issue by Fefedu973** [TranslucentTB/TranslucentTB#369]
Hello, (sorry if m'y english os Bad i am french)
Is it possible to add the fonctionnality to be able to apply taskbar changes to start menu, notification center and hidden icon menu
Tanks :)

**Comment by Fefedu973** [comment]
make the start menu blur for example

**Comment by sylveon** [comment]
Unfortunately no. These work completely differently from the taskbar, so the technique we use for the taskbar doesn't work on them.
