### ISSUE TITLE
Standardise behavior in task view

### ISSUE THREAD

**Issue by KyleDavidE** [TranslucentTB/TranslucentTB#37]
As of now with dynamic mode on, in task view it just uses the last style. It would be neat if it was standardized, always clear or always blurred.

**Comment by charlesmilette** [comment]
I would like it to return to default apparence personally, because it has the exact same tint than the task view background, making it blend with the Task View.

**Comment by olliethepikachu** [comment]
I personally would like that to be implemented with Dynamic Start Menu, which @ethanhs is working on I believe. Pretty much that means that when the Start Menu is open (and maybe Task View) the task bar will return to default.

**Comment by olliethepikachu** [comment]
https://github.com/TranslucentTB/TranslucentTB/commit/b6479fd6e60ca24e1a4a08a81490cb14b45e4c57 is the commit for the Start Menu, I will look into implementing it for Task View.

**Comment by olliethepikachu** [comment]
Observing extremely weird behaviour; it seems that
```InvalidateRect(hWnd, NULL, TRUE);
UpdateWindow(hWnd);```

doesn't work when Task View is open.

**Comment by olliethepikachu** [comment]
Interestingly, the taskbar *can* be repainted with SetWindowCompositionAttribute while Task View is open.

Also, `RedrawWindow(hWnd, NULL, NULL, (RDW_INTERNALPAINT, RDW_ERASENOW))` doesn't work either. We might have to experiment with sending a `WM_PAINT` message.

**Comment by ethanhs** [comment]
I dont see an issue with an internal WM_PAINT call as long as it is internal, and thus handled by the OS. Could you explain your concerns about this?

**Comment by olliethepikachu** [comment]
The problem is that you *can't* call an internal WM_PAINT from what I know.

Get Outlook for iOS




On Sat, Mar 25, 2017 at 9:52 PM +0800, "Ethan" <notifications@github.com> wrote:












I dont see an issue with an internal WM_PAINT call as long as it is internal, and thus handled by the OS. Could you explain your concerns about this?

**Comment by ethanhs** [comment]
You can via sendmessage to the window, but it isnt advised.

**Comment by olliethepikachu** [comment]
Ah never mind, I read up about it, it should be fine. I'll take a look into it later today.

Get Outlook for iOS




On Sat, Mar 25, 2017 at 10:52 PM +0800, "Ethan" <notifications@github.com> wrote:












You can via sendmessage to the window, but it isnt advised.

**Comment by olliethepikachu** [comment]
Using SetWindowCompositionAttribute to restore to normal doesn't work while TV is open... This is weird behaviour, as you can set the taskbar to opaque.

**Comment by sylveon** [comment]
Implemented in V4
