### ISSUE TITLE
[Bug] Color the taskbar text based on the wallpaper

### ISSUE THREAD

**Issue by avi12** [TranslucentTB/TranslucentTB#372]
- [x] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 9.0.0.0
 - Windows build number: 19042.867
 - Steps to reproduce: Have a dark wallpaper
 - Expected results: The text should be white if the wallpaper is dark, and vice versa
 - Actual results: The text stays black
 - Other:
The background: 
![2021-01-25_20-44-01_937_3840x2160](https://user-images.githubusercontent.com/6422804/111739646-0ffd7580-888c-11eb-933b-bbbd235a6a88.png)
The bottom-right corner:
![2021-03-19_08-20-32](https://user-images.githubusercontent.com/6422804/111739679-1f7cbe80-888c-11eb-90a2-e708e737a73f.png)

**Comment by sylveon** [comment]
Duplicate of #41
