### ISSUE TITLE
How do you install TranslucentTB as an .exe?

### ISSUE THREAD

**Issue by hello-smile6** [TranslucentTB/TranslucentTB#373]
I can't get Windows Store to work.

**Comment by sylveon** [comment]
Download TranslucentTB-setup.exe from here: https://github.com/TranslucentTB/TranslucentTB/releases/tag/2020.2

**Comment by 03302024** [comment]
Please provide setup exe files for the new releases, as well.

**Comment by 03302024** [comment]
Please provide setup exe files for the new releases, as well.
