### ISSUE TITLE
Chrome is under the taskbar when maximised

### ISSUE THREAD

**Issue by nmcc1212** [TranslucentTB/TranslucentTB#374]
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

![image](https://user-images.githubusercontent.com/48334675/112502966-70a41b00-8d82-11eb-88cd-3e8fb4963a1a.png)

 - TranslucentTB version: Latest Windows Store build
 - Windows build number: 20H2
 - Steps to reproduce: Maximising chrome 
 - Expected results: Chrome meets the taskbar boundary like all other apps
 - Actual results: Chrome overhangs as seen in image above
 - Other: As far as i can see this only happens with chrome, i have restarted chrome, TranslucentTB and my pc

**Comment by sylveon** [comment]
This is a bug in Chrome.

**Comment by nmcc1212** [comment]
ok, thanks
