### ISSUE TITLE
You don't need to ask whether the user agrees to the GPLv3 license or not

### ISSUE THREAD

**Issue by SamusAranX** [TranslucentTB/TranslucentTB#375]
[x] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 9.0.0.0

First off, thanks for this tool, it's incredibly useful.

Now, this is an incredibly minor thing (and the issue's title says it all), but:
https://twitter.com/Foone/status/1027009618294104064 (ignore the strong language please)

Basically the license doesn't apply if you just want to *use* the app. You can safely remove the message box entirely.

**Comment by sylveon** [comment]
The next major version gets rid of Inno Setup entirely so it won't be an issue anymore ;)

**Comment by SamusAranX** [comment]
I installed the app from the Windows Store, is Inno Setup part of that package?

I'm talking about this bit: https://github.com/TranslucentTB/TranslucentTB/blob/master/TranslucentTB/main.cpp#L230

**Comment by sylveon** [comment]
Oh no, it's not part of what you get on the Windows Store, but this bit is going away too for a better welcome screen.
