### ISSUE TITLE
hide TrayIcon 

### ISSUE THREAD

**Issue by dian-yu-luo** [TranslucentTB/TranslucentTB#377]
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 
 - Windows build number: 
 - Steps to reproduce: 
 - Expected results: 
 - Actual results: 
 - Other:

**Comment by dian-yu-luo** [comment]
I want hide the icon around the conner,

**Comment by sylveon** [comment]
What

**Comment by dian-yu-luo** [comment]
------------------ 原始邮件 ------------------
发件人:                                                                                                                        "TranslucentTB/TranslucentTB"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月31日(星期三) 中午12:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TranslucentTB/TranslucentTB] hide TrayIcon  (#377)





 
What

**Comment by dian-yu-luo** [comment]
thanks&nbsp; for you reply,I use this software for mouths.it is really a beautiful achievement,but I am OCD a little.I want clean it .make is neatness.thanks

**Comment by sylveon** [comment]
You can hide the tray icon in the configuration file by setting `no-tray` to `enable`

**Comment by dian-yu-luo** [comment]
where is its path(about eh config file)








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Charles ***@***.***&gt;; 
发送时间: 2021年3月31日(星期三) 中午12:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TranslucentTB/TranslucentTB] hide TrayIcon  (#377)





 
You can hide the tray icon in the configuration file by setting no-tray to enable

**Comment by sylveon** [comment]
If you got it from the Microsoft Store, it's in `%localappdata%\Packages\28017CharlesMilette.TranslucentTB_v826wp6bftszj\RoamingState`, otherwise it's in `%appdata%\TranslucentTB`

**Comment by tute123456** [comment]
Hello, I have Windows 10 22h2 19045.5487, and in the .JSON file I do not have the option to hide icon (before I was, and it was as simple as going from false to True). I leave my current configuration, to see if someone tells me where to place the code to hide the icon. Thank you
`// See https://TranslucentTB.github.io/config for more information
{
  "$schema": "https://TranslucentTB.github.io/settings.schema.json",
  "desktop_appearance": {
    "accent": "clear",
    "color": "#00000000",
    "show_peek": false,
    "show_line": false,
    "blur_radius": 9.0
  },
  "visible_window_appearance": {
    "enabled": false,
    "accent": "clear",
    "color": "#00000000",
    "show_peek": true,
    "show_line": false,
    "blur_radius": 9.0,
    "rules": {
      "window_class": {},
      "window_title": {},
      "process_name": {}
    }
  },
  "maximized_window_appearance": {
    "enabled": false,
    "accent": "acrylic",
    "color": "#00000000",
    "show_peek": true,
    "show_line": true,
    "blur_radius": 9.0,
    "rules": {
      "window_class": {},
      "window_title": {},
      "process_name": {}
    }
  },
  "start_opened_appearance": {
    "enabled": true,
    "accent": "normal",
    "color": "#00000000",
    "show_peek": true,
    "show_line": true,
    "blur_radius": 9.0
  },
  "search_opened_appearance": {
    "enabled": true,
    "accent": "normal",
    "color": "#00000000",
    "show_peek": true,
    "show_line": true,
    "blur_radius": 9.0
  },
  "task_view_opened_appearance": {
    "enabled": true,
    "accent": "normal",
    "color": "#00000000",
    "show_peek": false,
    "show_line": true,
    "blur_radius": 9.0
  },
  "battery_saver_appearance": {
    "enabled": false,
    "accent": "opaque",
    "color": "#00000000",
    "show_peek": true,
    "show_line": false,
    "blur_radius": 9.0
  },
  "ignored_windows": {
    "window_class": [],
    "window_title": [],
    "process_name": []
  },
  "disable_saving": false,
  "verbosity": "warn"
}`

**Comment by hi-bernardo** [comment]
What worked for me was: `"hide_tray": true`

> When changing _settings.json_ my configs came out, you can change in your _settings.json_ or set to `false` the option to hide the tray icon and change them to the TranslucentTB default. 

Example:. 
```
} 
// the rest of your code is above this... 
  "disable_saving": false, 
  "verbosity": "warn", 
  "hide_tray": true
}
```

**Comment by hi-bernardo** [comment]
> Hello, I have Windows 10 22h2 19045.5487, and in the .JSON file I do not have the option to hide icon (before I was, and it was as simple as going from false to True). I leave my current configuration, to see if someone tells me where to place the code to hide the icon. Thank you `// See https://TranslucentTB.github.io/config for more information { "$schema": "https://TranslucentTB.github.io/settings.schema.json", "desktop_appearance": { "accent": "clear", "color": "#00000000", "show_peek": false, "show_line": false, "blur_radius": 9.0 }, "visible_window_appearance": { "enabled": false, "accent": "clear", "color": "#00000000", "show_peek": true, "show_line": false, "blur_radius": 9.0, "rules": { "window_class": {}, "window_title": {}, "process_name": {} } }, "maximized_window_appearance": { "enabled": false, "accent": "acrylic", "color": "#00000000", "show_peek": true, "show_line": true, "blur_radius": 9.0, "rules": { "window_class": {}, "window_title": {}, "process_name": {} } }, "start_opened_appearance": { "enabled": true, "accent": "normal", "color": "#00000000", "show_peek": true, "show_line": true, "blur_radius": 9.0 }, "search_opened_appearance": { "enabled": true, "accent": "normal", "color": "#00000000", "show_peek": true, "show_line": true, "blur_radius": 9.0 }, "task_view_opened_appearance": { "enabled": true, "accent": "normal", "color": "#00000000", "show_peek": false, "show_line": true, "blur_radius": 9.0 }, "battery_saver_appearance": { "enabled": false, "accent": "opaque", "color": "#00000000", "show_peek": true, "show_line": false, "blur_radius": 9.0 }, "ignored_windows": { "window_class": [], "window_title": [], "process_name": [] }, "disable_saving": false, "verbosity": "warn" }`

What worked for me was: `"hide_tray": true`

> When changing _settings.json_ my configs came out, you can change in your _settings.json_ or set to `false` the option to hide the tray icon and change them to the TranslucentTB default. 

Example:. 
```
} 
// the rest of your code is above this... 
  "disable_saving": false, 
  "verbosity": "warn", 
  "hide_tray": true
}
```

**Comment by tute123456** [comment]
> > Hello, I have Windows 10 22h2 19045.5487, and in the .JSON file I do not have the option to hide icon (before I was, and it was as simple as going from false to True). I leave my current configuration, to see if someone tells me where to place the code to hide the icon. Thank you `// See https://TranslucentTB.github.io/config for more information { "$schema": "https://TranslucentTB.github.io/settings.schema.json", "desktop_appearance": { "accent": "clear", "color": "#00000000", "show_peek": false, "show_line": false, "blur_radius": 9.0 }, "visible_window_appearance": { "enabled": false, "accent": "clear", "color": "#00000000", "show_peek": true, "show_line": false, "blur_radius": 9.0, "rules": { "window_class": {}, "window_title": {}, "process_name": {} } }, "maximized_window_appearance": { "enabled": false, "accent": "acrylic", "color": "#00000000", "show_peek": true, "show_line": true, "blur_radius": 9.0, "rules": { "window_class": {}, "window_title": {}, "process_name": {} } }, "start_opened_appearance": { "enabled": true, "accent": "normal", "color": "#00000000", "show_peek": true, "show_line": true, "blur_radius": 9.0 }, "search_opened_appearance": { "enabled": true, "accent": "normal", "color": "#00000000", "show_peek": true, "show_line": true, "blur_radius": 9.0 }, "task_view_opened_appearance": { "enabled": true, "accent": "normal", "color": "#00000000", "show_peek": false, "show_line": true, "blur_radius": 9.0 }, "battery_saver_appearance": { "enabled": false, "accent": "opaque", "color": "#00000000", "show_peek": true, "show_line": false, "blur_radius": 9.0 }, "ignored_windows": { "window_class": [], "window_title": [], "process_name": [] }, "disable_saving": false, "verbosity": "warn" }`
> 
> What worked for me was: `"hide_tray": true`
> 
> > When changing _settings.json_ my configs came out, you can change in your _settings.json_ or set to `false` the option to hide the tray icon and change them to the TranslucentTB default.
> 
> Example:.
> 
> ```
> } 
> // the rest of your code is above this... 
>   "disable_saving": false, 
>   "verbosity": "warn", 
>   "hide_tray": true
> }
> ```

thx! works fine
