### ISSUE TITLE
pop "Error while setting startup registry value!" when try at [Open at oot]

### ISSUE THREAD

**Issue by vendettar** [TranslucentTB/TranslucentTB#382]
![图片](https://user-images.githubusercontent.com/22285482/114568540-c9dadc80-9ca6-11eb-8dcd-e58f3a4e34cf.png)

**Comment by sylveon** [comment]
Do you have any anti virus with some kind of ransomware protection enabled? They tend to be a bit overreaching in their "protection" and prevent normal programs from working.

As a workaround, you can go in `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run` and add a new string value named `TranslucentTB` with the path to the exe file as value

**Comment by vendettar** [comment]
> 
> 
> Do you have any anti virus with some kind of ransomware protection enabled? They tend to be a bit overreaching in their "protection" and prevent normal programs from working.
> 
> As a workaround, you can go in `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run` and add a new string value named `TranslucentTB` with the path to the exe file as value

Thanks!
