### ISSUE TITLE
I can't get the Start Menu to become clear (or any other effect)

### ISSUE THREAD

**Issue by Mackeriah** [TranslucentTB/TranslucentTB#383]
[X] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB file version 9.0.0.0, product version: 2020 2.0.5a...etc
 - Windows build number: 20H2 OS Build 19042.928
 - Steps to reproduce: TranslucentTB taskbar icon - Start Menu opened - (enabled) - clear (or other effects)
 - Expected results: Perhaps I'm misunderstanding, but I'm expecting the Start Menu to become transparent
 - Actual results: No matter what option I choose, the Start Menu is unaffected.  (clear, opaque, blur, fluent)
 - Other: The taskbar itself IS translucent and looks great!  :)

This is by no means an urgent issue!

**Comment by sylveon** [comment]
This is expected, the "start menu opened" state changes the appearance of the taskbar when start is opened. We can't easily change how the start menu looks, as it is implemented in a completely different manner than the taskbar.

**Comment by Mackeriah** [comment]
Oh I see, well fair enough then!  In which case that function is actually working perfectly!  :)

Thanks for making a great and free app.
Owen
