### ISSUE TITLE
For TranslucentTB developers

### ISSUE THREAD

**Issue by YyangHuiL** [TranslucentTB/TranslucentTB#384]
Hello, TranslucentTB developer. I'm yysoft from China. TranslucentTB is an excellent software. I want to translate its options into Chinese and publish them in the Chinese market. Chinese people like to try new things. TranslucentTB will be very popular in the Chinese market.

**Comment by sylveon** [comment]
There is already a Chinese-translated fork here: https://github.com/tpxxn/TranslucentTB, with a version on the Windows Store too.

But I won't stop you from making your own, after all the GPLv3 allows you to!
