### ISSUE TITLE
Remove unpackaged build and use MSIX instead

### ISSUE THREAD

**Issue by jaigak** [TranslucentTB/TranslucentTB#385]
Today TranslucentTB provides an unpackaged version in the releases tab. However unpackaged apps that are installed causes long-term damage to user's devices including the risk of causing machine rot. Since some users don't want to use the Store, you can provide an MSIX package instead on the release tab. Unpackaged builds should be used only if the app is portable and doesn't need to be installed on the target machine.

**Comment by sylveon** [comment]
This is already the plan
