### ISSUE TITLE
Right side (tray icons, time, date and quick settings) missing

### ISSUE THREAD

**Issue by jimmyedagawa78** [TranslucentTB/TranslucentTB#389]
- TranslucentTB version: 9.0.0.0
 - Windows build number: 19043.1023
 - Screenshot: [Link](https://imgur.com/aOLlno8)
 - Problem faced: Right side of the taskbar is missing. I'm not sure how, but I'm unable to see the time or access the entire right side of the taskbar entirely.

**Comment by sylveon** [comment]
I think that's a bug unrelated to TranslucentTB on the 21h1 update that occurs if you disable the news and weather widget. Try enabling it?

**Comment by jimmyedagawa78** [comment]
> I think that's a bug unrelated to TranslucentTB on the 21h1 update that occurs if you disable the news and widget icon. Try enabling it?

Thanks! That worked👍
