### ISSUE TITLE
Doesnot work on Windows 11

### ISSUE THREAD

**Issue by abusayed0206** [TranslucentTB/TranslucentTB#390]
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: Latest 
 - Windows build number: 21996.1 ( Win11)

It doesnot work on windows 11!

**Comment by sylveon** [comment]
I tried it and it mostly works for me. How does it not work for you? Any errors?

**Comment by abusayed0206** [comment]
Now it works fine! but sometimes conflicts with windows native transparent feature!~
