### ISSUE TITLE
Labeled as bad reputation by Virus Total

### ISSUE THREAD

**Issue by ghost** [TranslucentTB/TranslucentTB#394]
Upon checking the TranslucentTB-setup.exe file on Virus Total
Detection Results: https://www.virustotal.com/gui/file/b8a4f90865d681a31efa44f8b5098703b743a5050274503ca95d0e80e26c46fa/detection

**Comment by sylveon** [comment]
?
![image](https://user-images.githubusercontent.com/6440374/123380188-26872d00-d55d-11eb-94b0-a01006f0ee27.png)

**Comment by sylveon** [comment]
I see in the related executables page of VirusTotal, there seems to be an installer masquerading itself as TTB's installer, then installing a crypto miner alongside TTB. Did you accidentally download/run this and try to report it?
