### ISSUE TITLE
Access denied to source module referencing non-existing volume

### ISSUE THREAD

**Issue by rgutter** [TranslucentTB/TranslucentTB#395]
Likely benign, but as the title suggests my log contains multiple copies of:
Getting process handle of a window failed. Exception from HRESULT: Access is denied. (0x80070005) (**T:**\Projects\build\TranslucentTB\TranslucentTB\\**window.cpp:94** at function class std::shared_ptr<class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const > __thiscall Window::filename(void) const)

**Comment by sylveon** [comment]
Yeah, this error is benign and occurs when trying to match a window against the blacklist. If the error occurs, TTB assumes that the window doesn't matches any blacklisted process name, so it can safely be ignored.

The `T:\Projects\build\TranslucentTB\TranslucentTB\window.cpp` path is the source code file that contains the line failing, at the time the executable was built (so in this case, I built the last release version of TTB from `T:\Projects\build\TranslucentTB`), not something on your system.

The next major version does quite a few things to resolve this confusion:
- Benign errors like this one aren't logged by default.
- Specifically for this error, TranslucentTB tries to call `NtQuerySystemInformation` instead to avoid the error even happening.
- The full path to source code files is stripped from the output binary.
- The log output format is changed, to avoid any kind of implication between the error message and the source code line. For example:
  ```
  [2021-06-26 21:51:13.276] [debug] [taskbarattributeworker.cpp:878] Resetting worker state
  ```

**Comment by rgutter** [comment]
Right, understood. Thanks for the note about future plans.
