### ISSUE TITLE
[Feature Request] Add customization of title bar and settings app in Windows 11

### ISSUE THREAD

**Issue by TechyAditya** [TranslucentTB/TranslucentTB#397]
[x] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

The title bar of file explorer and literally background of settings app uses fluent design in Windows 11 dark mode. Please add customizations for that too, similar to the taskbar.  It would be great if we find the same set of options like choosing ascent colour and blur effect to transparent-themed windows, start menu, search bar and widgets too. 

One more suggestion: Fix Cortana the timeline option for windows 11.  And, aero peek seemingly doesn't work in Windows 11. 

Thanks for making my PC beautiful.

**Comment by Yilmaz4** [comment]
It's not actually Fluent design. It's only a basic animation that takes colors from your wallpaper image. This cannot be overrided with a blur effect.

**Comment by sylveon** [comment]
Out of scope.

**Comment by LeeBinder** [comment]
https://github.com/TranslucentTB/TranslucentTB/issues/234#issuecomment-2059750788
