### ISSUE TITLE
There is a line on the taskbar

### ISSUE THREAD

**Issue by KingJulien-XI** [TranslucentTB/TranslucentTB#398]
![Inked2021-07-04 (2)_LI](https://user-images.githubusercontent.com/77908916/124384615-20d3d900-dd0d-11eb-95f0-22e5a729171c.jpg)

 - TranslucentTB version: 
 - Windows build number: 
 - Steps to reproduce: 
 - Expected results: 
 - Actual results: 
 - Other:

**Comment by KingJulien-XI** [comment]
window11 사용 중입니다

**Comment by sylveon** [comment]
This is a bug in Windows 11, it occurs even without TranslucentTB.

**Comment by KingJulien-XI** [comment]
> 이것은 Windows 11의 버그이며 TranslucentTB가 없어도 발생합니다.


Thanks for your comment :)
