### ISSUE TITLE
Clear option makes my taskbar black

### ISSUE THREAD

**Issue by tardic** [TranslucentTB/TranslucentTB#399]
Hello, every time I choose the "clear" option my taskbar turns black.

**Comment by sylveon** [comment]
By default, the color for the taskbar when maximized is a black tint, try going to maximized windows > accent color and setting the alpha to 0.

**Comment by tardic** [comment]
It's still black.

**Comment by CentralPier9** [comment]
Probably the battery saving feature?

**Comment by sylveon** [comment]
Fixed in 2021.5

**Comment by cyberbasty2** [comment]
nope

**Comment by cyberbasty2** [comment]
still here
