### ISSUE TITLE
feature request: "normal mode" systray menu item

### ISSUE THREAD

**Issue by mailinglists35** [TranslucentTB/TranslucentTB#40]
The systray icon provides three options:
clear
blur
exit

it would be useful to add a fourth item, "normal"/"no effect"/"regular" (choose the best naming), that clears the effect but keeps the program in memory (it's small anyway).
this way I wouldn't have to launch it again if I want to switch modes.
thank you!

**Comment by ethanhs** [comment]
Sure, I can add this in my refactor. Should be pretty easy.

**Comment by mailinglists35** [comment]
On a second thought, I believe the correct name and behaviour should be split into three menus:
- windows default (see below)
![image](https://cloud.githubusercontent.com/assets/2054302/22550122/9ff5cafa-e95f-11e6-85c2-543d43146252.png)
- windows native transparency (and toggle the windows native settings to transparent on)
- windows native solid color (and toggle the windows native settings to transparent off)

**Comment by mailinglists35** [comment]
ps: I'm too lazy to open a new issue: the app does not restore the transparency state active before the launching. so if I set to clear or blur, it remains clear or blur even if I exit the app.

**Comment by charlesmilette** [comment]
#12
