### ISSUE TITLE
Crash when I click Accent Color from context menu

### ISSUE THREAD

**Issue by Yilmaz4** [TranslucentTB/TranslucentTB#400]
[ Yes ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 9.0.0.0
 - Windows build number: 22000.51
 - Steps to reproduce: While TranslucentTB running, right click the tray icon > Regular > Accent Color (click).
 - Expected results: I don't know what does this do.
 - Actual results: Simply crash without errors.
 - Other: No other things

**Comment by sylveon** [comment]
Can you check in the reliability history to see crash details?

**Comment by Yilmaz4** [comment]
> Can you check in the reliability history to see crash details?

Where can I check the reliability history?

**Comment by sylveon** [comment]
In control panel (System and Security > Security and Maintenance > Maintenance > View reliability history), but it's easier to just search for it:
![image](https://user-images.githubusercontent.com/6440374/124658813-3c0c2900-de72-11eb-8731-65a6af0e7e36.png)

**Comment by Yilmaz4** [comment]
```
Description
Faulting application name: TranslucentTB.exe, version: 9.0.0.0, time stamp: 0x5fea5c7d
Faulting module name: nvdxgiwrap.dll, version: 21.21.13.7654, time stamp: 0x586500e7
Exception code: 0xc0000005
Fault offset: 0x000025c9
Faulting process id: 0x2958
Faulting application start time: 0x01d772b5c2f16f0b
Faulting application path: C:\Program Files (x86)\Other Programs\TranslucentTB\TranslucentTB.exe
Faulting module path: C:\Program Files (x86)\NVIDIA Corporation\CoProcManager\nvdxgiwrap.dll
Report Id: 02520951-3066-4499-8349-6ba526f670f4
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by sylveon** [comment]
Seems like a bug in your Nvidia driver. I would recommend updating it.

**Comment by Yilmaz4** [comment]
> Seems like a bug in your Nvidia driver. I would recommend updating it.

It's latest driver for my graphics card (391.35).

**Comment by sylveon** [comment]
Is this something that only started happening after upgrading to Windows 11?

**Comment by Yilmaz4** [comment]
I wasn't used TranslucentTB before I upgraded to Windows 11. So I don't know if this issue only happens on Windows 11.

**Comment by sylveon** [comment]
Try setting TranslucentTB to use integrated graphics from the Nvidia Control Panel

**Comment by Yilmaz4** [comment]
No it's still crashing even after I selected Integrated Graphics.

**Comment by sylveon** [comment]
Does it occur in [the latest dev build](https://artprodcca1.artifacts.visualstudio.com/A9bd8285a-05b0-4590-a30d-489076a293f3/604b3a7f-cfeb-496e-aabc-35608a8095c9/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3N5bHZlMG4vcHJvamVjdElkLzYwNGIzYTdmLWNmZWItNDk2ZS1hYWJjLTM1NjA4YTgwOTVjOS9idWlsZElkLzE0MC9hcnRpZmFjdE5hbWUvUG9ydGFibGUreDY0K1JlbGVhc2U1/content?format=zip)?

**Comment by Yilmaz4** [comment]
No it doesn't occured! Problem fixed, thanks. Also new UI of your program looks good, keep it up :)

**Comment by sylveon** [comment]
Awesome, thanks!
