### ISSUE TITLE
not working multi monitor on windows 11

### ISSUE THREAD

**Issue by zafergurkan** [TranslucentTB/TranslucentTB#401]
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 
 - Windows build number: 
 - Steps to reproduce: 
 - Expected results: 
 - Actual results: 
 - Other:

**Comment by sylveon** [comment]
Please fill the issue template.

**Comment by zafergurkan** [comment]
I removed this app.  same here. https://github.com/TranslucentTB/TranslucentTB/issues/365

**Comment by sylveon** [comment]
Closing as duplicate then.
