### ISSUE TITLE
TranslucentTB wont start

### ISSUE THREAD

**Issue by Tsukaretaonesan** [TranslucentTB/TranslucentTB#402]
[x] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 9.00 
 - Windows build number:19042. 1083 
 - Steps to reproduce: I try to open the app 
 - Expected results: My taskbar should be translucent 
 - Actual results: Error "The application was unable to start correctly (0xc0000102) click ok to close the application" 
 - Other: I don't know how to fix this I tried repairing and restarting, I deleted and re-installed it, and I downloaded the other application by tpxxn

**Comment by Tsukaretaonesan** [comment]
Nvm I'm pretty sure its a windows issue

**Comment by sylveon** [comment]
That error code is STATUS_FILE_CORRUPT_ERROR. Some system DLL might be corrupt?
