### ISSUE TITLE
Add the translucent function of the notification bar

### ISSUE THREAD

**Issue by Marrrrrrrrry** [TranslucentTB/TranslucentTB#404]
As the title says

**Comment by sylveon** [comment]
I'm confused at what you're asking

**Comment by Marrrrrrrrry** [comment]
I mean, could you add transparency support for the notification bar (the notification center dotted on the lower right corner) so that it fits into your TTB?



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | Charles ***@***.***> |
| 日期 | 2021年07月15日 04:32 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [TranslucentTB/TranslucentTB] Add the translucent function of the notification bar (#404) |

I'm confused at what you're asking

**Comment by sylveon** [comment]
TTB can't alter the Action Center's appearance, but I could add support for changing what the taskbar looks like when the Action Center is opened.

**Comment by sylveon** [comment]
#335 is already opened for this, you can upvote it there
