### ISSUE TITLE
Visual C++ 2017 Redistributable (x86) failed; code 1638

### ISSUE THREAD

**Issue by ghost** [TranslucentTB/TranslucentTB#406]
when installing the latest TranslucentTB，an error is prompted：“**Visual C++ 2017 Redistributable (x86) failed; code 1638**”
The reason for the error should be that I installed a higher version of the VC library.
Could you provide a version that does not include the VC library？In this way we can get better compatibility.

**Comment by ghost** [comment]
I solved this problem after reinstalling the VC library.

**Comment by sylveon** [comment]
I can't help for issues related to installing the VC++ redist. The installer is skipped when higher versions are installed.
