### ISSUE TITLE
The text is not displayed clearly, and there is no transparency effect when opening the full-screen application

### ISSUE THREAD

**Issue by Dazzle-sys** [TranslucentTB/TranslucentTB#407]
TranslucentTB version: 9.0.0.0
Windows build number: Windows11  22000.100
Expected results: 
Actual results: 
Other: The text is not displayed clearly, and there is no transparency effect when opening the full-screen application
![image](https://user-images.githubusercontent.com/55978588/127741902-857ad936-5d46-48cb-a8b9-117423a7ddbb.png)
.
![image](https://user-images.githubusercontent.com/55978588/127741846-4d1fb4b9-6bc3-4bc7-b515-ea7e0cc63b48.png)

**Comment by sylveon** [comment]
Open the color picker by right-click the tray icon > Maximized Windows > Accent color and then set the alpha/opacity to 0.

For the text color, set the system to use a dark theme (you can keep apps on light theme still)

**Comment by sylveon** [comment]
Defaults have been changed in the latest version to avoid this confusion

**Comment by Dazzle-sys** [comment]
最新版在哪啊?@sylveon

**Comment by sylveon** [comment]
You can get it from the Microsoft Store or the GitHub release tab
