### ISSUE TITLE
Blur isn't working properly (I think)

### ISSUE THREAD

**Issue by hcesaropz** [TranslucentTB/TranslucentTB#408]
- TranslucentTB version: 9.0.0.0
 - Windows build number: 19043.1165
 - Steps to reproduce: Just use the "Blur" option. It's identical to the "Clear" option. At least to me...
 - Expected results: The taskbar should be blurred. (I have absolutely no idea)
 - Actual results: All it does is blur anything applications/programs behind it. ("it" as in the taskbar that I can't really see)
![image](https://user-images.githubusercontent.com/61612754/130391206-070a62e1-83b6-4b13-bc68-4325afa3b037.png)

**Comment by sylveon** [comment]
It actually is working as expect, just that the background you use makes it really not obvious. For example on the top-left the little line is blurrier when it goes under the taskbar:

![image](https://user-images.githubusercontent.com/6440374/130391316-9d235968-9c0d-4569-82a6-05c115e000da.png)

If you use a busier background, the effect will stand out more:
![image](https://user-images.githubusercontent.com/6440374/130391400-141eafe7-9d8c-46cc-9dd0-9f4c406935e1.png)

**Comment by hcesaropz** [comment]
![image](https://user-images.githubusercontent.com/61612754/130392966-20cd13cc-860f-4db1-a5eb-981aebef3db0.png)
not very blurry in my opinion but ok

**Comment by hcesaropz** [comment]
![image](https://user-images.githubusercontent.com/61612754/130393272-48c0b2f4-aec2-43c9-a0b6-921f2d3a88ef.png)
perfection
not really

**Comment by sylveon** [comment]
The blur radius doesn't scale with DPI unfortunately, this is a DWM bug, so nothing TTB can fix. It's much more blurry on 100% DPI.

**Comment by hcesaropz** [comment]
well that was quite the opposite of what i was expecting

**Comment by sylveon** [comment]
If you use Fluent it will be more blurry.

**Comment by hcesaropz** [comment]
i dont see why the fluent design language would include blurs
but im gonna use it, since it does
and it does a better job of it than the normal blur

**Comment by hcesaropz** [comment]
![image](https://user-images.githubusercontent.com/61612754/130394249-855d7dc6-271e-4e26-938b-58b6608b9f01.png)
Well, at least that line's gone now.

**Comment by MolotovCherry** [comment]
:/

![QQ截图20210830200308](https://user-images.githubusercontent.com/13651622/131434898-5e69a195-2be1-4d18-b39b-7fbd0ceba8a3.png)

**Comment by sylveon** [comment]
Maximised window > Accent color > Set alpha to 0 @cherryleafroad

**Comment by MolotovCherry** [comment]
> Maximised window > Accent color > Set alpha to 0 @cherryleafroad

I just did that, but I still see the weird blurring where you can still clearly see on parts of it. For clarification, maximized window is set to blur, and I went into the menu -> maximized window -> accent color and set it alpha to 0 as you said (I even restarted the program)

I'm figuring based on your above comment about the DWM bug, what I showed above probably isn't fixable?

**Comment by sylveon** [comment]
Oh yeah, that's a DWM bug too

**Comment by ghost** [comment]
I don't even have the "Blur" option on the new update. It's just gone... luckily I went into the config and changed it manually to Blur and it works but no idea why the option is gone from the UI for me (Windows 11)

**Comment by sylveon** [comment]
Yes, it's intentionally hidden on Windows 11 because it causes significant lag if you happen to accidentally drag an Explorer windows under the taskbar, see #405.
