### ISSUE TITLE
Issue when booting laptop on external monitor and then disconnecting external monitor

### ISSUE THREAD

**Issue by lucaptlr** [TranslucentTB/TranslucentTB#412]
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue. 
I found similar problems, but this seems a pretty specific issue.

 - Version: Windows store 2021.1.0.0
 
- I boot the laptop connected to an external monitor, and then in a second moment I disconnect the external monitor
 
- The program should function as expected and as it did before the update. 
 
- Instead, if for example there was the option to set the taskbar clear when on the desktop, after disconnecting the external monitor the taskbar turns black. Or if before was set to normal when the start menu is opened, after disconnecting the monitor it goes to clear.

**Comment by sylveon** [comment]
Please don't ignore the issue template. It's here for a reason.

**Comment by lucaptlr** [comment]
Edited

**Comment by lucaptlr** [comment]
Sorry, edited.

**Comment by sylveon** [comment]
The new update should help with this issue.
