### ISSUE TITLE
Start Menu Flickering still persist after update 

### ISSUE THREAD

**Issue by dfsss1** [TranslucentTB/TranslucentTB#415]
Im having problems opening the start menu in windows 10, for some reason the Blur effect start to flickering when I open the start menu, disabling the transparent effect. I saw a guy having the same problem as me but w11 I think, And for me the problem still persists

**Comment by sylveon** [comment]
#411. I thought I had fixed it but apparently not, will need to investigate more.

**Comment by sylveon** [comment]
I think I found this issue: the app is installed to a location that explorer.exe cannot normally read, so it fails loading the injected DLL (which is responsible to avoid this from happening in the first place). I'll devise a solution ASAP.

**Comment by dfsss1** [comment]
> I think I found this issue: the app is installed to a location that explorer.exe cannot normally read, so it fails loading the injected DLL (which is responsible to avoid this from happening in the first place). I'll devise a solution ASAP.

nicee =))

**Comment by Zokaper** [comment]
I also have this issue, glad to see it will be fixed soon.

**Comment by julianphp** [comment]
Same problem when i open the start or search box in windows 10 21H01 with the new update

**Comment by sylveon** [comment]
Fixed on 2021.4, the update is available in the store now.

**Comment by dfsss1** [comment]
good job men, the problem is fixed, thumbs up for your dedication in this program😁✌️
