### ISSUE TITLE
while clicking start menu the screen is going from translucent to black 

### ISSUE THREAD

**Issue by beastslayer-6310** [TranslucentTB/TranslucentTB#416]
[] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: Box version 2.0

 - Steps to reproduce:
   1. Take the box.
   2. Put the box on the table.

 - Expected results: The box sits on the table.

 - Actual results: The box disappears spontaneously once
   put on the table.

 - Other: The box I ordered was damaged.

**Comment by sylveon** [comment]
Duplicate of #411 #415
