### ISSUE TITLE
Tray icon become blurry after DPI changed many times

### ISSUE THREAD

**Issue by ysc3839** [TranslucentTB/TranslucentTB#417]
- [x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

Version information: 2021.1.0.0

Steps to reproduce:
   1. Open TranslucentTB.
   2. Change display scale in System Setting many times.

Expected results: The tray icon still clear.

Actual results: The tray icon become blurry.
![image](https://user-images.githubusercontent.com/12028138/131773864-d2cc4bbc-a760-4c65-bfea-6672af0db1c0.png)

Other: 
When DPI changed, the `WM_TASKBARCREATED` message is also being broadcasted. Then the program set `m_CurrentlyShowing` to false and try to add the icon. However at this time the icon is still there, the add operation failed, so `m_CurrentlyShowing` would never become true.
My solution:
```
LRESULT TrayIcon::MessageHandler(UINT uMsg, WPARAM wParam, LPARAM lParam)
{
	if (uMsg == m_TaskbarCreatedMessage)
	{
		if (m_ShowPreference)
		{
			LoadThemedIcon();
			m_CurrentlyShowing = Notify(NIM_MODIFY);
			Show();
		}

		return 0;
	}

	return MessageWindow::MessageHandler(uMsg, wParam, lParam);
}
```

**Comment by sylveon** [comment]
Thanks for the bug report, and sorry for taking forever to get to it! I pushed a commit fixing it.
