### ISSUE TITLE
Need Chinese，Need Chinese，Need Chinese，Need Chinese

### ISSUE THREAD

**Issue by HankMo** [TranslucentTB/TranslucentTB#419]
Need Chinese

Need Chinese

Need Chinese

Need Chinese

**Comment by Thor-x86** [comment]
**Please stop being arrogant**

Instead of forcing someone to learn your language, why not add it yourself via pull request? It's open source after all

**Comment by sylveon** [comment]
Translation support technically exists within TTB (I've experimented with a French one), but I indeed do not speak Chinese, so anybody is welcome to contribute translations.

**Comment by 5idereal** [comment]
> Translation support technically exists within TTB (I've experimented with a French one), but I indeed do not speak Chinese, so anybody is welcome to contribute translations.

@sylveon, sorry to bother you, but can you explain how can we translate TranslucentTB into other languages? I can help traslate it into Chinese (Traditional). Thanks in advance!

**Comment by sylveon** [comment]
You'll have to build the app yourself for now.

The build instructions are a bit outdated. You'll need VS 2022, and to install vcpkg.

Once vcpkg is installed and TTB is cloned locally, run the following:
```
vcpkg install --overlay-triplets=C:\path\to\ttb\vcpkg\triplets --triplet x64-windows-ttb fmt spdlog
vcpkg install --overlay-triplets=C:\path\to\ttb\vcpkg\triplets --triplet x64-windows-ttb --overlay-ports=C:\path\to\ttb\vcpkg\ports --head detours gtest member-thunk rapidjson wil
vcpkg integrate install
```

Then you should be able to open the solution, set AppPackage as the startup project and hit the green play button to run TTB.

Once that's done, to translate you have to do two files. The first is a .rc2 script. You can copy the English one (`TranslucentTB\resources\language\TranslucentTB.en.rc2`), changing `en` to `zh` and update the strings in here.

The other file is a .resw file in the XAML project. You'll have to create it and give `x:Uid`s to stuff (as that hasn't been done yet). You can follow [this guide from MS](https://docs.microsoft.com/en-us/windows/uwp/app-resources/localize-strings-ui-manifest) for instructions.

**Comment by Geeyun-JY3** [comment]
@sylveon Is it possible to use a web-based localization management system platform like [Weblate](https://weblate.org/) or [Crowdin](https://crowdin.com/) to manage translations of TTB? Or for now, more code work is needed?

**Comment by sylveon** [comment]
For now, code work is needed. A localization platform is a future plan.

**Comment by johnvp22** [comment]
商店有汉化版

**Comment by Thor-x86** [comment]
Internationalization feature (or i18n) currently in progress, see pull request https://github.com/TranslucentTB/TranslucentTB/pull/463

**Comment by sylveon** [comment]
Pull request has been merged. You can now follow the contributing guide to translate TranslucentTB.

**Comment by sylveon** [comment]
Would #493 work for you?

**Comment by Emperormummy** [comment]
I remember someone translated this app,but not updated from then on

**Comment by txyyh** [comment]
> I remember someone translated this app,but not updated from then on

@tpxxn have made it before, and it's still on Microsoft Store.

**Comment by sylveon** [comment]
Chinese (Traditional) and Chinese (Simplified) are now supported locales in the latest update

**Comment by LordMaddhi** [comment]
@sylveon how to change the language? today i started my pc and somehow translucenttb changed the language to japanese...

**Comment by sylveon** [comment]
Check your Windows language settings:
![](https://media.discordapp.net/attachments/312341949078306818/1051280370793984061/205079769-7ed32011-b3b2-4ed7-9821-0f9418819618.png)

**Comment by LordMaddhi** [comment]
ah okay, my windows is set to german but as second language i have japanese installed (cause i learn it haha). well, its time to contribute and add german language support :D

**Comment by sylveon** [comment]
There's already a German translation in the develop branch which will release at some point.
