### ISSUE TITLE
New MS Store Version not respecting Settings for Dynamics

### ISSUE THREAD

**Issue by pelaird** [TranslucentTB/TranslucentTB#420]
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: TranslucentTB ver. 9.0.0.0 vs. MS Store Version 8/1/2021; Windows ver. 19043.1202

 - Steps to reproduce:
   1. The MS Store version and the GitHub version don't appear to be the same as of 8/1/2021.
   2. The MS Store version has different Dynamic categories
   3. The MS Store version does not respect the Settings (config file).

 - Expected results: Example: MS Store Version: When "Start Menu Open" is set to clear, it should display as clear.

 - Actual results: it intermittently displays as normal
   put on the table.

 - Other: The MS Store version as of 8/1/2021 looks great, but does not respect the settings (config file).

**Comment by duk6046** [comment]
I have a same issue

**Comment by sylveon** [comment]
> The MS Store version and the GitHub version don't appear to be the same as of 8/1/2021.

This is currently because I'm going to fix the issue you're experiencing before making a GitHub release.

> When "Start Menu Open" is set to clear, it should display as clear.

This is being tracked in #415
