### ISSUE TITLE
IDP.ALEXA.53 infection avast report

### ISSUE THREAD

**Issue by adrien-lsh** [TranslucentTB/TranslucentTB#422]
Hey I just reboot my computer and avast warned me about this : 
![image](https://user-images.githubusercontent.com/50402620/131894204-07de26da-7b9d-4832-ae52-d16dceeb92ee.png)

Hope someone can help me, I trust TranslucentTB since the begining of the software, hope it did not get infected :/ 
Thx for your help

**Comment by sylveon** [comment]
I've reported a false positive to Avast, we have to wait now:

![image](https://user-images.githubusercontent.com/6440374/131895980-63018319-f33d-4dc7-bfb2-f06b8eabbd32.png)

**Comment by sylveon** [comment]
![image](https://user-images.githubusercontent.com/6440374/132029353-ebcf3d34-ebb4-48a6-9039-7a53a4f40af4.png)

That report was submitted for 2021.2 and now we're at 2021.4, so I'm not sure if I'll have to do a new one. Would be great if you could let me know

**Comment by sylveon** [comment]
Will close since nobody seems to be having problems
