### ISSUE TITLE
TranslucentTB deleting screenshots

### ISSUE THREAD

**Issue by DerZuntor** [TranslucentTB/TranslucentTB#426]
Hi,
I'm now using TranslucentTB for over 2 months, and I was really happy with it. This morning I was playing Sea of Thieves and when I was doing a Screenshot (Using the build in Win+Print Shortcut) my Antivirus (Avast Ultimate) Ransomware Protection kicked in and said TranslucentTB.exe wants to change file "Screenshot (21).png" and "Screenshot (22).png", for one image I let TranslucentTB change it and for the other I didn't, the one that was changed by the App was deleted while the other one is still there.

I'm using the newest Microsoft Store Version. It happends everytime I do a screenshot in a game, on the desktop however it's not happening. Do you know what's causing this? If not see this as a bug report.

Kind regards

**Comment by sylveon** [comment]
This is very odd, as TranslucentTB doesn't touch anything related to screenshots. If you disable the ransomware protection, are the files still being deleted?

**Comment by DerZuntor** [comment]
No, and Windows Defender Ransomware Protection is not flagging anything. I saw someone else on here said something about Avast false flagging TranslucentTB, so it's maybe something Avast related?

**Comment by sylveon** [comment]
Very likely :'(

**Comment by DerZuntor** [comment]
Is there some way to report it to Avast for manual review? I've seen it false flag multiple programs in the last months.

**Comment by sylveon** [comment]
They have a false positive form here: https://www.avast.com/false-positive-file-form.php

I already reported version 2021.2, not sure if that helps for 2021.4

**Comment by DerZuntor** [comment]
Ok. I'll report the newest version, just to be safe. Thanks for the help, have a nice day.
