### ISSUE TITLE
[Very Angryyyyyyyyyy] The latest version doesn't have some functions which the old version does.

### ISSUE THREAD

**Issue by sakurawald** [TranslucentTB/TranslucentTB#427]
I use a old version TranslucentTB and make my own advanced configs. Everything goes well.
However, today my TranslucentTB auto update without any information.
And I find that the new version change its config format, some configs are deleted.
PS: I love the old version, since it can set a specific color and you can change the transparency from 0-255 (usually i will set it to 128, it look better than BLUR effect).

**Comment by sylveon** [comment]
Blur is hidden (but still available if you edit the config file) in Windows 11 because of #405.
Search opened doesn't work in Windows 11 yet, so it is also hidden for now.
The alpha is now embedded in the color hex, you can use something like `#00000080` for black with 128 alpha.

**Comment by sakurawald** [comment]
> Blur is hidden (but still available if you edit the config file) in Windows 11 because of #405.
> Search opened doesn't work in Windows 11 yet, so it is also hidden for now.
> The alpha is now embedded in the color hex, you can use something like `#00000080` for black with 128 alpha.

ohh, i see the alpha option and now this program works well with a new beautiful UI.
