### ISSUE TITLE
Full transparency doesn't work - flickers back to default inexplicably.

### ISSUE THREAD

**Issue by WillFP** [TranslucentTB/TranslucentTB#428]
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

Only happened since version 5.0 - I only use TranslucentTB so that the taskbar is permanently completely transparent, however since 5.0 has been released, clicking the start button **occasionally** (most of the time, not all - i've checked my settings before you ask) will make it change back to default gray.

On a multi-monitor setup, this only happens on one or two of the monitors, not on all of them. Why wasn't 5.0 tested properly before being pushed?

**Comment by sylveon** [comment]
There's an update available in the store that solves this, it's the same issue as #415.

> Why wasn't 5.0 tested properly before being pushed?

It was tested, but this issue only showed up once released in the store because the store installs it in a special place (the `WindowsApps` folder) while local testing via VS doesn't. Sorry :(
