### ISSUE TITLE
The startup

### ISSUE THREAD

**Issue by ghost** [TranslucentTB/TranslucentTB#43]
It will be better if it can automatically starts when the system starts.

**Comment by Meychel** [comment]
I achieved by making shortcut to the exe file, placed in "Startup" folder

**Comment by olliethepikachu** [comment]
To get to the said Startup folder press Win-R and type shell:startup.

**Comment by Kasablanka1996** [comment]
i want to get clear as default,but the default is blur
]

**Comment by charlesmilette** [comment]
If you added a shortcut in your startup folder, you can simply open its properties and add ` --transparent` at the end of the "Target" field.

If you didn't, you can add ` --transparent` to the command line arguments whenever you launch the program

A configuration file feature will be available in the next update.
