### ISSUE TITLE
Windows 11: Acrylic doesn't work for 'Desktop', appears solid black.

### ISSUE THREAD

**Issue by nitz** [TranslucentTB/TranslucentTB#430]
- [x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: 2021.4.0.0

 - Steps to reproduce:
   1. Open TranslucentTB
   2. Set desktop option to "Acrylic"

 - Expected results: The task bar becomes Acrylic and seethru.

 - Actual results: The task bar turns black and opaque.

 - Other: Windows 11 issue, worked perfectly in Win 10. Currently on OS build `22000.160`. Acrylic also works fine for other options, like maximized window. Seems to be related to the default 'Desktop' state.

**Comment by sylveon** [comment]
This is a change in Windows 11, which is a [known issue](https://github.com/TranslucentTB/TranslucentTB/releases/tag/2021.4):
> Acrylic color does not work correctly. It seems Microsoft changed the API in 11 and I've yet to figure out how it works now. `#1C230F00` (or just using the normal appearance) works pretty decent for now.

**Comment by nitz** [comment]
Ah, I checked everywhere in issues, didn't think to check release notes for known issues :)

I appreciate the response!

**Comment by CentralPier9** [comment]
pretty sure there's the same issue with clear too. 

(edit: I'm on win 10)

**Comment by nitz** [comment]
> pretty sure there's the same issue with clear too.
> 
> (edit: I'm on win 10)

I'm using clear on Win 10 (19042.1237) and 11 (22000.194) and haven't noticed no issues. I'd imagine it might be something else going on for you.

**Comment by CentralPier9** [comment]
It was working again for a while but then not working again. I think it has something to do with my laptop being plugged in or not. It works when plugged in but doesn't when I unplug it. I haven't checked if that's really the case yet, I'll check again when I'm back home.

(edit: My issue has been mentioned before upon checking older posts. Apparently it's a battery saving feature, so its a different issue from yours.)

**Comment by sylveon** [comment]
Fixed in 2021.5
