### ISSUE TITLE
Copying stock configuration file failed! Exception from HRESULT: The system cannot find the file specified. (0x80070002)

### ISSUE THREAD

**Issue by 314749236** [TranslucentTB/TranslucentTB#431]
This error pops up every time I use it

(C:\Users\Sylveon\Desktop\TranslucentTB\TranslucentTB\main.cpp:216 at function void __cdecl ApplyStock(const class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > &))

**Comment by sylveon** [comment]
Can you try updating? You're on an old version.

**Comment by 314749236** [comment]
works, thanks
