### ISSUE TITLE
Entering RGB/HSV Values Manually only Works Intermittently

### ISSUE THREAD

**Issue by pelaird** [TranslucentTB/TranslucentTB#433]
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: Latest Store Version 2021.4.0.0/ Windows 19043.1202
![Screenshot 2021-09-06 091332](https://user-images.githubusercontent.com/83546781/132230236-d8af9ad8-4cd4-4415-9b6f-b8d57372a488.png)

 - Steps to reproduce:
   1. Open TranslucentTB in the taskbar
   2. Go to Desktop>Accent Color>RGB/HSV panel
   3. Set values by entering new values manually using keyboard
   4. Intermittently works/Mostly doesn't
   5. I have to use the JSON settings to enter values manually

 - Should be able to enter values manually from keyboard

 - Most of the time I can't enter values manually, but intermittently is does work 

 - Other: I really like the updated version. Thanks

**Comment by sylveon** [comment]
This does not appear to be an issue in Windows 11 SV2. Will close as it appears it was an OS bug.
