### ISSUE TITLE
where is blur in this ver.

### ISSUE THREAD

**Issue by Ehoumaki** [TranslucentTB/TranslucentTB#434]
[] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: Box version 2.0

 - Steps to reproduce:
   1. Take the box.
   2. Put the box on the table.

 - Expected results: The box sits on the table.

 - Actual results: The box disappears spontaneously once
   put on the table.

 - Other: The box I ordered was damaged.

**Comment by pelaird** [comment]
Each Dynamic setting has Normal, Opaque, Clear, Blur, and Acrylic in Windows 10.
If your using Windows 11, I'm not sure, but I believe there is an issue with Blur.
![Screenshot 2021-09-06 102329](https://user-images.githubusercontent.com/83546781/132238909-7fa46978-e145-4e1d-9018-4c55815f9fef.png)

**Comment by pelaird** [comment]
See #405

**Comment by sylveon** [comment]
Yes, blur is hidden from Windows 11, see that issue. Moreover, the issue template wasn't filled. Please fill the template next time.
