### ISSUE TITLE
[Feature Request] Select text color from background

### ISSUE THREAD

**Issue by FelixSchuetze** [TranslucentTB/TranslucentTB#439]
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

If you are using "clear" setting and dark/light wallpaper, certain icons can become really hard to read/see. I would love to have TranslucentTB choosing black or white font color automatically from the background to get high contrast.

**Comment by sylveon** [comment]
Duplicate of https://github.com/TranslucentTB/TranslucentTB/issues/41

**Comment by FelixSchuetze** [comment]
Oh I'm sorry
