### ISSUE TITLE
Taskbar stays transparent after uninstalling on Windows 11 build 22000.194

### ISSUE THREAD

**Issue by TyohDev** [TranslucentTB/TranslucentTB#444]
(Using the Microsoft Store version)
Coming from another Taskbar software for win10 I tried out TTB for its transparent taskbar.
I didn't really like it, because there is a weird sort of line that appears at the top of the taskbar. This seems to be a bug with win11 tho.
So after uninstalling TTB my Taskbar didn't revert back to normal and refuses to do so until I kill the explorer process und restart it. Are there any hooks left after uninstalling? Maybe even a registry entry, that just doesn't get deleted?
Really need help here because it's extremely inconvinient.

**Comment by sylveon** [comment]
TranslucentTB doesn't alter the registry. Does this issue happen if you exit TranslucentTB normally then uninstall it, rather than uninstall it while it's running?

**Comment by TyohDev** [comment]
Yes. It happens even if you close it manually before uninstalling. It happens every reboot, as if something is still in autostart. As mentioned above it goes back to normal, once you restart the explorer.

**Comment by 3060PlayZ-github** [comment]
Try using an uninstaller...

**Comment by sylveon** [comment]
I can't offer you support if you use any uninstaller. They do a vast amount of questionable changes to a system that I cannot predict what their impact is.

**Comment by 3060PlayZ-github** [comment]
Try changing all of the TB options to normal, then uninstalling...

**Comment by TyohDev** [comment]
Okay so I actually found a solution. Turns out, that there was still a taskschedule remaining of the other program I was using before using TranslucentTB.
So totally a mistake on my part.
Thanks for your help though!
