### ISSUE TITLE
Taskbar not fully transparent

### ISSUE THREAD

**Issue by xaavro** [TranslucentTB/TranslucentTB#449]
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: 2021.4.0.0
 - Windows version: 21H1 19043.1266

 - Steps to reproduce:
   1. Choose "clear" option as "Desktop"
  
 - Expected results: taskbar should be fully transparent

 - Actual results: taskbar has a slighty darker shade and its border is clearly visible

**Comment by xaavro** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/91946594/136015157-e1f6d468-f722-46f6-84e0-a3d31ec20716.png)

**Comment by sylveon** [comment]
Desktop > Accent Color > set opacity to 0

**Comment by xaavro** [comment]
I think it is already at 0, isn't it?
![Screenshot_2](https://user-images.githubusercontent.com/91946594/136017309-489a5bbe-9a3d-4565-b85c-39631195b0a1.png)

edit: I just saw there's a discord server. If this isn't really a bug but my own issue, I can ask for help there.

**Comment by xaavro** [comment]
Nevermind, I just found the problem.
I used Startisback to have a classic windows menu. Disabling it gave me the full transparency.
