### ISSUE TITLE
clear mode on startup

### ISSUE THREAD

**Issue by Turbocharger** [TranslucentTB/TranslucentTB#45]
hi there i am using TranslucentTB.2017.2.zip and i just created a shortcut on startup. now i want to know is there any option to make CLEAR MODE on startup instead of BLUR MODE?

**Comment by charlesmilette** [comment]
Append ` --transparent` to your startup shortcut.

**Comment by Turbocharger** [comment]
i just pasted the EXE file in startup folder. so shall i paste a shortcut instead and put <"location\of\exefile\"--transparent> in Target: box or in Start in: box???

**Comment by charlesmilette** [comment]
You must create a shortcut instead and set the __target__ as <"location\of\exefile" --transparent> (don't forget to add a space between the location of the exe and "--transparent").

For example, here's mine:
![image](https://cloud.githubusercontent.com/assets/6440374/22893439/b3cada48-f1e3-11e6-8e25-76787238196d.png)

**Comment by Turbocharger** [comment]
Thank you very much!!! appreciate your help :) 👍

**Comment by charlesmilette** [comment]
You're welcome
