### ISSUE TITLE
No "Blur" Option in Win 11

### ISSUE THREAD

**Issue by Shiemy** [TranslucentTB/TranslucentTB#450]
After Update to Win 11 Sadly there is no "Blur" Option Anymore only "Normal" "Opaque" "Clear" "Acrylic" (See Screenshot below)

Is there any way to get it Blurry (Transparent not Full Clear) again?

![Unbenannt](https://user-images.githubusercontent.com/46209678/136032530-0d98abb5-23b2-4692-8cfc-9d57001181f3.png)

**Comment by sylveon** [comment]
See https://github.com/TranslucentTB/TranslucentTB/issues/405

**Comment by Shiemy** [comment]
I already did that it is on here you can See:
![Unbenannt](https://user-images.githubusercontent.com/46209678/136033997-303fe70d-d6fe-4417-870d-3c30f90de4e0.png)

**Comment by sylveon** [comment]
As I explained in #405, it's voluntarily hidden because of a bug in Windows. It has been fixed in insider dev builds. Once the fix makes it back to a stable build, the option will come back.
