### ISSUE TITLE
Dynamic state bugs when change the monitor

### ISSUE THREAD

**Issue by duk6046** [TranslucentTB/TranslucentTB#451]
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: 2021.4.0.0 (Windows 11 store)

 - Steps to reproduce:
   1. change the monitor (ex: primary -> secondary monitor)

 - Results: transparency is disabled

 - Other: if reset dynamic state, temporarily resolved.

**Comment by duk6046** [comment]
still not solved in v2021.5

**Comment by sylveon** [comment]
The new update should help with this issue.
