### ISSUE TITLE
[Battery Saver] Some feedbacks, issue reports, and suggestions about battery saver mode on Windows 10

### ISSUE THREAD

**Issue by jimchen5209** [TranslucentTB/TranslucentTB#459]
- [X] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

## Version Info
 - Current APP Version: 2021.5
 - Current OS Version: Windows 10 Home 19043.1237

-----
Since I'm having some issues when using battery saver mode, I was looking around the issues here.

Like taskbar become completely transparent after app exit in battery saver mode mentioned in #244, #315, #323, and #324, which seems to be an upstream issue and can be fixed after restart explorer or disable and re-enable power saver mode. Also, there is a new option about battery saver a few moments ago mentioned in #429, which lets you control what it looks like in battery saver mode. 

However, the enable toggle seems not working. Even I have that **Enable** option unchecked, TTB still applies the settings previously set in the **Battery saver** option instead of the regular settings when I switch on power save mode.

Besides, **Normal** and **Acrylic** in **Battery saver** are not working, taskbar simply appears as clear with accent color when it is switched from **Opaque** and **Clear**, or stuck into the state before switching on battery saver mode. **Blur** in **Battery saver** seems to be working but it's actually frozen because it's not reflecting background change. When switching from **Blur** to **Normal** or **Acrylic**, accent color even disappeared, become completely transparent. **Opaque** and **Clear** are working fine.

Here is some suggestion for this: If issues in **Normal**, **Blur**, and **Acrylic** in **Battery saver** mentioned above could not be fixed, you can disable or remove those options to not be confused, it'd be better if these are fixable. Also, you can mention this upstream issue on the homepage like readme since this cannot be fixed on the app's side.

One more interesting thing is that taskbar will become completely transparent if you turn off and turn back on **Transparency effects** in Windows **Personalization > Colors** setting without TTB in battery saver mode. I'm not sure if this is after using TTB.

**Comment by notavgkaren** [comment]
In my case, when battery saver on Windows is on, the task bar just turns completely black, and the toggle on the app doesn't seem to be making any changes.
![image](https://user-images.githubusercontent.com/44011613/137350444-d47985f4-bb7d-404c-9f81-468f5ce41415.png)
