### ISSUE TITLE
Change Transparency of Start Menu

### ISSUE THREAD

**Issue by Warp00** [TranslucentTB/TranslucentTB#46]
Currently it's kind of jarring when my Start Menu has a different colour/transparency. Is there any way to apply the same effect to the start menu? :)

**Comment by ethanhs** [comment]
The Windows 10 start menu is a UWP app that we cannot easily change. Instead we plan on changing the taskbar. See #25

**Comment by charlesmilette** [comment]
![2017-02-16 1](https://cloud.githubusercontent.com/assets/6440374/23041393/d997237c-f462-11e6-9474-7c5d01cd0496.png)
Calling SetWindowCompositionAttribute is technically possible, it just looks weird

**Comment by ethanhs** [comment]
Ah, interesting. I had tried setting it to transparent and it did not work for me. If that does work, then maybe we should do this after all.

**Comment by ethanhs** [comment]
Spitballing a bit here, it might be possible to isolate the _background_ HWND of the start menu. One might need to use accessibility functions or something.

**Comment by olliethepikachu** [comment]
Perhaps, but it would be much more work than I (or most others) would be willing to put in. Closing for now, unless someone finds a way to isolate the background HWND.

**Comment by Solid-Block** [comment]
"Classic Shell" can change the start menu. I think you can do it, too.

**Comment by ethanhs** [comment]
@solid-block classic shell draws a completely new start menu. We aren't ever going to do that

**Comment by TeusDev** [comment]
what are alternatives so far to this ? is it at least possible using "Classic Shell" ?
