### ISSUE TITLE
任务栏状态显示不正确

### ISSUE THREAD

**Issue by lunfangyu** [TranslucentTB/TranslucentTB#460]
![操作演示](https://user-images.githubusercontent.com/41062458/136649641-c2466695-e85c-4d27-b516-2f29af510977.gif)

如演示图所示：当运行TranslucentTB后； 鼠标先滑过语言栏状态或者WIFI图标，然后再滑到空白任务栏处，在空白任务栏却显示了右下角的WIFI状态。 这显然是不对的。退出TranslucentTB并重启系统后，此问题消失。

**Comment by mlleemiles** [comment]
It is a bug introduced by Windows 11

**Comment by sylveon** [comment]
Yeah, that's a Windows 11 bug. The issue has been fixed in a newer Insider builds, and occurs even when TTB isn't running.

**Comment by yoshiask** [comment]
I can confirm this, I have never installed TTB on my desktop with Win11 but this bug is present.

**Comment by lunfangyu** [comment]
> Yeah, that's a Windows 11 bug. The issue has been fixed in a newer Insider builds, and occurs even when TTB isn't running.

感谢回复，经验证，确实如此
