### ISSUE TITLE
Win 11 Bug!

### ISSUE THREAD

**Issue by michelefrasca** [TranslucentTB/TranslucentTB#461]
![TranslucentBug](https://user-images.githubusercontent.com/90919828/136654394-8dfd7b63-5a1e-49fb-96df-86df5621d642.png)

As can be seen on the screenshot i've attached, there's a little bug for the new Win11 OS. There's a thin line over the hidden bar.
Can you fix this?

Thanks
Michele

**Comment by vigo113** [comment]
> ![TranslucentBug](https://user-images.githubusercontent.com/90919828/136654394-8dfd7b63-5a1e-49fb-96df-86df5621d642.png)
> 
> As can be seen on the screenshot i've attached, there's a little bug for the new Win11 OS. There's a thin line over the hidden bar. Can you fix this?
> 
> Thanks Michele

hello developer know about this #425 you can close this thread
