### ISSUE TITLE
Super small but simple bug to fix (HEX issue)

### ISSUE THREAD

**Issue by DaikoDubs** [TranslucentTB/TranslucentTB#466]
Ive notice that when trying to set HEX settings for "Start Opened", the HEX for "Maximized Window" overrides "Star Opened".  For example, I have my start menu set to display orange when I open it, however when I window is maximized, i have it set to be black.  When the windows is maximized, the TB is black as expected.  But when I press "Windows Key" it stays black and does not change to orange, sometimes it does flicker to the color ive selected for "Start Opened" but it is not consistent.

**Comment by DaikoDubs** [comment]
![Screenshot (59)](https://user-images.githubusercontent.com/92585224/137490753-7b7ee745-a89e-45bc-a3a8-aa2e314a8501.png)
![Screenshot (56)](https://user-images.githubusercontent.com/92585224/137490756-b7ef8a42-1bde-4ab0-92a0-295485e2c5e3.png)
![Screenshot (57)](https://user-images.githubusercontent.com/92585224/137490759-5d91a910-ac4a-401b-bcd7-b18e7f88b9b0.png)
![Screenshot (58)](https://user-images.githubusercontent.com/92585224/137490760-4e1309b2-3699-4c88-9a72-84cc188ccb0c.png)

**Comment by DaikoDubs** [comment]
No rush but maybe in the next patch this could me considered

**Comment by sylveon** [comment]
Fixed in https://github.com/TranslucentTB/TranslucentTB/commit/ef45fe25d9c3e4538f7d6461c5400c9025513870
