### ISSUE TITLE
Taskbar appears black if "Energy Save" Windows mode is enabled.

### ISSUE THREAD

**Issue by serious-angel** [TranslucentTB/TranslucentTB#472]
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

Thank you very much for the project!

 - Version information: The latest - 2021.5.

 - Steps to reproduce:
   1. Install the software;
   2. Wait until Windows enables "Energy Save" mode or enable it manually.

 - Expected results: Transparent/Default taskbar.

 - Actual results: The taskbar appears black.

It seems the issue is related to "`battery_saver_appearance`" settings option, and either it's enabled or disabled (it seems it's disabled by default). If its "accent" parameter is set to "opaque", the taskbar appears black when the "Energy Save" OS mode is active.

Perhaps #459 is related, too.

**Comment by sylveon** [comment]
Yeah I have accidentally forgot to check if the appearance is enabled before applying it. I'll fix it in the next update.

**Comment by tylvn** [comment]
This problem does not seem to have been solved until now.

**Comment by sylveon** [comment]
There hasn't been an update with the fix yet - it's coming
