### ISSUE TITLE
Allow us to change the transparency of the start menu in Windows 10 and 11

### ISSUE THREAD

**Issue by CharlieWilkinson005** [TranslucentTB/TranslucentTB#474]
It would be cool if we could change the transparency of the start menu to match the taskbar. I have been looking for a tool everywhere and I can't find one that changes the transparency of the start menu.

**Comment by sylveon** [comment]
This is because the start menu is implemented completely differently to the taskbar and every attempt at it has been unsuccessful.

**Comment by sylveon** [comment]
(see #46)
