### ISSUE TITLE
Add a slider to change the blur from 0 to 100 percent

### ISSUE THREAD

**Issue by CharlieWilkinson005** [TranslucentTB/TranslucentTB#475]
TranslucentTB would be even better if we could have a slider for how intense the blur effect is for the taskbar like how there is a slider for the opacity of the taskbar. TranslucentTB is a great tool!

**Comment by sylveon** [comment]
This can't be implemented, because we just tell DWM to render the taskbar with blur - we can't control the intensity of that blur, just the color tint.
