### ISSUE TITLE
Blur option stopped working for me in Windows 10

### ISSUE THREAD

**Issue by creativegamer03** [TranslucentTB/TranslucentTB#478]
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - **Version information:** 
 Windows 10 20H2 19042.1320 (desktop PC)
 TranslucentTB version 2021.5

 - **Steps to reproduce:**
   1. Enable Blur on Visible Window.
   2. Drag visible window to behind the taskbar.

 - Expected results: Taskbar should blur out the "hidden" part dynamically.

 - **Actual results:**
 Window is not blurred. Taskbar hides the window instead of blurring it as expected.
![image](https://user-images.githubusercontent.com/66676126/139449734-a30ffdeb-8b68-4934-93f5-433518b6ec21.png)
![image](https://user-images.githubusercontent.com/66676126/139449757-b00c9e52-678d-424d-ad0a-8afb9449862f.png)
Only works when changing settings (like changing the Accent Color) to Visible Window.
![image](https://user-images.githubusercontent.com/66676126/139449634-dc158ff3-052e-404c-aa31-2408e68a95b1.png)
It also leaves the blurred out "hidden" part of the window until setting is changed.
![image](https://user-images.githubusercontent.com/66676126/139449872-4066f3e8-fe7f-4e83-843d-081ddf35da60.png)

 - **Other:** 
 "Disable savings settings" is enabled. Also did "Reset dynamic state".
This feature once worked dynamically before, but somehow it didn't after. Tried disabling StartIsBack, thinking it might be interfering it; same result.

EDIT: Surprisingly, the "left-over" blurred part of the window stays when opening the minimized application. Minimizing it clears or replaces the "left-over".

**Comment by sylveon** [comment]
Are you on battery saver mode?

**Comment by creativegamer03** [comment]
> Are you on battery saver mode?

I'm on a desktop PC. Plugged to a power source.
Sorry, forgot to mention that too.

**Comment by creativegamer03** [comment]
ok this is weird.. it dynamically changes the "left-over" to whatever tab is on screen.

**Comment by creativegamer03** [comment]
another note: the taskbar updates every time the desktop bg changes if its a slideshow bg. it does flicker when updating tho.

**Comment by creativegamer03** [comment]
It seems it was affected after a cumulative update (10-21). same issue with StartIsBack when i enabled Blur for the taskbar: when dragging the window to the taskbar it would blur like this issue im having with translucentTB, but updates only when dragging out and in the window, which it would have function as what i expected with TTB's blur.
I'll try to test this.

**Comment by creativegamer03** [comment]
ok nvm. it was the missing acrylic blur bug. fixed it with the registry fix.
