### ISSUE TITLE
Access Denied for Install from TranslucentTB.appinstaller

### ISSUE THREAD

**Issue by hessam-kk** [TranslucentTB/TranslucentTB#480]
Hi, 
Today I want to install this app on my fresh install of window 10 21H1. First I tried to do installation from Microsoft Store, it installed and applied but couldn't make it running for a long time. so perforce uninstall it and tried to install from `TranslucentTB.appinstaller` from github. But after downloading at clicking on it, after a second I face this error due to lack of permission:
`App installation failed with error message: AppX Deployment operation failed with error 0x0 from API Logging data because access was denied for file: \\?\C:\Program Files\WindowsApps\28017CharlesMilette.TranslucentTB_2021.5.0.0_neutral_split.scale-150_v826wp6bftszj\AppxManifest.xml, user SID: S-1-5-18 (0x80070005)`

also there is no option for running as administrator in context menu.
plaese guide me.

thanks in advance.

**Comment by sylveon** [comment]
How did you force uninstall it?

**Comment by hessam-kk** [comment]
> How did you force uninstall it?

Version from Windows Store: Open `Start menu` > Find app > right click > click `Uninstall`

**Comment by sylveon** [comment]
This seems right, the app installer doesn't need admin rights either. Is the issue solved after rebooting?

**Comment by hessam-kk** [comment]
Well, the functionality after reboot is even more sophisticated, I mean first I could install it from MS Store, worked fine. But after a reboot, I couldn't open the app(and it didn't auto start), and my taskbar resets to the Windows default color. So I uninstalled the app and tried to install it from github, and then I faced Permission Error(which created this issue for).
When I try to reopen the app, I see `Check the Windows Store for more info about TranslucentTB.`:
![image](https://user-images.githubusercontent.com/24957423/139730298-db8a3cad-c5e5-4793-bd21-2f08a69ea9a4.png)

also in start menu:
![image](https://user-images.githubusercontent.com/24957423/139730356-345ae649-b923-4458-95c0-38a580bff8e1.png)

**Comment by sylveon** [comment]
Did you end up fixing the issue?

**Comment by hessam-kk** [comment]
well, I uninstalled that github version, and tried to install it from MS-Store again, fortunately that has been working till now. but I decided to completely stop using this app because of very high battery and CPU usage, that mean I have experienced maximum fan speed and lags on my Windows which I never seen before... I removed the app and my laptop is working fluency as before...
in addition to high cpu usage, there was one more reason for stop using the app, when I opened a full screen window like browser or MS-Word with color white on entire screen and Blur-Mode, I couldn't see the clock and texts on the taskbar... Blured white background and white text on taskbar mixed together and nothing was clear to see (i'm not going to open a new issue, but you may want to consider that).

bests.

**Comment by sylveon** [comment]
> when I opened a full screen window like browser or MS-Word with color white on entire screen and Blur-Mode, I couldn't see the clock and texts on the taskbar... Blured white background and white text on taskbar mixed together and nothing was clear to see (i'm not going to open a new issue, but you may want to consider that).

You can change what it looks like when there is a maximized window by using the "maximized window" submenu
