### ISSUE TITLE
Bug that causes Windows to say that the user profile service cannot be loaded.

### ISSUE THREAD

**Issue by 3060PlayZ-github** [TranslucentTB/TranslucentTB#481]
Hello! 3 months ago , I found this bug,
after installing TranslucentTB, and logging off it says that the user profile service cannot be loaded, it eventually fixes itself...
I think that this is a Windows issue, but am not sure...

**Comment by sylveon** [comment]
Yes, this sounds like a Windows issue. Any screenshots of the problem?

**Comment by 3060PlayZ-github** [comment]
Here!
https://drive.google.com/file/d/13LKDeJ83vBcdWkeUrfhVanQAZndiJxPL/view?usp=sharing
I've noticed it happens with apps which add themselfs to startup, TB is one of them... Strangely it does not happen with Spotify...

**Comment by sylveon** [comment]
Yeah, seems like a Windows issue, don't think there's much we can do to fix it...

**Comment by 3060PlayZ-github** [comment]
So it seems like Windows 10's Store got updated, I will see if it still has that bug...

**Comment by sylveon** [comment]
OS issue

**Comment by 3060PlayZ-github** [comment]
It was fixed now...
