### ISSUE TITLE
Acrylic not working in Windows 11

### ISSUE THREAD

**Issue by jairocontreras** [TranslucentTB/TranslucentTB#482]
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

Acrylic (for Desktop) not working in Windows 11

**Comment by sylveon** [comment]
What does "not working" means? Any screenshots?

**Comment by jairocontreras** [comment]
Normal
![normal](https://user-images.githubusercontent.com/43326330/139949908-22573296-d32b-43d3-987d-8a21f02dbc91.png)

Acrylic
![acrylic](https://user-images.githubusercontent.com/43326330/139949907-3dde365c-04f1-4850-83e7-305587c0d54b.png)

**Comment by sylveon** [comment]
It seems you're running an out of date version. Try updating

**Comment by jairocontreras** [comment]
i installed from microsoft store, latest version (2021.5)

**Comment by ghost** [comment]
Hi there! I have the same issue.

Normal:
![Normal](https://i.imgur.com/hR7v2uu.png)

With Acrylic Effect:
![Acrylic Effect](https://i.imgur.com/m4756c4.png)

![Version Proof](https://i.imgur.com/nHXNQrO.png)

**Comment by younyokel** [comment]
I have the same issue.

**Comment by Vyexk** [comment]
In Windows 10 it works without having transparency enabled in Windows settings.
Now in Windows 11 it is necessary to enable transparency for the acrylic option to work correctly.

I would like you to give a solution to this problem since I only want transparency in the taskbar, but not in the other windows.

**Comment by bapeey** [comment]
I changed the configuration file manually from "acrylic" to "blur" (the blur option is not shown in the panel).

**Comment by jairocontreras** [comment]
very nice. thanks!

**Comment by 9xbt** [comment]
same for me, thanks!

**Comment by kushraval1** [comment]
solution for anyone today is to go to: Windows Settings/Personalization/Colors 
and then enable transparency mode.

**Comment by Dill-pickle-spear** [comment]
I have a similar issue, except acrylic looks identical to clear.

**Comment by Pointless-Overthinker** [comment]
> I have a similar issue, except acrylic looks identical to clear.

same for me here and I have no idea how to fix it

**Comment by DanielHKayser** [comment]
Same here

**Comment by thatotherguy** [comment]
> I have a similar issue, except acrylic looks identical to clear.
This just happened to me as well

**Comment by thatotherguy** [comment]
> I have a similar issue, except acrylic looks identical to clear.

This just happened to me as well

**Comment by Itchy-Feets** [comment]
> > I have a similar issue, except acrylic looks identical to clear.
> 
> This just happened to me as well

same :((

**Comment by Daniyal-Sultan** [comment]
Same! The acrylic looks exactly like the "Clear" version. Fortunately, the Blur option is still working as intended, but it doesn't look anywhere near as good, so if anyone has a solution (on Windows 11, specifically, since toggling Transparency Effect isn't doing anything) please do share it.

**Comment by sylveon** [comment]
Power saver also needs to disabled.

**Comment by Daniyal-Sultan** [comment]
> Power saver also needs to disabled.

Oh wow, that worked like a charm. Thank you so much, mate. Cheers!
