### ISSUE TITLE
Strange grey line in recent build (Not necessarily bug of TTB)

### ISSUE THREAD

**Issue by PhyX-Meow** [TranslucentTB/TranslucentTB#486]
First thank you for your great work--TTB!
After upgrade to recent build of win11 (Now in 22499), the taskbar looks like this:
![image](https://user-images.githubusercontent.com/17513581/141478959-8ba24e43-bb01-4d01-9665-2677be81bebc.png)
![image](https://user-images.githubusercontent.com/17513581/141478998-cec46247-81d8-435a-9520-86b2dbe60564.png)
I am very annoyed with the grey line on the top of task bar. I know this is more likely a bug of windows, but I have no idea where to report this, so, come here for advise or any help.
Appraciate any reply.

**Comment by Only-Bimal** [comment]
Please refer #425
