### ISSUE TITLE
Support styling the task bar independently when Search Opened under Win11

### ISSUE THREAD

**Issue by dbaeumer** [TranslucentTB/TranslucentTB#489]
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

Version info:

OS; Windows 11
<img width="169" alt="capture" src="https://user-images.githubusercontent.com/1931590/142417801-ed464194-c142-4a42-8288-b4a862ce3b59.png">

Support to style the task bar when using Win+S to search. Basically the same support as for Start Opened

Currently the default style is used which might make it inconsistent to Start Opened.

**Comment by sylveon** [comment]
This is a known issue, the way to detect search changed in windows 11 so the feature has been hidden until I implement the new method.

**Comment by dbaeumer** [comment]
@sylveon thanks for letting me know.

**Comment by sylveon** [comment]
Implemented in https://github.com/TranslucentTB/TranslucentTB/commit/ef45fe25d9c3e4538f7d6461c5400c9025513870
