### ISSUE TITLE
dynamis-ws Build

### ISSUE THREAD

**Issue by jtvjan** [TranslucentTB/TranslucentTB#49]
Since I want to use --dynamic-ws, I made a new build. Here is that build from the unmodified master branch if any of you others want to use it. https://www.virustotal.com/nl/file/9a4b434a81cfecbf69582912d4853498e15ad1cde7eec4befddc9664cca1e08a/analysis/1489163483/
[TranslucentTB.zip](https://github.com/TranslucentTB/TranslucentTB/files/834512/TranslucentTB.zip)

**Comment by ethanhs** [comment]
I don't think I will delete this, but I will give a couple of warnings: This is an in-progress feature, there are known bugs. I cannot verify the validity of the above users code or build. Please use at your own risk.

Also a note on why development has slowed so much. Essentially, I and everyone else on the team have gotten busy. For myself, I have little incentive on working on new features as I see this program as fulfilling all of my needs, and I get no remuneration. Of course, as always I am happy to review PRs with new features.

**Comment by jtvjan** [comment]
The feature was working pretty well for me. I wasn't sure if I was going to post this, but I wanted to save people the trouble of installing Visual Studio.

**Comment by olliethepikachu** [comment]
Why don't we try to merge develop with master once we've ironed out the bugs, and then create a new release?

**Comment by ethanhs** [comment]
I have the same plan, but no time to iron out the bugs at the moment. If you would like to work on it, please go ahead.

**Comment by PLyczkowski** [comment]
Doesn't work for me, Win10 64 creators's update : (

**Comment by ethanhs** [comment]
Expect a release within a week.
