### ISSUE TITLE
I want to know how the DLL is injected explorer

### ISSUE THREAD

**Issue by Fall-Rain** [TranslucentTB/TranslucentTB#492]
Hi, I'm interested in TranslucentTB, I recently looked at the source code of 2017.3 and 2018.1 and would like to write a simple TranslucentTB, like 2017.3. But I would like to know how the DLL is injected into explorer

**Comment by sylveon** [comment]
2017.3 and 2018.1 did not inject into Explorer. In 2021.1 and up, SetWindowsHookEx is used.

**Comment by Fall-Rain** [comment]
Thank you for your reply, I will have a look at it and study it.

**Comment by Fall-Rain** [comment]
Hi, sorry to bother you, I was recently looking into the TranslucentTB implementation and found that after it is injected into the dll, the dll sends messages out to communicate with the application as a way to change active changes to inert changes, but I don't know how the main application receives these messages, it seems to be related to MessageWindow::init, where it registers the messages listener?

**Comment by sylveon** [comment]
The messages are handled by overriding the WndProc:

https://github.com/TranslucentTB/TranslucentTB/blob/fabcc771f69166b35c0611d61100cbf81f9b3ac7/TranslucentTB/taskbar/taskbarattributeworker.cpp#L267-L275
