### ISSUE TITLE
Add the support for Chinese

### ISSUE THREAD

**Issue by tylvn** [TranslucentTB/TranslucentTB#495]
There are quite a few Chinese people using TranslucentTB, maybe it's time to add support for Chinese.

**Comment by 5idereal** [comment]
*Might* be a duplicate of #419 
#493 already tries to implement Traditional Chinese translation into TTB.
There's also a Simplified Chinese clone version on Microsoft store, but it's not offical.
![image](https://user-images.githubusercontent.com/30827929/143551847-88a645af-dbb7-450c-80a6-1951141ac625.png)

**Comment by qier19** [comment]
In fact, I prefer to use the official version. Maybe I am not at ease with the unofficial version. After all, I can't understand and analyze the code.

**Comment by 5idereal** [comment]
I can help with adding Simplified Chinese translation. But I'm not quite familiar with the terminology. So I'll need someone to review it.

**Comment by 5idereal** [comment]
I've submitted the PR (#498).

**Comment by Geeyun-JY3** [comment]
don't forget #255
And that fork is here: https://github.com/tpxxn/TranslucentTB

**Comment by sylveon** [comment]
Seeing as I merged both traditional and simplified chinese translations, I will close this issue
