### ISSUE TITLE
There is a small gray line above the taskbar

### ISSUE THREAD

**Issue by FiberAhmed** [TranslucentTB/TranslucentTB#499]
There is a small gray line above the taskbar

**TranslucentTB version: 2021.5 **
**OS: Microsoft Windows 11 Pro Insider Preview**
**Windows Build Number: 22504.1010)**

![Screenshot_1](https://user-images.githubusercontent.com/72029350/143727944-3e6af0e7-40c8-46c1-b68d-a8f674d6d956.png)

**Comment by sylveon** [comment]
Duplicate of #425
