### ISSUE TITLE
Using ACCENT_ENABLE_TRANSPARENTGRADIENT in Windows 10 Insider build 15048 persists correctly.

### ISSUE THREAD

**Issue by charlesmilette** [TranslucentTB/TranslucentTB#50]
I felt like this would be interesting to document.
On my computer, there is no need to constantly set it with a loop ever since I upgraded to that build. Setting it once will keep it permanently for this session, even when usually it would be reset (for example, opening the start menu)
I tried with blur and it keeps the old behaviour.
![gif](https://cloud.githubusercontent.com/assets/6440374/23908198/b829d79c-08a9-11e7-831f-3913d6c8b915.gif)

**Comment by ethanhs** [comment]
I am on 15042, and observing the same behavior. This is great! Furthermore, if you set it to clear then blur, it applies the _previous_ style, so it goes back to clear. This also means #12 is more important now.

**Comment by olliethepikachu** [comment]
This could be why the `dynamic-start` feature is broken on newer builds.

**Comment by olliethepikachu** [comment]
I think that if we were to store the `WINCOMPATTRDATA` returned from the undocumented `GetWindowCompositionAttribute` on application startup, then we could pass it to `SetWindowCompositionAttribute` upon exit / `dynamic-start` to perhaps restore it to normal.

**Comment by ethanhs** [comment]
Yes, I think this is a good idea. We should reset to what it was on exit, and people will want to toggle back to it on some occaisons

**Comment by olliethepikachu** [comment]
Try your `dynamic-start` now, with my newest push.

Get Outlook for iOS




On Wed, Mar 29, 2017 at 1:57 PM +0800, "Ethan" <notifications@github.com> wrote:












Yes, I think this is a good idea. We should reset to what it was on exit, and people will want to toggle back to it on some occaisons

**Comment by ethanhs** [comment]
By the way, I am no longer experiencing this on Windows 10 build 16179. The opening of the start menu _should_ cause the taskbar to redraw, so this is the expected behavior.
