### ISSUE TITLE
Taskbar flickers when wallpaper is changed

### ISSUE THREAD

**Issue by younyokel** [TranslucentTB/TranslucentTB#503]
- [ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.
### Version Information:
 - Version information: Latest 2021.5, Microsoft Store
 - Windows version: Windows 11 22000.348
### Steps to reproduce:
   1. Have Windows 11, because I don't know if it works correctly on Windows 10.
   2. Set slideshow wallpapers up.
   3. Change wallpaper.
 ### Results:
 - Expected: Wallpapers should not affect taskbar.
 - Actual: 
![translucenttb](https://user-images.githubusercontent.com/53343081/143782222-4f37b88a-9939-4b44-bdde-1f2f52102b9f.gif)
- Other: It works correctly while wallpaper animation is still running (even with acrylic mode), but as long as it stops, the taskbar flickers. It also flickers after opening startup menu and maximizing the "hidden icons" after wallpaper is changed.

**Comment by dongle-the-gadget** [comment]
Seems that the flickers also occur with Blur + moving windows around.
