### ISSUE TITLE
Does not work after turning monitor on and off

### ISSUE THREAD

**Issue by adambnmohd** [TranslucentTB/TranslucentTB#506]
https://imgur.com/a/GpzfKxc

**Comment by Charlielx** [comment]
Seconding this, although mine just turns to solid gray. I could've sworn I read a comment saying this was supposed to be fixed in a patch ages ago.

**Comment by Charlielx** [comment]
Is there any updates on this? It's really annoying having to select "reset dynamic state" (or restart the app) every time I turn my monitors back on

**Comment by sylveon** [comment]
The new update should help with this issue.
