### ISSUE TITLE
Delayed window movement with TTB enabled

### ISSUE THREAD

**Issue by Northernside** [TranslucentTB/TranslucentTB#507]
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information:
   - TTB: 2021.5.0.0
   - Windows: Build 22523

 - Steps to reproduce:
   1. Start TTB
   2. "Wiggle"/Move a window at a faster speed.

 - Expected results: No delay/lag when moving a window at a certain speed.

 - Actual results: Laggy/delayed movement

 - Other: https://imgur.com/a/iP4wXuN video is a few days old but it's the same today. When I exit TTB everything is normal

**Comment by Globespy** [comment]
It's not fixed, and probably won't be since no update since October last year.
It's a really nice little mod, but not at the expense of making the OS run like turd.

**Comment by sylveon** [comment]
I can't fix issues coming from DWM (which this one is). Moreover this is an Insider build, so the issue may fix itself in a later build.

**Comment by Globespy** [comment]
Hello Sylveon,
Thank you for your reply.
You are indeed correct; the issues persist even after removing your app.
I am on 'release preview' Win 11 build (22000.466), and it's not fixed.
Hopefully soon, but I will be reinstalling your app until then as I really like the 'clear' taskbar, very clean looking.

Take care.
