### ISSUE TITLE
Ordinal not found

### ISSUE THREAD

**Issue by iron2000** [TranslucentTB/TranslucentTB#508]
Recently started see this dialog on Windows start up:
![ordinal](https://user-images.githubusercontent.com/43039016/147245409-fff9653a-b72f-4ee1-8bfb-f8572b657242.png)

Had set TranslucentTB to open at boot and one day this dialog show up.
Had to manual open TranslucentTB after.

Running the MS Store version on Windows 10 21H2 19044.1415

**Comment by sylveon** [comment]
Have you tried uninstalling and reinstalling the app?

**Comment by iron2000** [comment]
Nope but the dialog disappears for a few days after manually starting TranslucentTB.
This is not the first time I've seen this dialog.

**Comment by sylveon** [comment]
From a quick Google, this seems to stem from an issue with LoadIconMetric from common controls 6 somehow not being present - have you tried running `sfc /scannow`? Has this started happening after a recent update to Windows?

**Comment by iron2000** [comment]
Just run a scan, no integrity violations it says.

Anyway the dialog popped up again today, not yesterday though.
I just uninstall and reinstall the app.
Will see if it shows up again.

**Comment by iron2000** [comment]
The dialog popped up on boot again.

**Comment by iron2000** [comment]
![dialog](https://user-images.githubusercontent.com/43039016/149930084-f6c856fd-6119-4cf5-b4c7-f45bac41ea5f.png)
This dialog came on startup today. First time I see this.
Though TranslucentTB still open when I activate it manually.

Still see the Ordinal Not Found dialog every other day.

Not sure if it affects but I run TranslucentTB with [CenterTaskbar](https://github.com/mdhiggins/CenterTaskbar) on startup.

**Comment by iron2000** [comment]
![dialog](https://user-images.githubusercontent.com/43039016/150624180-fe8d336b-95b2-4157-a690-45d47060856d.png)
Got another dialog on startup, first time seeing this too.

**Comment by sylveon** [comment]
These error dialogs are coming from Windows before the program even got to launch, so I suspect that something is wrong with your OS.

**Comment by hello-smile6** [comment]
> These error dialogs are coming from Windows before the program even got to launch, so I suspect that something is wrong with your OS.

@iron2000 Your RAM might be the issue.

**Comment by iron2000** [comment]
Hmm, I do run a [RAMdisk](https://www.softperfect.com/products/ramdisk/) too, for the browser caches.
Nothing very wrong with the OS here, had been gaming, surfing etc without problems.
Only dialogs are the TranslucentTB titled ones sometimes on startup.

**Comment by hello-smile6** [comment]
> Hmm, I do run a [RAMdisk](https://www.softperfect.com/products/ramdisk/) too, for the browser caches. Nothing very wrong with the OS here, had been gaming, surfing etc without problems. Only dialogs are the TranslucentTB titled ones sometimes on startup.

There's just that reference to failed memory reads/writes.

**Comment by iron2000** [comment]
I was thinking maybe there was some contention of memory allocation between TranslucentTB and the RAMdisk?
Due to arbitrary order of startup apps execution?

Anyway I only see the dialog in the first post on every other boot.
The next 2 dialog I posted are pretty much one-offs for now.
So far all is titled to TranslucentTB.

**Comment by hello-smile6** [comment]
> I was thinking maybe there was some contention of memory allocation between TranslucentTB and the RAMdisk? Due to arbitrary order of startup apps execution?
> 
> Anyway I only see the dialog in the first post on every other boot. The next 2 dialog I posted are pretty much one-offs for now. So far all is titled to TranslucentTB.

Does it happen if you try copying the contents of your SSD to another SSD and using the same OS on a different computer?

**Comment by iron2000** [comment]
lol, I have no means to do that test.

Anyway I've never seen that memory dialog before until yesterday.
Didn't see it today as well.
These dialogs only pop up at boot and always reference TranslucentTB.
Never see them when I'm using the PC.

**Comment by hello-smile6** [comment]
> lol, I have no means to do that test.
> 
> Anyway I've never seen that memory dialog before until yesterday. Didn't see it today as well. These dialogs only pop up at boot and always reference TranslucentTB. Never see them when I'm using the PC.

Huh. Try adding it to the startup directory of the start menu and removing the normal entry, that might work.

**Comment by hello-smile6** [comment]
Wait, is the .exe being loaded as a DLL?

**Comment by iron2000** [comment]
I don't know how Windows Store apps work.
Is it still an exe?
The executable seems to be in some obscure system location and not the usual Program Files.

**Comment by hello-smile6** [comment]
> I don't know how Windows Store apps work. Is it still an exe? The executable seems to be in some obscure system location and not the usual Program Files.

But, if you look at the error, it references the .exe as if it was a DLL. Also, that is in the `Program Files` directory.

**Comment by iron2000** [comment]
Oh! Ok.
Tried and I cannot access the Windows App folder.
Don't want to mess with the permissions.

**Comment by hello-smile6** [comment]
> Oh! Ok. Tried and I cannot access the Windows App folder. Don't want to mess with the permissions.

I mean, I think TranslucentTB is trying to load itself as a DLL.

**Comment by sylveon** [comment]
OS issue.
