### ISSUE TITLE
dynamic-start - Repeatedly clicking Start Button causes application to not work

### ISSUE THREAD

**Issue by denosawr** [TranslucentTB/TranslucentTB#51]
I recently pushed out commit https://github.com/TranslucentTB/TranslucentTB/commit/b6479fd6e60ca24e1a4a08a81490cb14b45e4c57 which adds support for `dynamic-start`, but I've observed some weird behavior -

* The feature works as expected when using the Start button **on your keyboard** or clicking the Start Button on the taskbar once
* When repeatedly pressing the Start button on your keyboard the feature still works as expected
* But, when repeated pressing the Start Button on the taskbar, the feature stops working (hangs on normal taskbar state) until you put another window in focus.

This could be because when closing the Start Menu using the keyboard, the original window goes back into focus, while when using the mouse to open it you change focus to the Taskbar.

This isn't a deal breaker, and isn't too important, but just an observation which I think should be fixed if possible.

**Comment by olliethepikachu** [comment]
Also, if you happen to be hovering over the taskbar, pressing the Win button on your keyboard follows the weird behaviour observed above - until you hover your mouse over another window. Observed by @MrAksel - perhaps that could be the cause of the mouse behaviour.

**Comment by ethanhs** [comment]
I also can repro once I made the requisite changes. If I understand the issue correctly, if we search for the start menu Window using EnumWindows or the like, we should be able to just check if the actual correct window is open, and not need to worry about who has foreground.

**Comment by denosawr** [comment]
Fixed in commit `a45a96c`.

**Comment by Kaedin** [comment]
In which release will this fix be included? :)

**Comment by sylveon** [comment]
Next release
