### ISSUE TITLE
Search bar 

### ISSUE THREAD

**Issue by UnDeadLolomat** [TranslucentTB/TranslucentTB#511]
Hey, i wonder if you guys can make the search bar customizable.
I want to make it clear like my taskbar.
[Here](https://imgur.com/a/HTtJKaR) a picture of my taskbar and my search bar, which i want to be clear like my taskbar.

**Comment by sylveon** [comment]
This is much more complicate than changing the taskbar, so not something we're willing to do. If you don't like how it's not transparent, you can right-click the taskbar and turn it into a button instead of a bar.
