### ISSUE TITLE
Application installation failed with error message: Access Denied. (0x80070005)

### ISSUE THREAD

**Issue by ZainKow** [TranslucentTB/TranslucentTB#514]
Hi,
 today i tried to install translucentTB but couldn't. Windows gives me this error message. I am on Windows 10. I am French so the screen is in French but the written message is the same as my title.
Thanks.
![Capture](https://user-images.githubusercontent.com/97196969/148291812-2073f247-cce8-44b7-9a91-8538c0ea550a.PNG)

**Comment by sylveon** [comment]
If you try from the Windows Store, does it work any better?

**Comment by hello-smile6** [comment]
> Hi, today i tried to install translucentTB but couldn't. Windows gives me this error message. I am on Windows 10. I am French so the screen is in French but the written message is the same as my title. Thanks. ![Capture](https://user-images.githubusercontent.com/97196969/148291812-2073f247-cce8-44b7-9a91-8538c0ea550a.PNG)

Related: https://answers.microsoft.com/en-us/windows/forum/all/cant-install-apps-from-store-error-0x80070005/1da61861-26ee-41b4-ada9-8ac516b0107a

**Comment by ZainKow** [comment]
> If you try from the Windows Store, does it work any better?

Hi, when I press it nothing happens. I do not understand.
![1](https://user-images.githubusercontent.com/97196969/148345221-a1689fb0-7bd1-4b28-822c-ece81051057f.PNG)

**Comment by TY-The-King** [comment]
Me too,so i just download Version 4 hotfix 5 to used

> Hi, today i tried to install translucentTB but couldn't. Windows gives me this error message. I am on Windows 10. I am French so the screen is in French but the written message is the same as my title. Thanks. ![Capture](https://user-images.githubusercontent.com/97196969/148291812-2073f247-cce8-44b7-9a91-8538c0ea550a.PNG)

**Comment by sylveon** [comment]
OS issue, nothing we can fix on our side.

**Comment by spinda** [comment]
FWIW, I'm running into this with both the downloaded bundle and installing from the Microsoft Store, on a fresh Windows 11 install. I can install other apps from the Store just fine, and the portable build works.
