### ISSUE TITLE
[FEATURE REQUEST] Temporarily disable TranslucentTB closing when explorer restarts twice.

### ISSUE THREAD

**Issue by reason-to-fork** [TranslucentTB/TranslucentTB#517]
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.    
  
When explorer restarts 2 times in 30 seconds, you get this error as a safety precaution:
  
![image](https://user-images.githubusercontent.com/97267919/148833745-3b7cfb56-7724-467b-9a49-19a39413f51a.png)
  
Could you add a way to temporarily disable this if you are doing something that requires restarting explorer?

**Comment by sylveon** [comment]
Just exit TTB and restart it once done?

**Comment by Prabesh01** [comment]
+1
