### ISSUE TITLE
Add TranslucentTB as scheduled task

### ISSUE THREAD

**Issue by amzon-ex** [TranslucentTB/TranslucentTB#518]
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: 2021.5.0.0

I wish to add TranslucentTB as a startup task using the Windows Task Scheduler. Why? Because I'd like it to start before by desktop opens, and this can be achieved through the Task Scheduler. However, the task fails to execute, even if run manually. This procedure probably fails because TTB is a Store App and cannot be run manually as an application without proper permissions. 

Is there a way in which I can successfully run TTB through the Task Scheduler?

**Comment by sylveon** [comment]
Use the `ttb.exe` app execution alias
