### ISSUE TITLE
Multiple taskbar buttons highlighted most of the time

### ISSUE THREAD

**Issue by Poolee** [TranslucentTB/TranslucentTB#524]
[X] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: MS Store version, 2021.5.0.0
 - Steps to reproduce:
   1. In dual monitor scenario, click on a taskbar button on the left screen
   2. Click on a taskbar button on the right screen
 - Expected results: The highlighted taskbar button on the left screen should no longer be highlighted
 - Actual results: Both the original taskbar button on the left screen and the newly-clicked taskbar button on the right screen are highlighted.
 - Other: When I click on an empty space on the taskbar, no buttons are then highlighted
![snap1570](https://user-images.githubusercontent.com/6788707/150654647-855326ea-3fc1-41c5-8eb4-214aa9038df0.png)

**Comment by sylveon** [comment]
TranslucentTB doesn't do anything to how those buttons are rendered. Does the issue occur even when TranslucentTB isn't running?

**Comment by Poolee** [comment]
@sylveon you are right, it does happen even when TTB isn't running.  Just wasn't noticeable due to the lack of contrast between an active button and the background colour - which is why I sought out a solution like TTB in the first place! :-D
And now it's really noticeable... but now that I know it's "baked in" to Windows, I will deal with it.

Thanks for your reply!
