### ISSUE TITLE
Fix for refresh app on resolution\scaling\multi-display change:

### ISSUE THREAD

**Issue by TimmyP777** [TranslucentTB/TranslucentTB#526]
NM. I have it fixed. Cant post it properly here. If someone wants this tell me how to post plain text lol.

**Comment by TimmyP777** [comment]
Take this file, rename extension to .ps1 from .txt. It is a lowershell task that always sits in the background. Doesnt use more mem or cpu than normal task, which you already have a ton of.

[TransTBResChangeFix.txt](https://github.com/TranslucentTB/TranslucentTB/files/7930221/TransTBResChangeFix.txt)

It will run a console window. Now, you can change res, screens, orientation and it will call the trtb exe which has the effect of refreshing the taskbar.

C:\Windows\System32\cmd.exe /c start /min "" powershell -WindowStyle Hidden -ExecutionPolicy Bypass -File "######\TransTBResChangeFix.ps1"

This syntax above will start the powershell shortcut, replace the #### with path to the .ps1 script you renamed. Make it run at startup. Bam. Permanent fix. Devs you can have this if you wanna incorporate it. Its really small and pretty much ready to go. Works great too.

**Comment by sylveon** [comment]
This powershell script is a workaround, not a proper fix.

**Comment by TimmyP777** [comment]
Obviously, since Im not the dev. It wont have any more of an overhead that would be incorporated into the program though. This works 100 percent perfect (for res\scaling changing at least, assuming it works for orientation) and is irrelevant cpu usage. 

Its almost as good of a fix as you can get, even if it were in the program.

**Comment by sylveon** [comment]
TranslucentTB already handles a display change so there is something else going on. The script forces a restart of the app.

**Comment by TimmyP777** [comment]
It definitely does not handle any display change on my non-problematic setup. It is a standard 1080p 165hz monitor with no problems anywhere else.

I used DSR and now DLDSR really got me into a fix (1080p to 1440p, 1080p native\desktop). Any upscaled resolution resulted in the bar being recolored and i would always have to run the program to refresh the taskbar (I tried all enabling all the options as well), as far as I know it does not open a second instance upon second exec, and this seems to be equivalent to a programmatic refresh of the program. Thats the primary reason this works so well.

I also see posts about orientation changing doing the same thing. DisplayChanged catches all of this (so I assume it works), and its minimal CPU usage due to being a native Windows function. What is the program doing if it is not using this detection? This function\variable is native and is the most optimized!

**Comment by sylveon** [comment]
It does use WM_DISPLAYCHANGE:
https://github.com/TranslucentTB/TranslucentTB/blob/fabcc771f69166b35c0611d61100cbf81f9b3ac7/TranslucentTB/taskbar/taskbarattributeworker.cpp#L251-L256

**Comment by TimmyP777** [comment]
Okay well... Im not trying to be complicated.  Let me first state that I know I probably am a "unique use" scenario, but this happens on 2 completely different devices:
 
It happens on my desktop, like above 1080p monitor with DSR/DLDSR/Custom res even if I change my resolution with Windows display settings control panel. Any state change, and when I enable a second display (probably a state change too idkwtf) and disable it redraws it. It only happens when it changes back to 1080p, it draws fine at the upscaled resolution.

Also on my Surface Pro 1. Custom resolution 540p. Intel graphics. Whenever I use the custom res, when i change back its redrawn same as desktop. Same when I tilt it.

I see some posts about it, but there has to be other use cases out there.

**Comment by ForgottenMaven** [comment]
I also seem to have this issue, whenever a monitor powers off and then back on, the taskbar on the main monitor fails to reset to translucent. Pressing “reset dynamic state” fixes it until the monitor is power off again. 

I don't think the setup for my case is particularly unique its, a 2160p@120hz which gets turned off every day and a secondary 1080P@60hz monitor on the side which never gets powered off. Oddly the secondary monitor sometimes manages to reset to translucent and other times will fail to do so.

**Comment by MrVonkey** [comment]
I have the same issue when my second monitor is turned on and the windows 11 scaling animation has run. Always have to hit "Reset dynamic state".

**Comment by ForgottenMaven** [comment]
For anyone with this issue, I went ahead and downloaded one of the development versions (2021.5.97) which seems to have helped a bit. It will now, rather than never manage to recover on powering off and on the monitor, recover occasionally, which isn’t great but I imagine it might work better for others. I’m running the portable version on windows 11 if that matters.

**Comment by sylveon** [comment]
What's your monitor configuration (monitor models, cable used, graphics cards, etc.)?

I have a dual monitor system with an AOC C3583FQ, LG 27UL550-W. The AOC is connected using DisplayPort while the LG uses a DP to USB-C cable. Both are connected to a Radeon RX 6900 XT, and I've never managed to break TranslucentTB with any kind of monitor sleep or power cycling. So there is something in your setup that is different to mine which breaks it.

**Comment by TimmyP777** [comment]
It breaks when using DSR or custom resolutions about 60 percent of  the time. I only have a vr set on Hdmi and 1080p monitor on displayport.

Anyways, you all can try TaskbarX too it does the same thing. Cant guarantee anything tho. Seems to give me a bit better results.

**Comment by MrVonkey** [comment]
> 2021.5.97

Where can the development version 2021.5.97 be downloaded? Or did you compiled it yourself?

**Comment by TimmyP777** [comment]
https://dev.azure.com/sylve0n/TranslucentTB/_build/results?buildId=243&view=artifacts&pathAsName=false&type=publishedArtifacts

Look at 3 dots on right for portable x64 and download artifacts.

**Comment by ForgottenMaven** [comment]
My setup is a LG OLED55C1PUB connected via HDMI and a cheapo dell 1080p connected through a DVI to DP cable to an EVGA RTX 3080. I'm not running any custom resolutions or anything, everything is at native. I really have no idea what would be unique about the setup. The monitors are switched off overnight and when I come back and turn them back on it fails to recover. This happens with only the HDMI connected monitor however, as the dvi-dp cable never actually disconnects when the monitor is powered off so there is nothing to recover from.

**Comment by TimmyP777** [comment]
I feel i should mention that I have a WMR VR headset on HDMI, and 1080p displayport monitor that I use 1440p (DL)DSR on for games. When the switch happens... when it switches back is when it fails.

**Comment by MrVonkey** [comment]
@TimmyP777: Thanks for the download link. With version 2021.5.103.f6c9b2a my problems seem to be gone! The taskbar didn't lost its styling and I hadn't have to hit 'Reset dynamic state' the whole day, though I've turned my secondary monitor on and off several times. 

Regarding my setup: My primary monitor is connected via DP and my secondary monitor via HDMI. I don't use any custom resolutions or scalings, but I use Wallpaper Engine on my primary monitor, if this matters.

**Comment by TimmyP777** [comment]
I use deskscapes. Its most likely caused by these two programs.

I would love if the developer posted the certs so us Windows 10 users can try it. The portable one is Windows 11 only, and the msi is missing certs to install.

**Comment by ForgottenMaven** [comment]
I don't happen to use any wallpaper app so at the very least for me its not a wallpaper app. Since downloading the development version its managed to recover on almost everything, the only thing that it still fails to recover from is multiple windows rescalings / resolution changes in succession (such as Nvidia nis in my case, which was kinda mentioned).

**Comment by TimmyP777** [comment]
Does developer know we cannot test Windows 10?

**Comment by sylveon** [comment]
The CI builds are not signed, because I do not upload my signing certificate anywhere for security reasons (plus, CAs are starting to require a HSM, which would prevent this). And the portable mode requires Windows 11 only APIs (specifically, dynamic dependencies).

To test on Windows 10, you can extract the msix (it's just a renamed .zip) to a location you want, and then from a powershell prompt run `Add-AppxPackage -DisableDevelopmentMode -Register C:\TranslucentTB\AppxManifest.xml` (replacing `C:\TranslucentTB` for the location you extracted the msix of course)

**Comment by TimmyP777** [comment]
Thank you kind sir! Thank you for continuing development. It baffles me that MS doesn't have a native option, but thats MS I guess.

**Comment by TimmyP777** [comment]
Actually I get this error:
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF9, Install failed. Please contact your software vendor.
(Exception from HRESULT: 0x80073CF9)
Rejecting a request to register from AppxManifest.xml because the manifest is not in the package root.

I did exactly as you instructed. Any ideas?

**Comment by TimmyP777** [comment]
and if I do it from the WindowsApps folder I get a different error:

Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFF, To install this application you need either a Windows
developer license or a sideloading-enabled system.
Deployment of package TranslucentTB_2021.5.103.0_x64__99myrp4edc0yc with package origin Unsigned failed because no
valid license or sideloading policy could be applied. A developer license
(http://go.microsoft.com/fwlink/?LinkId=233074) or enterprise sideloading configuration
(http://go.microsoft.com/fwlink/?LinkId=231020) may be required.

**Comment by sylveon** [comment]
Enable development mode:
![image](https://user-images.githubusercontent.com/6440374/185003732-187163b2-d74e-4874-aca7-31210dbde4d8.png)

**Comment by sylveon** [comment]
Enabling development mode should also allow you to use the -Register command without moving it in WindowsApps

**Comment by TimmyP777** [comment]
I have it on already.

**Comment by TimmyP777** [comment]
Heres the full error when trying to deploy

Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF9, Install failed. Please contact your software vendor.
(Exception from HRESULT: 0x80073CF9)
Rejecting a request to register from AppxManifest.xml because the manifest is not in the package root.
NOTE: For additional information, look for [ActivityId] 2f069d83-b1be-0009-1cdf-0b2fbeb1d801 in the Event Log or use
the command line Get-AppPackageLog -ActivityID 2f069d83-b1be-0009-1cdf-0b2fbeb1d801
At line:1 char:1
+ Add-AppxPackage -DisableDevelopmentMode -Register D:\TransTB\AppxMani ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (D:\TransTB\AppxManifest.xml:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

**Comment by TimmyP777** [comment]
Uhhh I just discovered the registry key in Windows 10 

Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced

and the key is

TaskbarAcrylicOpacity (DWORD32 set to 0 for total transparency)

Either this app, or TaskbarX uses this key, but the program adds a space after the key title and the key doesn't work as intended.

If you remake this reg key it is a native solution! I cannot get it to bug again, nor even blink a color because its acting as if its native transparent now!

**Comment by sylveon** [comment]
TTB doesn't touch the registry

**Comment by TimmyP777** [comment]
Use the key above. No more issues if you just need transparent taskbar. 100 percent solved because native.

**Comment by sylveon** [comment]
Sorry, TTB doesn't touch the registry because it *can't*, packaged apps get their registry writes virtualized. Plus, the registry key wouldn't support the dynamic modes.

**Comment by TimmyP777** [comment]
Oh im not accusing you or anything, and I wouldnt mind either way if it used the registry.

The only point Im trying to make is that if you simply need a totally transparent taskbar, with no features that your software provides. just a plain clear taskbar... Use that regkey for a native, bug free solution. I dont think that key has been around for that long.

**Comment by sylveon** [comment]
The new update should help with this issue.
