### ISSUE TITLE
large log file

### ISSUE THREAD

**Issue by SainoNamkho** [TranslucentTB/TranslucentTB#529]
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.
the log file become more than 10GB everytime the system have run half a day or so.
![image](https://user-images.githubusercontent.com/23036788/151913584-27592d5a-a801-458b-812d-f230636d723e.png)

**Comment by sylveon** [comment]
What's your log verbosity? is it set to trace or verbose?

**Comment by SainoNamkho** [comment]
> What's your log verbosity? is it set to trace or verbose?


Verbose is disabled in the config
> verbose=disable

Let me extract a fragment from the log
> (Tue Feb 01 10:01:55 2022) Verifying if a window is on the current virtual desktop failed. Exception from HRESULT: Class not registered (0x80040154) (T:\Projects\temp\TranslucentTB\TranslucentTB\window.cpp:123 at function bool __thiscall Window::on_current_desktop(void) const)
(Tue Feb 01 10:01:55 2022) Verifying if a window is on the current virtual desktop failed. Exception from HRESULT: Class not registered (0x80040154) (T:\Projects\temp\TranslucentTB\TranslucentTB\window.cpp:123 at function bool __thiscall Window::on_current_desktop(void) const)
(Tue Feb 01 10:01:55 2022) Verifying if a window is on the current virtual desktop failed. Exception from HRESULT: Class not registered (0x80040154) (T:\Projects\temp\TranslucentTB\TranslucentTB\window.cpp:123 at function bool __thiscall Window::on_current_desktop(void) const)

There're about 80 entries for one second, and the logging level seems to be info:https://github.com/TranslucentTB/TranslucentTB/blob/f0ed4fdb29251f9c970c85ff1d6dffba39819fb8/TranslucentTB/windows/window.cpp#L148

**Comment by sylveon** [comment]
> verbose=disable

That's an old version, we haven't used that config format for a while now. I would recommend updating and seeing if that helps.

**Comment by SainoNamkho** [comment]
> > verbose=disable
> 
> That's an old version, we haven't used that config format for a while now. I would recommend updating and seeing if that helps.

OK, I'm updating it. But I guess the "Class not registered" problem will still be here, should these repeating logs be reduced to something like
> (Tue Feb 01 10:01:55 2022) Verifying if a window is on the current virtual desktop failed. Exception from HRESULT: Class not registered (0x80040154) (T:\Projects\temp\TranslucentTB\TranslucentTB\window.cpp:123 at function bool __thiscall Window::on_current_desktop(void) const) [2045 same info since (Tue Feb 01 10:01:55 2022)]

**Comment by sylveon** [comment]
The newer version (and the code you referenced) only attempts to create the instance of IVirtualDesktopManager once, so I believe it should solve the issue.

**Comment by SainoNamkho** [comment]
> The newer version (and the code you referenced) only attempts to create the instance of IVirtualDesktopManager once, so I believe it should solve the issue.

Nice work
