### ISSUE TITLE
After latest Windows 11 Dev update, blur isn't working & now just black. 

### ISSUE THREAD

**Issue by chooky19** [TranslucentTB/TranslucentTB#531]
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

--> 
 - Windows 11 Insider Preview Build 22557.1
 - Version information: 2021.5.0.0
 

 - Other: After latest Windows 11 Dev update the blur option just makes the taskbar black. All other options work as they should.

![TB blur](https://user-images.githubusercontent.com/51835591/154448245-206f44d9-5266-49f5-ad4d-db0e8f7b8c0f.jpg)

**Comment by sherloked** [comment]
Yep, I'm facing the same issue on the same Windows 11 dev build. All options apart from Blur work fine.

**Comment by 24kcsplus** [comment]
I met the same problem on the same version.

**Comment by Grenouille-2** [comment]
The same issue on Windows 11 Insider Preview Build 22557.1.
![image](https://user-images.githubusercontent.com/60314805/154798289-cf3589a4-ec83-41b7-94de-a94ccf70da2f.png)

**Comment by sylveon** [comment]
This is a bug in insider build 22557.1. There is nothing that can be done on our side to fix it, MS has to solve it. As already noted, acrylic still works.

**Comment by AgrockP** [comment]
Oh okay, so I'm on the latest dev build of windows 11, and except opaque and normal nothing works. MS should probably fix it.

**Comment by AliHussain332** [comment]
> Oh okay, so I'm on the latest dev build of windows 11, and except opaque and normal nothing works. MS should probably fix it.

I'm in latest dev build too and nothing works. hope they fix it.

**Comment by 1111mp** [comment]
+1

**Comment by Moonbladelmao** [comment]
I'm on windows 10 and have the same issue(specific build is 10.0.19044), let's hope it gets fixed someday

**Comment by BlankFX1** [comment]
Blur just works fine on Windows 11 Retail 21H2 Build 22000.795.
Tested with TranslucentTB v9.0.0.0 / 2020.2.0.897e[...].
For that reason I'd be happy if it weren't hidden on Win11 in newer versions.

//Edit: Verified to also work fine with the latest version of TranslucentTB by manually changing "accent" in the settings.json to "blur".

**Comment by sylveon** [comment]
The next update will enable it on builds 22000 that aren't broken, but won't on anything newer, because it's broken there. We can't do much about it being broken directly in the OS.
