### ISSUE TITLE
Windows 11 no blur option

### ISSUE THREAD

**Issue by daveo76** [TranslucentTB/TranslucentTB#533]
Running Windows 11 21H2 Build 22000.527. I have no blur option. So it makes no difference with this running. Windows 11 already has transparent option. It the same for all. I was wanting the blur option
![TranslucentTB](https://user-images.githubusercontent.com/7221776/154827464-9371602f-9105-4f83-9bac-ef4567a4f937.jpg)

**Comment by sylveon** [comment]
Duplicate of #405
