### ISSUE TITLE
Dual Monitor

### ISSUE THREAD

**Issue by dylanstenzinger728482** [TranslucentTB/TranslucentTB#538]
Does anyone else have an issue with the settings not working with dual monitors? Particularly non primary monitors? 

I have the settings for the task bar set to make the task bar a blurred black color when application windows are maximized. However, it doesn't work on any monitor that isn't my primary monitor. (And even the regular clear setting I have for there being now windows open look off)

This is issue appears on both my windows 10 device (PC) and windows 11 (Microsoft Book 2 Laptop).

**Comment by cardin** [comment]
Window 11 (build 22000.527) here. I find that TranslucentTB only worked on the secondary display. Whereas my primary display went back to the default, non-TranslucentTB taskbar.

![image](https://user-images.githubusercontent.com/553816/156493006-18c20679-236e-4194-aa98-cec2825df611.png)

**Comment by cardin** [comment]
A quickfix would be to install RoundedTB on top of TranslucentTB. https://github.com/torchgm/RoundedTB

When I toggled Dynamic Mode on RoundedTB, both my monitors' taskbar went translucent.

**Comment by sylveon** [comment]
The new update should help with this issue.
