### ISSUE TITLE
win11 窗口最大化任务栏透明失效

### ISSUE THREAD

**Issue by ssgnh** [TranslucentTB/TranslucentTB#540]
更新win11后，win11 窗口最大化任务栏透明失效，系统是win11专业版21H2

**Comment by sylveon** [comment]
Update your copy of TranslucentTB

**Comment by Wndstorms** [comment]
在设置里进行设置

**Comment by ok406lhq** [comment]
> 在设置里进行设置

请问如何设置呢？

**Comment by 1191000814** [comment]
> 在设置里进行设置

请问具体应该如何设置呢？

**Comment by Pixel556** [comment]
leave the insider program

**Comment by Pixel556** [comment]
by going into settings > updates and security > windows insider program

**Comment by Pixel556** [comment]
you should see an option to leave the insider program there

**Comment by John-China** [comment]
English please
