### ISSUE TITLE
Issues with all options except Desktop on Windows 11

### ISSUE THREAD

**Issue by mcdonamw** [TranslucentTB/TranslucentTB#542]
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Issue
If I set any of the options under Desktop properly changes the effects of the Taskbar.  Is Desktop solely meant to affect taskbar?

Setting options in Visible Window overrides that which is set in Taskbar and these effects (like Desktop) only affect the taskbar.  No Windows are affected, active or not.

Setting options in any of the other areas seem to have no effect at all on anything so I'm not sure of their purpose.  Note: have not tested Battery Saver as I have no use for that.

 - Version information: 2021.5.0.0

 - Steps to reproduce:
   1. Set Desktop options to Acrylic or Transparent (taskbar changes accordingly)
   2. Now enable and change options for Visible Window.  The taskbar now takes on settings set here ignoring those in Desktop and no effect on any windows.
   3. Set any options in Maximized Window (no effect on any maximized window)
   4. Set any options Start Opened (no effect on start menu or anywhere else)
   
 - Expected results: The box sits on the table.
Expect settings in Visible window to not override those in Desktop.
Expect to see transparency options applying where intended.

 - Other: 
Windows 11 21H2 (build 22000.527)
Transparency effects enabled
Tried enabling and disabling "Show Accent color" on both start/taskbar and title bars and window borders to no effect.

**Comment by sylveon** [comment]
This is how TranslucentTB is supposed to work. These options determine how the taskbar looks when a condition is met. For example, you can have the taskbar such that it's fully transparent by default, and then when a window is maximized, it becomes opaque. TranslucentTB only affects the taskbar, nothing else.
