### ISSUE TITLE
YSK: Older versions of this program work better at redrawing after specific instances.

### ISSUE THREAD

**Issue by TimmyP777** [TranslucentTB/TranslucentTB#544]
Ive been using a ps1 script to help the program keep the taskbar invisible. It no longer stays hidden after a recent powershell update.

HOWEVER, most of the old versions dont suffer from the redraw issues that I was having regarding resolution changes, orientation, etc...

Just a PSA in case anyone out there is having issues.

**Comment by sylveon** [comment]
The new update should help with this issue.
