### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Dyuthibs** [TranslucentTB/TranslucentTB#545]
I am only seeing black taskbar not transparent

**Comment by sylveon** [comment]
Are you running Windows Insider builds

**Comment by bad0s1** [comment]
Same issue for me.

**Comment by bad0s1** [comment]
> Are you running Windows Insider builds

Yes
![image](https://user-images.githubusercontent.com/48060869/159320865-b1eb5ef6-4b41-431f-a06c-195c699397f6.png)

**Comment by sylveon** [comment]
See #537
