### ISSUE TITLE
translucenttaskbar source

### ISSUE THREAD

**Issue by imre1902** [TranslucentTB/TranslucentTB#55]
With which compiler to assemble the source?
I have visua6l C++. It does not work.
thank you.

**Comment by charlesmilette** [comment]
I have Visual Studio 2015. Not sure which version it uses.

**Comment by ethanhs** [comment]
You should use v140 or above of the visual studio compiler. It probably will work with 2013, but we test against building with 2015. You can get the community edition free

**Comment by imre1902** [comment]
hello;
thank you for your response.
Iwould have liked to use TranslucentTB without Trayicon. If you can compile it, it would do me good service.
Best looks.



________________________________

**Comment by ethanhs** [comment]
For the iconless start see #15. It is planned, but I haven't done any work on it yet.
