### ISSUE TITLE
Not working on Win11, it's not "clear".

### ISSUE THREAD

**Issue by Caladryn** [TranslucentTB/TranslucentTB#554]
So, it was working in the last few days, but as you can see in the image, is not now.
![1](https://user-images.githubusercontent.com/91733171/158578498-df15ecc6-fa55-4a87-bba3-af29b4daf948.png)
I setted "Clear" on Desktop menu, but it's still with my color, and not transparent.

**Comment by PPAmaZzz** [comment]
Same. My computer is updated to the latest Win11 Beta version, so I guess Translucent TB is currently not compatible with it.

**Comment by sylveon** [comment]
Duplicate of #537
