### ISSUE TITLE
TranslucentTB doesn't work on newest version of Windows 11

### ISSUE THREAD

**Issue by EmelKesten** [TranslucentTB/TranslucentTB#559]
Just updated W11 and the app runs normal but it doesn't do anything to the taskbar. 
I tried reinstalling the app but still nothing, I tried  everything I know but still nothing :( 
Good Luck fixing that LOL

**Comment by sylveon** [comment]
Are you on Windows insider builds?

**Comment by EmelKesten** [comment]
Yes

**Comment by sylveon** [comment]
Duplicate of #537
