### ISSUE TITLE
Change Transparency of the Overflow Notification Area

### ISSUE THREAD

**Issue by ethanhs** [TranslucentTB/TranslucentTB#56]
This shouldn't be too hard to do hopefully. The Window name is `Overflow Notification Area`, and class name is `ToolbarWindow32`. This is not a child of the ShellTray_Wnd process (thanks Microsoft), so it doesn't get effected by the program. For consistency, it would be a nice thing to do.

**Comment by charlesmilette** [comment]
It's also possible to change opacity of the action center, doing so will also change it for the notification popup (not sure about the composition attribute though)

You can change the opacity of the action center and the value will persist until you restart explorer

**Comment by ethanhs** [comment]
That is handy to know, I think we should add that too if possible. Also, you seem to have made a general purpose transparency/transluceny program? Mind sharing it? I would make it myself, but why dup the effort. You can drag the exe onto gitter or share a link. It would be appreciated.

**Comment by charlesmilette** [comment]
I grabbed it from here: http://glass8.eu/download

In the "others" section

**Comment by ethanhs** [comment]
After thinking about it further. I do not want to change the transparency of the Notification Area or Notifications. Its not really part of the taskbar and I don't want more bloat for a feature people don't ask for. Feel free to implement it yourself. As you said it shouldn't be too hard.

**Comment by charlesmilette** [comment]
I was not able to control the color. Only on whether it's blurred or not

**Comment by ethanhs** [comment]
I believe I misspoke. I do want to do the notification area, but not the action center. I think it is acceptable to only make it blurred or clear if that is possible.

**Comment by ethanhs** [comment]
With the change to fluent for this, I think this is lower priority.
