### ISSUE TITLE
it's not work in for windows 11 beta 22581

### ISSUE THREAD

**Issue by LastAttack** [TranslucentTB/TranslucentTB#566]
Edition	Windows 11 Home
Version	22H2
Installed on	‎2022/‎3/‎24
OS build	22581.1
	Windows Feature Experience Pack 1000.22581.1.0

aka

Build 22581.ni_release.220318-1623

**Comment by kennylee60** [comment]
the same

**Comment by sagars007** [comment]
Yes it doesn't work in latest win 11 dev & beta builds coz of the new tablet-optimized taskbar

**Comment by sylveon** [comment]
Duplicate of #537
