### ISSUE TITLE
TB isn't working in windows 11 22H2

### ISSUE THREAD

**Issue by Rimon551** [TranslucentTB/TranslucentTB#570]
My computer is running windows 11 22H2 version, and for a few days now, TB isn't working (The 'clear' option isn't working).
![Screenshot_7](https://user-images.githubusercontent.com/61230038/160092211-a97f4d07-f052-4e73-9965-d37c3ed8a525.png)

**Comment by andeivanovue** [comment]
+1

**Comment by JjIiNnXx** [comment]
+1

**Comment by JjIiNnXx** [comment]
please fix it，I can't live without it😭😭😭😭

**Comment by Asayaka** [comment]
This is happening in Windows Insider Ver 22579 until now, And its happening to me too. Translucent TB doesnt working

**Comment by sylveon** [comment]
Duplicate of #537

**Comment by xyzuser12** [comment]
I also had the same issue, is it because of the build itself, or is it coming from the software? Thanks.

**Comment by sylveon** [comment]
It's because of changes in the windows Insider build

**Comment by xyzuser12** [comment]
> 

Thanks for the info!
