### ISSUE TITLE
Not working with latest Windows 11 build - 22581

### ISSUE THREAD

**Issue by bkuriach** [TranslucentTB/TranslucentTB#577]
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: 2021.5.0

 - Steps to reproduce:
   Taskbar not changing - windows 11 latest build 22581.ni release

 - Expected results: task bar becomes transparent

 - Actual results: nothing

 - Other:

**Comment by sylveon** [comment]
Duplicate of #537
