### ISSUE TITLE
Why is TranslucentTB not working in Windows 11? Is there a fix coming?

### ISSUE THREAD

**Issue by web3221** [TranslucentTB/TranslucentTB#578]
[] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: Box version 2.0

 - Steps to reproduce:
   1. Take the box.
   2. Put the box on the table.

 - Expected results: The box sits on the table.

 - Actual results: The box disappears spontaneously once
   put on the table.

 - Other: The box I ordered was damaged.

**Comment by sylveon** [comment]
Duplicate of #537

**Comment by web3221** [comment]
LOL, that link does not answer the question, LOL

**Comment by sylveon** [comment]
You haven't filled the issue template. This is the best I can do with the little amount of information you provided.
