### ISSUE TITLE
Weird shadow/line around taskbar

### ISSUE THREAD

**Issue by FluffyDiscord** [TranslucentTB/TranslucentTB#580]
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

Windows 11 21H2

There seems to be a weird line (shadow ?) around taskbar when its transparent.

Can I remove it somehow ?

![obrazek](https://user-images.githubusercontent.com/10332247/160437186-80f9ea99-4914-444a-9d42-9cc36541f17e.png)

**Comment by genna04** [comment]
U have to download roundedtb that would help u

**Comment by genna04** [comment]
U can find it on microsoft store.
After installing it u open and put 0 to margin and 1 to corner radius.
Hope I helped

**Comment by sylveon** [comment]
Duplicate of #425
