### ISSUE TITLE
TranslucentTB not working after latest windows update

### ISSUE THREAD

**Issue by arkaprabhaP** [TranslucentTB/TranslucentTB#584]
Hi, so I recently updated my laptop (Asus Vivobook K15) to version 22H2 , OS Build 22581.200 of windows 11. Ever since the update, Translucent TB was not working properly. I deleted it, restarted my machine and tried it again. All the other options like Acrylic, Opaque, Blur work except the Clear option, which I want for myself. 

Translucent TB version: 2021.5.0.0
Windows version: 22H2
OS Build: 22581.200

**Comment by sylveon** [comment]
Duplicate of #537
