### ISSUE TITLE
No longer compatible with Windows 11 22H2

### ISSUE THREAD

**Issue by obsessedlady** [TranslucentTB/TranslucentTB#591]
Self explanatory, TB no longer works with Windows 11 update. TaskbarX either.
I hope someone has the time to fix it, I miss my transparent bar hahaha

**Comment by obsessedlady** [comment]
![image](https://user-images.githubusercontent.com/79773674/162219729-d5dc9dc2-5ebc-4e2b-b03c-8592a46da6d5.png)

**Comment by sylveon** [comment]
Duplicate of #537
