### ISSUE TITLE
寻求帮助：翻译并告知选项的作用。Ask for help translating into Chinese and tell what the option does

### ISSUE THREAD

**Issue by bai12123** [TranslucentTB/TranslucentTB#593]
我安装了最新版的ttb。截图中，红框圈出来的选项实在不知道是什么意思（或者说有什么作用），请求帮助翻译并告知作用。

I installed the latest version of ttb。In the screenshot, the options circled in the red box really don't know what they mean (or what they do)。Ask for help translating into Chinese and tell what the option does。
![Snipaste](https://user-images.githubusercontent.com/99849852/162763722-3cf75d57-3194-45b1-b69b-2e91c294008c.png)

**Comment by sylveon** [comment]
These are there mostly for diagnosing issues with the app - you shouldn't need them under normal conditions. There is a chinese translation for the next version.
