### ISSUE TITLE
Start the computer and the window pops up

### ISSUE THREAD

**Issue by bai12123** [TranslucentTB/TranslucentTB#594]
Every time i start or restart the computer,TTB will pop up such a window。I know this is a necessary process to start TTB,but I want to be able to cancel the popup from showing (hide the startup popup)
![Snipaste](https://user-images.githubusercontent.com/99849852/162979344-457a00f4-1921-4845-8522-0efc88fa42f5.png)

**Comment by sylveon** [comment]
This popup is not part of TranslucentTB

**Comment by bai12123** [comment]
ok
