### ISSUE TITLE
Please bringt back classical installer, independent from MS-Store/appx infrastructure

### ISSUE THREAD

**Issue by Joachim-Otahal** [TranslucentTB/TranslucentTB#596]
I tried the newer "Store" version, and by that I mean the 7 MB offline installer msix.bundle - which did not work in first place since it detected the old installation from 2017, event though not running, and barked with "already installed" at me without giving an "update old install" choice. 
Issue easy solved - Since then I see more officiousness than ever, for example use "I am checking for updates" prompt and a few other things which are disturbing.
Please bring the normal .exe offline installer back. Else I'll be using this version ( https://github.com/TranslucentTB/TranslucentTB/releases/tag/2020.2 ) until the universe gets cold. Offering 50 € if you do for the current build, and hoping it won't disappear again with subsequent builds.

**Comment by yoshiask** [comment]
I'm not 100% sure what issue you're having, but the MSIX package auto-updates. Also, MSIX bundles have nothing to do with the MS Store.

**Comment by sylveon** [comment]
You also shouldn't be encountering issues with the 2017 version being installed - the app installer has no logic to detect "normal" installers and the end result should simply be both versions being installed at once. I suspect something else is happening on your system. What error are you getting when trying to install it?

**Comment by Joachim-Otahal** [comment]
> What error are you getting when trying to install it?

"Was getting", that part is already solved, though my wording might have not pointed that out 100% clearly.
The message I got was "a newer version already installed" which was not possible. So I uninstalled the 2017 version, and then it worked.
The offer still stands, I don't like Microsoft to track and know which programs I am using, and how often and so on. Classic .exe installers are independent.

**Comment by Joachim-Otahal** [comment]
> I'm not 100% sure what issue you're having, but the MSIX package auto-updates. Also, MSIX bundles have nothing to do with the MS Store.

The "checking for new version of translucentTB" "You version is up to date" in the optics of Microsoft store popped up on reboot - such notifications are really not my type if there is no newer version available. It is fine to tell about a new version available, but not only when checking.
As for the .msix package having nothing to do with the Store: When I installed it this way it appeared in the Store as "installed". I am not deep enough into that to tell who is right or not, I just report what I see.

**Comment by sylveon** [comment]
> I don't like Microsoft to track and know which programs I am using, and how often and so on. Classic .exe installers are independent.

Oh boy do I have news for you.

> The "checking for new version of translucentTB" "You version is up to date" in the optics of Microsoft store popped up on reboot - such notifications are really not my type if there is no newer version available. It is fine to tell about a new version available, but not only when checking.

Not sure why the store gave you that after installing, but it probably shouldn't going forward.

If you do end up in a situation where an update hasnt been installed yet, or auto updates are disabled, the store will tell you a newer version is available when you go in there and check for updates.

> When I installed it this way it appeared in the Store as "installed". I am not deep enough into that to tell who is right or not, I just report what I see.

This is because the package available here has the same package ID as the store package does - so the store is able to associate the installed app with TTB's store listing. (technically, we actually ship the exact same package the store installs, for simplicity's sake, but that doesn't prevent editions of windows without the store from installing the app or auto-updating it as long as the certificate used for signature is trusted - which it is).

---

The next update should have a portable build, but that portable version will only work in Windows 11 due to limitations mentionned here: https://github.com/TranslucentTB/TranslucentTB/issues/548#issuecomment-1066167855

**Comment by Joachim-Otahal** [comment]
> Oh boy do I have news for you.
> The next update should have a portable build, but that portable version will only work in Windows 11 due to limitations mentionned here: [#548 (comment)](https://github.com/TranslucentTB/TranslucentTB/issues/548#issuecomment-1066167855)

Oh, nice! I don't mind putting a link manually in shell:startup. But isn't it technically possible to just link yourself there instead of fiddling around the registry with auto-start?
When the portable version appears and works I consider this to be solved. As for Windows 11: A timeframe when that new start menu will be transparent too? I was forced to switch to 11 to get Nested-V for AMD. And the second best new feature, for me, is robocopy /iorate.

**Comment by sylveon** [comment]
> But isn't it technically possible to just link yourself there instead of fiddling around the registry with auto-start?

Well now instead of fiddling around with the registry we're just fiddling around with the file system. Same difference.

> As for Windows 11: A timeframe when that new start menu will be transparent too?

TranslucentTB never tried to modify the start menu, and we don't have plans to do so. The start menu already has an acrylic effect, as well.

**Comment by dongle-the-gadget** [comment]
> The offer still stands, I don't like Microsoft to track and know which programs I am using, and how often and so on.

If MS does indeed track your installed programs, they have a better way than tracking MSIX installs anyway since they know most aren't going to even use it.

**Comment by SynapseScribe** [comment]
I am unable to install the pkg TranslucentTB.appinstaller as it requires internet connection which i have blocked. Why would an offline app require internet connection? I find myself in the impossibility of installing TTB in the last 2 years since the rewrite.

**Comment by dongle-the-gadget** [comment]
> I am unable to install the pkg TranslucentTB.appinstaller as it requires internet connection which i have blocked. Why would an offline app require internet connection? I find myself in the impossibility of installing TTB in the last 2 years since the rewrite.

AppInstaller doesn't actually contain the app, it tells Windows the URL of the app to download, and also any dependencies that it needs to download and install. If you need a package that actually contains the app, use `bundle.msixbundle` (but it apparently fails if you don't have the necessary dependencies installed.)

**Comment by sylveon** [comment]
Portable mode is out

**Comment by SynapseScribe** [comment]
thank you !!!
