### ISSUE TITLE
Windows 11: TranslucentTB fails to deserialize JSON document because "the document is empty"

### ISSUE THREAD

**Issue by ghost** [TranslucentTB/TranslucentTB#601]
This happens randomly at a pc startup. When the TB system tray app loads I get a message saying that it fails to deserialize the JSON document and this causes my custom settings of the TTB to default back to plain transparent.

**Comment by sylveon** [comment]
This seems like a system issue - either Windows is giving us an empty file instead of the real thing at startup, or it's not saving changes correctly when the app saves settings at shutdown. I put mitigations for the latter in the code, but I wonder if they're not working correctly for you.

**Comment by sylveon** [comment]
Sorry, misclick

**Comment by ghost** [comment]
Maybe it is a force shut-down related issue. Ill see if this is what causes the issue.

UPDATE: In conclusion of trying to replicate the issue, it is true that the issue happens whenever a force/sudden shutdown occurs. At normal shutdowns (including restarts of course) my settings for TTB are loaded up and I do not get the error message. I sometimes do force shutdowns on occasions but never when I have an update or important thing going on.

**Comment by sylveon** [comment]
The new update should help with this issue.
