### ISSUE TITLE
Takes too much time to load after boot.

### ISSUE THREAD

**Issue by iammiraj** [TranslucentTB/TranslucentTB#602]
After I boot the device it takes time to change the taskbar. It's annoying. Is there any fix ?

Thanks in Advance.

**Comment by ninjaeon** [comment]
I started having this issue after installing "2022-04 Cumulative Update for Windows 11 for x64-based Systems (KB5012643)" on Windows 11.  Also takes minutes for TranslucentTB to startup when starting manually.

I have ExplorerPatcher 22000.613.44.1 also installed.

**Comment by ninjaeon** [comment]
The Windows 11 updates release on patch Tuesday May 10, 2022 resolved this issue for me.  There were four updates that day, so I don't know which one was responsible for the fix, but these are what I installed:

2022-05 Cumulative Update for Windows 11 for x64-based Systems (KB5013943)
2022-05 .NET 5.0.17 Security Update for x64 Client (KB5014329)
2022-05 .NET 6.0.5 Security Update for x64 Client (KB5014330)
2022-05 Cumulative Update for .NET Framework 3.5 and 4.8 for Windows 11 for x64 (KB5013628)

**Comment by Dhyfer1** [comment]
The same thing happens in the latest Dev build.

@sylveon Is there anything that can be done about it?

**Comment by imrozhkov** [comment]
![image](https://github.com/user-attachments/assets/b2899add-a4c3-4b69-bdfc-93fa93dc7677)
![image](https://github.com/user-attachments/assets/ba2cad4a-d154-4137-8b49-720459210cbd)

Same issue.

**Comment by sylveon** [comment]
Not a bug, this is due to explorer staggering the launch of startup apps to avoid overwhelming your computer. The more startup apps you have, the longer it'll take to start all of them.

Use something like EarlyStart to bypass this.

**Comment by Dhyfer1** [comment]
> Use something like EarlyStart to bypass this.

But you said before that translucenttb needs some updates to work properly with earlystart https://github.com/sylveon/EarlyStart/issues/4#issuecomment-1749968235 and earlystart has not received updates for 6 years! 😐
