### ISSUE TITLE
Translucenttb在win11最新系统上失效

### ISSUE THREAD

**Issue by 961120** [TranslucentTB/TranslucentTB#604]
![image](https://user-images.githubusercontent.com/85940528/165430231-5085d109-aea1-4ae6-98fe-2ae3fc6b6273.png)

**Comment by sylveon** [comment]
Duplicate of #537

**Comment by 961120** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 961120** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
