### ISSUE TITLE
Downloaded, Open, Doesn't Work

### ISSUE THREAD

**Issue by xpert777** [TranslucentTB/TranslucentTB#610]
I've had this issue for over 3 months now. I looked everywhere online and nobody had the same issue. I never realised that i can open a ticket in GitHub for the developers to see. I have no idea what the problem is but whenever it launches, the taskbar doesnt become clear. I made sure that everything is enabled and that it's set to clear but it doesnt work. I tried to delete it, restart my pc and download it again but that doesn;t work. I even did a clean install of my pc and it stil doesn;t work. I'm using Windows 11 22610.1

I used TranslucentTB before and i loved every second of it, nut its a shame that it just doesn't work for me anymore. I would greatly appreciate any help i can get in fixing this issue and going back to my clean taskbar. 

![Screenshot (1)](https://user-images.githubusercontent.com/83773714/170729772-b0aa7416-3e9c-46a8-96a6-6f0058178403.png)

**Comment by TalViloznyGrunitech** [comment]
> I've had this issue for over 3 months now. I looked everywhere online and nobody had the same issue. I never realised that i can open a ticket in GitHub for the developers to see. I have no idea what the problem is but whenever it launches, the taskbar doesnt become clear. I made sure that everything is enabled and that it's set to clear but it doesnt work. I tried to delete it, restart my pc and download it again but that doesn;t work. I even did a clean install of my pc and it stil doesn;t work. I'm using Windows 11 22610.1
> 
> I used TranslucentTB before and i loved every second of it, nut its a shame that it just doesn't work for me anymore. I would greatly appreciate any help i can get in fixing this issue and going back to my clean taskbar.
> 
> ![Screenshot (1)](https://user-images.githubusercontent.com/83773714/170729772-b0aa7416-3e9c-46a8-96a6-6f0058178403.png)

Same here. It doesn't really matter what you'll try to do. A certain windows 11 update made TranslucentTB and TaskbarX break. I thought it would get fixed by now but eh. I guess we gotta keep waiting

**Comment by xpert777** [comment]
I forgot to mention, I paid to get TaskBarX TOO, and it DOESN'T WORK EITHER. I can only hope that this gets fixed because I truly miss having a clean desktop. I'm currently in the middle of returning my PC to its custome state after the clean install.

**Comment by TalViloznyGrunitech** [comment]
> 

Did you read my reply? Both taskbarx and translucentTB are glitched because of this Windows 11 update. And for now we need to hope either translucentTB finds a work around. or taskbarx

**Comment by xpert777** [comment]
I read you're reply. I want to know if a fix is currently being worked on ir is this the end

**Comment by TalViloznyGrunitech** [comment]
> I read you're reply. I want to know if a fix is currently being worked on ir is this the end

I have no idea. For now I joined the TranslucentTB discord server to get updated if something happens. Here it is if you're interested: https://discord.com/invite/translucenttb

**Comment by sylveon** [comment]
This is an old build of Windows. The latest insider builds, and the latest stable build, do not exhibit this issue.
