### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by Arclight25** [TranslucentTB/TranslucentTB#614]
[X] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

Got an error in TTB upon booting up today. (never had an issue before) I uninstalled via the MS store, and downloaded the installer.  Got this error upon installing

_App installation failed with error message: An internal error occurred with error 0x800700B7. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x800700b7)_

**Comment by sylveon** [comment]
What error where you getting on boot? This error code also comes from Windows, so I would try rebooting and seeing if it helps/

**Comment by sylveon** [comment]
Closing for lack of reply
