### ISSUE TITLE
[Feature Request] Different configuration for a certain program

### ISSUE THREAD

**Issue by fe-aribeiro** [TranslucentTB/TranslucentTB#618]
It would be interesting to create a configuration that the user would pass the path of a specific .exe and then the TranslucentTB would ask which type of bar the user would want for that .exe

So when this specific .exe is maximized the configuration chosen for this .exe would override the default settings and change the taskbar

**Comment by sylveon** [comment]
This has already been implemented by https://github.com/TranslucentTB/TranslucentTB/pull/513, but is not released yet.
