### ISSUE TITLE
[Feature Request] I am not sure if possible but, can the time be adjustable to show seconds as well? example 9:16:20 AM ?

### ISSUE THREAD

**Issue by godswift** [TranslucentTB/TranslucentTB#627]
I know there are applications like elevenclock, but, it does not mix well to TTB, I get all sorts of visual placement problems.

**Comment by christianlewis21** [comment]
You can try [T-clock](https://github.com/White-Tiger/T-Clock).

**Comment by godswift** [comment]
apologies, i dont think this t-clock is compatible to windows 11, but
thanks

**Comment by sylveon** [comment]
This is a feature in the latest Windows 11 Insider Builds, and was out of scope of TTB.
