### ISSUE TITLE
Win 10 applications make Taskbar blurry

### ISSUE THREAD

**Issue by ChristianBDev** [TranslucentTB/TranslucentTB#628]
I had got translucentTB and when I have google chrome open or any application in borderless fullscreen mode, it is blurry like the picture below, when I make it not fullscreen borderless, it goes clear.

![image](https://user-images.githubusercontent.com/58433059/184270567-603d8a0b-99fa-4071-9942-54fb33b3623d.png)

**Comment by ChristianBDev** [comment]
left side is clear with no applications open and then the right is with the apps open

**Comment by sylveon** [comment]
That's the default settings. You can disable this by unchecking "enabled" under "maximized window".

**Comment by ChristianBDev** [comment]
how?

**Comment by sylveon** [comment]
Right-click on the tray icon and uncheck this (menu will look slightly different on 10): 
![image](https://user-images.githubusercontent.com/6440374/184988965-75de3f84-ad4e-472d-aa25-c9825688cd30.png)
