### ISSUE TITLE
Translucent TB - Error (Startup task failed to be enabled)

### ISSUE THREAD

**Issue by MrBull6425** [TranslucentTB/TranslucentTB#631]
After install and first run of Translucent TB an error message appears and says the following:

TranslucentTB has encountered an error. A request to enable the startup task did not result in it being enabled.

I am wondering if there is a solution to this issue. 
Thanks

[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: Box version 2.0

 - Steps to reproduce:
   1. Take the box.
   2. Put the box on the table.

 - Expected results: The box sits on the table.

 - Actual results: The box disappears spontaneously once
   put on the table.

 - Other: The box I ordered was damaged.

**Comment by sylveon** [comment]
Set the following registry keys in `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System`

```
"EnableFullTrustStartupTasks"=dword:00000002
"EnableUwpStartupTasks"=dword:00000002
"SupportFullTrustStartupTasks"=dword:00000001
"SupportUwpStartupTasks"=dword:00000001
```

Normally they should be set and allow TranslucentTB to normally start, but some "debloaters" remove them...

**Comment by MrBull6425** [comment]
Sorry, bit new to doing what you mentioned. How exactly do I need to do this @sylveon?

**Comment by sylveon** [comment]
Open the registry editor, and navigate to the key I specified. Make sure all of these values exist and are set to the the appropriate numbers
