### ISSUE TITLE
TB is running but not changing taskbar to clear. or change taskbar at all.

### ISSUE THREAD

**Issue by ghost** [TranslucentTB/TranslucentTB#632]
[] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: Box version 2.0

 - Steps to reproduce:
   1. Take the box.
   2. Put the box on the table.

 - Expected results: The box sits on the table.
 - clear taskbar

 - Actual results: T.
normal taskbar

 - Other: The box I ordered was damaged.
![Imported_2022_08_21_12_13_33](https://user-images.githubusercontent.com/110556802/185784199-7d3b83c5-bd59-4f61-b0dd-4109968e2b52.png)

**Comment by sylveon** [comment]
Please fill the issue template
