### ISSUE TITLE
The "Blur" effect doesn't work in WIN11 ver22621.382

### ISSUE THREAD

**Issue by Ptilopsis01** [TranslucentTB/TranslucentTB#634]
As the title said, the blur effect doesn't work in win11 22621.382 (it's just a black bar when turned on), but other effects all work normally.
So I'm not sure whether it is the same bug with #537

**Comment by sylveon** [comment]
Blur was broken by this Insider build. Next update of TTB will remove this option

**Comment by Ptilopsis01** [comment]
> Blur was broken by this Insider build. Next update of TTB will remove this option
what a pity
thx for answering
