### ISSUE TITLE
Blur option not available Windows 11 stable

### ISSUE THREAD

**Issue by nicholasprins** [TranslucentTB/TranslucentTB#636]
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: Box version 2.0

 - Steps to reproduce:
   1. Take the box.
   2. Put the box on the table.

 - Expected results: The box sits on the table.

 - Actual results: The box disappears spontaneously once
   put on the table.

 - Other: The box I ordered was damaged.

**Comment by sylveon** [comment]
This is intentional and expected, MS broke blur on Windows 11.

**Comment by nicholasprins** [comment]
The blur does work for a while now actually, I've changed the desktop theme
to blur via the settings json file and it works, only issue is that i
cannot change the blur value (transparency/opaqueness) from the file like
in windows 10, i don't remember the code snippet

**Comment by sylveon** [comment]
The blur was broken again in 22621.
