### ISSUE TITLE
Taskbar loses clear state when switching active screens

### ISSUE THREAD

**Issue by ghost** [TranslucentTB/TranslucentTB#637]
I am using Windows 11 and I run my PC in a setup where I run 2 monitors usually, with the 3rd disabled (it's a TV) when it's off but when I turn it on thanks to Windows 11 being smarter after I set it up it will auto disable the 2 monitors and use the TV only and vice versa when turning the TV off. 

Onto the problem, when I switch between using these different screens the taskbar is refreshed partially it seems because it loses my Desktop Clear option I have set in this software (might also affect Acrylic etc?) and it's no longer clear unless I manage go into the software and use the reset dynamic state option. 

Is it possible to have this option trigger itself automatically when it detects the screens have changed

**Comment by nopeless** [comment]
Having same exact issue

**Comment by sylveon** [comment]
The new update should help with this issue.

**Comment by MrVonkey** [comment]
Unfortunately, the new update did not help in my case in this regard (Windows 11, first monitor display port, second monitor HDMI). The issue was fixed for me with the Azure pipeline build 2021.5.97 until one of the last Windows updates was rolled out. Now I have to hit "Reset dynamic state" again whenever the second monitor is turned on.

**Comment by ghost** [comment]
Only partially fixed for me and also introduces a new bug. I run 2 monitors as my main setup then when I turn the tv on it swaps to only using the TV (as intended) and the reset dynamic state doesn't work here. When I turn tv off to go back to my monitors the reseting of dynamic state partially works, see the second monitor will have it's state reset but the main monitor won't. 

Interestingly this creates a bug as well, when I have a fullscreen application on the main monitor the task bar on the second monitor acts like it does on the main by thinking there's a 'maximized window' on the secondary monitor when it's actually just on the desktop so it should be using the 'desktop' settings. 

Running the reset dyanmic state manually fixes this little bug but yeah in general hasn't solved it.
