### ISSUE TITLE
Still seeing taskbar line in 2021.5.0.0

### ISSUE THREAD

**Issue by Xalaxis** [TranslucentTB/TranslucentTB#638]
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

I think I'm still seeing the behavior described in #425 in the latest version of TTB.

![image](https://user-images.githubusercontent.com/12937964/186982239-603a2d75-58b9-4532-9635-e5f26e1b6985.png)
![image](https://user-images.githubusercontent.com/12937964/186982021-cd56a0e6-dc5c-4c71-a8ac-c128e04e4c1e.png)
![image](https://user-images.githubusercontent.com/12937964/186982039-b3c3ce17-ea59-4256-9142-b97e7eaa8825.png)

**Comment by sylveon** [comment]
Fix has not been released yet

**Comment by Xalaxis** [comment]
> Fix has not been released yet

Ah, my bad, I saw the issue was closed.

**Comment by TheShark27** [comment]
> Fix has not been released yet

Hi, will the fix remove the line from the clear preset alone or also the others?

**Comment by sylveon** [comment]
It's a per state option

![image](https://user-images.githubusercontent.com/6440374/191855949-7757f7af-761b-425f-9572-291298f58abc.png)

**Comment by TheShark27** [comment]
> It's a per state option

Fantastic, thank you!
