### ISSUE TITLE
When I press the ⊞ (windows) key on windows 11 clear taskbar changes to normal taskbar and looks buggy

### ISSUE THREAD

**Issue by 09kmrz** [TranslucentTB/TranslucentTB#639]
It looks like normal taskbar when I press ⊞ key on keyboard with a little space that‘s left clear on the right. Overall, it looks buggy and unsmooth.

**Comment by 09kmrz** [comment]
![Uploading CC800EFF-F566-4102-A6AB-7BF6972FAD4B.png…]()

**Comment by 09kmrz** [comment]
![Uploading 56BD0985-CF28-4535-B395-8C77B25BA727.jpeg…]()

**Comment by sylveon** [comment]
Should work in 2023.1
