### ISSUE TITLE
Add custom taskbar state for Dynamic States

### ISSUE THREAD

**Issue by denosawr** [TranslucentTB/TranslucentTB#64]
Add an option like `--dynamic-ws RESET` or `--dynamic-ws BLUR` so that when a window is maximised (or start menu is open), the specified taskbar state will be applied. I propose:
```
NORMAL: reset to normal Windows taskbar state
BLUR: blur. Same as ACCENT_ENABLE_BLURBEHIND.
CLEAR: transparent. Same as ACCENT_ENABLE_TRANSPARENTGRADIENT.
OPAQUE: completely opaque with specified gradient. Same as ACCENT_ENABLE_GRADIENT.
```

**Comment by ethanhs** [comment]
I like this idea, but I think the RESET should be named "normal" the other names should be the same as the context menu (transparent should be clear instead) opaque is fine by me.

**Comment by denosawr** [comment]
Yes, that is a good idea.

**Comment by charlesmilette** [comment]
Ideally there would be two settings set: One for maximised and one for regular, so the user could have full control on `dynamic-ws`'s behavior.

**Comment by denosawr** [comment]
Yep. So, `TranslucentTB --blur --dynamic-ws normal` would be blurred with no window maximised and Windows default when a window is maximised.

**Comment by denosawr** [comment]
Implemented in https://github.com/TranslucentTB/TranslucentTB/commit/3618f9b58adf6308e68cbaef748a713f60803642. It is yet to be properly tested and merged to `develop` though.
