### ISSUE TITLE
No Blur second monitor

### ISSUE THREAD

**Issue by Jacrispys** [TranslucentTB/TranslucentTB#640]
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: 2021.5

 - Expected results: Second monitor taskbar doesn't "blur" when application maximised/visible window.

 - Actual results: The main monitor taskbar blurs but the second monitor remains 100% transparent.

**Comment by sylveon** [comment]
The new update should help with this issue.
