### ISSUE TITLE
Issue: Taskbar bugging (completely changes back to normal for a second, and then going back to clear state. Also uninstalling translucenttb while in clear state, and then not going back in normal state again.)

### ISSUE THREAD

**Issue by justanordinaryperson999** [TranslucentTB/TranslucentTB#642]
![image](https://user-images.githubusercontent.com/113168872/189298488-1fdb0fab-b77c-4b5b-a9d3-a7337bf852c7.png)

Hello, im looking for a solution which helps my windows 11 taskbar back to normal.
as u can see in the photo, this shows my taskbar in clear state while translucenttb is not opened.
I accidentally uninstaled translucenttb while cleaning my laptop, it wont go back to normal, i was finding solutions on how to fix it but nothing. Also i cant reset my laptop. it has valuable things here that cant be backed up. I would be so happy if someone would respond to this. Im using a detachable 2 in 1 laptop Lenovo Ideapad d330 10igl.
I will just wait and find any solutions here.

**Comment by sylveon** [comment]
Try restarting

**Comment by justanordinaryperson999** [comment]
Sylveon thanks for helping but I figured it out. I have a system restore which I used now and its still not fixed. But I restarted windows explorer several times and it came back to normal.
