### ISSUE TITLE
No "Blur" and "Fleunt" modes

### ISSUE THREAD

**Issue by ErisonNull** [TranslucentTB/TranslucentTB#643]
Also "Acrylic" just turns my taskbar black.
[] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.
 - Version information: 2021.5.0.0
 - Windows edition: 11

**Comment by nopeless** [comment]
acrylic will appear black if

- Your computer is on battery saver
- Windows deems your hardware incapable of acrylic effects

Can you check for these two possiblities?

**Comment by ErisonNull** [comment]
> acrylic will appear black if
> 
>     * Your computer is on battery saver
> 
>     * Windows deems your hardware incapable of acrylic effects
> 
> 
> Can you check for these two possiblities?

how?

**Comment by nopeless** [comment]
> > acrylic will appear black if
> > 
> >     * Your computer is on battery saver
> > 
> >     * Windows deems your hardware incapable of acrylic effects
> > 
> > 
> > Can you check for these two possiblities?
> 
> how?

Check whether your computer is on battery saver

Is your computer a potato

@ErisonNull

**Comment by ErisonNull** [comment]
> > > acrylic will appear black if
> > > ```
> > > * Your computer is on battery saver
> > > 
> > > * Windows deems your hardware incapable of acrylic effects
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Can you check for these two possiblities?
> > 
> > 
> > how?
> 
> Check whether your computer is on battery saver
> 
> Is your computer a potato
> 
> @ErisonNull

1. did you think power plan? no
2. no i think

**Comment by nopeless** [comment]
I'm out of ideas :/

Do other acrylic effects work for you? If so, then its most likely that there is some kind of bug in the code

**Comment by TheShark27** [comment]
> I'm out of ideas :/
> 
> Do other acrylic effects work for you? If so, then its most likely that there is some kind of bug in the code

I have the same issue with an RTX 2060. Definitely a bug.

**Comment by JasonJasu** [comment]
this might be late but turning on transparency effects on windows 11 personalization setting worked for me.
![image](https://user-images.githubusercontent.com/48150396/194427380-d14bcbf6-d5a5-4371-8261-1caa06d5cf2d.png)
worth a try

**Comment by ErisonNull** [comment]
> this might be late but turning on transparency effects on windows 11 personalization setting worked for me. ![image](https://user-images.githubusercontent.com/48150396/194427380-d14bcbf6-d5a5-4371-8261-1caa06d5cf2d.png) worth a try

THANK YOU VERY MUCH! IT WORKED

**Comment by ErisonNull** [comment]
but i still get no blur and fluent modes :(((

**Comment by ErisonNull** [comment]
i can set blur mode through settings.json, but not fluent. but, i don't need it. thanks for helping me!

**Comment by sylveon** [comment]
Fluent got renamed to acrylic, blur is removed because it's broken in the OS

**Comment by ErisonNull** [comment]
> blur is removed because it's broken in the OS

i don't think so, it works perfectly for me

**Comment by sylveon** [comment]
It could lead to heavy lagging in Windows 11 RTM when dragging a window (this was fixed with a KB but it was not worth updating the program due to confusion - some people would see the option, others wouldn't), and in 22621 it outright just renders as a black background.

**Comment by ErisonNull** [comment]
> It could lead to heavy lagging in Windows 11 RTM when dragging a window (this was fixed with a KB but it was not worth updating the program due to confusion - some people would see the option, others wouldn't), and in 22621 it outright just renders as a black background.

i have 22000.1098, so i think it does work for me
