### ISSUE TITLE
White line in windows 11 22H2

### ISSUE THREAD

**Issue by Zanoxxx** [TranslucentTB/TranslucentTB#648]
![unknown](https://user-images.githubusercontent.com/102561837/192160330-697ce323-e48a-49ac-aaa0-7602af387697.png)

**Comment by sylveon** [comment]
Duplicate of #425

**Comment by DexterzGretege** [comment]
Just install RoundedTB from Windows Store and Under Advanced Options select TranslucentTb Compatibility. It should fix the issue. I had the same issue after updating to Win 11 Version 22H2 and after doing the above it was fixed instantly.
