### ISSUE TITLE
White line in windows 11 update 22H2

### ISSUE THREAD

**Issue by Zanoxxx** [TranslucentTB/TranslucentTB#649]
![unknown](https://user-images.githubusercontent.com/102561837/192264437-d0580d56-44dd-46fa-b4a1-5d710781315d.png)

**Comment by Zanoxxx** [comment]
duplicate again sorry

**Comment by Zanoxxx** [comment]
Duplicate of https://github.com/TranslucentTB/TranslucentTB/issues/425

**Comment by DexterzGretege** [comment]
Just install RoundedTB from Windows Store and Under Advanced Options select TranslucentTb Compatibility. It should fix the issue. I had the same issue after updating to Win 11 Version 22H2 and after doing the above it was fixed instantly.
