### ISSUE TITLE
Taskbar bottom renders clear in Blurred mode

### ISSUE THREAD

**Issue by ethanhs** [TranslucentTB/TranslucentTB#65]
![yby4gja](https://cloud.githubusercontent.com/assets/9504279/26031962/0d89922a-383b-11e7-8c5d-ccf08a63447a.png)

As reported by Aton_Freson on Discord.

I am currently not sure what would cause this issue. More investigation needed.

**Comment by charlesmilette** [comment]
I too began to experience this issue but only when the taskbar overlaps a window:
![image](https://cloud.githubusercontent.com/assets/6440374/26763663/7cfbd196-4924-11e7-9133-55d7b617225d.png)

**Comment by ethanhs** [comment]
I don't really see how we can fix this sadly, but I will leave it open.
