### ISSUE TITLE
línea negra al aplicar el efecto transparencia en Windows 11.

### ISSUE THREAD

**Issue by TEOACV** [TranslucentTB/TranslucentTB#657]
![Captura de pantalla 2022-10-04 160737](https://user-images.githubusercontent.com/115046839/193941974-81776066-d71a-4abb-8b3f-3a59b36e466c.png)
saludos, la aplicación translucentTB no funciona bien en Windows 11, debido a que se queda una línea negra al aplicar la transparencia.

**Comment by sylveon** [comment]
Duplicate of #425
