### ISSUE TITLE
Windows 11 Update Version 22H2, Taskbar Unhidable Line Issue

### ISSUE THREAD

**Issue by 7krai** [TranslucentTB/TranslucentTB#658]
After the Windows 11 Updated to 22H2, the taskbar now has a visible line on top of it which TrunslucentTB can't hide anymore in "Clear" option.  [here is how it looks like](https://ibb.co/tpKZbzf)

**Comment by tomzappala** [comment]
Same. Eager for a fix.

**Comment by sylveon** [comment]
Duplicate of #425
