### ISSUE TITLE
Top line of taskbar not translucent after updating to Windows 11 22H2

### ISSUE THREAD

**Issue by Jaage** [TranslucentTB/TranslucentTB#660]
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: Box version 2.0

 - Steps to reproduce:
   1. Start TranslucentTB

 - Expected results: The line at the top of the taskbar should be translucent.

 - Actual results: Only the body of the taskbar and not the top line 
 - becomes translucent, resulting in a constant grey line.

**Comment by sylveon** [comment]
Duplicate of #425
