### ISSUE TITLE
any options other than clear or normal do not work

### ISSUE THREAD

**Issue by Frenchy-AU** [TranslucentTB/TranslucentTB#662]
recently upgraded to windows 11 Pro 22H2, and app seems to be bugged, as title says only the clear and normal options work, blue, acrylic all seem to not function and make the task bar pitch black

**Comment by bbilginerdem** [comment]
I am using version 10.0.25217 Build 25217 and none of it works, unfortunately.  Only coloring works. I suppose the changes windows made conflict with what is used in the app

**Comment by sylveon** [comment]
Your issue is #537

**Comment by dnullptr** [comment]
second this, on W11 Insider build 25217 it doesn't seem to work.
Of course also with the new experimental azure jobs builds.

I Love your work so so much!
