### ISSUE TITLE
Translucent TB completely broken with windows insider build 22H2 22623.746

### ISSUE THREAD

**Issue by raptor1820** [TranslucentTB/TranslucentTB#668]
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

Translucent TB version 2021.5.0.0

Steps to reproduce:
Enable flighting the in the Beta Channel and install insider build 22623.746

Description :  TranslucentTB completely breaks. None of the options present in the application work.  Only the default black windows taskbar is shown. 

Remarks: I believe this issue is due to the taskbar changes in the recent insider build.  
Link to the changes in the insider build:  https://blogs.windows.com/windows-insider/2022/10/13/announcing-windows-11-insider-preview-build-22621-746-and-22623-746/

They are:
1. Changes to taskbar for tablet optimization 
2. Updated UI for the System tray.

**Comment by sylveon** [comment]
Duplicate of #537
