### ISSUE TITLE
在Windows 11 Insider Preview 10.0.25217.1010 版本的任务栏透明工具失效

### ISSUE THREAD

**Issue by Zhenxir** [TranslucentTB/TranslucentTB#669]

**Comment by Zhenxir** [comment]
现在的版本已经更新至
Windows 11 Insider Preview 25227.1000 (rs_prerelease)

在其及以上的版本中，TranslucentTB的透明任务栏仍然失效。
目前任务栏显示为默认任务栏效果，没有任何加成。

![image](https://user-images.githubusercontent.com/88704538/196870319-48f963b9-9082-44f7-b04d-067179e2f35a.png)

**Comment by simear2004** [comment]
22623.746上同样失效了

**Comment by Zhenxir** [comment]
> 22623.746上同样失效了

![image](https://user-images.githubusercontent.com/88704538/196878941-d8150e71-eee5-4669-aec7-b8c5e42fb4c1.png)

_**EN：**_
In the version of Windows I've used, TranslucentTB in the system versions listed above could work.
But when I upgraded Windows 11 Insider Preview 10.0.25217.1010 yesterday, TranslucentTB didn't work.

**_SC：_**
在我使用过的Windows版本中，以上列举出的系统版本中的TranslucentTB均未失效。
但当我昨天升级Windows 11 Insider Preview 10.0.25217.1010之后，TranslucentTB才出现失效问题。

**Comment by sylveon** [comment]
Duplicate of #537
