### ISSUE TITLE
clear or blur BUG

### ISSUE THREAD

**Issue by v253626452** [TranslucentTB/TranslucentTB#67]
I set clear, but each reboot will become blur.

**Comment by denosawr** [comment]
Launch the program with the `--clear` option. Assuming that you have a shortcut to TTB in your Startup folder, right-click and select Properties, and type `--clear` at the end of the Target field.
![image](https://cloud.githubusercontent.com/assets/20185977/26280530/c2ef428e-3e0a-11e7-8555-473975f6b664.png)
