### ISSUE TITLE
App don't restart after sleep mode

### ISSUE THREAD

**Issue by PietroD-lab** [TranslucentTB/TranslucentTB#671]
Hello everybody,
as object, translucent TB does not start after I wake up pc from sleep. I've enabled all background processes without result; I also tried to reinstall the app and create a routine with task scheduler but starting the app from its executable doesn't work, only start when lunch from the search bar. 
Rounded TB had the same problem but with task scheduler I solved it. Anyone have any ideas?

Windows 11 version 22H2 build 22621.674
App ver. 2021.5.0.0

Executable path: C:\Program Files\WindowsApps\28017CharlesMilette.TranslucentTB_2021.5.0.0_x64__v826wp6bftszj\TranslucentTB.exe

**Comment by DannyCtinescu** [comment]
Hi,
Translucent doesn't start at all after the upgrade to windows 11 insider 25227. 
Thanks.
Dan

**Comment by sylveon** [comment]
The new update should help with this issue.
