### ISSUE TITLE
Problem with Windows 11 22H2 Insider version

### ISSUE THREAD

**Issue by Keymetal** [TranslucentTB/TranslucentTB#674]
Hi!
Translucent doesn't work with Windows 11 22H2 Insider version.

My Windows 11 version is:

Edizione	Windows 11 Home
Versione	22H2
Build sistema operativo	22623.870
Esperienza	Windows Feature Experience Pack 1000.22636.1000.0

**Comment by sylveon** [comment]
Duplicate of #537
