### ISSUE TITLE
TranslucentTB not displaying pop up menu, essentially broken

### ISSUE THREAD

**Issue by tpmeader** [TranslucentTB/TranslucentTB#676]
So, I am had checked the tracker a couple days ago and I didn't see any mention, but I write this after that so I am not sure and I apologize if it has already been discussed and or fixed. But The latest Dev build has seemed to break the application on all of my computers. I have four HP's, an ASUS and a Lenovo. The context menu will not display at all from the system tray and if I try to open it from the start menu, it just tells me it is already running and lives in the system tray. I have tried uninstalling and reinstalling, repairing, and resetting to no avail. Any help would be welcome. Thank You.

[] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: Box version 2.0

 - Steps to reproduce:
   1. Take the box.
   2. Put the box on the table.

 - Expected results: The box sits on the table.

 - Actual results: The box disappears spontaneously once
   put on the table.

 - Other: The box I ordered was damaged.

**Comment by ifermi** [comment]
me too

**Comment by sylveon** [comment]
I cannot repro on build 25236

**Comment by Hepi34** [comment]
same here on build 22623.875

**Comment by Migod11** [comment]
Same on build 22623.875

**Comment by Migod11** [comment]
Windows Build 22623.885 restores the menu, but transparency effects do no work

**Comment by sylveon** [comment]
#537 

As a rule of thumb, stop using Insider builds if you want things to work :)
