### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by gagisu** [TranslucentTB/TranslucentTB#677]
I downloaded Translucent TB and not working. I tried deleting and reinstalling the app several times  and it didnt work. I dont really remember if this started after an update on windows. I am using this version of windows

Windows 11 Pro
Version	22H2 
Installed on	‎9.‎11.‎2022.
OS build	22623.885
Experience	Windows Feature Experience Pack 1000.22637.1000.0

**Comment by sylveon** [comment]
Duplicate of #537
