### ISSUE TITLE
wont open on boot

### ISSUE THREAD

**Issue by iodly** [TranslucentTB/TranslucentTB#679]
![Screenshot_1](https://user-images.githubusercontent.com/117858846/200919940-ea61c242-2fbd-4a7d-aae2-2e4dae13e918.png)

as you can see, the open at boot feature is greyed out and i cant activate it, tryed to reinstall and didnt helped even a bit so idk what to do, i want it back to open at boot automatically :((

**Comment by twxxle** [comment]
I have the same issue, can you tell me how you fixed it?

**Comment by sylveon** [comment]
Import the following reg file in the registry:
```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System]
"EnableFullTrustStartupTasks"=dword:00000002
"EnableUwpStartupTasks"=dword:00000002
"SupportFullTrustStartupTasks"=dword:00000001
"SupportUwpStartupTasks"=dword:00000001
```

**Comment by Zoopiter0** [comment]
hey @sylveon  I have absolutely no clue how to code and I just got this account to ask where and how im supposed to paste this in since its the only solution I have found to my TranslucentTB not opening up on startup

**Comment by sylveon** [comment]
- Open a new notepad window
- Put the snippet above in it
- Save the file. In the save as dialog box, set "Save as type" to "All files (\*.\*)" first, then the filename to `startup.reg` second.
- Double click the file, accept the UAC prompt.
- Click yes on the prompt to merge the file with the registry.
- Reboot

**Comment by Zoopiter0** [comment]
It worked, thanks for the quick response and great app!
