### ISSUE TITLE
translucent tb is not working

### ISSUE THREAD

**Issue by taki0786** [TranslucentTB/TranslucentTB#683]
my translucent tb is not working please help me

**Comment by sylveon** [comment]
Are you on Insider builds?

**Comment by Arclight25** [comment]
Same here.  No right click menu appears.

**Comment by sylveon** [comment]
Are you on insider builds

**Comment by Arclight25** [comment]
I am.  Ugh.  Forgot about that.  I assume that is the issue?

**Comment by sylveon** [comment]
Yes, see #537

**Comment by Arclight25** [comment]
OK.  Thank you for the prompt reply and your work on this app.  Will have to unenroll this computer in the insider program so I can utilize this. :)
