### ISSUE TITLE
How to change application language?

### ISSUE THREAD

**Issue by YoriMirus** [TranslucentTB/TranslucentTB#688]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Install TranslucentTB from the Microsoft store.

### Expected results

Application should be in my system language (Czech) or English if Czech is not supported.

### Actual results

Application is in Japanese.

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

Is there a way for me to change the language through the settings.json file or other way? Microsoft store seems to be installing the app in Japanese and I can't figure out how to fix it.

I do have a japanese keyboard layout and non-unicode characterset application support set to Japanese but setting that back to Czech does not fix anything.

Issue [https://github.com/TranslucentTB/TranslucentTB/issues/343](url) does not help me as I'm already installing the application through the correct source.

**Comment by sylveon** [comment]
This is unfortunately intentional behavior from the OS. The "language and region" page explicitly points this out:
![image](https://user-images.githubusercontent.com/6440374/205079769-7ed32011-b3b2-4ed7-9821-0f9418819618.png)

**Comment by YoriMirus** [comment]
Ohhh I see, if TranslucentTB does not support the Czech language it falls back to Japanese?
<img width="349" alt="image" src="https://user-images.githubusercontent.com/66534752/205095535-6f36a347-f2e1-4dc1-a84c-ff37e3cd99d4.png">

I hope there is a way to have a prefered language without having a keyboard layout for it then. I don't need an English keyboard layout.

Seems like adding english to my language list worked though. Thanks!

**Comment by sylveon** [comment]
FWIW I'm thinking of adding a way in the config file to set [PrimaryLanguageOverride](https://learn.microsoft.com/en-us/uwp/api/windows.globalization.applicationlanguages.primarylanguageoverride?view=winrt-22621) which would let you override the language to "en-US" in the future.
