### ISSUE TITLE
[feature request] apply to the trays area 

### ISSUE THREAD

**Issue by EMLVIRUS** [TranslucentTB/TranslucentTB#69]
![image](https://cloud.githubusercontent.com/assets/16912240/26757628/afa571ea-48f4-11e7-8dc4-2d5dbb2e2672.png)

make the `clear` or `blur` effect effective on trays area as well. Apply for admin right if necessary.

**Comment by ethanhs** [comment]
this is a duplicate of #56

**Comment by EMLVIRUS** [comment]
seems so. Sorry about that.

**Comment by ethanhs** [comment]
No worries! I'd really like to get it to run on that.
