### ISSUE TITLE
How to make Taskbar symbols/icons bigger and reduce space gap between them?

### ISSUE THREAD

**Issue by pstein** [TranslucentTB/TranslucentTB#692]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

As you may know there is another Taskbar configuration tool 7+ Taskbar Tweaker
freely available from 

https://ramensoftware.com/7-taskbar-tweaker#download

This tool allows to make all the symbols/icons in Taskbar bigger and reduce the space gap between them.

How can I achieve this with TranslucentTB?

Have a look of the below attached partial snapshot a TaskBar configured with 7+ Taskbar Tweaker 

If this is currently not possible: Could you add these features int the next release?

![Snapshot Taskbar 7+ Taskbar Tweaker](https://user-images.githubusercontent.com/2775875/205249235-03da4b39-4b44-42e4-8ec5-f22af21bc65a.png)

### Expected results

See above

### Actual results

See above

### Windows version

Windows 10 2004-22H2 (builds 19041-19045)

**Comment by sylveon** [comment]
This is not something TranslucentTB can do - however you can combine both tools together without problem.
