### ISSUE TITLE
Is there a way to make the app make my taskbar translucent instantly upon starting my pc? There's like a 5-8 second delay. Windows 11 pro

### ISSUE THREAD

**Issue by darkwolf57** [TranslucentTB/TranslucentTB#696]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Starting up windows. 

### Expected results

Taskbar isn't translucent until 5 seconds after starting up my pc. Is there a way to make it translucent right away.

### Actual results

Taskbar is translucent after 5 seconds. 

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

**Comment by theoqrz** [comment]
I thought this was the normal behaviour of the app because I've had it like that since windows 10 maybe 2 years ago. I got used to just wait 4 or 5 seconds after starting.

**Comment by sylveon** [comment]
This is normal windows behavior. All startup apps are started after a short amount of time to avoid bringing the system down to a crawl. There are tools like https://github.com/sylveon/EarlyStart that can make this faster
