### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Yashwanthramka** [TranslucentTB/TranslucentTB#697]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Right click

### Expected results

Wanted the context menu but its not even showing up

### Actual results

Context menu not showing up after rightclick. But TB service is running

### Windows version

Windows 10 May/November 2019 Update (builds 18362 and 18363)

### Other details

Context menu not showing up after rightclick. But TB service is running

### Relevant log output

```shell
Logs are empty
```

**Comment by sylveon** [comment]
Are you on windows 11 insider builds?

**Comment by Yashwanthramka** [comment]
Yes

**Comment by sylveon** [comment]
Duplicate of #537
