### ISSUE TITLE
[Bug]: Taskbar border sometimes won't disappear

### ISSUE THREAD

**Issue by theoqrz** [TranslucentTB/TranslucentTB#699]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

1. Set "desktop" to Clear and uncheck "show taskbar border".
2. Set "maximized window" to Acrylic and select "show taskbar border".
3. Set "start opened" to Acrylic and select "show taskbar border".
4. Minimize all windows and open the Start menu.

### Expected results

When closing the start menu the bar should change to the Clear state without the border.

### Actual results

Sometimes (I would say it happens 35~40% of the times) after closing the start menu the bar goes invisible but the white line border stays and the only way to clear that is opening a maximized window and minimize again.

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

I'm using the last version 2022.1 for 3 days now and have been doing some tests but can't seem to know how to fix this. Sorry if this is already a known issue.

**Comment by Zahir-Khan** [comment]
I have not been able to reproduce this bug consistently but it happens to me often. Its not just the border but the clear settings also doesn't work. The only way to fix it is to quit and restart.

**Comment by Zahir-Khan** [comment]
It seems to me the tb app is not able to apply the taskbar settings again after using an app in full screen. I am also using the wallpaper engine so there may be some incompatibilities. I also use Dual monitors and frequently change screens etc.

**Comment by sylveon** [comment]
Should be fixed in 2023.1
