### ISSUE TITLE
update checking

### ISSUE THREAD

**Issue by Rictusempra** [TranslucentTB/TranslucentTB#70]
add ability to check for update.
at least the exe should post a warning when a version is available

**Comment by charlesmilette** [comment]
we will either have to look for a C++ web library or a small update stub in a better language for web downloads (I'm thinking about putting this on the windows store so this could work too)

Also a nightly and stable channel would be neat

**Comment by denosawr** [comment]
I think the Windows Store would be a great idea. It takes care of updates for us, and _could_ help visibility (if it becomes big enough).

**Comment by EMLVIRUS** [comment]
> Windows Store would be a great idea

Are you suggesting to wrap a Win32 exe or rewrite your app into a new framework

**Comment by denosawr** [comment]
There's the Desktop App Converter, which might work. It is yet to be tested on TTB, though: https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-run-desktop-app-converter

**Comment by charlesmilette** [comment]
Wrap the WIN32 exe, the UWP app model too much sandboxed for what we do.

I already passed the centennial approval program. Only thing we would have to do:
- [ ] Complete savefiles
- [ ] Color picker
- [ ] Opacity picker
- [ ] Blacklist picker
- [ ] A few changes related to auto-startup to make it work (something like [this](https://github.com/charlesmilette/CentennialStartupHelper), which could also benefit a few improvements in the way)
- [ ] Automate packaging the APPX (quite easy actually - documented [here](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-packaging-dot-net))
- [ ] Write a description
- [ ] Screenshots

I am in the process of making my own app approved, so I could do checks 5 and 6.

This could also be an occasion to reach Windows 10 S users.

**Comment by ethanhs** [comment]
Im cautious about putting it in the Window store, as I am pretty sure we would break sandbox and a dozen other requirements. But I do think an update mechanism would be nice. I am thinking cURL would be good enough for what we are doing, but I want to look into other options.

**Comment by denosawr** [comment]
cURL? That's not built into Windows... You'd have to bundle it with the executable.

**Comment by ethanhs** [comment]
It could be linked in. But then again things could get complicated 🤷‍♂️

**Comment by charlesmilette** [comment]
What we are doing doesn't breaks the sandbox. Heck mine just bypasses a
Microsoft limitation and it got through. The only "real" requirements is
not to leave too much stuff behind and be able to run on a clean windows
install

**Comment by ethanhs** [comment]
>bypasses a Microsoft limitation

Tell me more?

Also I am concerned about depending on MS to release our program. I would feel better with parallel releases here and through the Windows store, but I am concerned that MS could argue that our app doesn't fit in the Windows Store and it will disappear.

**Comment by denosawr** [comment]
I was thinking along the lines of parallel releases, where we'd let the Store handle auto-updates.

**Comment by charlesmilette** [comment]
Yes ofc, parallels release it is for my app too.

It's [SearchWithMyBrowser](https://github.com/charlesmilette/SearchWithMyBrowser). Allows to open Cortana search results in something else than Edge.

**Comment by HarshaThota** [comment]
If you are OK with an external dependency, look into [Squirrel](https://github.com/Squirrel/Squirrel.Windows).

**Comment by denosawr** [comment]
I think that using an external library would be a last resort; the team are certainly leaning towards a Windows Store release for the time being. If the application is for some reason rejected from the store or it is not compatible, Squirrel looks really neat, and the seamless updates seem much nicer than an update dialog used by something like WinSparkle. Thanks! @HarshaThota

**Comment by Rictusempra** [comment]
Hey, any release schedule on uwp version now?

**Comment by denosawr** [comment]
Heya! Thanks for your interest in TranslucentTB. Unfortunately, the developers (including me) are occupied with other things, and development has slowed significantly (most code is being written by sylveon, in the `store` branch). That means that we don't have an ETA for release, unfortunately, and it may be a while before the version is released.

**Comment by sylveon** [comment]
Due to me being given free reign over the code in the `store` branch, I'm removing a lot of obsolete stuff, moving and refactoring code around, making it better and easier to use.

While a lot of progress as been done, there are still other things to implement and fix. I'll release when I think it is ready.

<sup>PRs of course are welcome.<sup>

**Comment by denosawr** [comment]
This issue should, for all intents and purposes, be finished. The final verdict is that we will be running parallel releases; TranslucentTB will be released to the Microsoft Store and also releases will be submitted through GitHub Releases as usual. Thank you all for your suggestions.
