### ISSUE TITLE
[Bug]: Windows 11 context menu on Windows 10

### ISSUE THREAD

**Issue by lotawek** [TranslucentTB/TranslucentTB#705]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Open TranslucentTB from tray.

### Expected results

Windows 10 context menu.

### Actual results

Windows 11 context menu on Windows 10

### Windows version

Windows 10 2004-22H2 (builds 19041-19045)

**Comment by lotawek** [comment]
![image](https://user-images.githubusercontent.com/120841882/208268011-4bcbab70-db9f-4e47-9725-b5efe4a53ec5.png)
![image](https://user-images.githubusercontent.com/120841882/208268012-a177e24e-da59-444d-8b03-476eede2af1e.png)

**Comment by sylveon** [comment]
This is a UWP context menu. You can see the same context menu in other UWP apps using WinUI 2.7 and newer even on Windows 10.

**Comment by lotawek** [comment]
any way to change them to the old look?

**Comment by sylveon** [comment]
Not at the moment

**Comment by sylveon** [comment]
You can disable this in 2023.1

**Comment by rollingmoai** [comment]
@sylveon I don't see 2023.1 in the releases? https://github.com/TranslucentTB/TranslucentTB/releases

**Comment by sylveon** [comment]
It's pending store certification
