### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ar6355410** [TranslucentTB/TranslucentTB#706]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

the app is not opening
I even reinstalled it but still, it's the same

### Expected results

opened

### Actual results

not opening

### Windows version

Windows 10 2004-22H2 (builds 19041-19045)

**Comment by sylveon** [comment]
Please fill in the template
