### ISSUE TITLE
[Bug]: TranslucentTB has encountered a fatal error and cannot continue executing.

### ISSUE THREAD

**Issue by Dhyfer1** [TranslucentTB/TranslucentTB#709]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Just opening the TranslucentTB.exe file of the latest portable version (TranslucentTB-portable-x64.zip) on a clean install of Windows 11 causes an error.

### Expected results

I was expecting to see a transparent taskbar, because that's the style TranslucentTB applies after opening it for the first time.

### Actual results

This error message appears when I open TranslucentTB in its portable version.

<p align="center"><img src="https://user-images.githubusercontent.com/50301201/209664994-796f55a8-b9b0-4245-bc06-3ebdfa35d97f.png">

### Windows version

Windows 11 Insider builds (builds 22623 and up). 
### Other details

- Windows 11 Pro 64bits beta channel. Version 22H2 (OS Build 22623.1037)

- As I said before, after a clean install of Windows 11, TranslucentTB portable doesn't work.
 
- I know that TranslucentTB doesn't work with the new taskbar, so I'm using the classic taskbar where TranslucentTB does work
 
- After trying to open the TranslucentTB.exe file, no new file is created after the error message appears.

### Relevant log output

```shell
No output log file is created inside the unzipped folder
```

**Comment by sylveon** [comment]
This error message is correct - WinUI 2.8 is missing from a clean install of Windows 11. Normally if you go the store/appinstaller route it is automatically installed by Windows, but the portable version cannot. The error message will be improved in the future.

**Comment by Dhyfer1** [comment]
Hi @sylveon 

You are right, the portable version cannot install Xaml 2.8 Before the clean install of Win11 and when the new portable version came out, I uninstalled TranslucentTB that I downloaded from the store, and instead I used the portable version that did not present any error message when I opened the executable, so I think Xaml 2.8 was not uninstalled together with TranslucentTB.

Then I had to reinstall Windows and reinstall all my programs, I use several of them in portable version so I also wanted TranslucentTB in portable version. If I install TranslucentTB from the store or using the .appinstaler file it loses the portable version meaning, so if the problem is the lack of Xaml 2.8 I just had to download it from the [store](https://apps.microsoft.com/store/detail/microsoftuixaml28/9NSTH9KHZDLQ) and TranslucentTB portable now opens without any error.

Finally, I have a few questions:

1. Why is the blur effect no longer listed? 
2. Could you apply the effects that TranslucentTB uses, but in the system tray? I guess the system tray is part of the taskbar, or not? In the image, Windows apparently applies a mica effect and I would like to see the system tray with an acrylic effect.

![image](https://user-images.githubusercontent.com/50301201/209737577-1499ec7a-4943-49d1-be50-867d401125e2.png)

**Comment by sylveon** [comment]
Blur has been removed from build 22621 and up of Windows by Microsoft

I'm fairly sure the tray overflow does use Acrylic - this would be against their own guidelines to use Acrylic for transient UI. I just checked on my own system and see Acrylic.

**Comment by Dhyfer1** [comment]
Ok, I understand why we don't have blur in Windows 11 anymore. I think you are right, it is acrylic 🤔 By the way, there are more effects that maybe could work with TranslucentTB, like aero or tabbed. 

_Tabbed is a Mica like material that incorporates theme and desktop wallpaper, but is more sensitive to desktop wallpaper color. Works only on later Windows 11 versions (builds higher than 22523)._

I read about it in https://github.com/alexmercerind/flutter_acrylic Have you tested how this aero glass effect, or tabbed effect with translucenttb could look like?

**Comment by sylveon** [comment]
This Aero glass effect *was* Blur, and if you try this example repo on build 22621, it gives you acrylic instead.
As for Mica, I have not been able to make the APIs work with the taskbar yet.

**Comment by Dhyfer1** [comment]
Uhm. That's good. I hope you can implement more effects later, and I also hope TranslucentTB can work with the new taskbar.

This issue has been resolved, so I will close it.

Thank you for your attention 😉

**Comment by e-t-l** [comment]
I'm encountering the exact same error when trying to launch the MS store version of TranslucentTB! It also had been installed and working fine for the last week, and has just suddenly started throwing this error. Something clearly got corrupted, but I have no idea what or how to fix it.

**Comment by Cohenl19** [comment]
Same with above comment, I'm getting [THIS ERROR](https://i.upload.systems/iiziipiizii/l9v7ZVuv) with the Microsoft Store and I'm unsure on what to do to fix this.

**Comment by Cohenl19** [comment]
Same with above comment, I'm getting [THIS ERROR](https://cdn.upload.systems/uploads/l9v7ZVuv.png) with the Microsoft Store version and I'm unsure on what to do to fix this.

**Comment by Cohenl19** [comment]
Same with above comment, I'm getting an error with the Microsoft Store version and I'm unsure on what to do to fix this.
![l9v7ZVuv](https://github.com/TranslucentTB/TranslucentTB/assets/16529293/66ac5103-4b2c-455e-8514-86b12c4cc2ae)

**Comment by e-t-l** [comment]
Similar to #290. I completely uninstalled TranslucentTB, rebooted my PC, and reinstalled it. Now it works.

**Comment by Tythla** [comment]
Rebooting works for me

**Comment by AbhinavSharma486** [comment]
step 1 - firstly to uninstall this app from our device 
step 2 - restart / reboot our device
step 3 - go to microsoft store then search translucentTB app for install
step 4 - then open app from app list of your computer / laptop 
then its work definately because it works for me i do these things when i get this error

**Comment by mintearlysummer** [comment]
![Image](https://github.com/user-attachments/assets/934e7722-399a-43ef-bd1c-04573322ecbf)
I've done all of the above, and uninstalling and reinstalling still gives me an error. I guess it's still due to the Windows upgrade.
