### ISSUE TITLE
[Bug]:  DOES NOT WORK AT ALL !

### ISSUE THREAD

**Issue by MChecks** [TranslucentTB/TranslucentTB#714]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

NOT WORKING ON WINDOWS 11

### Expected results

I HAVE OPENED THE PROGRAM MULTIPLE TIMES, Installed and re installed several differnt ways! 

### Actual results

DOES NOT WORK or RESPOND

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

Edition	Windows 11 Home
Version	22H2
Installed on	‎04/‎09/‎2022
OS build	22623.1095
Experience	Windows Feature Experience Pack 1000.22638.1000.0

**Comment by sylveon** [comment]
Duplicate of #537
