### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Rashed509** [TranslucentTB/TranslucentTB#716]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

ssssssssssssssssssssssssssssssssssssssssssssssssssssssssss

### Expected results

sssssssssssssssssssssssssssssssssssssssss

### Actual results

sssssssssssssssssssssssssssssssssssssssss

### Windows version

Windows 10 May/November 2019 Update (builds 18362 and 18363)

### Other details

sssssssssssssssssssssssssssssssssss

### Relevant log output

```shell
ssssssssssssssssssssss
```

**Comment by sylveon** [comment]
Uh?

**Comment by Aquoo** [comment]
cool spam lol
