### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by chuhaixu** [TranslucentTB/TranslucentTB#717]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

更新windos最新版本后任务栏透明失效

### Expected results

可以继续可以使用

### Actual results

还没有处理

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

**Comment by sylveon** [comment]
Duplicate of #537
