### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by nian-jiu** [TranslucentTB/TranslucentTB#727]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

这个软件和win11系统中的部分软件有冲突导致本软件停止运行。

### Expected results

希望可以看一下和win11系统文件的兼容性，是否有冲突。

### Actual results

文件资源管理器一直重启，致TB软件冲突退出使用。

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment]
Dupliucate of #537
