### ISSUE TITLE
[Bug]: Open at boot (greyed out) and no longer functions

### ISSUE THREAD

**Issue by alcyone7** [TranslucentTB/TranslucentTB#729]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

On start, the app fails to start as it previously has, requiring a manual start every time the system is logged in.

### Expected results

App starts on login / boot

### Actual results

App fails to start (checked the Taskmanager).

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

Tried uninstalling and reinstallation.  Used the Appinstaller version from here and the MS.Store.

**Comment by sylveon** [comment]
This is often caused by debloating utilities changing registry keys. Try importing the following reg file in your system and rebooting afterwards:

```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System]
"EnableFullTrustStartupTasks"=dword:00000002
"EnableUwpStartupTasks"=dword:00000002
"SupportFullTrustStartupTasks"=dword:00000001
"SupportUwpStartupTasks"=dword:00000001
```

**Comment by alcyone7** [comment]
Spot on, thanks - I didn't even notice the "repair" tool used to solve a different problem had wiped all the policy entries from the registry.  Nice of the tool not to put back the default keys!  Tool deleted and posted warning to others.

**Comment by sylveon** [comment]
Glad to hear this is fixed! Mind mentioning the tool in case this comes up in the future?

**Comment by Snevenz** [comment]
Thanks to sylveon's registry fix I can now get Translucent Toolbar to start with Windows, when before the entry was greyed out. I've looked everywhere for a fix...thanks man!

**Comment by Jay-Jay57** [comment]
Hi, I'm a little late to this conversation but I'm having a similar problem, I used a debloat software and after that Translucenttb stopped opening on startup and the "boot on start" option was greyed out and I have no idea how to import the reg file you have provided. Do I copy and paste it into a new folder? I'm new to this technology stuff sorry :(

**Comment by sylveon** [comment]
What debloat software did you use?

**Comment by Jay-Jay57** [comment]
it was Ccleaner
