### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by THEwabbit212** [TranslucentTB/TranslucentTB#734]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

In Windows 11, the taskbar extends all the way to the left of the screen, as if the widgets button is still there (which has been disabled), when it should be stopping right at the windows icon to the left.

I also have roundedTB installed, however this makes no difference upon exiting the app.
![Skærmbillede 2023-02-28 131510](https://user-images.githubusercontent.com/69145095/221851872-81901c48-956d-4635-86a8-986d19048b25.png)

### Expected results

I expected it to wrap around the windows logo.

### Actual results

It acutally extends too far over to the screen's edge.

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment]
This is definitely a RoundedTB issue, TranslucentTB doesn't set the window region. It appears to be already known on their side: https://github.com/torchgm/RoundedTB/issues/98
