### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 15301155** [TranslucentTB/TranslucentTB#739]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

win11版本22H2  22621.1344 无法使任务栏透明

### Expected results

win11版本22H2  22621.1344 无法使任务栏透明

### Actual results

win11版本22H2  22621.1344 无法使任务栏透明

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment]
Duplicate of #537
