### ISSUE TITLE
feature request: making the Taskbar transparent to the foreground app

### ISSUE THREAD

**Issue by anhtuan23** [TranslucentTB/TranslucentTB#74]
I want to maximize display area on small laptop screen but I hate auto hide Taskbar. So I hope TranslucentTB can have an effect like this attached image.
![image](https://cloud.githubusercontent.com/assets/7277399/26823948/ab633dc4-4ad9-11e7-9fd3-2360f8e333dc.png)

It would be ideal if the the Taskbar can be click through too. Thanks!

**Comment by denosawr** [comment]
The first request is easily doable, making the taskbar transparent (somelike a reverse of `dynamic-ws`?) but the click through is harder, as we'll have to watch out for icons. It certainly feels like something which would overcomplicate the program, but we'll look into it to see if it can be done easily in a way which doesn't affect other users of the program! Also, help wanted.

**Comment by ethanhs** [comment]
I am confident to say we won't implement the click through. However, the hardest part will be changing the client area. Im not really sure that is in the scope of this program.

**Comment by denosawr** [comment]
Also, out of curiosity, why do you dislike auto-hide taskbar? I'd assume that there are ways to change the hide speed, if that's what you don't like of it.

**Comment by anhtuan23** [comment]
@denosawr yes, the motion is one reason, but I also need to promptly check the current keyboard language (I typed in many languages); and knowing the destination of the pointer beforehand is vital.

**Comment by anhtuan23** [comment]
An opinion regarding the click-through feature: What if you make a few bottom pixel rows to be Taskbar control area. Anything above is for interacting with the foreground program. That way, you don't need to track the Taskbar icons. Would it be more straightforward to implement?

**Comment by denosawr** [comment]
I don't think it would be any easier, unfortunately.

**Comment by denosawr** [comment]
Closing, as this is too difficult and irrelevant to the idea of TTB (a transparent taskbar).
