### ISSUE TITLE
[Bug]: Windows update

### ISSUE THREAD

**Issue by Rosu-Robert** [TranslucentTB/TranslucentTB#743]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

I just updated to the latest version of W11 and translucentTB works somehow behind the actual taskbar. 
I only use full transparency and it doesn't seem to work, but if i use accent color it works , a bit blurred so i guess it works somehow behind the actual taskbar.
Windows version as "winver" "Version 22H2 (OS Build 22621.1344)

### Expected results

Transparency

### Actual results

Blurry accent colors and transparency doesn't work.

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment]
Duplicate of #537
