### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by wxc1124** [TranslucentTB/TranslucentTB#745]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

更新了win11系统透明功能就无法使用了

### Expected results

解决适配问题

### Actual results

没有透明按钮

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment]
Duplicate of #537
