### ISSUE TITLE
[Bug]: TranslucentTB doesn't work on the latest Windows 11 update 22H2 build 22621.1344

### ISSUE THREAD

**Issue by itsziye** [TranslucentTB/TranslucentTB#747]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Update to Windows 11 Home version 22H2 build number 22621.1344.

### Expected results

Taskbar should be customised.

### Actual results

The taskbar is stuck on the Windows 11 default.

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

I think instructions to restore the tray icon would be helpful. I have disabled it a long time ago, and I'm not sure how to restore it to do troubleshooting.

**Comment by Etern213** [comment]
Same here, it seems that everyone update to 22621.1344 have this problem

**Comment by sylveon** [comment]
I have an issue for this pinned on top of the issue list, but I've been getting tons of duplicates. Are you folks not seeing it for some reason?

Anyways, duplicate of #537

**Comment by Etern213** [comment]
> I have an issue for this pinned on top of the issue list, but I've been getting tons of duplicates. Are you folks not seeing it for some reason?
> 
> Anyways, duplicate of #537

Sorry......

**Comment by itsziye** [comment]
> I have an issue for this pinned on top of the issue list, but I've been getting tons of duplicates. Are you folks not seeing it for some reason?
> 
> Anyways, duplicate of #537

My bad! I see that this is a duplicate issue. I'll be marking this thread as closed.

**Comment by itsziye** [comment]
About restoring the system tray icon though, how might I go about doing it?

**Comment by sylveon** [comment]
Just open the configuration file (under `%localappdata%\Packages\28017CharlesMilette.TranslucentTB_v826wp6bftszj\RoamingState\settings.json`) and set hide_tray to false

**Comment by itsziye** [comment]
> Just open the configuration file (under `%localappdata%\Packages\28017CharlesMilette.TranslucentTB_v826wp6bftszj\RoamingState\settings.json`) and set hide_tray to false

Thank you!

**Comment by whk-newbie** [comment]
> Just open the configuration file (under `%localappdata%\Packages\28017CharlesMilette.TranslucentTB_v826wp6bftszj\RoamingState\settings.json`) and set hide_tray to false

It doesn't seem to work，and the hide_tray was false in my settings.json file
