### ISSUE TITLE
Feature Request: Disable Transparency when any application is maximized.

### ISSUE THREAD

**Issue by Octagoncito** [TranslucentTB/TranslucentTB#75]
I would like an option for the transparency effects on the taskbar & title bar to be disabled when an application is maximized. When an application is not maximized I would like to have transparency effects. I don’t want to see what is behind my taskbar/title bar when I have an application maximized. I believe Windows Vista had this functionality.

**Comment by ethanhs** [comment]
You can do this now with the V3 release! If you set dynamic-ws in the tray or any setting, you can get this behavior. Let me know if you have questions about this.

**Comment by charlesmilette** [comment]
The opaque behavior is not visible from the GUI. You would have to do

    --dynamic-ws opaque

To get the behavior you want

**Comment by Octagoncito** [comment]
I want the taskbar to be opaque when an application is maximized, but change to blur when the window is not maximized.
How would I go about to config it that way?

**Comment by charlesmilette** [comment]
You can either use the `--dynamic-ws opaque` command line argument or put `dynamic-ws=opaque` in your config file.

**Comment by charlesmilette** [comment]
Sorry, misread.

Impossible actually without code changes.

I suggested different options (accent state and color) for each
dynamic state. Maybe this will make v4.

-- 
Envoyé de mon Gmail

**Comment by denosawr** [comment]
No, it is possible - `--dynamic-ws opaque --blur`! Make sure that the `--blur` is _after_ the `--dynamic-ws` - that's currently a bug.
