### ISSUE TITLE
[Bug]: taskbar is no longer transparent

### ISSUE THREAD

**Issue by kgerhardy** [TranslucentTB/TranslucentTB#751]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

After installing Windows KB5022913 my taskbar is no longer transparent. Uninstalling and reinstalling TranslucentTB did not help either. 
What can I do?
Many thanks for your support
Klaus Gerhardy

### Expected results

The taskbar should be transparent again

### Actual results

taskbar is no longer transparent

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by Cccc-owo** [comment]
same problem.

**Comment by Spacellary** [comment]
Latest windows (11) update made design changes to the taskbar (for the better at least) but that broke TanslucentTB :'(

**Comment by alfredosuriano** [comment]
Now my win11 sucks without TanslucentTB >:( 
I hate also new search bar (menu start) and these damned space between icons on taskbar 
For me it's fine new animation of hide tray icons only ....

**Comment by CodinGeoR** [comment]
This is a duplicate of [#537](https://github.com/TranslucentTB/TranslucentTB/issues/537).
It is pinned at the beginning of the issue page. Had you really checked?

**Comment by EagerSun09** [comment]
GeoRCode is right. Try to reset your windows with ViVeTool. It works for me :)

**Comment by sylveon** [comment]
Duplicate of #537

**Comment by Gllimpse** [comment]
> 
You can right click the taskbar to open the taskbar settings, where you can close the search box and the leftmost news recommendation. I hope the author of translatTB can resolve the issue of Win11 failure as soon as possible

**Comment by Anchor6777** [comment]
> Now my win11 sucks without TanslucentTB >:( I hate also new search bar (menu start) and these damned space between icons on taskbar For me it's fine new animation of hide tray icons only ....

You can right click the taskbar to open the taskbar settings, where you can close the search box and the leftmost news recommendation. I hope the author of translatTB can resolve the issue of Win11 failure as soon as possible

**Comment by avixityyt** [comment]
> > Now my win11 sucks without TanslucentTB >:( I hate also new search bar (menu start) and these damned space between icons on taskbar For me it's fine new animation of hide tray icons only ....
> 
> You can right click the taskbar to open the taskbar settings, where you can close the search box and the leftmost news recommendation. I hope the author of translatTB can resolve the issue of Win11 failure as soon as possible

he ain't gonna

**Comment by AlizerUncaged** [comment]
is this solved? my taskbar is still not transparent

**Comment by EagerSun09** [comment]
> is this solved? my taskbar is still not transparent

I think yes. Check post quoted in GeoRCode's comment.

**Comment by ChaoQiezi** [comment]
关闭windows系统设置中自带的任务栏中的透明效果: ![image](https://github.com/user-attachments/assets/81567996-7374-4391-ba06-15da0dfe2bd5) 在CTRL+R中输入msconfig在服务界面关闭"NVIDIA Display Container LS". ![image](https://github.com/user-attachments/assets/3c9032c9-ff66-4fdc-ba73-a2be5c9dead0)
