### ISSUE TITLE
[Bug]: After updating Windows 11 KB5022913 transparent taskbar doesn't work

### ISSUE THREAD

**Issue by Pheli0n** [TranslucentTB/TranslucentTB#752]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

 update to Windows 11 KB5022913

### Expected results

Transparent taskbar

### Actual results

No transparent taskbar

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment]
Duplicate of #537
