### ISSUE TITLE
[Bug]: Windows 11 Moment update 2 (KB5022913) not working anymore

### ISSUE THREAD

**Issue by verygenericname** [TranslucentTB/TranslucentTB#755]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Run the program, it runs, but the taskbar doesn't change at all

### Expected results

the taskbar to go transparent

### Actual results

nothing

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by verygenericname** [comment]
my bad, didn't see the issue

**Comment by tahayparker** [comment]
does it work for you?
