### ISSUE TITLE
[Bug]: it doesn't work on win11 professional after KB5022913

### ISSUE THREAD

**Issue by xubanxian233** [TranslucentTB/TranslucentTB#758]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/52060081/222903620-e8000d4b-ea33-42e1-bcf1-b0d9834ffc6a.png)
when i update my windows to KB5022913,it doesn't work again,even restarting my computer.

### Expected results

the task bar should be transparent

### Actual results

the task bar doesn't changed

### Windows version

Windows 11 RTM (build 22000)

**Comment by xubanxian233** [comment]
duplicate

**Comment by xubanxian233** [comment]
duplicate

**Comment by sylveon** [comment]
Duplicate of #537
