### ISSUE TITLE
Feature Request: --dynamic-ws normal

### ISSUE THREAD

**Issue by The0x539** [TranslucentTB/TranslucentTB#76]
As I see it, there's currently no way to have a taskbar that's normal with a maximized window, and transparent otherwise.

**Comment by ethanhs** [comment]
You can achieve this with `dynamic-ws=opaque`

**Comment by denosawr** [comment]
Not exactly - but if you have chosen for no accent colour on the taskbar (i.e. the option "Show accent color on the following surfaces: Start, taskbar and action center" is disabled in Settings under Personalisation -> Colors), it can be done using `--dynamic-ws tint --tint d9000000` - the color `d9000000` specifies the colour to be black and the alpha value to be `d9`, which is the exact value Windows uses.

**Comment by denosawr** [comment]
We're working on making this easier and more accessible, for everybody, especially those with accent colours.

**Comment by ethanhs** [comment]
Ah your right, I forgot opaque != normal. Silly me.

**Comment by sylveon** [comment]
Added in store branch
