### ISSUE TITLE
[Bug]: It no longer works in the latest version of windows 11

### ISSUE THREAD

**Issue by renlucana** [TranslucentTB/TranslucentTB#760]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Almost all customization options have no effect including transparency with the latest Windows 11 March update

### Expected results

Maybe a correction is necessary

### Actual results

Currently it does not work in any of the modes that the application has

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by ghost** [comment]
Same here

**Comment by sylveon** [comment]
Duplicate of #537
