### ISSUE TITLE
[Bug]: TranslucentTB-portable unable to set language.

### ISSUE THREAD

**Issue by xaoyaoo** [TranslucentTB/TranslucentTB#764]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

System version: win11
I want to set it to Chinese, but I can't find the set option

### Expected results

TranslucentTB-portable able to set language.

### Actual results

TranslucentTB-portable unable to set language.

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

No other problems

**Comment by sylveon** [comment]
Even in portable mode, the note from Windows language and region settings apply: 
![image](https://user-images.githubusercontent.com/6440374/223012720-af5d9754-1e84-410a-8c7f-0f18f195c4f6.png)


To change language, reorder your language list. An option to override the language will also be added to the configuration file in the next update.

**Comment by Uoki-im** [comment]
It is also impossible to achieve the top Chinese

**Comment by Uoki-im** [comment]
Sequential language lists are also not possible
