### ISSUE TITLE
Experiment with non-builtin virtual desktop programs

### ISSUE THREAD

**Issue by ethanhs** [TranslucentTB/TranslucentTB#77]
Im hoping it wouldn't be too hard to support things like Sysinternals Desktops, virtuawin, and dexpot. If it is, we should have a notice.

**Comment by charlesmilette** [comment]
Deskscapes is a animated wallpaper program 😛

**Comment by ethanhs** [comment]
Corrected. Thanks :P

**Comment by mzomparelli** [comment]
@ethanhs looking for a VirtualWin replacement that uses Win10 virtual desktop?
https://github.com/mzomparelli/zVirtualDesktop

**Comment by denosawr** [comment]
I think this is currently unnecessary. There seems to be no demand for such an application, and it would be painful to implement.
