### ISSUE TITLE
[Bug]: Does not work after Win 11 update (KB5022913)

### ISSUE THREAD

**Issue by kztera** [TranslucentTB/TranslucentTB#770]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Software no longer works when I do Win 11 update

2023-02 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5022913)

More about update:
https://support.microsoft.com/en-us/topic/february-28-2023-kb5022913-os-build-22621-1344-preview-3e38c0d9-924d-4f3f-b0b6-3bd49b2657b9

![image](https://user-images.githubusercontent.com/116504460/223468050-aac8fa7d-4276-43ac-bbd6-a7ca6096b7a8.png)

### Expected results

App working

### Actual results

Nothing happens to the taskbar. I tried restarting the app but it still doesn't work

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by Aquoo** [comment]
Duplicate. #537
