### ISSUE TITLE
[Bug]: Dosen't worki since last windows 11 update

### ISSUE THREAD

**Issue by GO2CRY** [TranslucentTB/TranslucentTB#772]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

It happens by itself when i start up the computer.

### Expected results

A fix to make it work again please. 

### Actual results

Translucent TB stopped working since last win update.

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by Korki19** [comment]
check this. https://youtu.be/LJ7SmM6TtOM

**Comment by sylveon** [comment]
Duplicate of #537
