### ISSUE TITLE
[Bug]: win11 22H2 22621.1344 is not work

### ISSUE THREAD

**Issue by 1213mmm** [TranslucentTB/TranslucentTB#775]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

![1](https://user-images.githubusercontent.com/127377356/223931748-7c2e4d93-4c0b-4223-a7bc-9f2807dac949.png)

### Expected results

please fix

### Actual results

software not working

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

please fix

**Comment by sylveon** [comment]
Duplicate of #537
