### ISSUE TITLE
[Bug]: There is no option of "Blur" in Windows 11 

### ISSUE THREAD

**Issue by SupBro5** [TranslucentTB/TranslucentTB#778]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/112799505/224120330-8e2c5316-7aa7-4b4a-a931-c91efa0b09ce.png)

### Expected results

I used this app before but recently I bought a new PC so I started setting up my pc and I wanted this app so that my taskbar would look nice and blurry, I don't want to use the clear option as it confuses me a lot.

### Actual results

After I installed the app, I see that there is no "Blur" option in the whole app!!

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

It would be really helpful if you put the "Blur" option back again!

**Comment by sylveon** [comment]
The blur effect was removed from the OS by Microsoft, so it had to be removed from TranslucentTB as an option. Acrylic is the closest equivalent.
