### ISSUE TITLE
Dynamic window state does not work on a dual monitor setup

### ISSUE THREAD

**Issue by PLyczkowski** [TranslucentTB/TranslucentTB#78]
It may also be possible that it's due to how monitors are switched here? (The main one is left, but windows loading icon when booting appears on the right one..)

**Comment by charlesmilette** [comment]
It actually is monitor aware. The problem probably is an application blocking it.

Try this (from the README) and see if it works:
> Dynamic windows (dynamic-ws) on occaison has an issue with UWP Windows. To fix this problem, try ending the ApplicationFrameHost process (this will close open UWP programs!), and restart TranslucentTB. We are working on a solution to this. The alternative to this is to uncomment the ApplicationFrameHost line in the blacklist, but this will cause dynamic-ws to fail on UWP windows.
