### ISSUE TITLE
[Feature Request]: Option to remove the start icon

### ISSUE THREAD

**Issue by CatGamer23** [TranslucentTB/TranslucentTB#790]
Just like StartKiller, remove the icon, and the spacing for it. Still allowing for the use of the Windows key on the keyboard, and ctrl + esc
![image](https://user-images.githubusercontent.com/44417404/225162429-4d2a0104-fd35-4156-8652-18a801b38e8f.png)

**Comment by sylveon** [comment]
This is out of scope for TranslucentTB
