### ISSUE TITLE
TranslucentTB [Bug]: Перестало панель задач в win 11 перекрашивать в чёрный цвет под чёрный фон. 

### ISSUE THREAD

**Issue by naumgod** [TranslucentTB/TranslucentTB#792]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue
TranslucentTB
Перестало работать в марте 2023. Приложение скаченное с майкрософт стор.
Перестало панель задач в win 11 перекрашивать в чёрный цвет под чёрный фон. 

### Expected results

Чистый чёрный цвет                              **черный** 
Имя цвета HTML / CSS |                         **#000000**
Шестнадцатеричный код#RRGGBB       **rgb (0,0,0)**

### Actual results

А на деле не меняет цвет. Цвет остаётся по умолчанию серый как по умолчанию Стандартная тёмная тема.

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

win 11 pro 22621.1413

**Comment by sylveon** [comment]
Duplicate of #537
