### ISSUE TITLE
[Bug]: does not work in windows 22621.1413

### ISSUE THREAD

**Issue by Peebinens** [TranslucentTB/TranslucentTB#793]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

upgrade windows11 to 22621.1413

### Expected results

still work

### Actual results

it does not work after upgrading

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment]
Duplicate of #537
