### ISSUE TITLE
[Bug]: TTB Doesn't work after latest Windows 11 Security Update

### ISSUE THREAD

**Issue by anantnrg** [TranslucentTB/TranslucentTB#797]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Update Windows 11 to latest update. Restart

### Expected results

Taskbar to be completely transparent (clear)

### Actual results

Taskbar shows default Windows 11 Mica Effect

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

It used to work properly before the 22621 Update. After restarting during the update, TTB doesn't make the taskbar transparent.

**Comment by sylveon** [comment]
Duplicate of #537
