### ISSUE TITLE
Feature Request: Make an acrylic mode for newer versions of Windows 10

### ISSUE THREAD

**Issue by yagomont** [TranslucentTB/TranslucentTB#80]
Hi, I'm a big fan of this application and it makes my desktop not feel very inconsistent. However, new versions of Windows made most apps have the acrylic texture with strong blurring, which I absolutely love, and now the Action Center and Start Menu are being rendered with an acrylic background, which makes the taskbar's blur a little bit out of the place. (I am using the Insider Preview build 16226.1000) 

**Could you implement in this app a feature to render the background of the taskbar using the acrylic filter?** I see Microsoft has released some documentation about XAML and acrylic effects which might help.

Regards, Yago

**Comment by ethanhs** [comment]
I think this might be possible, but would require a bit of reverse engineering. I cannot look into it as I am on the Creator's Update. If someone else wants to take this, be my guest.

**Comment by charlesmilette** [comment]
If a build releases on slow, I could try something.

**Comment by yagomont** [comment]
Thankfully ethanhs is now trying to look into this. Glad to see this suggestion isn't going to the dumpster.

**Comment by WindfallProphet** [comment]
Microsoft has a page about it [here](https://docs.microsoft.com/en-us/windows/uwp/style/acrylic).

**Comment by charlesmilette** [comment]
Unfortunately that page is for UWP apps. There is no documented way to reach this effect on classical Win32 executables. However the addition of the Acrylic effect on the start menu in the latest insider builds might help reverse-engineering it and find out how to use it on win32.

**Comment by WindfallProphet** [comment]
Yeah, sorry I should have specified. I meant it more as an overview of the acrylic aspect of Fluent design. While it can be found easily via google, I thought it better to link for discussion purposes.

**Comment by DennisBednarz** [comment]
Any updates on this?

**Comment by ethanhs** [comment]
Not really. The development of this program has slowed, as this program is entirely created by volunteer contributors and their time. The core development team is currently otherwise occupied with other things, so we are not really working on this, at least at the moment.

**Comment by DennisBednarz** [comment]
That's sad to hear. Good luck.

**Comment by Guerra24** [comment]
Hi, with insider build 17063 is now possible to use acrylic in win32 apps. (ignore my java code, but it's the only way I can try it)

![image](https://user-images.githubusercontent.com/9023392/34197939-23bfc230-e52e-11e7-857c-7fecb1517278.png)

**Comment by sylveon** [comment]
Yeah I figured out the same. They also managed to break regular blur:

![image](https://i.imgur.com/uJODf06.gifv)

**Comment by sylveon** [comment]
Added in https://github.com/TranslucentTB/TranslucentTB/commit/6df6361c3644b8d3c6c25c583f317464dee53352, you can use the latest AppVeyor build to try it.
