### ISSUE TITLE
After updating the new version of win11KB5022913, it's no longer useful

### ISSUE THREAD

**Issue by nanjimao** [TranslucentTB/TranslucentTB#800]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

After updating the new version of win11KB5022913, it's no longer useful

### Expected results

After updating the new version of win11KB5022913, it's no longer useful

### Actual results

After updating the new version of win11KB5022913, it's no longer useful

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment]
Duplicate of #537
