### ISSUE TITLE
[Bug]: not working

### ISSUE THREAD

**Issue by saar2145** [TranslucentTB/TranslucentTB#806]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

its changed a theme by accident and then it just didnt work no matter what i did

### Expected results

want the taskbar to be clear

### Actual results

not working 

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

no

**Comment by Kyber7567** [comment]
Duplicate of #537
