### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jer1825** [TranslucentTB/TranslucentTB#808]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Não funciona para a versão recente do Windows 11 Momento 3

### Expected results

Esperava-se que torne a barra de tarefas do Windows 11, Momento 3 transparente.

### Actual results

Mesmo instalado e reinstalado, após a última desatualização do Windows 11 para momento 3, o aplicativo deixou de funcionar.

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

A versao do programa é 2022.1 de 1/12/2022

**Comment by sylveon** [comment]
Duplicate of #537
