### ISSUE TITLE
How to hide the system tray icon

### ISSUE THREAD

**Issue by sohengha** [TranslucentTB/TranslucentTB#81]
my English is poor
I really like this procedure
but  Cannot hide

**Comment by ScruffyRules** [comment]
Clear or hide completely?
for hide completely you have this
![Windows Settings](https://i.scruffyrules.com/dPjELE.png)

**Comment by charlesmilette** [comment]
If i understand correctly, you want to hide the tray icon. In that case you
can use the --no-tray command line argument.

Le lun. 3 juil. 2017 à 07:23, Scott Scheiner <notifications@github.com> a
écrit :

**Comment by denosawr** [comment]
That should fix the issue. If it still persists, feel free to reopen it.

**Comment by SeriousHoax** [comment]
Hello, now that the program has "open at boot" option, how do I hide the system tray icon? I want the program to run at startup without showing the icon in tray in Windows 10. Is it possible?

**Comment by sylveon** [comment]
Add `no-tray=enable` in the configuration file

**Comment by SeriousHoax** [comment]
Perfect, thank you.
