### ISSUE TITLE
[Bug]: App will not boot after 

### ISSUE THREAD

**Issue by JGlover27** [TranslucentTB/TranslucentTB#817]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

trying to open translucent TB from home screen

### Expected results

app would open

### Actual results

app does not open

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment]
What do you mean does not open? Is the tray icon present?

**Comment by sylveon** [comment]
Closing for lack of reply
