### ISSUE TITLE
[Bug]: no puedo hacer transparente la barra de tareas

### ISSUE THREAD

**Issue by renox97** [TranslucentTB/TranslucentTB#820]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

no puedo hacer transparente la barra de tareas

### Expected results

no puedo hacer transparente la barra de tareas

### Actual results

no puedo hacer transparente la barra de tareas

### Windows version

Windows 10 May/November 2019 Update (builds 18362 and 18363)

### Other details

no puedo hacer transparente la barra de tareas

### Relevant log output

```shell
no puedo hacer transparente la barra de tareas
```

**Comment by Kourii** [comment]
no puedo hacer transparente la barra de tareas

**Comment by Dhyfer1** [comment]
no puedo hacer transparente la barra de tareas x 2

**Comment by sylveon** [comment]
Duplicate of #537
