### ISSUE TITLE
[Bug]: Windows 11 22H2 的 x64 的系统 (KB5023706)软件失效了

### ISSUE THREAD

**Issue by sayoeri** [TranslucentTB/TranslucentTB#821]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

在“2023-适用于 Windows 11 Version 22H2 的 03 累积更新，适合基于 x64 的系统 (KB5023706)”系统版本更新后，软件失效了，不能正常设置透明效果

### Expected results

希望可以更新修复一下

### Actual results

不能正常设置透明效果

### Windows version

Windows 10 May/November 2019 Update (builds 18362 and 18363)

### Other details

版本是Windows 11 Version 22H2 2023 年 3 月 14 日 - KB5023706 (OS 内部版本 22621.1413)

**Comment by sylveon** [comment]
Duplicate of #537
