### ISSUE TITLE
[Bug]: TranslucentTB not making my taskbar clear

### ISSUE THREAD

**Issue by Dannissario** [TranslucentTB/TranslucentTB#825]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

I have only done the normal windows updates, nothing specific to reach this issue

### Expected results

clear taskbar

### Actual results

normal taskbar

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by WantedTab** [comment]
If you still look for a fix, you can install ViveTool, run the exe, open cmd with administration rights, go to .exe folder and run the following commands: "vivetool /disable /id:26008830" and "vivetool /disable /id:38764045", and then restart the windows, the program will function as expected.
