### ISSUE TITLE
"Error in parsing the app package" occurs when trying .appinstaller

### ISSUE THREAD

**Issue by J0n-b0** [TranslucentTB/TranslucentTB#827]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

When attempting to install TranslucentTB via the .appinstaller, it shows the following error after opening it:
![MainError](https://user-images.githubusercontent.com/119065467/231261084-80571747-bf67-47fb-962e-89168e78ceb9.png)

I've retried downloading it multiple times, and showed the same message except on one occurrence when it showed this error:
![OtherError](https://user-images.githubusercontent.com/119065467/231261642-687ee248-1530-469e-b0ab-5b5c4b3e4282.png)

However, this second error hasnt occurred again and i it may not have to do with this error.

### Expected results

I should be able to install TranslucentTB

### Actual results

I can't install TranslucentTB.

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

Dont know if this will help, but i downloaded the file from the DuckDuckGo Beta. Its new so it may affect something.

**Comment by sylveon** [comment]
This is, AFAIK, a bug in some update of the App Installer App. My file does not appear to be broken, since PowerShell can still install it just fine, plus I did not change the file since it last worked. EarTrumpet is also affected.

There are alternatives you can use:
- [Install the app from the Microsoft Store](https://apps.microsoft.com/store/detail/translucenttb/9PF4KZ2VN4W9?hl=en-us&gl=us)
- Install the .appinstaller file via PowerShell: `Add-AppxPackage -AppInstallerFile TranslucentTB.appinstaller`

**Comment by sylveon** [comment]
This should now work. Changing the mime type of the file server side to be application/appinstaller instead of application/octet-stream seems to have solved it

![](https://media.discordapp.net/attachments/844069077621407794/1096352703313104896/image.png)

Thanks MS...

**Comment by J0n-b0** [comment]
I completely forgot to install this, and trying it again now still gives me the same results, with the same errors.

**Comment by sylveon** [comment]
This should actually work now. My host was not properly responding to HTTP range requests and that screwed up the app installer. Migrated to a different one

**Comment by RokeJulianLockhart** [comment]
> [`#issuecomment-1504042295`](https://github.com/TranslucentTB/TranslucentTB/issues/827#issuecomment-1504042295)

@sylveon, where does one report such a bug? The `winget-cli` repository, since they publish versions in its `/releases`, or did you never report it?

**Comment by sylveon** [comment]
I fixed the issue from my side so never reported it back. Are you still having problems?

**Comment by RokeJulianLockhart** [comment]
@sylveon, just wasn't certain whether [`microsoft/winget-cli/issues/5789`](https://github.com/microsoft/winget-cli/issues/5789#issuecomment-3387554662) was filed in the correct place, but in retrospect, it was. Apologies, and thanks.
