### ISSUE TITLE
Pinned Apps disappeared after reboot.

### ISSUE THREAD

**Issue by Ming0206** [TranslucentTB/TranslucentTB#83]
I got some Apps pinned on the taskbar and every time after reboot, it disappeared. I have to re-pin it again in order to fix it. Is it actually a bug?

The command lines that I applied: 
--dynamic-ws opaque 
--dynamic-start 
--no-tray 
--save-all

**Comment by ethanhs** [comment]
It can't be a bug in TranslucentTB, it doesn't touch the taskbar icons. Must be a Windows bug, sorry :/
