### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mzdoublexx** [TranslucentTB/TranslucentTB#834]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

เมื่อฉันเปิดโปรแกรม มันไม่ทำให้ taskbar ของฉันใส

### Expected results

taskbar ของฉันจะใส 

### Actual results

มันไม่ใส

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment]
Duplicate of #537
