### ISSUE TITLE
--dynamic-ws not working properly

### ISSUE THREAD

**Issue by EugeneNguyen1403** [TranslucentTB/TranslucentTB#84]
I suppose with dynamic ws enabled, the taskbar will be transparent normally, and when there are a maximized window it will become blur. I have tried default and also try to set up paramenters but when I enable dynamic ws, the taskbar is always blurred whether I have maximized window or not.
Current parameters in target field:
C:\TranslucentTB.2017.3\TranslucentTB.exe --tint 262626 --transparent 100 --dynamic-ws --dynamic-start --save-all
Is this an issue or I make mistakes? If so how to fix? Please give example

**Comment by Meychel** [comment]
Don't use tint and transparent together, just use tint with alpha value.

Put what mode you want after dynamic ws

**Comment by EugeneNguyen1403** [comment]
I see, how can I get alpha value for the ocappacity I wanted?

**Comment by Meychel** [comment]
From "usage" on github

The color parameter is interpreted as a three or four byte long number in
hexadecimal format that describes the four color channels 0xAARRGGBB
([alpha,] red, green and blue). These look like this: 0x80fe10a4 (the '0x'
is optional). You often find colors in this format in the context of HTML
and web design, and there are many online tools to convert from familiar
names to this format. These tools might give you numbers starting with '#',
in that case you can just remove the leading '#'. You should be able to
find online tools by searching for "color to hex" or something similar. If
the converter doesn't include alpha values (opacity), you can append them
yourself at the start of the number. Just convert a value between 0 and 255
to its hexadecimal value before you append it

**Comment by EugeneNguyen1403** [comment]
Ah I got it already, but didn't get the alpha value

**Comment by EugeneNguyen1403** [comment]
Update, no it's still not working, if I restart the computer, it working properly then after some time it back to the problem again. I'm not touching anything or changing any parameter

**Comment by Meychel** [comment]
Try opening task manager, stop application "ApplicationFrameHost"

**Comment by EugeneNguyen1403** [comment]
Oh it fixed, but I have to do that everytime I use my computer? or is there any way to prevent or auto stop it?

**Comment by Meychel** [comment]
It is the known bug. See "readme.md"
The translucenttb dev said upgrading to creators update will fix it

**Comment by EugeneNguyen1403** [comment]
I'm running creator update here... and yet got that issue.
Do you know what dev mean? Or it means that the creator update fix the issue itself?

**Comment by Meychel** [comment]
That is what they suggest me, but I am still on anniv update. The problem
comes from api used to detect maximized window.

**Comment by denosawr** [comment]
The bug is not one with TranslucentTB, but instead a Windows bug (UWP apps are started through ApplicationFrameHost). If you upgrade to the Insider builds, it should be fixed as they change UWP behaviour. Of course, this isn't recommended Insider builds are meant for developers.

**Comment by EugeneNguyen1403** [comment]
I see... well let's see if dev come across this issue and reply :)
Thank you for helping me with those earlier problem

**Comment by denosawr** [comment]
I am a dev :)

**Comment by EugeneNguyen1403** [comment]
Yea... Your reply show up right the moment I send the comment so... LOL @denosawr

**Comment by denosawr** [comment]
Lol :)
[dynamic-ws-exclude.zip](https://github.com/TranslucentTB/TranslucentTB/files/1143864/dynamic-ws-exclude.zip)
If you are alright with not having `dynamic-ws` work for _all_ UWP apps (that is, the 'new' ones like Settings, Edge, Store, or any apps which you install from the Windows Store), extract the zip file and place `dynamic-ws-exclude.csv` in **the same folder as `TranslucentTB.exe`**, and you won't get the problem again (hopefully).

**Comment by EugeneNguyen1403** [comment]
Okay I will try and report back
