### ISSUE TITLE
 How to switch TranslucentTB to Chinese

### ISSUE THREAD

**Issue by kerblion** [TranslucentTB/TranslucentTB#840]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

How to switch TranslucentTB to Chinese.
https://TranslucentTB.github.io/config Unable to access

### Expected results

How to switch TranslucentTB to Chinese.
https://TranslucentTB.github.io/config Unable to access

### Actual results

How to switch TranslucentTB to Chinese.
https://TranslucentTB.github.io/config Unable to access

### Windows version

Windows 10 May/November 2019 Update (builds 18362 and 18363)

**Comment by sylveon** [comment]
The language is currently based on your Windows language list:
![image](https://user-images.githubusercontent.com/6440374/234158614-2a7242d0-29fc-4a1d-ba5f-d734c060fc55.png)

You should be able to make TTB Chinese by putting Chinese above English in your language list.

**Comment by sylveon** [comment]
Language switching is supported in 2023.1
