### ISSUE TITLE
[Bug]: TTB acrylic no longer works after updating and then downgrading

### ISSUE THREAD

**Issue by ParodyVerse** [TranslucentTB/TranslucentTB#843]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

update to latest windows 11, then downgrade and open TTB and set it to acrylic mode.
(I also have Rectify 11 and Micaforeveryone+explorerframe)

### Expected results

acrylic mode enabled.

### Actual results

taskbar turns solid black rather than acrylic.

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

2023-04 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5025239)

**Comment by WantedTab** [comment]
If you still look for a fix, you can install ViveTool, run the exe, open cmd with administration rights, go to .exe folder and run the following commands: "vivetool /disable /id:26008830" and "vivetool /disable /id:38764045", and then restart the windows, the program should function as expected.

**Comment by ParodyVerse** [comment]
It actually fixed itself this morning when I woke up, haha.

**Comment by sylveon** [comment]
Probably a GPU driver screw up that restarting fixed
