### ISSUE TITLE
[Bug] It stopped working because of some Windows update

### ISSUE THREAD

**Issue by WantedTab** [TranslucentTB/TranslucentTB#844]

**Comment by WantedTab** [comment]
It's strange that if it doesn't work normally, you can install ViveTool, run the exe, open cmd with administration rights, go to .exe folder and run the following commands: "vivetool /disable /id:26008830" and "vivetool /disable /id:38764045", and then restart the windows, the program will function as expected.

For those looking for a fix, here is your fix. :))

**Comment by Bustling** [comment]
试试
`ViveTool.exe /disable /id:26008830`
然后重启电脑
