### ISSUE TITLE
Question: Colour autochange

### ISSUE THREAD

**Issue by Leerv474** [TranslucentTB/TranslucentTB#845]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Can I make it so that the taskbar colour changes to a complementary colour of current window opened?
For instance, if I had ligh-themed app opened taskbar colour would change to white, if I had dark-themed app opened it would change to dark-blue or smth.

### Expected results

...

### Actual results

...

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment]
You can use rules to do this, but you'll have to create them yourself in a per app manner

**Comment by Leerv474** [comment]
> You can use rules to do this, but you'll have to create them yourself in a per app man

can you give an example?
