### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Kero251** [TranslucentTB/TranslucentTB#846]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

not working

### Expected results

not working

### Actual results

not working

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

not working

### Relevant log output

```shell
not working
```

**Comment by Kero251** [comment]
the ttb is not working

**Comment by sylveon** [comment]
Duplicate of #537
