### ISSUE TITLE
[Mistake]: a translation mistake in Chinese

### ISSUE THREAD

**Issue by chengge348** [TranslucentTB/TranslucentTB#847]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

change “清晰”into“透明”

### Expected results

"clear" is translated into”透明“

### Actual results

"clear" is translated into”清晰“

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

In Chinese,the exact meaning of the word ”透明“is "translucent",but the word”清晰“doesn't have that meaning.In this software's English language,"clear" actually expresses the meaning"translucent",the two word have a same meaning;but in Chinese,"透明”and"清晰“don't have any similar meaning.

**Comment by sylveon** [comment]
The string got updated to 透明 in developer builds a bit ago. It'll be fixed next release :)
