### ISSUE TITLE
[Question]: Can I apply TranslucentTB to the Start Menu?

### ISSUE THREAD

**Issue by NaeemChakera** [TranslucentTB/TranslucentTB#850]
### Question

I couldn't find a page to ask a question here, so here it is, is it possible for TranslucentTB to work with the start menu?
I wanted to make the start bar acrylic, you may be able to tell the difference between the TranslucentTB Taskbar and the stock Start Menu. I've attached an image below for reference.
https://imgur.com/a/BYrIpYN

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

Installed build: 22624.1755 ni release

**Comment by sylveon** [comment]
We don't support modifying the appearance of the start menu at the moment
