### ISSUE TITLE
Will it ever work again?

### ISSUE THREAD

**Issue by perigozin** [TranslucentTB/TranslucentTB#851]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Windows updated and it doesn't work anymore (build 22621) as seen on [#537](https://github.com/TranslucentTB/TranslucentTB/issues/537).

The last reply on that issue is from march and then it was closed. Will it ever be fixed or should I start looking for alternatives. It's been 2 months...

### Expected results

---

### Actual results

---

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment]
The issue is locked, which is different than closed (it was locked cause conversation on that thread was going in circle and went as low as to promote piracy). It is still opened, and I am working on it.
