### ISSUE TITLE
[Bug]: Went i click on open it doesn't open

### ISSUE THREAD

**Issue by Shohib090** [TranslucentTB/TranslucentTB#854]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

how do i fix this?

### Expected results

translucenttb opens

### Actual results

it doesn't open

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by tahayparker** [comment]
Check #537
