### ISSUE TITLE
[Bug]: Flashing taskbar

### ISSUE THREAD

**Issue by 1111Al** [TranslucentTB/TranslucentTB#861]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

I'm using RoundedTB with systray hidden, When I hover on systray area to show it, the taskbar flashes.
Windows 11 Pro build 22621.1105

### Expected results

No flash

### Actual results

It flashes

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment]
Please report this issue to RoundedTB.

**Comment by 1111Al** [comment]
Ok, but when TranslucentTB is not running. the flash doesn't happen.

**Comment by sylveon** [comment]
RoundedTB has special code that integrates with TTB to avoid that flash, so I'd still believe it might be an issue on their side.
