### ISSUE TITLE
[Bug]: TranslucentTB doesnt work

### ISSUE THREAD

**Issue by franciscombsp** [TranslucentTB/TranslucentTB#865]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

I tried to install a lot of times TranslucentTB but my taskbar doesnt get transparent

### Expected results

A transparent taskbar when I open TranslucentTB for the first time

### Actual results

The taskbar doesnt get transparent

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

**Comment by Amnesia1211** [comment]
Leider wurde der Fehler bis jetzt noch nicht korrigiert, obwohl er bereits seit einigen Monaten besteht. Ab einer bestimmten Windows-Version läuft das Programm nicht mehr. Ein Eintrag zu diesem Thema existiert hier, wurde jedoch von einem Administrator geschlossen. Leider kann ich dir keine weiteren Informationen zu diesem Problem liefern. Hoffen wir einfach weiter das er bald mal behoben wird.

**Comment by sylveon** [comment]
Duplicate of #537
