### ISSUE TITLE
[Bug]: my task bar dont go invisible

### ISSUE THREAD

**Issue by jontebou** [TranslucentTB/TranslucentTB#866]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

pls help

### Expected results

hi

### Actual results

hi

### Windows version

Windows 10 May/November 2019 Update (builds 18362 and 18363)

**Comment by sylveon** [comment]
Duplicate of #537
