### ISSUE TITLE
[Bug]: A white line on the taskbar in transparent mode

### ISSUE THREAD

**Issue by YaeSakuraQvQ** [TranslucentTB/TranslucentTB#867]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

On win11 22621.1825, tb didn't work, so I followed the method in issue537 to fix it
Although it works normally, there will be a white line on the taskbar in transparent mode, which is really ugly
(In win10, tb can work beautifully)

### Expected results

Works the same way as before, without the annoying white line

### Actual results

(Note the white line on the taskbar as shown in the image below)
![image](https://github.com/TranslucentTB/TranslucentTB/assets/87939280/00334758-2c41-4338-b9e1-cc083a6e43c0)

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Relevant log output

```shell
(haven't found it yet, if you need it, I can reproduce the bug and then copy the log)
```

**Comment by sylveon** [comment]
Turn off "show taskbar border"

**Comment by YaeSakuraQvQ** [comment]
Solved, everything works now, thanks a lot
