### ISSUE TITLE
[Bug]: English Language not available 

### ISSUE THREAD

**Issue by Fabiano-Thimotheo** [TranslucentTB/TranslucentTB#874]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

![Tela Translucent Traduzir 1](https://github.com/TranslucentTB/TranslucentTB/assets/110348175/72010459-33ef-4e48-9609-47a09ca432a4)

I downloaded it from the Microsoft Store (Windows 10). (Translucent TB Version 2022.1.0.0). And only the Mandarin Chinese language is available. I can't change it to english language, even though it says on the documentation that english is a supported language. 

### Expected results

Let me able to change the language to english

### Actual results

Only Mandarin is available 
![Tela Translucent Traduzir 1](https://github.com/TranslucentTB/TranslucentTB/assets/110348175/b3f31d7b-2206-4e83-bdad-20f953995858)

### Windows version

Windows 10 2004-22H2 (builds 19041-19045)

**Comment by sylveon** [comment]
Make sure you get this version: https://apps.microsoft.com/store/detail/translucenttb/9PF4KZ2VN4W9

There is a third party translated version on the store, it's possible you downloaded that instead.
