### ISSUE TITLE
[Bug]: It is not working at all 

### ISSUE THREAD

**Issue by AquaFrostByte** [TranslucentTB/TranslucentTB#876]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Downloaed via the stor and github

### Expected results

the app works fine but the taskbar isnt changing

### Actual results

Not working

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment]
Duplicate of #537
