### ISSUE TITLE
I can't change the language back to English.

### ISSUE THREAD

**Issue by vivadavid** [TranslucentTB/TranslucentTB#877]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Hi,

In version 2023.1, TranslucentTB provides a Spanish translation, but I'd like to keep the programme in English as I used to. In the changelog for 2023.1, I've found this:

> Add hidden configuration options to override the language used by TranslucentTB

However, I can't find these "hidden configuration options".

### Expected results

I'd like to be able to switch the language to English, and if possible, through a menu, and not through a hidden option.

### Actual results

TranslucentTB remains in Spanish, which is the language of my installation of Windows 11.

### Windows version

Windows 11 RTM (build 22000)

**Comment by sylveon** [comment]
Add `"language": "en-US"` to the JSON file and restart TranslucentTB.

**Comment by vivadavid** [comment]
Thank you for your message.

In Advaced > Edit Settings, I have opened a file called _settings.json_.

I don't know where to write the code above: I've tried in a couple of places, but I've got error messages and the changes haven't been saved.

At the top of the file, there's a website link with, I suppose, indications on how to edit the settings file, but my browser says the page doesn't exist.

Could you give me more details, please?

**Comment by sylveon** [comment]
You'd add it at the bottom, so something like this (note the extra comma after verbosity)
```
  "hide_tray": false,
  "disable_saving": false,
  "verbosity": "warn",
  "language": "en-US"
}
```

The option is hidden because it's a workaround for Windows's sometimes bad language detection, not really meant to be used outside of that.

**Comment by vivadavid** [comment]
It worked now! Thanks, @sylveon !
