### ISSUE TITLE
Won't run at startup [Bug]: 

### ISSUE THREAD

**Issue by Robstathelobster** [TranslucentTB/TranslucentTB#880]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Start Windows 11

### Expected results

Translucent TB running in system tray, taskbar clear and transparent. Settings file quotes:

// See https://TranslucentTB.github.io/config for more information
{
  "$schema": "https://sylveon.dev/TranslucentTB/schema",
  "desktop_appearance": {
    "accent": "clear",
    "color": "#00000000",
    "show_peek": false,
    "show_line": false
  },
  "visible_window_appearance": {
    "enabled": false,
    "accent": "clear",
    "color": "#00000000",
    "show_peek": true,
    "show_line": false,
    "rules": {
      "window_class": {},
      "window_title": {},
      "process_name": {}
    }
  },
  "maximized_window_appearance": {
    "enabled": false,
    "accent": "acrylic",
    "color": "#00000000",
    "show_peek": true,
    "show_line": true,
    "rules": {
      "window_class": {},
      "window_title": {},
      "process_name": {}
    }
  },
  "start_opened_appearance": {
    "enabled": true,
    "accent": "clear",
    "color": "#00000000",
    "show_peek": true,
    "show_line": false
  },
  "search_opened_appearance": {
    "enabled": false,
    "accent": "normal",
    "color": "#00000000",
    "show_peek": true,
    "show_line": true
  },
  "task_view_opened_appearance": {
    "enabled": true,
    "accent": "normal",
    "color": "#00000000",
    "show_peek": false,
    "show_line": true
  },
  "battery_saver_appearance": {
    "enabled": false,
    "accent": "opaque",
    "color": "#00000000",
    "show_peek": true,
    "show_line": false
  },
  "ignored_windows": {
    "window_class": [],
    "window_title": [],
    "process_name": []
  },
  "hide_tray": false,
  "disable_saving": false,
  "verbosity": "warn"
}

### Actual results

Taskbat not transpaernt, No system tray icon. Task manager reports no TransTb task in list but settings in TransTB set to run at startup. If the exe is run manually, the tackbar becomes transparet as expected. 

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

Win 11 build 22621.1928
Windows Feature Experience Pack 1000.22644.1000.0

**Comment by sylveon** [comment]
If you check in the "startup" tab of task manager is TranslucentTB enabled there?

**Comment by TianQian-A** [comment]
> If you check in the "startup" tab of task manager is TranslucentTB enabled there?

In the "startup" tab of task manager, there's no app named TranslucentTB

**Comment by sylveon** [comment]
Are you using the portable builds?

**Comment by TianQian-A** [comment]
> Are you using the portable builds?

Oh yes, my bad. After switching to Microsoft Store's version, it works fine.

**Comment by Robstathelobster** [comment]
> If you check in the "startup" tab of task manager is TranslucentTB enabled there?

No, it's not. I have now moved the exe to the Windows 11 startup directory manually and that work fine :)
