### ISSUE TITLE
[Bug]: Tray icon right-click menu UI display exception (text/icon alignment, menu item spacing)

### ISSUE THREAD

**Issue by Hovn** [TranslucentTB/TranslucentTB#881]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

I haven't fully figured out how to reproduce it, but now I record at least 3 menu UI states (icon/text alignment, menu item spacing).
TranslucentTB 2023.1（Previous versions are also observed）
(1) The app has just been opened and pops up for the first time
(2) When ejecting for the second time
(3) After making certain adjustments, it may appear, and I have not yet figured out the pattern

![image](https://github.com/TranslucentTB/TranslucentTB/assets/6801952/0b9f506f-375b-4fed-a740-29509d35b03f)

### Expected results

At all times, the right-click menu UI of the tray icon should behave consistently.

### Actual results

At least 3 UI states have been observed (there may be more), and icon/text alignment is often abnormal.

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

Device Information
Model: HP ENVY x360 Convertible 15-cn1xxx
OEM: HP
OS: WINDOWS 11
OS Version: 10.0.22621.1928
Language: zh-CN
Screen: 1920*1080
DPI Scale: Custom 125%

![image](https://github.com/TranslucentTB/TranslucentTB/assets/6801952/bc99c177-77a4-446a-921b-c13299c9b7e3)

**Comment by sylveon** [comment]
These are OS bugs, nothing I can do about this AFAIK :(

**Comment by Hovn** [comment]
> These are OS bugs, nothing I can do about this AFAIK :(

Thanks for replying, really fast. Although this did not affect the use, it bothered me for a while, tried to flip through the list of problems, but did not find it, so I brought it.
Best wishes!

**Comment by Hovn** [comment]
I've observed this spacing change on other software, again on the first and second opens. Microsoft is solely responsible (Bug 11).
![image](https://github.com/TranslucentTB/TranslucentTB/assets/6801952/52eb0c70-1da2-40ab-9868-0a56cf90c80c)

I guess it could be a bug related to tablet mode? Even if I am in PC mode, but because I have triggered tablet mode, the Win11 judgment is abnormal? Because tablet mode will increase the menu spacing somewhat.
![image](https://github.com/TranslucentTB/TranslucentTB/assets/6801952/b013381b-9f84-49d8-acd1-17d07aef05eb)

**Comment by sylveon** [comment]
It's not tablet mode that increases spacing, it's touch input. But both explorer (where your screenshot comes from) and TTB programmatically open this menu, therefore the menu doesn't know if the open action comes from touch or mouse, so it defaults to touch. When you use the menu, it sees you interacted with it with a mouse, then remembers it next time.

**Comment by Hovn** [comment]
@sylveon 
In addition, I think it is possible to consider separating the fixed icon from the dynamic option icon, and whether the performance will be normal?
For example, only display fixed icons to the left of the menu item text, do not display dynamic icons here (indicating checked/unchecked), and move the state to the secondary menu for representation.
Perhaps the confusion can be alleviated. I'm not sure.

![image](https://github.com/TranslucentTB/TranslucentTB/assets/6801952/e1a2a14c-103a-46f0-8235-879370ace7f9)

**Comment by Hovn** [comment]
> 

You are right, when I touch it with my hand, the phenomenon reverses. The first time it shows a small-pitch menu (you have to click on a menu item), the second time and then it shows a large-pitch menu.
Is this Microsoft's thoughtful design, am I misunderstood? [doge][doge][doge]

**Comment by Hovn** [comment]
> 

I looked at the explorer menu item, it is relatively stable, maybe give a point of reference. 

![image](https://github.com/TranslucentTB/TranslucentTB/assets/6801952/6648dab7-866e-4bcc-a345-4217fb4ec8a0)
