### ISSUE TITLE
[Bug]: 2023 latest portable version won't run

### ISSUE THREAD

**Issue by dinaau** [TranslucentTB/TranslucentTB#883]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

![2023-07-12_12-03-52](https://github.com/TranslucentTB/TranslucentTB/assets/68769882/156063d2-f991-4fbd-9698-9893565f2865)

### Expected results

run with windows start up

### Actual results

started with win startup but pops up a window 

after close windows it quit 

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

23h2

25398.1

**Comment by sylveon** [comment]
You are missing a dependency on the system. Install this: https://github.com/TranslucentTB/TranslucentTB/releases/download/2023.1/winui-x64.appx
