### ISSUE TITLE
[Bug]: System tray not transparent

### ISSUE THREAD

**Issue by WilliamLeGod** [TranslucentTB/TranslucentTB#884]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Click on the up arrow to see system tray and it shows as not transparent![image](https://github.com/TranslucentTB/TranslucentTB/assets/70202711/f30108cc-1b71-4512-9a37-2af5cfe15e0b)

### Expected results

system tray and it shows as not transparent

### Actual results

system tray and it shows as not transparent

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment]
TranslucentTB only affects the taskbar, the system tray is out of scope.
