### ISSUE TITLE
[Bug]: All UI using win11 style

### ISSUE THREAD

**Issue by yyk725** [TranslucentTB/TranslucentTB#889]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

click the TranslucentTB icon in the taskbar

### Expected results

i think using win10 style on windows10 is better

### Actual results

it's using win11 style which looks very uncomfortable in the system, also have smaller fonts compared to other programs
![image](https://github.com/TranslucentTB/TranslucentTB/assets/72236930/65a9ca6c-fb4c-4fee-88bb-59148f6ad9de)

### Windows version

Windows 10 2004-22H2 (builds 19041-19045)

**Comment by sylveon** [comment]
This is a normal feature of WinUI. You can notice the same on all apps using WinUI 2.6 or higher.
