### ISSUE TITLE
Inconsistent painting with top taskbar and maximised windows

### ISSUE THREAD

**Issue by Daniel-Beardsmore** [TranslucentTB/TranslucentTB#89]
Windows 10 Creators Update, top taskbar, TranslucentTB version 2017.3, non maximised window:

![before maximise](https://user-images.githubusercontent.com/5874930/28739809-0c6f2e76-73f6-11e7-8cba-0cbf79de8616.png)

Window maximised: notice how the top of the windows's title bar gets a blur applied to it, which you can see at the bottom of the taskbar:

![after maximise](https://user-images.githubusercontent.com/5874930/28739811-0c77ebb0-73f6-11e7-8bd9-0a002e8430e6.png)

Now if I point to any active taskbar button, this title bar blur is removed:

![disturbance in the force](https://user-images.githubusercontent.com/5874930/28739810-0c75ad00-73f6-11e7-98d8-ba69c8b6da34.png)

Simply clicking in the taskbar _may_ remove the title bar blur, but not always. It comes back sometimes when switching to a maximised window but not always — the behaviour is erratic.

Configuration:

accent=blur
color=0
opacity=165

**Comment by ethanhs** [comment]
This is due to the window's and taskbar's focus state changing, and we cannot fix this, it is a bug in Windows (technically). Sorry

**Comment by Daniel-Beardsmore** [comment]
If you set dynamic-ws to blur, then the first window that is maximised is not affected. The bug is only observed when the second window is maximised. dynamic-ws = blur effects a sequence where the taskbar redraw occurs at the correct point in time (after maximise has occurred, I assume). Consequently it should be possible to apply a redraw upon any maximise to resolve this.

**Comment by denosawr** [comment]
This would be pretty difficult without dramatically increasing CPU usage. We cannot set a hook for window maximize, so instead we check for maximized windows every x milliseconds. This causes the delay you see. We have tried decreasing this delay, but then CPU usage increases twofold.
