### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Alighazi786** [TranslucentTB/TranslucentTB#893]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

failed to inilization the disgonsation

### Expected results

failed to inilization the disgonsation

### Actual results

failed to inilization the disgonsation

### Windows version

Windows 10 May/November 2019 Update (builds 18362 and 18363)

### Other details

failed to inilization the disgonsation

### Relevant log output

```shell
failed to inilization the disgonsation
```

**Comment by sylveon** [comment]
Can you provide more details? Screenshots, messages, etc.
