### ISSUE TITLE
splash screen

### ISSUE THREAD

**Issue by buraCharles** [TranslucentTB/TranslucentTB#898]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

how to hide splash screen at startup in left top

### Expected results

how to hide splash screen at startup in left top

### Actual results

how to hide splash screen at startup in left top

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Relevant log output

```shell
how to hide splash screen at startup in left top
```

**Comment by sylveon** [comment]
There is no splash screen already.

**Comment by buraCharles** [comment]
I had installed via the store, I just reinstalled on the github site with TranslucentTB.appinstaller.
now i have no more splash screen
