### ISSUE TITLE
How can I set dynamic windows  automatically when the computer is on？

### ISSUE THREAD

**Issue by ZeroWickD** [TranslucentTB/TranslucentTB#90]
My English is not very good, please forgive me

**Comment by mmdtoycar** [comment]
This cannot be done now, you need to wait until the new version released. Check #Known issues at Readme

**Comment by charlesmilette** [comment]
You can actually.

Open the Windows registry editor, go to `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`. You should see an entry named TranslucentTB. Double-click on it to edit it and add `--dynamic-ws`. Press OK, and reboot.

**Comment by ZeroWickD** [comment]
fix #90
