### ISSUE TITLE
[Bug]: 22H2 Blur effect

### ISSUE THREAD

**Issue by Undisputed00x** [TranslucentTB/TranslucentTB#905]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

.

### Expected results

.

### Actual results

.

### Windows version

Windows 10 May/November 2019 Update (builds 18362 and 18363)

### Other details

Is there any way even by using a other mods to restore blur effect on Win11 22H2 ? 

### Relevant log output

```shell
.
```

**Comment by sylveon** [comment]
No, there is not. The code for the effect is gone from the OS
