### ISSUE TITLE
[Bug]:it aint exaclly a bug

### ISSUE THREAD

**Issue by shazam2k** [TranslucentTB/TranslucentTB#917]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Well i just downloaded it and its full japonese. How do i change it pls? I cant read japonese sooo i cant even be sure on where its the setting.   Please help  

### Expected results

To be in english

### Actual results

it was in japonese

### Windows version

Windows 11 RTM (build 22000)

**Comment by sylveon** [comment]
Add "language": "en-US" to the config file if Windows' language selection algorithm doesn't use the right language for you.
