### ISSUE TITLE
Feature Request: Android-like fade to black effect(not sure whats the proper term)

### ISSUE THREAD

**Issue by hayzq** [TranslucentTB/TranslucentTB#92]
I love this thing but i always use the automatic taskbar hide so whenever i browse chrome and need to peek the taskbar, all the white text is basically impossible to read.

can you add something like this as an option?
![image](https://user-images.githubusercontent.com/30745342/28993914-a36c539e-7a04-11e7-9d6b-a5b4bf56924a.png)

**Comment by denosawr** [comment]
We'd need to draw a window under the taskbar. It isn't exactly a priority, though.

**Comment by Dreemlan** [comment]
I'd like to add that I'd love a feature like this as well.

For now I'll just add it to my desktop backgrounds myself, lol.

**Comment by t-kitsune** [comment]
I wouldn't want this. IMHO, It's ugly (also its called Vignette)

**Comment by ethanhs** [comment]
@t-kitsune if we did it, the feature would be optional

**Comment by Mach525** [comment]
@hayzq Look like this？
![untitled](https://user-images.githubusercontent.com/8449041/29752243-ddd93670-8b8c-11e7-9210-68e9304ee3f4.png)

**Comment by sylveon** [comment]
This can probably be made with rainmeter or by changing your wallpaper to include the fade effect

**Comment by hayzq** [comment]
![capturev](https://user-images.githubusercontent.com/30745342/29772928-5541b4ba-8c3e-11e7-8667-0bfc720479f8.PNG)

Something like this if its possible. I'm using a 13 inch laptop so I usually set my taskbar to autohide, but whenever I want to peek at the time or click anything on the taskbar it gets pretty difficult especially if its a white icon on a white background (e.g. chrome or any documents)

This is how it looks now.
![capturen](https://user-images.githubusercontent.com/30745342/29773227-b958b628-8c3f-11e7-8be5-477f31d0fd13.PNG)

**Comment by hayzq** [comment]
@Mach525 a bit like that but attached to the taskbar not the wallpaper, nice wallpaper btw, is that from the movie where the kid is a shoemaker or something?

**Comment by Mach525** [comment]
@hayzq Not wallpaper just using "TB Shadow",it's old and not have much configuration,if TranslucentTB add this feature will be great, about wallpaper i'm using"Live Wallpaper Engine"with"言の葉の庭(The Garden of Words)"wallpaper,come from "kotonohanoniwa"movie i think.(Forgive my English)

**Comment by Dreemlan** [comment]
Mach525 makes a good point, with animated wallpapers like you can get from Wallpaper Engine, you can't really add the kind of vignette effect yourself, so it would definitely be nice to have as an optional feature.

Here's a comparison of a default wallaper and one with a light vignette behind the taskbar that I think is light enough to not be a noticeable, distracting, gradient, but still improves visibility of taskbar icons. 

![vigentte-preview](https://user-images.githubusercontent.com/23227532/29792744-465e72c8-8bf6-11e7-8eff-37ad112e9ef4.jpg)

The vignette is a lot more noticeable when looking at a small preview image, it's much less distracting when it's on your full size resolution across your monitor and you're sitting in front of it.

**Comment by JBoxman7** [comment]
@Dreemlan Good idea. A little vignette could go a long way. Would adding such a feature to the taskbar be more complicated than applying a gradient to it's alpha channel? I've yet to look through the source, but (conceptually) if transparent mode is available, a gradient wouldn't be super difficult.

**Comment by denosawr** [comment]
I don't think the workings of the `SetWindowCompositionAttribute` API allowed us to set a gradient; we'd have to draw a window under the taskbar with a vignette effect. Development for TTB has mostly halted, but feel free to try to implement this yourself!

**Comment by denosawr** [comment]
I'm going to close this issue, as I don't think it's really inside the scope of TTB as it requires us to draw a window behind the taskbar as opposed to what we do now, which merely modifies some attributes of the taskbar's window. If any talented programmers out there want to make that, though, feel free to make us aware of it so we can link to it!

**Comment by sylveon** [comment]
When we eventually get to the point where we hook explorer (which should be by version 6, I want to prioritize lazy dynamic windows and a graphical blacklist editor in version 5) achieving this and custom user textures will be as simple as getting a GDI device context for the taskbar and drawing with it.

**Comment by bitbotzgames** [comment]
I would really like to have the gradient feature. Making windows showing behind the taskbar isn't important for me. Why don't we split this into 2 separate features. Is it ok to open a new feature request for only the gradient feature?

I like the transparent taskbar. But then white icons are not so good to see on white backgrounds:
![TB Feature A](https://user-images.githubusercontent.com/83534976/132090257-2ac3a1ad-7e9e-47bb-8238-43a2faf24efc.jpg)

A gradient would be way better:
![TB Feature B](https://user-images.githubusercontent.com/83534976/132090354-0558b3f4-0cf2-4ce8-b8b9-54f0aca6841e.jpg)
