### ISSUE TITLE
功能建议：开始菜单背景可以一同设置

### ISSUE THREAD

**Issue by sjtuwater** [TranslucentTB/TranslucentTB#923]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

开始菜单无法半透明
![image](https://github.com/TranslucentTB/TranslucentTB/assets/61745138/c550922e-9450-49f8-9a31-9b213ab25c9b)

### Expected results

希望开始菜单能够半透明

### Actual results

希望开始菜单能够半透明

### Windows version

Windows 10 2004-22H2 (builds 19041-19045)

**Comment by sylveon** [comment]
TranslucentTB only modifies the taskbar, not the start menu
