### ISSUE TITLE
[Bug]: 没有开机启动选项

### ISSUE THREAD

**Issue by HHuiLin** [TranslucentTB/TranslucentTB#924]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

无法进行开机自启动，任务管理器启动项没有找到，软件右键菜单也没有自启动选项

### Expected results

如何更改自启动选项使软件自行启动

### Actual results

如何更改自启动选项使软件自行启动

### Windows version

Windows 11 RTM (build 22000)

**Comment by sylveon** [comment]
Use the store version. Portable version is *portable*, so support for startup would not fit with this (as it is not portable across computers).

**Comment by HHuiLin** [comment]
> 使用商店版本。便携式版本是_可移植的_，因此对启动的支持不适合此（因为它不可跨计算机移植）。

好的谢谢
