### ISSUE TITLE
[Bug]: Taskbar not shown when startup

### ISSUE THREAD

**Issue by littlewhitecloud** [TranslucentTB/TranslucentTB#925]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Open the computer.

![image](https://github.com/TranslucentTB/TranslucentTB/assets/71159641/58f926e6-e030-44c3-89a6-b7ba9c1f394f)

Note: I didn't use hide taskbar.

### Expected results

Show taskbar with acrylic effect

### Actual results

No taskbar

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

22631.2271

Windows load a long time when login.

**Comment by sylveon** [comment]
Does this still happen on the latest version?

**Comment by littlewhitecloud** [comment]
It has fixed :)
