### ISSUE TITLE
[Bug]:language somehow change to Russian

### ISSUE THREAD

**Issue by temginson** [TranslucentTB/TranslucentTB#926]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

its

### Expected results

not 

### Actual results

a bug

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

i just wannt to change the language to english

**Comment by sylveon** [comment]
Check your Windows language settings:
![](https://media.discordapp.net/attachments/312341949078306818/1051280370793984061/205079769-7ed32011-b3b2-4ed7-9821-0f9418819618.png)

Make sure Russian isn't above English

**Comment by temginson** [comment]
thanks it fixted it!
________________________________
Från: Charles Milette ***@***.***>
Skickat: den 16 september 2023 00:11
Till: TranslucentTB/TranslucentTB ***@***.***>
Kopia: temginson ***@***.***>; Author ***@***.***>
Ämne: Re: [TranslucentTB/TranslucentTB] [Bug]:language somehow change to Russian (Issue #926)


Check your Windows language settings:
[https://camo.githubusercontent.com/2e752aaa31c89be307654510ae3cb3adaaeba146bff7d7aca04ed9e63fe662fb/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3331323334313934393037383330363831382f313035313238303337303739333938343036312f3230353037393736392d37656433323031312d623362322d346564372d393832312d3066393431383831393631382e706e67]<https://camo.githubusercontent.com/2e752aaa31c89be307654510ae3cb3adaaeba146bff7d7aca04ed9e63fe662fb/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3331323334313934393037383330363831382f313035313238303337303739333938343036312f3230353037393736392d37656433323031312d623362322d346564372d393832312d3066393431383831393631382e706e67>

Make sure Russian isn't above English
