### ISSUE TITLE
[Bug]: Accent color has effect even when alpha was set to 0

### ISSUE THREAD

**Issue by Ptilopsis01** [TranslucentTB/TranslucentTB#928]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

https://github.com/TranslucentTB/TranslucentTB/assets/93318731/2c37c95c-d9cc-4db9-a13e-0f9e5f1b8a95
As shown in the video, even alpha was set to 0, the accent color still effects the acrylic.

### Expected results

Accent color has no effect when alpha was set to 0

### Actual results

Shown above

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment]
This is a bug in the OS implementation of the acrylic effect:
![image](https://github.com/TranslucentTB/TranslucentTB/assets/6440374/8ddaa717-b645-469c-a704-b48b946019ae)

TranslucentTB just passes the specified color unmodified to the system.

**Comment by Ptilopsis01** [comment]
> This is a bug in the OS implementation of the acrylic effect: ![image](https://user-images.githubusercontent.com/6440374/269171158-8ddaa717-b645-469c-a704-b48b946019ae.png)
> 
> TranslucentTB just passes the specified color unmodified to the system.

Is it possible for us to choose not to pass the accent color?

**Comment by sylveon** [comment]
If no accent color is passed, you get a default gray-ish color.

**Comment by Ptilopsis01** [comment]
> If no accent color is passed, you get a default gray-ish color.

I see... By the way, I found it only happens when I use two screens, and it behaves normally when I'm just using my laptop inner screen
