### ISSUE TITLE
[Bug]: It doesn't automatically start anymore

### ISSUE THREAD

**Issue by VRequiemV** [TranslucentTB/TranslucentTB#929]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

When I try to turn on the auto startup on the task manager it doesn't work.

### Expected results

I am trying to activate the auto-startup.

### Actual results

It just disable the auto-startup automatically.

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment]
This is most likely caused by a recent registry change, probably some privacy/debloat script. Save the following file as "StartupTasks.reg", then open it to fix the problem
```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System]
"EnableFullTrustStartupTasks"=dword:00000002
"EnableUwpStartupTasks"=dword:00000002
"SupportFullTrustStartupTasks"=dword:00000001
"SupportUwpStartupTasks"=dword:00000001
```

**Comment by VRequiemV** [comment]
> This is most likely caused by a recent registry change, probably some privacy/debloat script. Save the following file as "StartupTasks.reg", then open it to fix the problem
> 
> ```reg
> Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System]
> "EnableFullTrustStartupTasks"=dword:00000002
> "EnableUwpStartupTasks"=dword:00000002
> "SupportFullTrustStartupTasks"=dword:00000001
> "SupportUwpStartupTasks"=dword:00000001
> ```

Thank you, I did it manually because I don't know how to create .bat files exactly but it worked!
