### ISSUE TITLE
[Bug]: Windows 11 with top bar using Explorer Patcher doesn't show Taskbar Icons on Second Monitor 

### ISSUE THREAD

**Issue by Dragontamer333** [TranslucentTB/TranslucentTB#931]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

I am using Explorer Patcher to have my windows 11 taskbar at the top of my screen. Using Translucent TB makes the taskbar clear but it also removes my icons on my second monitor.

### Expected results

Being able to see my icons on my second monitor.

### Actual results

Unable to see my icons even though the taskbar becomes clear.

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

Edition	Windows 11 Home
Version	22H2
Installed on	‎9/‎30/‎2022
OS build	22621.2283
Experience	Windows Feature Experience Pack 1000.22662.1000.0

Explorer Patcher Version: 22621.2361.58.1

TranslucentTB Version: 2023.1.0.0

**Comment by sylveon** [comment]
Known issue: #702

Enable "show taskbar line" as a workaround for now (doesn't apply to classic taskbar anyways)
