### ISSUE TITLE
[Bug]: application won't open

### ISSUE THREAD

**Issue by therandompersonn** [TranslucentTB/TranslucentTB#934]
### Please check for a duplicate first

- [x] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

I download translucenttb from MS store and open it, the intro bit works then when i click continue nothing shows although the taskbar turns transparent. The same happened for me on the portable version.

### Expected results

for the settings to appear

### Actual results

after opening the app and clicking continue, it does not show settings although the taskbar does turn transparent

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

on the portable version and the MS store version this happens for me

**Comment by sylveon** [comment]
TranslucentTB is interacted through the system tray. Once you've clicked continue, a tray icon appears and you can edit the settings there.
