### ISSUE TITLE
[Bug]: TranslucentTB

### ISSUE THREAD

**Issue by ingxhe** [TranslucentTB/TranslucentTB#935]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

![image](https://github.com/TranslucentTB/TranslucentTB/assets/30750321/be166cd9-be6b-4e04-b40c-ea3474b3732b)
![image](https://github.com/TranslucentTB/TranslucentTB/assets/30750321/362dc68d-1020-4de4-a601-4ab9f438414c)

Windows：
![image](https://github.com/TranslucentTB/TranslucentTB/assets/30750321/26b07b0c-4036-40ea-a9c8-9202d5ac56e2)

### Expected results

TranslucentTB

### Actual results

TranslucentTB

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

TranslucentTB

### Relevant log output

```shell
TranslucentTB
```

**Comment by sylveon** [comment]
Your download is probably corrupt, please try redownloading

**Comment by Univers4craft** [comment]
Hello, I am French, so I apologize for my approximate English. Here are the steps that personally resolved my issue:

1 Uninstall the application.

2 Delete all temporary files without exception from the control panel, as shown in the photo if necessary.
![Screenshot 2023-10-12 204304](https://github.com/TranslucentTB/TranslucentTB/assets/32676828/cc98ecbe-5e9a-472e-bd2a-1759ce8ffc6f)

3 Restart pc

4 Reinstall the program, and it should work.
