### ISSUE TITLE
[Bug]: Some Application ping on taskj bar''s icon is not normal showing

### ISSUE THREAD

**Issue by tonylinmax** [TranslucentTB/TranslucentTB#939]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Some Application ping on taskj bar''s icon is not normal showing
![圖片](https://github.com/TranslucentTB/TranslucentTB/assets/23489289/548d6e1d-2a14-477a-93ad-7cae10b17266)

### Expected results

there is Application is not show Firefox Browser, Opera Browser, Brave Browser, Line messager
![圖片](https://github.com/TranslucentTB/TranslucentTB/assets/23489289/5b6d7ffc-884b-41ec-9ebc-12bccb14d624)

### Actual results

![圖片](https://github.com/TranslucentTB/TranslucentTB/assets/23489289/8f0bcd6e-1e18-4027-b170-5bc69474b2a4)

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

**Comment by sylveon** [comment]
This doesn't appear to be a TranlucentTB issue but rather a Windows bug.
