### ISSUE TITLE
[Bug]: Arcylic and Normal not working properly

### ISSUE THREAD

**Issue by Haroonnxh** [TranslucentTB/TranslucentTB#940]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Switch to Arcylic or Normal

### Expected results

![Desktop Screenshot 2023 09 12 - 18 04 10 62](https://github.com/TranslucentTB/TranslucentTB/assets/148341597/1a009c68-fbf9-4f5c-a63a-1f6e7e7648e3)

This is how normal looked like

![Desktop Screenshot 2023 07 12 - 22 49 43 55](https://github.com/TranslucentTB/TranslucentTB/assets/148341597/08377373-a982-486a-8f72-3e5e87f3f390)
This is how arcylic looked like

### Actual results

Normal
![Desktop Screenshot 2023 10 18 - 17 07 34 09](https://github.com/TranslucentTB/TranslucentTB/assets/148341597/3dc0a160-af94-40ff-8a80-19ddf5624053)

Arcylic is either clear or identical to normal
![Desktop Screenshot 2023 10 18 - 17 08 11 97](https://github.com/TranslucentTB/TranslucentTB/assets/148341597/690927db-598c-4145-aac0-ce7c8726c6ee)
![Desktop Screenshot 2023 10 18 - 17 07 56 72](https://github.com/TranslucentTB/TranslucentTB/assets/148341597/c938142a-5636-44d7-8b08-6285d0282b0c)

### Windows version

Windows 10 2004-22H2 (builds 19041-19045)

### Other details

Blur, Clear and Opaque is working properly.  
Transparency effect is on.
Restarting Window Explorer temporarily fixes Arcylic however Normal is still the same. After restart or opening of any another application it breaks again.

**Comment by Haroonnxh** [comment]
Apparently it was a driver's issue, The latest update broke the transparency.

**Comment by Squall-Leonhart** [comment]
What monitor are you using?
