### ISSUE TITLE
[Bug]: Won't run

### ISSUE THREAD

**Issue by pugsforlifebruh12** [TranslucentTB/TranslucentTB#942]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

I use Windows 10, TranslucentTB 2023.1 arm64

appinstallers and the Microsoft store have been broken ever since I've had this computer, So it's kinda hard to reproduce it with a good computer

### Expected results

For TTB to actually run

### Actual results

When I run TranslucentTB it says "This app can't run on your computer," is there some kind of issue with my computer or is it only windows 11?

### Windows version

Windows 10 May/November 2019 Update (builds 18362 and 18363)

**Comment by sylveon** [comment]
You need the x64 version, not ARM64.
