### ISSUE TITLE
[Bug]: Win11 22621.2428 - 0x80070490 Element not found (crash on launch)

### ISSUE THREAD

**Issue by Mystard** [TranslucentTB/TranslucentTB#943]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Launch TranslucentTB on Win11 22621.2428

### Expected results

TranslucentTB launches and works

### Actual results

Error message "TranslucentTB has encountered a fatal error and cannot continue executing. Failed to initialize XAML Diagnostics. 0x80070490: Element not found."

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

Win11 22621.2428

Tried rebooting, reinstalling, clearing temp files etc. 

![image](https://github.com/TranslucentTB/TranslucentTB/assets/28576956/815e274a-a713-4584-bb5d-470a6c336557)

### Relevant log output

```shell
[2023-10-29 20:42:40.300] [critical] [taskbarattributeworker.cpp:1206] Failed to initialize XAML Diagnostics. (0x80070490: Elementtiä ei löydy.)
```

**Comment by GeorgeCiesinski** [comment]
Same issue, and same solution. Simply restarting fixed the issue for me.

Also worth noting, this happened directly after my Win11 updated and finished rebooting. An additional reboot was all that was needed in my case.

**Comment by Mystard** [comment]
Restart did not fix it for me, as the prompt kept popping up on every restart. However it started working randomly.

**Comment by RameshGokamalla** [comment]
I am using the build 22621.2715 (Windows 11 Pro 22H2). Facing the same problem. I uninstalled and reinstalled the application but not working.
