### ISSUE TITLE
[Bug]: Takes too long to start on windows 11

### ISSUE THREAD

**Issue by ppfmagno** [TranslucentTB/TranslucentTB#944]
### Please check for a duplicate first

- [x] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Fresh installed on windows.
Start the system.

### Expected results

Start windows with translucenttb working already or at least not to take so long.

### Actual results

Takes about 10 sec on my machine, since I have other initialization apps that I really need.

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

Maybe letting the TTB be used as a service could solve this.

**Comment by sylveon** [comment]
This is normal Windows behavior. Use something like https://github.com/sylveon/EarlyStart if you want faster startup.
