### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by IAMNEVERWIN** [TranslucentTB/TranslucentTB#945]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

I stupidly disable the app's icon on taskbar and now i cant open it again to configure it 

### Expected results

i want to reopen the icon on taskbar again

### Actual results

.

### Windows version

Windows 10 May/November 2019 Update (builds 18362 and 18363)

### Other details

.

### Relevant log output

```shell
.
```

**Comment by IAMNEVERWIN** [comment]
am stupid

**Comment by sylveon** [comment]
Open the config file at `%LocalAppData%\Packages\28017CharlesMilette.TranslucentTB_v826wp6bftszj\RoamingState\settings.json` and set `hide_tray` to `false`
