### ISSUE TITLE
[Bug]: Windows 11 23H2 22631.2715 Taskbar works, but no other options (e.g. Start Opened) are effective

### ISSUE THREAD

**Issue by PythonesqueSpam** [TranslucentTB/TranslucentTB#947]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Using the Microsoft Store version: Select each option in turn from the TTB icon in the taskbar and select 'Enable'; Select the 'Accent Color' option and change the colour to bright red (for testing purposes), then any option from Normal/Opaque/Clear/Acrylic.

### Expected results

Each of the panels described in the popup menu from the TTB icon in the taskbar show the visual effect chosen from the four available options.

### Actual results

None of the options make any difference to any panels they are supposed to customise.  Yet the taskbar does show the effect according to the option selected from the four available. I also uninstalled the Microsoft Store version and tried the portable version instead, but this did not show any effect chosen from the four in any panel, including the taskbar.

### Windows version

Windows 10 May/November 2019 Update (builds 18362 and 18363)

### Other details

My version is Windows 11 23H2 22631.2715

### Relevant log output

```shell
I could not locate the log file.
```

**Comment by sylveon** [comment]
Yes, these are currently broken and the fix is more involved than I expected. Will have to do some significant changes to fix them.

**Comment by sylveon** [comment]
Fixed in 2024.1
