### ISSUE TITLE
[Bug]: It doesn't recognize gestures from laptop and doesn't recognize start menu from explorer patcher

### ISSUE THREAD

**Issue by Pawel2282** [TranslucentTB/TranslucentTB#950]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Have normal theme taskbar when maximized and clear on desktop and use gestures to show desktop. Second install explorer patcher choose fullscreen start menu and option acrylic and it doesn't work.

### Expected results

Correct taskbar themes

### Actual results

Incorrect taskbar themes

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by Pawel2282** [comment]
Problem with gestures seems to fix by itself, but it still doesn't recognize start menu

**Comment by sylveon** [comment]
Start menu is #947

**Comment by sylveon** [comment]
Should be fixed now.
