### ISSUE TITLE
[Bug]: I cannot download Translucent TB as it becomes a problem when i press install.

### ISSUE THREAD

**Issue by JEEAA** [TranslucentTB/TranslucentTB#951]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

 I cannot download Translucent TB as it becomes a problem when i press install. It takes me to the microsoft store where it says "The thing youre looking for isnt here" Code: 0X00000005 CV: vU5AAkWFfE2AqWEN. Not sure what this is.

### Expected results

To just download as usual.

### Actual results

Didn't exist according to microsoft store.

### Windows version

Windows 10 May/November 2019 Update (builds 18362 and 18363)

**Comment by sylveon** [comment]
What region is your system in?

**Comment by hassanmagueri** [comment]
dsda
