### ISSUE TITLE
[Bug]: Maximized window doesent show taskbar  

### ISSUE THREAD

**Issue by AndrewBello** [TranslucentTB/TranslucentTB#952]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

When the cursor is placed at the bottom of the screen the taskbar doesn't pop up until the windows key is pressed

### Expected results

I expect the taskbar to popup

### Actual results

The taskbar doesent open

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment]
This is a bug with the taskbar itself. Use a tool like RudeWindowFixer to fix it: https://github.com/dechamps/RudeWindowFixer
