### ISSUE TITLE
[Bug]: In startup apps TraslucentTB won't stay enabled 

### ISSUE THREAD

**Issue by Ammo64** [TranslucentTB/TranslucentTB#954]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

After downloading the app it works fine accept it won't automatically start on startup. 

### Expected results

 I tried a lot of steps to fix this but non of them worked then i thought the problem might be in my laptop only so i tried it in a pc but still the problem remained.

### Actual results

this might be caused by the app not working well by the task scheduler 

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

i could fix it manually but that might be to hard for the non tec sayy people if any one wants to fix it 1st download the portable version of the app form GitHub and then schedul the app to startup on login through task scheduler. This should fix it 50% off the times but if the app is generally not working then i suggest trying https://github.com/thebookisclosed/ViVe/releases . there are multiple vd on yt to show how to use it. plz the devs do something to fix the issue 

### Relevant log output

```shell
i am using this version but i was unable to find it from the win versions options 
Windows 11, version 22H2.(home)
```

**Comment by sylveon** [comment]
This is a problem with your registry. Put the following text in Notepad and save it as "StartupTasks.reg", then double-click it, accept the prompt that appears and reboot Windows:
```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System]
"EnableFullTrustStartupTasks"=dword:00000002
"EnableUwpStartupTasks"=dword:00000002
"SupportFullTrustStartupTasks"=dword:00000001
"SupportUwpStartupTasks"=dword:00000001
```
