### ISSUE TITLE
[Bug]: Cant Install: Error 0x80073D05

### ISSUE THREAD

**Issue by rafachavantes** [TranslucentTB/TranslucentTB#955]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Go to Windows Store, hit download it sends me to download the installer. After running the installer. It downloads and tries to install.

It shows that cant install and sends me back to Microsoft Store. I try to install from there and it shows that an error ocurred.

Error: 0x80073D05

### Expected results

Be able to install

### Actual results

Cant install

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

Build 22631

**Comment by jonathan-thorsell** [comment]
To provide just a tiny bit more information to hopefully help with some troubleshooting, this is the error message I received when downloading the portable version for windows 11 and running the exe from there:
![image](https://github.com/TranslucentTB/TranslucentTB/assets/108808053/4cab29ee-68b9-4093-b302-4e998ce16a4b)

**Comment by sylveon** [comment]
Did you make sure to fully extract it?

**Comment by joelm3103** [comment]
I am also receiving both errors. Got a previous error where it said "Failed to set hook", so I uninstalled it completely. After reinstalling the set up, I was prompted with the first error (Original Post) and then tried portable and was greeted with the 2nd.

> Did you make sure to fully extract it?

Yes it was fully extracted.

Current OS: Windows 11 Pro (Version 23H2, Build 22631.3007)

**Comment by sylveon** [comment]
The issue with the portable version is fixed in 2024.1.
The issue from OP is a most likely a problem with the Store on their system.
