### ISSUE TITLE
[Bug]: No suitable application license found

### ISSUE THREAD

**Issue by Reversedeer** [TranslucentTB/TranslucentTB#959]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

2023/12/5运行本软件时提示签名到期

### Expected results

正常运行或者有办法部署新的签名

### Actual results

微软商店更新的最新版本仍然不可用
![ocr](https://github.com/TranslucentTB/TranslucentTB/assets/87823528/ae9435ce-73d7-41d7-95a6-3de96384ac4f)

### Windows version

Windows 10 2004-22H2 (builds 19041-19045)

**Comment by sylveon** [comment]
When first running the MSIX version, you need to be able to use the Microsoft Store so it can acquire a license. If this is a problem for you, you can install the portable version.

**Comment by Reversedeer** [comment]
我一直在使用它，只是今天出现了这样的问题

**Comment by Reversedeer** [comment]
保留个人数据重新安装win10以解决问题.......
