### ISSUE TITLE
The software doesn't change the background of the hidden icons bar

### ISSUE THREAD

**Issue by 534387130** [TranslucentTB/TranslucentTB#96]
the software is really wonderful,but it doesn't change the background of the hidden icon bar,another issue is if i set the software into Dynamic windows or blur mode and maximize a software which doesn't use the standard frame(for example, chrome and office)and open the start screen,there will be a white line on the top of the taskbar
![1](https://user-images.githubusercontent.com/16594167/29756197-8378ce64-8bd4-11e7-8953-49955f26cbc8.png)
sorry for my poor English,hopefully you could understand it

**Comment by 534387130** [comment]
thank you for your help

**Comment by ethanhs** [comment]
Closing in favor of #56
