### ISSUE TITLE
[Bug]: Windows11 update Don't Use

### ISSUE THREAD

**Issue by k-0-i** [TranslucentTB/TranslucentTB#961]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

![image](https://github.com/TranslucentTB/TranslucentTB/assets/95953449/401b06e8-84fb-4298-b672-c5b6abe42f55)
![image](https://github.com/TranslucentTB/TranslucentTB/assets/95953449/6f22298a-1d93-4c3b-8fa9-d5b00c1ae13c)

### Expected results

can use

### Actual results

don't use

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

**Comment by NowINEwww** [comment]
To solve this problem, you don't need to restart your PC or install TranslucentTB again，just open the Windows exploer and restart it in task manager，and then reopen TranslucentTB, you will find that it works properly.
在任务管理器里找到Windows资源管理器，右键重新启动它，然后再重新启动TranslucentTB就可以了。

**Comment by overfog** [comment]
> To solve this problem, you don't need to restart your PC or install TranslucentTB again，just open the Windows exploer and restart it in task manager，and then reopen TranslucentTB, you will find that it works properly. 在任务管理器里找到Windows资源管理器，右键重新启动它，然后再重新启动TranslucentTB就可以了。

Following this approach, I did not find TranslucentTB in the task manager

**Comment by k-0-i** [comment]
> > To solve this problem, you don't need to restart your PC or install TranslucentTB again，just open the Windows exploer and restart it in task manager，and then reopen TranslucentTB, you will find that it works properly. 在任务管理器里找到Windows资源管理器，右键重新启动它，然后再重新启动TranslucentTB就可以了。
> 
> Following this approach, I did not find TranslucentTB in the task manager

Restart Windows Explorer instead of Translucent.
