### ISSUE TITLE
[Bug]: How do I set up automatic startup of software on my computer?

### ISSUE THREAD

**Issue by lucakiseki** [TranslucentTB/TranslucentTB#968]
### Please check for a duplicate first

- [x] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

I'm using the latest version, but I noticed that there is no option to "boot automatically", which existed in the old version!

### Expected results

I need TranslucentTB to start automatically when I turn on my computer.

### Actual results

I need TranslucentTB to start automatically when I turn on my computer.

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

**Comment by sylveon** [comment]
The Microsoft Store version has a checkbox, for the portable version you can drop a shortcut to the exe in `%AppData%\Microsoft\Windows\Start Menu\Programs\Startup`
