### ISSUE TITLE
[NOT Bug]: Windows 10 portable

### ISSUE THREAD

**Issue by PlazmaKG** [TranslucentTB/TranslucentTB#973]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

It's not a bug, It would just be nice if the portable version of TranslucentTB worked on Windows 10. From an outside perspective it looks like an arbitrary limitation. Not saying it is or isn't, it just seems weird. Thanks for reading this! :)

### Expected results

Not a bug

### Actual results

Not a bug

### Windows version

Windows 10 2004-22H2 (builds 19041-19045)

**Comment by sylveon** [comment]
Windows 10 does not have the [MSIX dynamic dependencies](https://learn.microsoft.com/en-us/windows/win32/api/appmodel/nf-appmodel-addpackagedependency) API. This is not possible at the moment.

**Comment by PlazmaKG** [comment]
Oh that makes sense; thanks.
