### ISSUE TITLE
[Bug]: not seeing installed packages 📦 

### ISSUE THREAD

**Issue by Sputchik** [TranslucentTB/TranslucentTB#977]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Installed ui xaml and webview2 through powershell.
Were 2 errors with these packages, but xaml persists
![IMG_2414](https://github.com/TranslucentTB/TranslucentTB/assets/138970407/b3616594-215d-428b-9f38-7b8a6bb3f880)

### Expected results

Work

### Actual results

Not work 😨

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

Rebooting didn’t work

**Comment by sylveon** [comment]
You installed the NuGet packages, which are development dependencies. You need to install the runtime MSIX framework packages. The easiest way to do this is getting TranslucentTB from the store or downloading and running the app installer in the releases file.

Alternatively, you can open up the NuGet package's contents and you'll find the MSIX file there.
