### ISSUE TITLE
[Bug]: Can TranslucentTB help with white lines between systray icons when using the greyeve.theme ?

### ISSUE THREAD

**Issue by shodanx2** [TranslucentTB/TranslucentTB#978]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Install the greyeve.theme

https://github.com/nitschis/GreyEveTheme/releases/download/v1/GreyEveTheme.theme

### Expected results

No lines between the systray icons

### Actual results

![image](https://github.com/TranslucentTB/TranslucentTB/assets/10621885/35121d38-672b-444d-955c-ff5f12fad924)

![image](https://github.com/TranslucentTB/TranslucentTB/assets/10621885/5531f1f8-481b-45a2-b79f-ae972113ad29)

These lines are not caused by TranslucentTB but I am asking, can TranslucentTB do anything about them ?

These lines appear because this is a modified dark mode theme that override colours that can't be changed by normal themes. 

I imagine this particular colour, is the colour of text in other applications.

But maybe TranslucentTB can override this colour, only on the taskbar ? 

Or maybe even better, make the systray background transparent as well ?

### Windows version

Windows 10 2004-22H2 (builds 19041-19045)

**Comment by sylveon** [comment]
Not really. These squares show up because you're using a high contrast theme.

**Comment by shodanx2** [comment]
Yes, but I mean, if TTB can change the backcolor of the taskbar to transparent, could I make it change that specific colour between the systray icons to something gray ?

I am considering hex-editing explorer.exe, to change the specific place where it chooses that white colour and change it to something else.

But since TTB is already changing the taskbar's colour, maybe you have a much easier way of doing it ?

**Comment by sylveon** [comment]
The method we use to change the taskbar background is vastly different to what is used to draw the taskbar contents, so not easily. Hooking the return value of GetSysColor could lead to breakages somewhere else.
