### ISSUE TITLE
I don't know why on both sides

### ISSUE THREAD

**Issue by WPNEAL** [TranslucentTB/TranslucentTB#98]
![_3adg45 3qc7i s_k d p3](https://user-images.githubusercontent.com/16266197/29811293-8d54a3b6-8cd5-11e7-9e0c-f2f254c205af.png)

**Comment by denosawr** [comment]
I don't understand? What's the problem here?

**Comment by WPNEAL** [comment]
The desktop and taskbar don't even look like a picture, and the feeling of the taskbar sinks a little

**Comment by WPNEAL** [comment]
![image](https://user-images.githubusercontent.com/16266197/29952370-8248a724-8efb-11e7-8ffa-763888eadb2a.png)
I don't know if that's the reason for that picture. It's just a feeling
