### ISSUE TITLE
[Bug]: Taskbar border 

### ISSUE THREAD

**Issue by Modchi** [TranslucentTB/TranslucentTB#980]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

the app Bugged my Windows 11 Taskbar border, now if I close
 the app it shows the taskbar border by default :/ 

![Screenshot 2024-02-14 013947](https://github.com/TranslucentTB/TranslucentTB/assets/91514785/f0571f03-6169-4ca2-a8bf-10dccfb46f1d)

### Expected results

.

### Actual results

.

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

Windows 11 Pro 22631.3155

**Comment by sylveon** [comment]
Windows 11 has a taskbar border by default.
