### ISSUE TITLE
TranslucentTB exits when trying to run GlazeWM [Bug]: 

### ISSUE THREAD

**Issue by ghost** [TranslucentTB/TranslucentTB#981]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Run GlazeWM with TranslucentTB enabled. 

### Expected results

Didn't expect an error to be thrown. 

### Actual results

Received this error message when trying to run GlazeWM:

“Windows Explorer restarted twice in the last 30 seconds! This may be a conflict between TranslucentTB and other shell customization software, or a Windows Update. To avoid further issues, TranslucentTB will now exit.”

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

I set GlazeWM to ignore TranslucentTB, and the error still occurred.

**Comment by txj-xyz** [comment]
Same issue here.

![image](https://github.com/TranslucentTB/TranslucentTB/assets/7461476/09f9230c-83f2-4b37-99f4-77f1f30512bd)

**Comment by sylveon** [comment]
Should be fixed in latest release

**Comment by Soumyadeep-Chakravarti** [comment]
still not fixed same error occurs

**Comment by shitalmoirangcha188-dot** [comment]
“Windows Explorer restarted twice in the last 30 seconds! This may be a conflict between TranslucentTB and other shell customization software, or a Windows Update. To avoid further issues, TranslucentTB will now exit.”

**Comment by shitalmoirangcha188-dot** [comment]
“Windows Explorer restarted twice in the last 30 seconds! This may be a conflict between TranslucentTB and other shell customization software, or a Windows Update. To avoid further issues, TranslucentTB will now exit.”
