### ISSUE TITLE
[Bug]: broken Azure Pipelines link in ReadMe

### ISSUE THREAD

**Issue by e-t-l** [TranslucentTB/TranslucentTB#982]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Click the link to [Azure Pipelines build](https://dev.azure.com/sylve0n/TranslucentTB/_build?definitionId=4) in https://github.com/TranslucentTB/TranslucentTB/blob/release/README.md. (I'm not too familiar with AP; maybe it works if you have an account or something. If the link works for you, try doing it in an incognito tab.)

### Expected results

The link navigates to some page where dev builds can be downloaded

### Actual results

404 error

### Windows version

N/A

### Other details

I'm interested in trying the improvements made in #957, so I was hoping to download a dev build from Azure Pipelines, but I can't figure out how since the link is broken.

**Comment by sylveon** [comment]
Thanks for pointing that out! Fixed :)

Also for future record, you can click the checkmark on a commit to get a link to that CI run: 
![image](https://github.com/TranslucentTB/TranslucentTB/assets/6440374/fc55583a-30ff-46a1-9c01-ba10fc439491)
