### ISSUE TITLE
there is a color behind apps

### ISSUE THREAD

**Issue by Zeyadmo178** [TranslucentTB/TranslucentTB#983]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

![image](https://github.com/TranslucentTB/TranslucentTB/assets/160337993/c88db5b9-101b-4103-9135-0fbcebf01d59)

### Expected results

i hope it will fix soon

### Actual results

i hope it will fix soon

### Windows version

Windows 10 May/November 2019 Update (builds 18362 and 18363)

**Comment by sylveon** [comment]
Check https://translucenttb.github.io/tips
