### ISSUE TITLE
[Bug]: TranslucentTB 不能在便捷模式中启动，因为Microsoft.Ul.Xaml.2.8 8wekyb3d8bbwe (版本 8.2305.5001.0)未安装在系统上。

### ISSUE THREAD

**Issue by muua666** [TranslucentTB/TranslucentTB#984]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

TranslucentTB 不能在便捷模式中启动，因为Microsoft.Ul.Xaml.2.8 8wekyb3d8bbwe (版本 8.2305.5001.0)未安装在系统上。
![微信图片_20240218140258](https://github.com/TranslucentTB/TranslucentTB/assets/154310792/a9415858-9b95-4871-b196-1d5ec7e8d30f)

### Expected results

no

### Actual results

no

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

**Comment by sylveon** [comment]
You need to install it: https://github.com/TranslucentTB/TranslucentTB/releases/download/2023.1/winui-x64.appx

**Comment by muua666** [comment]
Thanks a lot

**Comment by lzh878801027** [comment]
microsoft.ui.xaml.2.8_8wekyb3d8bbwe （ 版本8.2310.30001.0）怎么下载

**Comment by ThromamiomAdd** [comment]
出现了这个怎么办：
已经安装了此应用包的较新版本。若要安装较旧版本，请卸载当前安装在系统上的版本 (0x80073D06)

**Comment by sylveon** [comment]
If a newer version is already installed, then you don't have to install it

**Comment by ThromamiomAdd** [comment]
But I can use TranslucentTB

|
ThromamiomAdd
Unknown Company  - 
不做无法实现的梦
14767867006
***@***.***
广东省湛江市遂溪县
|
---- 回复的原邮件 ----
| 发件人 | Charles ***@***.***> |
| 发送日期 | 2024年08月07日 07:58 |
| 收件人 | TranslucentTB/TranslucentTB ***@***.***> |
| 抄送人 | ThromamiomAdd ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [TranslucentTB/TranslucentTB] [Bug]: TranslucentTB 不能在便捷模式中启动，因为Microsoft.Ul.Xaml.2.8 8wekyb3d8bbwe (版本 8.2305.5001.0)未安装在系统上。 (Issue #984) |

If a newer version is already installed, then you don't have to install it

**Comment by ThromamiomAdd** [comment]
But i can't  Use it.

**Comment by sylveon** [comment]
What error message are you getting?

**Comment by ThromamiomAdd** [comment]
Still this:TranslucentTB 不能在便捷模式中启动，因为Microsoft.Ul.Xaml.2.8 8wekyb3d8bbwe (版本 8.2305.5001.0)未安装在系统上.






---- 回复的原邮件 ----
| 发件人 | Charles ***@***.***> |
| 发送日期 | 2024年8月8日 16:31 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [TranslucentTB/TranslucentTB] [Bug]: TranslucentTB 不能在便捷模式中启动，因为Microsoft.Ul.Xaml.2.8 8wekyb3d8bbwe (版本 8.2305.5001.0)未安装在系统上。 (Issue #984) |

What error message are you getting?

**Comment by J-Ollie** [comment]
https://github.com/TranslucentTB/TranslucentTB/releases/download/2024.1/winui-x64.appx

**Comment by FourDragon** [comment]
> Still this:TranslucentTB 不能在便捷模式中启动，因为Microsoft.Ul.Xaml.2.8 8wekyb3d8bbwe (版本 8.2305.5001.0)未安装在系统上.
> […](#)  [...](#)

我也碰到了这个，但我现在已经解决了
我本来想着将其放到DawnLauncher（一个分类软件并快速启动的软件）里的，情形类似于在桌面创建快捷方式，但结果却是产生如你相同问题的弹窗。不说废话了，我直接给你讲哈，

按win键，在跳出来的窗口右上面点击全部，找到TranslucentTB将其固定到“开始”屏幕，然后在桌面创建一个文件夹（随便什么文件夹），将“开始”屏幕中的TranslucentTB图标拖入

![Image](https://github.com/user-attachments/assets/48db167b-93b7-44ad-9457-c82beb98b2a2)

![Image](https://github.com/user-attachments/assets/e034c29c-2d26-48a8-9254-8cf510f4ef43)


然后把这个能够正常启动TranslucentTB的快捷方式随意安置了。唯一缺点是他的图标有点异常。

当然如果你想让这个图标正常点，也不难。

首先运行该软件，然后打开任务管理器，通过搜索框快速找到该进，展开内容右键点击打开文件所在位置

![Image](https://github.com/user-attachments/assets/394fd194-5e16-4819-a331-a4f7ad235438)

![Image](https://github.com/user-attachments/assets/4503e70b-7760-43df-a917-50b85f430d79)

在Assets里就有其相应的图标，剩下的就不写了

**Comment by szdalw** [comment]
winui-x64(8.2310.30001.0)下载地址：https://github.com/TranslucentTB/TranslucentTB/releases/download/2024.1/winui-x64.appx

**Comment by yikuainailao** [comment]
你可以去微软商店更新所有应用，大概率会解决问题。
You can go to the Microsoft Store to update all apps; this will most likely solve the problem.
