### ISSUE TITLE
[Bug]: The failure of Acrylic

### ISSUE THREAD

**Issue by Takenforgranted** [TranslucentTB/TranslucentTB#988]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Yesterday,I try to install the software CareUeyes. However, When I am unsatisfied and uninstall it, I was amazed at the failure of Acrylic Effect. After trying to fix regedit, using vivotools(a way to fix the failure of transparent)，install&uninstall TranslucentTB and rebooting the computer for several times, I am quite depressed now(maybe it's the bleeding Win11 23H2 that causes it). 

### Expected results

Hoping acrylic can come into effect.

### Actual results

Now my TranslucentTB can only show transparent or default two modes.Other modes cannot work well.

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

My windows version is 23H2 now.

**Comment by sylveon** [comment]
Check if transparency effects are enabled in Windows settings.

**Comment by Takenforgranted** [comment]
> Check if transparency effects are enabled in Windows settings.

**Thanks for reminding!** It is solved well. Regedit is such a pamdora's box if you take action on it without guides.

**Comment by Takenforgranted** [comment]
> Check if transparency effects are enabled in Windows settings.

It's a basic but needed pre-action, I think, while debugging this software.
