### ISSUE TITLE
[Bug]: White dot in the middle of taskbar

### ISSUE THREAD

**Issue by Jfruiz** [TranslucentTB/TranslucentTB#994]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

None. It appear as soon I make taskbar transparent.

### Expected results

A clean tasckbar

### Actual results

A taskbar with a white dot in the bottom middle of it

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

Windows version:  22631.3296
![image](https://github.com/TranslucentTB/TranslucentTB/assets/30754365/11b56051-1e16-40b9-8732-87a0744a3b05)

**Comment by sylveon** [comment]
Could this be part of your wallpaper?

**Comment by Jfruiz** [comment]
Shame on me. It was the wallpaper
